import {readFile} from 'node:fs/promises'
import {expect,test} from '@playwright/test'

for(const width of [320,360])test(`upgrade qualification real draft persists and fits ${width}px`,async({page,browser},testInfo)=>{
 const fixture=JSON.parse(await readFile('artifacts/normalized-browser/fixture.json','utf8'))
 test.skip(!fixture.memberCardFixture,'Requires isolated qualification fixture')
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
 await page.setViewportSize({width,height:740});await page.goto(fixture.staffUrl)
 await page.getByLabel('门店口令').fill(fixture.dailyCredential);await page.getByRole('button',{name:/验证设备/}).click()
 await page.getByLabel('员工账号').fill('chenfangyu');await page.getByLabel('四位 PIN').fill(fixture.employeePin);await page.getByRole('button',{name:/进入工作台/}).click()
 await expect(page.getByTestId('normalized-workspace')).toBeVisible();await page.goto('/staff/customer-experience')
 const panel=page.getByRole('region',{name:'付款前升级与履约产能配置',exact:true})
 await panel.getByRole('button',{name:'配置',exact:true}).click()
 await panel.getByText('新建规则草稿',{exact:true}).click()
 const code=`QA_STRICT_${width}_${Date.now()}`
 await panel.getByLabel('规则代码',{exact:true}).fill(code)
 await panel.getByLabel('规则名称',{exact:true}).fill('隔离测试准入规则，不可用于真实经营')
 await expect(panel.getByLabel('原商品',{exact:true}).locator('option').first()).toBeAttached()
 await panel.getByLabel('原商品',{exact:true}).selectOption({label:'隔离升级原饮品 · BROWSER-UPGRADE-SOURCE'})
 await panel.getByLabel('升级套餐',{exact:true}).selectOption({label:'隔离升级双份套餐 · BROWSER-UPGRADE-TARGET'})
 const productId=await panel.getByLabel('原商品',{exact:true}).inputValue()
 await panel.getByLabel(/最多加价/).fill('3000')
 await panel.getByLabel(/升级后最低贡献额/).fill('1000')
 await panel.getByLabel(/最低新增贡献额/).fill('0')
 await panel.getByLabel('适配依据',{exact:true}).fill('隔离测试：保留原具体选择，核对新增商品与份量；不用于实际推荐')
 await panel.getByRole('combobox',{name:'份量上限商品',exact:true}).selectOption(productId)
 await panel.getByRole('button',{name:'保存此份量上限',exact:true}).click()
 const responsePromise=page.waitForResponse(response=>response.request().method()==='PUT'&&response.url().includes(`/checkout-upgrade-rules/${code}`))
 await panel.getByRole('button',{name:'保存草稿',exact:true}).click()
 const response=await responsePromise;expect(response.ok(),await response.text()).toBe(true)
 const row=panel.locator('.checkout-rule-list article').filter({hasText:code})
 await expect(row).toBeVisible();await row.getByText('核对高度匹配条件',{exact:true}).click()
 await expect(row).toContainText('最多加价 ¥30.00')
 await expect(row).toContainText('最低贡献额 ¥10.00')
 const size=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,content:Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)}))
 expect(size.content).toBeLessThanOrEqual(size.viewport+1)
 await row.screenshot({path:testInfo.outputPath('persisted-upgrade-qualification.png')})
 await expect(row.getByRole('button',{name:'审批',exact:true})).toHaveCount(0)
 const reviewerContext=await browser.newContext({viewport:{width,height:740}})
 try{
  const reviewer=await reviewerContext.newPage();await reviewer.goto(fixture.staffUrl)
  await reviewer.getByLabel('门店口令').fill(fixture.dailyCredential);await reviewer.getByRole('button',{name:/验证设备/}).click()
  await reviewer.getByLabel('员工账号').fill('hugu');await reviewer.getByLabel('四位 PIN').fill(fixture.employeePin);await reviewer.getByRole('button',{name:/进入工作台/}).click()
  await expect(reviewer.getByTestId('normalized-workspace')).toBeVisible();await reviewer.goto(`${new URL(page.url()).origin}/staff/customer-experience`)
  const reviewPanel=reviewer.getByRole('region',{name:'付款前升级与履约产能配置',exact:true})
  await reviewPanel.getByRole('button',{name:'配置',exact:true}).click()
  const reviewRow=reviewPanel.locator('.checkout-rule-list article').filter({hasText:code})
  await reviewRow.getByRole('button',{name:'审批',exact:true}).click()
  await reviewer.getByRole('dialog').getByLabel('审批依据',{exact:true}).fill('隔离规则审批测试，不启用推荐')
  const approvedPromise=reviewer.waitForResponse(response=>response.request().method()==='POST'&&response.url().includes(`/checkout-upgrade-rules/${code}/approve`))
  await reviewer.getByRole('dialog').getByRole('button',{name:'确认审批',exact:true}).click()
  const approved=await approvedPromise;expect(approved.ok(),await approved.text()).toBe(true)
  await expect(reviewRow).toContainText('已审批')
  await expect(reviewRow.getByRole('button',{name:'发布',exact:true})).toHaveCount(0)
 }finally{await reviewerContext.close().catch(()=>{})}
 expect(errors).toEqual([])
})
