import {readFile} from 'node:fs/promises'
import {expect,test} from '@playwright/test'
for(const width of [320,360])test(`gift campaign drafting and full review layout at ${width}px`,async({page,browser},testInfo)=>{
  const fixture=JSON.parse(await readFile('artifacts/normalized-browser/fixture.json','utf8'))
  test.skip(!fixture.memberCardFixture,'Requires isolated gift fixture, no real grants')
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
  await page.setViewportSize({width,height:800});await page.goto(fixture.staffUrl)
  await page.getByLabel('门店口令').fill(fixture.dailyCredential);await page.getByRole('button',{name:/验证设备/}).click()
  await page.getByLabel('员工账号').fill(fixture.employeeCode);await page.getByLabel('四位 PIN').fill(fixture.employeePin);await page.getByRole('button',{name:/进入工作台/}).click()
  await expect(page.getByTestId('normalized-workspace')).toBeVisible();await page.goto('/staff/member-management');await page.getByRole('button',{name:/会员经营配置中心/}).click()
  const panel=page.getByRole('region',{name:'入卡礼与定向发券'})
  await panel.getByLabel('本次操作原因',{exact:true}).fill('隔离赠品规则页面验收')
  await panel.getByText('新建活动版本',{exact:true}).click()
  const code=`BROWSER_GIFT_${width}_${Date.now()}`
  await panel.getByLabel('活动编号',{exact:true}).fill(code);await panel.getByLabel('活动名称',{exact:true}).fill(`测试赠券${width}`)
  for(const [label,value] of [['每人赠送','1'],['活动总上限','100'],['每日上限','20'],['活动成本预算','10000'],['每日成本预算','2000'],['单份最高成本','100']])await panel.getByLabel(label!,{exact:true}).fill(value!)
  const local=(date:Date)=>new Date(date.getTime()+8*3600000).toISOString().slice(0,16)
  await panel.getByLabel('发放开始（北京时间）').fill(local(new Date(Date.now()-3600000)));await panel.getByLabel('发放截止（北京时间）').fill(local(new Date(Date.now()+86400000)))
  const products=panel.getByRole('group',{name:'赠品商品池',exact:true})
  await products.getByRole('textbox').fill('测试发券小食');await products.getByRole('button',{name:'查找',exact:true}).click();await products.getByRole('button',{name:/测试发券小食/}).click()
  const calendars=panel.getByRole('group',{name:'已发布券时间规则',exact:true})
  await calendars.getByRole('textbox').fill('BROWSER_GIFT_CAL');await calendars.getByRole('button',{name:'查找',exact:true}).click();await calendars.getByRole('button',{name:/BROWSER_GIFT_CAL/}).click()
  await panel.getByRole('button',{name:'保存活动草稿',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'确认执行',exact:true}).click()
  await expect(panel.getByRole('status')).toContainText('操作已记录')
  await panel.getByRole('button',{name:'读取活动',exact:true}).click()
  const draft=panel.locator('article').filter({hasText:code});await expect(draft).toContainText('待审核')
  await draft.getByText('核对完整发放条件',{exact:true}).click();await expect(draft).toContainText('测试发券小食');await expect(draft).toContainText('每日20份')
  await expect(draft.getByRole('button',{name:'审核',exact:true})).toHaveCount(0)
  await panel.getByRole('button',{name:'读取发券任务',exact:true}).click()
  const size=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,content:Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)}));expect(size.content).toBeLessThanOrEqual(size.viewport+1)
  await draft.screenshot({path:testInfo.outputPath('gift-draft-review.png')});expect(errors).toEqual([])
  for(const [employee,action] of [['hugu','审核'],['chenfangyu','发布']] as const){
    const context=await browser.newContext({viewport:{width,height:800}})
    try{
      const reviewer=await context.newPage();await reviewer.goto(fixture.staffUrl)
      await reviewer.getByLabel('门店口令').fill(fixture.dailyCredential);await reviewer.getByRole('button',{name:/验证设备/}).click()
      await reviewer.getByLabel('员工账号').fill(employee);await reviewer.getByLabel('四位 PIN').fill(fixture.employeePin);await reviewer.getByRole('button',{name:/进入工作台/}).click()
      await expect(reviewer.getByTestId('normalized-workspace')).toBeVisible();await reviewer.goto(`${new URL(page.url()).origin}/staff/member-management`);await reviewer.getByRole('button',{name:/会员经营配置中心/}).click()
      const management=reviewer.getByRole('region',{name:'入卡礼与定向发券'})
      await management.getByLabel('本次操作原因',{exact:true}).fill('隔离活动分人审核发布')
      await management.getByRole('button',{name:'读取活动',exact:true}).click()
      await management.locator('article').filter({hasText:code}).getByRole('button',{name:action,exact:true}).click()
      await reviewer.getByRole('alertdialog').getByRole('button',{name:'确认执行',exact:true}).click();await expect(management.getByRole('status')).toContainText('操作已记录')
    }finally{await context.close()}
  }
  await panel.getByRole('button',{name:'读取活动',exact:true}).click();await expect(draft).toContainText('发放中')
  await panel.getByText('向选定会员发券',{exact:true}).click()
  await panel.getByRole('combobox',{name:'已发布活动',exact:true}).selectOption({label:`测试赠券${width} · ${code}`})
  await panel.getByLabel('发放批次编号',{exact:true}).fill('browser-launch')
  const customers=panel.getByRole('group',{name:'目标会员',exact:true})
  await customers.getByRole('textbox').fill(`MBX-CARD${width}`);await customers.getByRole('button',{name:'查找',exact:true}).click();await customers.getByRole('button',{name:new RegExp(`MBX-CARD${width}`)}).click()
  await panel.getByRole('button',{name:'提交发券任务',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'确认执行',exact:true}).click();await expect(panel.getByRole('status')).toContainText('操作已记录')
  await panel.getByRole('button',{name:'读取发券任务',exact:true}).click()
  const job=panel.locator('article').filter({hasText:`browser-card-${width}`}).filter({hasText:`测试赠券${width}`})
  await expect(job).toContainText('等待发放')
  await job.getByRole('button',{name:'取消未发任务',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'确认执行',exact:true}).click()
  await expect(panel.getByRole('status')).toContainText('操作已记录');await panel.getByRole('button',{name:'读取发券任务',exact:true}).click();await expect(job).toContainText('已取消')
  expect(errors).toEqual([])
})
