import {readFile} from 'node:fs/promises'
import {expect,test} from '@playwright/test'
test.use({permissions:['camera'],launchOptions:{args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']}})
for(const width of [360,1280])test(`v9 custody, export and launch configuration at ${width}px`,async({page,request},testInfo)=>{
 const fixture=JSON.parse(await readFile('artifacts/normalized-browser/fixture.json','utf8'))
 test.skip(!fixture.memberCardFixture,'requires throwaway member fixture')
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
 await page.setViewportSize({width,height:900});await page.goto(fixture.staffUrl)
 await page.getByLabel('门店口令').fill(fixture.dailyCredential);await page.getByRole('button',{name:/验证设备/}).click()
 await page.getByLabel('员工账号').fill(fixture.employeeCode);await page.getByLabel('四位 PIN').fill(fixture.employeePin);await page.getByRole('button',{name:/进入工作台/}).click()
 await expect(page.getByTestId('normalized-workspace')).toBeVisible();await page.goto('/staff/member-management')
 const custody=page.locator('section.bottle-custody-panel').filter({has:page.getByRole('heading',{name:'会员存酒',exact:true})})
 await expect(custody).toBeVisible();await custody.getByText('存酒配置与品类',{exact:true}).click()
 await custody.getByLabel('启用新存酒',{exact:true}).check();await custody.getByRole('button',{name:'保存存酒规则',exact:true}).click()
 await expect(custody.getByRole('status')).toContainText('存酒配置已保存')
 await custody.getByLabel('品类编号',{exact:true}).fill(`LOCAL${width}`);await custody.getByLabel('品类名称',{exact:true}).fill(`本地酒类${width}`)
 await custody.getByRole('button',{name:'保存品类',exact:true}).click();await expect(custody.getByRole('status')).toContainText('品类已保存')
 await custody.getByText('录入新存酒',{exact:true}).click()
 const entry=custody.locator('details').filter({has:page.getByText('录入新存酒',{exact:true})})
 await entry.getByLabel('会员号',{exact:true}).fill('MBX-CARD320');await entry.getByLabel('酒名',{exact:true}).fill(`本地寄存样品${width}`)
 await entry.getByRole('combobox',{name:'品类',exact:true}).selectOption({label:`本地酒类${width} · 20天`})
 await entry.getByLabel('存酒登记价值（元，选填，非收入）',{exact:true}).fill('12.50')
 await expect(entry.getByRole('button',{name:'登记存酒',exact:true})).toBeDisabled()
 await entry.getByLabel('瓶内剩余比例',{exact:true}).selectOption('2/5');await expect(entry.getByLabel('数量',{exact:true})).toHaveValue('0.4')
 await entry.getByLabel('存酒联系手机号',{exact:true}).fill('13800012345');await entry.getByRole('button',{name:'打开摄像头拍照',exact:true}).click();await expect(entry.getByRole('button',{name:'拍摄并使用',exact:true})).toBeEnabled();await entry.getByRole('button',{name:'拍摄并使用',exact:true}).click();await expect(entry.getByAltText('本次存酒照片预览，保存后添加时间水印')).toBeVisible()
 await entry.screenshot({path:testInfo.outputPath('deposit-entry.png'),style:'.normalized-staff-action-shell > header { position: static !important; }'});await entry.getByRole('button',{name:'登记存酒'}).click();await expect(custody.getByRole('status')).toContainText('存酒已登记')
 await custody.getByText('存入照片与联系记录（1）',{exact:true}).click();await expect(custody).toContainText('138****2345');await expect(custody).toContainText('2/5 瓶');await custody.getByRole('button',{name:'查看带时间水印照片',exact:true}).click();await expect(custody.getByAltText('存入时的酒瓶、余量及服务器时间水印')).toBeVisible();await page.evaluate(()=>window.scrollTo(0,0));await custody.getByAltText('存入时的酒瓶、余量及服务器时间水印').screenshot({path:testInfo.outputPath('deposit-watermark.jpg'),style:'.normalized-staff-action-shell > header { position: static !important; }'});await custody.locator('.custody-detail').screenshot({path:testInfo.outputPath('deposit-detail.png'),style:'.normalized-staff-action-shell > header { position: static !important; }'});await custody.getByText('存入照片与联系记录（1）',{exact:true}).click()
 expect((await request.get('/api/staff/bottle-custody/member-contact?memberNo=MBX-CARD320')).status()).toBe(401)
 expect((await request.get('/api/staff/bottle-custody/00000000-0000-4000-8000-000000000001/photos/00000000-0000-4000-8000-000000000002')).status()).toBe(401)
 await custody.getByLabel('编号或酒名',{exact:true}).fill(`本地寄存样品${width}`);await custody.getByRole('button',{name:'查询 / 刷新'}).click()
 await expect(custody).toContainText('当前筛选共 1 单')
 const downloadPromise=page.waitForEvent('download');await custody.getByRole('button',{name:'按筛选导出 Excel'}).click();const download=await downloadPromise;expect(download.suggestedFilename()).toBe('MBOX-存酒明细.xlsx');await download.saveAs(testInfo.outputPath('custody.xlsx'))
 const popupPromise=page.waitForEvent('popup');await custody.getByRole('button',{name:'生成打印凭证'}).click();const preview=await popupPromise;await expect(preview.getByText('会员号：MBX-CARD320',{exact:true})).toBeVisible();await preview.close()
 const popup=page.locator('section.bottle-custody-panel').filter({has:page.getByRole('heading',{name:'小程序打开弹窗',exact:true})})
 await popup.getByLabel('标题',{exact:true}).fill(`本地推荐${width}`);await popup.getByRole('textbox',{name:'内容',exact:true}).fill('本地测试，不启用真实宣传');await popup.getByRole('button',{name:'保存弹窗'}).click();await expect(popup.getByRole('status')).toContainText('弹窗配置已保存')
 await custody.getByText('数据中心：选择统计范围',{exact:true}).click()
 await custody.getByLabel('报表品类名称或代码',{exact:true}).fill(`本地酒类${width}`);await custody.getByRole('button',{name:'查询统计',exact:true}).click();await expect(custody).toContainText('存酒 1 单 · 登记价值 12.50 CNY')
 const reportDownload=page.waitForEvent('download');await custody.getByRole('button',{name:'导出所选范围',exact:true}).click();const report=await reportDownload;expect(report.suggestedFilename()).toBe('MBOX-可选范围报表.xlsx');await report.saveAs(testInfo.outputPath('selected-report.xlsx'));await custody.getByText('数据中心：选择统计范围',{exact:true}).click()
 expect(errors).toEqual([])
 const dimensions=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,content:Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)}));expect(dimensions.content).toBeLessThanOrEqual(dimensions.viewport+1)
 await custody.getByText('存酒配置与品类',{exact:true}).click();await custody.getByText('录入新存酒',{exact:true}).click()
 await custody.screenshot({path:testInfo.outputPath('custody.png')})
})
