import { readFile } from 'node:fs/promises'
import { expect, test } from '@playwright/test'

for (const width of [320, 360]) test(`ordinary member card review and lifecycle at ${width}px`, async ({ page }, testInfo) => {
  const fixture = JSON.parse(await readFile('artifacts/normalized-browser/fixture.json', 'utf8'))
  test.skip(!fixture.memberCardFixture, 'Requires opt-in isolated card fixture; no production permission changes')
  const errors:string[]=[]
  page.on('pageerror',error=>errors.push(error.message))
  await page.setViewportSize({ width, height: 800 })
  await page.goto(fixture.staffUrl)
  await page.getByLabel('门店口令').fill(fixture.dailyCredential)
  await page.getByRole('button', { name: /验证设备/ }).click()
  await page.getByLabel('员工账号').fill(fixture.employeeCode)
  await page.getByLabel('四位 PIN').fill(fixture.employeePin)
  await page.getByRole('button', { name: /进入工作台/ }).click()
  await expect(page.getByTestId('normalized-workspace')).toBeVisible()
  await page.goto('/staff/member-management')
  const panel=page.locator('.member-card-management')
  await panel.getByRole('button',{name:'读取 / 刷新',exact:true}).click()
  const application=panel.locator('article').filter({hasText:`MBX-CARD${width}`})
  await expect(application).toHaveCount(1)
  await expect(application).toContainText('金卡')
  await application.getByRole('button',{name:'通过',exact:true}).click()
  await expect(panel.getByRole('status')).toContainText(`MBX-CARD${width}：通过成功`)
  await expect(application).toHaveCount(0)
  await panel.getByText('持卡状态管理',{exact:true}).click()
  await panel.getByRole('button',{name:'读取 / 刷新持卡',exact:true}).click()
  const holding=panel.locator('article').filter({hasText:`browser-card-${width}`})
  await expect(holding).toContainText('有效')
  await panel.getByLabel('变更原因',{exact:true}).fill('隔离持卡生命周期验收')
  for(const action of ['冻结','恢复','撤销']){
    await holding.getByRole('button',{name:action,exact:true}).click()
    await page.getByRole('alertdialog').getByRole('button',{name:'确认',exact:true}).click()
    await expect(panel.getByRole('status')).toContainText(`持卡已${action}`)
  }
  await expect(holding.getByRole('button',{name:'恢复',exact:true})).toHaveCount(0)
  await expect(holding).toContainText('已撤销')
  await panel.getByText('卡项目配置与开放',{exact:true}).click()
  await panel.getByLabel('项目编号',{exact:true}).fill(`DRAFT_${width}_${Date.now()}`)
  await panel.getByLabel('名称',{exact:true}).fill('后台草稿测试卡')
  await panel.getByLabel('开始时间（北京时间）',{exact:true}).fill('2037-09-01T00:00')
  await panel.getByLabel('结束时间（北京时间）',{exact:true}).fill('2037-10-01T00:00')
  await panel.getByLabel('顾客申请说明',{exact:true}).fill('这是隔离测试说明，保存不会发卡或发券。')
  await panel.getByRole('button',{name:'保存未开放草稿'}).click()
  await expect(panel.getByRole('status')).toContainText('已保存草稿，尚未开放申请')
  const dimensions=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,content:Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)}))
  expect(dimensions.content).toBeLessThanOrEqual(dimensions.viewport+1)
  await panel.screenshot({path:testInfo.outputPath('member-cards.png')})
  expect(errors).toEqual([])
})
