import { readFile } from 'node:fs/promises'
import { expect, test } from '@playwright/test'

for (const viewportWidth of [320, 360]) test(`staff previews stacking and calendar at ${viewportWidth}px without changing prices`, async ({ page, browser }, testInfo) => {
  const fixture = JSON.parse(await readFile('artifacts/normalized-browser/fixture.json', 'utf8'))
  await page.setViewportSize({ width: viewportWidth, height: 800 })
  await page.goto(fixture.staffUrl)
  await page.getByLabel('门店口令').fill(fixture.dailyCredential)
  await page.getByRole('button', { name: /验证设备/ }).click()
  // Store managers may edit commercial drafts; system administrators must not
  // acquire this authority merely because they administer employee accounts.
  await page.getByLabel('员工账号').fill(fixture.employeeCode)
  await page.getByLabel('四位 PIN').fill(fixture.employeePin)
  await page.getByRole('button', { name: /进入工作台/ }).click()
  await expect(page.getByTestId('normalized-workspace')).toBeVisible()
  await page.goto('/staff/member-rule-drafts')
  await page.getByRole('button', { name: /会员经营配置中心/ }).click()
  const panel = page.locator('details').filter({ has: page.locator('summary').filter({ hasText: /^优惠叠加规则试算$/ }) })
  await panel.locator('summary').click()
  await panel.getByRole('button', { name: '服务端试算' }).click()
  await expect(panel.getByText('实付 ¥9.90 · 优惠 ¥58.10')).toBeVisible()
  await panel.getByLabel('会员价', { exact: true }).check()
  await panel.getByLabel('计算顺序').selectOption('coupon,member,points')
  await panel.getByRole('button', { name: '服务端试算' }).click()
  await expect(panel.getByText('实付 ¥8.91 · 优惠 ¥59.09')).toBeVisible()
  const code = `E2E_${Date.now()}`
  await panel.getByLabel('规则编号').fill(code)
  await panel.getByLabel('修改原因').fill('隔离环境验证叠加配置')
  const response = page.waitForResponse(candidate => candidate.url().endsWith('/stacking-price-drafts') && candidate.request().method() === 'POST')
  await panel.getByRole('button', { name: '保存为第1版草稿' }).click()
  expect((await response).status()).toBe(201)
  await expect(panel.getByText(`已保存 ${code} 第1版草稿，尚未发布，不改变订单价格。`)).toBeVisible()
  await panel.getByRole('button', { name: '读取最近50个草稿版本' }).click()
  await expect(panel.getByRole('combobox',{name:'选择版本',exact:true}).locator('option').filter({hasText:code})).toHaveCount(1)
  await panel.getByRole('combobox',{name:'选择版本',exact:true}).selectOption({ label: `${code} · 第1版（草稿）` })
  await expect(panel.getByLabel('计算顺序')).toHaveValue('coupon,member,points')
  await expect(panel.getByRole('button', { name: '保存为第2版草稿' })).toBeVisible()
  await page.locator('.coupon-calendar-preview summary').click()
  const calendar = page.locator('.coupon-calendar-preview')
  // 2037 has the same September weekday layout as 2026, without expiring this
  // isolated publication test immediately after the development month.
  await calendar.getByLabel('可用日期起', { exact: true }).fill('2037-09-01')
  await calendar.getByLabel('可用日期止（含当天）', { exact: true }).fill('2037-09-30')
  await calendar.getByLabel('绝对截止时间（北京时间）').fill('2037-10-01T06:00')
  await calendar.getByLabel('日期归属', { exact: true }).selectOption('business')
  await calendar.getByRole('button', { name: '生成可用日历' }).click()
  await expect(calendar.getByText(/最后截止：10\/01 02:00/)).toBeVisible()
  await expect(calendar.locator('.coupon-calendar-days li')).toHaveCount(30)
  await calendar.getByLabel('绝对截止时间（北京时间）').fill('2037-10-01T00:00')
  await expect(calendar.locator('.coupon-calendar-days')).toHaveCount(0)
  await calendar.getByRole('button', { name: '生成可用日历' }).click()
  await expect(calendar.getByText(/最后截止：10\/01 00:00/)).toBeVisible()
  await calendar.getByRole('button', { name: '添加时间段' }).click()
  await calendar.getByLabel('时段2开始').fill('22:00')
  await calendar.getByLabel('时段2结束').fill('01:00')
  await calendar.getByRole('button', { name: '生成可用日历' }).click()
  const lastDay = calendar.locator('.coupon-calendar-days li').filter({ hasText: '2037-09-30' })
  await expect(lastDay).toHaveCount(1)
  await expect(lastDay).not.toContainText('；')
  const versions = calendar.getByRole('region', { name: '券时间规则版本管理' })
  const calendarCode = `CAL_${viewportWidth}_${Date.now()}`
  await versions.getByLabel('活动规则编号').fill(calendarCode)
  await versions.getByLabel('每人每日上限').fill('1')
  await versions.getByLabel('每人每周上限').fill('2')
  await versions.getByLabel('本次版本操作原因').fill('隔离页面时间规则版本测试')
  await versions.getByRole('button', { name: '保存时间规则第1版' }).click()
  await expect(versions.getByText(`已保存 ${calendarCode} 第1版草稿，未发布、未发券。`)).toBeVisible()
  await versions.getByRole('button', { name: '读取最近30个时间规则版本' }).click()
  await versions.getByLabel('选择时间规则版本', { exact: true }).selectOption({ label: `${calendarCode} · 第1版 · 草稿` })
  await expect(versions.getByLabel('每人每日上限')).toHaveValue('1')
  await expect(calendar.getByLabel('时段2结束')).toHaveValue('01:00')
  await expect(versions.getByRole('button', { name: '审批时间规则' })).toHaveCount(0)
  await calendar.getByRole('button', { name: '生成可用日历' }).click()
  await expect(calendar.getByText(/最后截止：10\/01 00:00/)).toBeVisible()
  const width = await page.evaluate(() => ({ viewport: document.documentElement.clientWidth, content: Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) }))
  expect(width.content).toBeLessThanOrEqual(width.viewport + 1)
  await calendar.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('coupon-calendar.png') })
  for (const [employeeCode, buttonLabel, confirmation, previousStatus, nextStatus] of [
    ['hugu', '审批时间规则', '确认审批', '草稿', '待发布'],
    ['chenfangyu', '发布时间规则', '确认发布', '待发布', '已发布'],
    ['chenfangyu', '停止此版本新发券', '确认停发', '已发布', '已停发'],
  ]) {
    const context = await browser.newContext({ viewport: { width: viewportWidth, height: 800 } })
    try {
      const reviewer = await context.newPage()
      const origin = new URL(page.url()).origin
      await reviewer.goto(origin)
      await reviewer.getByLabel('门店口令').fill(fixture.dailyCredential)
      await reviewer.getByRole('button', { name: /验证设备/ }).click()
      await reviewer.getByLabel('员工账号').fill(employeeCode!)
      await reviewer.getByLabel('四位 PIN').fill(fixture.employeePin)
      await reviewer.getByRole('button', { name: /进入工作台/ }).click()
      await expect(reviewer.getByTestId('normalized-workspace')).toBeVisible()
      await reviewer.goto(`${origin}/staff/member-management`)
      await reviewer.getByRole('button', { name: /会员经营配置中心/ }).click()
      if(previousStatus!=='已发布'){
      const stacking=reviewer.locator('details').filter({has:reviewer.locator('summary').filter({hasText:/^优惠叠加规则试算$/})})
      await stacking.locator('summary').click()
      await stacking.getByRole('button',{name:'读取最近50个草稿版本'}).click()
      await stacking.getByRole('combobox',{name:'选择版本',exact:true}).selectOption({label:`${code} · 第1版（${employeeCode==='hugu'?'草稿':'已审核'}）`})
      await stacking.getByLabel('审核／发布／停发原因',{exact:true}).fill('隔离环境逐级审核叠加规则')
      const stackingDecision=reviewer.waitForResponse(r=>r.url().includes('/stacking-price-drafts/')&&r.url().endsWith('/decisions')&&r.request().method()==='POST')
      await stacking.getByRole('button',{name:employeeCode==='hugu'?'审核已保存版本':'发布已审核版本',exact:true}).click()
      await reviewer.getByRole('alertdialog').getByRole('button',{name:'确认记录',exact:true}).click()
      const stackingResponse=await stackingDecision
      expect(stackingResponse.status()).toBe(200)
      expect((await stackingResponse.json()).data.status).toBe(employeeCode==='hugu'?'approved':'published')
      await expect(stacking.getByText('决定已保存；不会改变已发券的原承诺。')).toBeVisible()
      if(employeeCode==='chenfangyu'){
        await stacking.getByLabel('审核／发布／停发原因',{exact:true}).fill('验证停发保留既有版本')
        const stopped=reviewer.waitForResponse(r=>r.url().includes('/stacking-price-drafts/')&&r.url().endsWith('/decisions')&&r.request().method()==='POST')
        await stacking.getByRole('button',{name:'停止新发券使用',exact:true}).click()
        await reviewer.getByRole('alertdialog').getByRole('button',{name:'确认记录',exact:true}).click()
        expect((await(await stopped).json()).data.status).toBe('stopped')
      }
      const stackingWidth=await reviewer.evaluate(()=>({content:Math.max(document.documentElement.scrollWidth,document.body.scrollWidth),viewport:document.documentElement.clientWidth}))
      expect(stackingWidth.content).toBeLessThanOrEqual(stackingWidth.viewport+1)
      }
      await reviewer.locator('.coupon-calendar-preview summary').click()
      const management = reviewer.getByRole('region', { name: '券时间规则版本管理' })
      await management.getByRole('button', { name: '读取最近30个时间规则版本' }).click()
      await management.getByLabel('选择时间规则版本', { exact: true }).selectOption({ label: `${calendarCode} · 第1版 · ${previousStatus}` })
      await management.getByLabel('本次版本操作原因').fill('隔离岗位规则审批发布验收')
      await management.getByRole('button', { name: buttonLabel!, exact: true }).click()
      await reviewer.getByRole('alertdialog').getByRole('button', { name: confirmation!, exact: true }).click()
      await expect(management.getByText(`已选：${calendarCode} 第1版 · ${nextStatus}`)).toBeVisible()
      const reviewWidth = await reviewer.evaluate(() => ({ content: Math.max(document.documentElement.scrollWidth, document.body.scrollWidth), viewport: document.documentElement.clientWidth }))
      expect(reviewWidth.content).toBeLessThanOrEqual(reviewWidth.viewport + 1)
    } finally { await context.close() }
  }
  await calendar.getByLabel('发放后有效天数（留空仅按固定日期）').fill('2')
  await calendar.getByLabel('发放后有效期口径').selectOption('natural_end')
  await calendar.getByLabel('模拟发放时间（北京时间）').fill('2037-09-09T22:00')
  await calendar.getByRole('button',{name:'生成可用日历'}).click()
  await expect(calendar.getByText(/最后截止：09\/10 02:00/)).toBeVisible()
  await versions.getByLabel('活动规则编号').fill(`REL_${viewportWidth}_${Date.now()}`)
  await versions.getByLabel('本次版本操作原因').fill('验证发放后有效期保存和读取')
  await versions.getByRole('button',{name:'保存时间规则第1版'}).click()
  await expect(versions.getByText(/已保存 REL_.*第1版草稿/)).toBeVisible()
  await versions.getByRole('button',{name:'读取最近30个时间规则版本'}).click()
  await versions.getByLabel('选择时间规则版本',{exact:true}).selectOption({label:(await versions.getByLabel('选择时间规则版本',{exact:true}).locator('option').allTextContents()).find(value=>value.startsWith(`REL_${viewportWidth}_`))!})
  await expect(calendar.getByLabel('发放后有效天数（留空仅按固定日期）')).toHaveValue('2')
  await expect(calendar.getByLabel('发放后有效期口径')).toHaveValue('natural_end')
  await expect(calendar.getByLabel('模拟发放时间（北京时间）')).toHaveValue('')
})
