import { readFile } from 'node:fs/promises'
import { expect, test } from '@playwright/test'

for (const width of [320, 390]) test(`printer recovery is isolated and readable at ${width}px`, async ({ page }, testInfo) => {
  const fixture = JSON.parse(await readFile('artifacts/normalized-browser/fixture.json', 'utf8'))
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width, height: 800 })
  await page.goto(fixture.staffUrl)
  await page.getByLabel('门店口令').fill(fixture.dailyCredential)
  await page.getByRole('button', { name: /验证设备/ }).click()
  const cashier = fixture.employees.find((employee: { code: string; roleNames: string[] }) => employee.roleNames.includes('收银员'))
  if (!cashier) throw new Error('Missing isolated cashier fixture')
  await page.getByLabel('员工账号').fill(cashier.code)
  await page.getByLabel('四位 PIN').fill(fixture.employeePin)
  await page.getByRole('button', { name: /进入工作台/ }).click()
  await expect(page.getByTestId('normalized-workspace')).toBeVisible()
  const sourceResponse = page.waitForResponse(response => response.url().endsWith('/api/hardware/print-sources') && response.request().method() === 'GET')
  await page.goto('/staff/devices')
  await expect(page.getByRole('heading', { name: '票据生成检查' })).toBeVisible()
  const response = await sourceResponse
  expect(response.status()).toBe(200)
  const sourceRows = (await response.json()).data
  expect(Array.isArray(sourceRows)).toBe(true)
  const sources=page.locator('.print-source-recovery').filter({has:page.getByRole('heading',{name:'票据生成检查'})})
  await expect(sources.locator('article')).toHaveCount(sourceRows.length)
  const policies=page.locator('.print-source-recovery').filter({has:page.getByRole('heading',{name:'自动打印单据'})})
  await expect(policies.locator('article')).toHaveCount(9)
  const cardHeights=await policies.locator('article').evaluateAll(elements=>elements.map(e=>e.getBoundingClientRect().height))
  expect(Math.max(...cardHeights)).toBeLessThan(180)
  const prebill=policies.locator('article').filter({hasText:'预结算单（未收款）'})
  await prebill.getByLabel('自动打印').check()
  await prebill.getByLabel('份数').selectOption('2')
  await policies.getByLabel('修改原因').fill('隔离验收预结算两份')
  await prebill.getByRole('button',{name:'保存',exact:true}).click()
  await expect(policies.getByText('已保存；只影响后续生成的票据，已排队票据请在打印任务中处理。')).toBeVisible()
  await policies.getByRole('button',{name:'重新读取规则（放弃未保存选择）'}).click()
  await expect(prebill.getByLabel('份数')).toHaveValue('2')
  await expect(prebill.getByLabel('自动打印')).toBeChecked()
  if (sourceRows.length === 0) await expect(page.getByText('当前没有待处理的票据生成记录。')).toBeVisible()
  await page.route('**/api/hardware/print-sources', route => route.fulfill({ status: 503, json: { error: { code: 'TEST_READ_UNAVAILABLE' } } }))
  await page.getByRole('button', { name: '刷新生成状态' }).click()
  await expect(page.getByText('票据生成状态暂未读到，可重试；不影响营业')).toBeVisible()
  const dimensions = await page.evaluate(() => ({ viewport: document.documentElement.clientWidth,
    content: Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) }))
  expect(dimensions.content).toBeLessThanOrEqual(dimensions.viewport + 1)
  await page.screenshot({ path: testInfo.outputPath('print-recovery.png'), fullPage: true })
  await page.goto('/staff/payments')
  const history=page.locator('[aria-label="营业日账务与历史订单"]')
  await history.getByText('营业日账务与历史订单',{exact:true}).click()
  const historyResponse=page.waitForResponse(response=>response.url().includes('/api/operations/history?'))
  await history.getByRole('button',{name:'查看账务与历史'}).click()
  expect((await historyResponse).status()).toBe(200)
  await expect(history.getByRole('heading',{name:/全店已入账资金/})).toBeVisible()
  const exportButton=history.getByRole('button',{name:'导出全部筛选结果'})
  // The complete business-day suite has real fixture orders; an isolated empty day must not export fictional rows.
  if(await exportButton.isEnabled()){
    const exported=page.waitForEvent('download')
    const exportResponse=page.waitForResponse(response=>response.url().includes('exportAll=true'))
    await exportButton.click()
    expect((await exportResponse).status()).toBe(200)
    const download=await exported
    expect(download.suggestedFilename()).toContain('全部筛选结果')
    const stream=await download.createReadStream()
    const chunks:Buffer[]=[]
    for await(const chunk of stream!)chunks.push(Buffer.from(chunk))
    const csv=Buffer.concat(chunks).toString('utf8')
    expect(csv).toContain('送达员工');expect(csv).toContain('送达时间')
    expect(csv.split('\r\n').length).toBeGreaterThan(1)
  }else await expect(history.getByText('没有符合筛选条件的订单。')).toBeVisible()
  const historyWidth=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,content:document.documentElement.scrollWidth}))
  expect(historyWidth.content).toBeLessThanOrEqual(historyWidth.viewport+1)
  await page.screenshot({path:testInfo.outputPath('operating-history.png'),fullPage:true})
  await page.goto('/staff/floor')
  await expect(page.getByTestId('normalized-workspace')).toBeVisible()
  expect(errors).toEqual([])
})
