import {readFile} from 'node:fs/promises'
import {test,expect,type Page} from '@playwright/test'
test.use({viewport:{width:1024,height:600},isMobile:false,hasTouch:true})
const fixture=async()=>JSON.parse(await readFile('artifacts/normalized-browser/fixture.json','utf8'))
async function login(page:Page,code:string){
  const f=await fixture();test.skip(!f.threeScreenFixture,'requires isolated three-screen fixture')
  await page.goto('/')
  await page.getByLabel('门店口令').fill(f.dailyCredential);await page.getByRole('button',{name:/验证设备/}).click()
  await page.getByLabel('员工账号').fill(code);await page.getByLabel('四位 PIN').fill(f.employeePin)
  await page.getByRole('button',{name:/进入工作台/}).click();await expect(page.getByTestId('normalized-workspace')).toBeVisible()
  return f
}

test('取餐最小权限从普通出品入口进入，不请求桌台、不反复退回登录',async({page})=>{
  const f=await login(page,'test_pickup_only')
  const session=await page.request.get('/api/auth/session');expect((await session.json()).data.permissions).toEqual(['kds.deliver'])
  expect((await page.request.get('/api/operations')).status()).toBe(403)
  let operations=0;page.on('request',r=>{if(new URL(r.url()).pathname==='/api/operations')operations++})
  await page.goto('/staff/fulfillment')
  await expect(page.getByRole('heading',{name:'本机尚未设为取餐屏'})).toBeVisible()
  await expect(page.getByRole('button',{name:'设为取餐屏',exact:true})).toHaveCount(0)
  await expect(page.getByLabel('员工账号')).toHaveCount(0)
  await page.reload();await expect(page.getByRole('heading',{name:'本机尚未设为取餐屏'})).toBeVisible()
  expect(operations).toBe(0);expect((await page.request.get('/api/auth/session')).status()).toBe(200)
  // Configure only this isolated browser's device as an administrator, then restore the restricted account.
  expect((await page.request.post('/api/auth/switch',{data:{employeeCode:'wuya',pin:f.employeePin}})).ok()).toBe(true)
  await page.goto('/staff/fulfillment?screen=pickup')
  await page.getByRole('button',{name:'设为取餐屏',exact:true}).click()
  await page.getByRole('button',{name:'切换工作账号',exact:true}).click()
  await page.getByLabel('员工账号').fill('test_pickup_only');await page.getByLabel('四位 PIN').fill(f.employeePin)
  await page.getByRole('button',{name:/进入工作台/}).click()
  await expect(page.locator('.pickup-connection')).toHaveText('已更新');await expect(page.locator('.pickup-waiting')).toBeVisible()
  await page.goto('/staff/fulfillment')
  await expect(page.locator('.pickup-connection')).toHaveText('已更新');await expect(page.locator('.pickup-waiting')).toBeVisible()
  const pickup=await page.request.get('/api/commerce/pickup-board')
  expect((await pickup.json()).data.actor).toMatchObject({canPickup:true,canConfigure:false})
  let leaseReads=0
  await page.route('**/api/commerce/pickup-board',r=>++leaseReads===1?r.fulfill({status:403,json:{error:{code:'PICKUP_SESSION_INVALID',message:'登录已过期'}}}):r.continue())
  await page.reload();await expect(page.locator('.pickup-connection')).toHaveText('已更新');await expect(page.locator('.pickup-waiting')).toBeVisible()
  expect(leaseReads).toBeGreaterThanOrEqual(2)
  await page.unroute('**/api/commerce/pickup-board')
  await page.route('**/api/commerce/pickup-board',r=>r.fulfill({status:403,json:{error:{code:'PICKUP_FORBIDDEN',message:'当前岗位没有取餐权限'}}}))
  await page.reload();await expect(page.getByText('当前岗位没有取餐权限')).toBeVisible()
  await expect(page.getByRole('button',{name:'恢复登录',exact:true})).toHaveCount(0)
  expect((await page.request.get('/api/auth/session')).status()).toBe(200)
})

test('普通出品权限拒绝保留登录，不再形成登录循环',async({page})=>{
  await login(page,'shenliangliang')
  await page.route('**/api/operations',r=>r.fulfill({status:403,json:{error:{code:'STAFF_ACCESS_FORBIDDEN',message:'当前岗位没有桌台看板权限'}}}))
  await page.goto('/staff/fulfillment?view=all')
  await expect(page.getByText('当前岗位没有桌台看板权限')).toBeVisible()
  await expect(page.getByLabel('员工账号')).toHaveCount(0)
  expect((await page.request.get('/api/auth/session')).status()).toBe(200)
})

for(const [code,station,label] of [['shenliangliang','kitchen','后厨'],['lengyanzhi','bar','酒水']] as const){
  test(`${label}默认入口及返回旧页后完成新批次，不再发送错误的旧命令`,async({page})=>{
    const f=await login(page,code);let legacyWrites=0
    page.on('request',r=>{if(r.method()==='POST'&&/\/api\/commerce\/kds\/.+\/actions$/.test(new URL(r.url()).pathname))legacyWrites++})
    await page.goto('/staff/fulfillment');await expect(page).toHaveURL(new RegExp(`screen=${station}`))
    await page.getByRole('region',{name:'待制作',exact:true}).getByRole('button').filter({hasText:f.threeScreenFixture.products[station].name}).first().click()
    const before=await page.request.get(`/api/commerce/kitchen-board?station=${station}`)
    const beforeIds=new Set((await before.json()).data.batches.map((b:{id:string})=>b.id))
    await page.getByRole('button',{name:'开始制作 2 份',exact:true}).click()
    await expect(page.getByRole('button',{name:'本页 2 份已放好',exact:true})).toBeEnabled()
    const created=await page.request.get(`/api/commerce/kitchen-board?station=${station}`)
    const newBatch=(await created.json()).data.batches.find((b:{id:string})=>!beforeIds.has(b.id))
    expect(newBatch).toBeTruthy()
    await page.getByRole('button',{name:'返回出品',exact:true}).click()
    await expect(page).toHaveURL(/view=all/)
    const link=page.getByRole('button',{name:`到${label}制作屏完成`,exact:true}).first()
    await expect(link).toBeVisible()
    await expect(link.locator('..').getByRole('button',{name:'制作完成',exact:true})).toHaveCount(0)
    await link.click();await expect(page).toHaveURL(new RegExp(`screen=${station}`))
    await page.getByRole('button',{name:'本页 2 份已放好',exact:true}).click()
    await expect.poll(async()=>{const r=await page.request.get(`/api/commerce/kitchen-board?station=${station}`);return (await r.json()).data.batches.filter((b:{id:string;units:{state:string}[]})=>b.id===newBatch.id&&b.units.some(u=>u.state==='started')).length}).toBe(0)
    expect(legacyWrites).toBe(0)
  })
}


test('后厨只有在制批次时直接展示制作中，整页刷新保留份数且不提交命令',async({page})=>{
  const f=await login(page,'shenliangliang')
  await page.goto('/staff/fulfillment?screen=kitchen')
  await page.getByRole('region',{name:'待制作',exact:true}).getByRole('button').filter({hasText:f.threeScreenFixture.products.kitchen.name}).first().click()
  await page.getByRole('button',{name:'开始制作 2 份',exact:true}).click()
  await expect(page.getByRole('button',{name:'本页 2 份已放好',exact:true})).toBeEnabled()
  const state=await page.evaluate(()=>Object.keys(localStorage).find(key=>key.startsWith('mbox.kitchen.drafts.v1:'))!)
  const batchId=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!).selectedBatch,state)
  await page.route('**/api/commerce/kitchen-board?station=kitchen',async route=>{
    const response=await route.fetch(),body=await response.json()
    body.data.pending=[];body.data.batches=body.data.batches.filter((b:{id:string})=>b.id===batchId)
    await route.fulfill({response,json:body})
  })
  await page.evaluate(key=>localStorage.removeItem(key),state)
  await page.setViewportSize({width:600,height:960});await page.reload()
  const working=page.getByRole('region',{name:'正在制作',exact:true})
  await expect(working).toBeVisible()
  await working.locator('.kitchen-group').first().click()
  await working.getByRole('spinbutton').first().fill('1')
  await page.evaluate(()=>{document.querySelector<HTMLMetaElement>('meta[name="mbox-build-commit"]')!.content='a'.repeat(40)})
  let newer=false
  await page.route('**/staff/fulfillment?screen=kitchen',route=>route.request().isNavigationRequest()?route.continue():route.fulfill(newer?{contentType:'text/html',body:`<meta name="mbox-build-commit" content="${'b'.repeat(40)}">`}:{status:503,body:'unavailable'}))
  let documents=0,writes=0
  page.on('request',r=>{if(r.isNavigationRequest()&&r.frame()===page.mainFrame())documents++;if(r.method()==='POST'&&r.url().includes('/kitchen-board/commands'))writes++})
  await page.getByRole('button',{name:'刷新',exact:true}).click()
  await expect(page.getByRole('button',{name:'刷新',exact:true})).toBeEnabled()
  expect(documents).toBe(0)
  await expect(working.getByRole('spinbutton').first()).toHaveValue('1')
  newer=true
  await page.getByRole('button',{name:'刷新',exact:true}).click()
  await expect.poll(()=>documents).toBe(1)
  await expect(working.getByRole('spinbutton').first()).toHaveValue('1')
  await expect(page.getByRole('button',{name:'本页 1 份已放好',exact:true})).toBeEnabled()
  expect(writes).toBe(0)
  await page.getByRole('navigation',{name:'制作工序切换'}).getByRole('button',{name:/待制作/}).click()
  await expect(page.getByRole('region',{name:'待制作',exact:true})).toBeVisible()
  // Polls must not take the employee back to another pane after an explicit choice.
  await expect(working).toBeHidden();await page.waitForTimeout(5200);await expect(working).toBeHidden()
  await page.getByRole('navigation',{name:'制作工序切换'}).getByRole('button',{name:/制作中/}).click()
  await page.route('**/api/commerce/kitchen-board/commands',route=>route.abort('connectionfailed'))
  await page.getByRole('button',{name:'本页 1 份已放好',exact:true}).click()
  await expect(page.getByRole('button',{name:'恢复原操作',exact:true})).toBeEnabled()
  await expect(page.getByRole('button',{name:'刷新',exact:true})).toBeDisabled()
  expect(writes).toBe(1)
  await page.reload()
  await expect(page.getByRole('button',{name:'恢复原操作',exact:true})).toBeEnabled()
  await expect(page.getByRole('button',{name:'刷新',exact:true})).toBeDisabled()
  expect(writes).toBe(1)
})
