import {describe,it,expect} from 'vitest'
import {qualifyCheckoutUpgrade,parseUpgradeQualificationRule,type UpgradeQualificationFacts} from './checkout-upgrade-eligibility.js'
const rule={maximumAddMinor:3000,maximumAddBasisPoints:2000,minimumContributionMinor:1000,minimumIncrementalContributionMinor:0,minimumMarginBasisPoints:2000,minimumPartySize:1,maximumPartySize:4,requiredOccasions:[],requiredAlcoholPreferences:[],maximumQuantitiesPerPerson:[{productId:'snack',quantity:1}],excludedProductIds:['allergen'],positiveFitReason:'保留原酒水，增加明确适配的小食'}
const core={productId:'cocktail',specificationId:'ml60',optionKey:'no_ice',quantity:1},snack={productId:'snack',specificationId:'one',optionKey:'normal',quantity:1}
const facts=():UpgradeQualificationFacts=>({published:true,available:true,inventoryKnownAndSufficient:true,productionAvailable:true,partySize:2,occasion:null,alcoholPreference:null,originalPayableMinor:22800,upgradedPayableMinor:25800,originalCostMinor:8000,upgradedCostMinor:9000,sourcePortionPayableMinor:22800,targetPortionPayableMinor:25800,sourcePortionCostMinor:8000,targetPortionCostMinor:9000,originalComposition:[core],upgradedComposition:[core,snack],otherTableComposition:[],restrictionsVerified:true,restrictionsSatisfied:true,choicesComplete:true,quoteComparable:true})
describe('strict checkout upgrade eligibility before ranking',()=>{
  it('allows a matching configured mapping without forcing an unnecessary questionnaire',()=>{expect(qualifyCheckoutUpgrade(rule,facts())).toMatchObject({eligible:true,addedPayableMinor:3000,contributionMinor:16800,incrementalContributionMinor:2000})})
  it.each(['published','available','inventoryKnownAndSufficient','productionAvailable','restrictionsVerified','restrictionsSatisfied','choicesComplete','quoteComparable'] as const)('fails closed for %s',key=>{expect(qualifyCheckoutUpgrade(rule,{...facts(),[key]:false}).eligible).toBe(false)})
  it.each(['originalPayableMinor','upgradedPayableMinor','originalCostMinor','upgradedCostMinor','sourcePortionPayableMinor','targetPortionPayableMinor','sourcePortionCostMinor','targetPortionCostMinor','partySize'] as const)('does not treat unknown %s as zero',key=>{expect(qualifyCheckoutUpgrade(rule,{...facts(),[key]:null}).eligible).toBe(false)})
  it('rejects the 228-to-258 example when cost grows by 55 and contribution decreases',()=>{expect(qualifyCheckoutUpgrade(rule,{...facts(),upgradedCostMinor:13500})).toMatchObject({eligible:false,reason:'contribution_or_margin_limit'})})
  it('checks both absolute and relative price ceilings, including zero denominator',()=>{expect(qualifyCheckoutUpgrade({...rule,maximumAddBasisPoints:1000},facts()).eligible).toBe(false);expect(qualifyCheckoutUpgrade({...rule,maximumAddMinor:2999},facts()).eligible).toBe(false);expect(qualifyCheckoutUpgrade({...rule,minimumIncrementalContributionMinor:0},{...facts(),originalPayableMinor:0,upgradedPayableMinor:1000,originalCostMinor:0,upgradedCostMinor:0,sourcePortionPayableMinor:0,targetPortionPayableMinor:1000,sourcePortionCostMinor:0,targetPortionCostMinor:0})).toMatchObject({reason:'relative_added_price_limit'})})
  it('does not use another expensive table item to relax the source portion relative ceiling',()=>{
    expect(qualifyCheckoutUpgrade(rule,{...facts(),originalPayableMinor:100000,upgradedPayableMinor:103000,sourcePortionPayableMinor:1000,targetPortionPayableMinor:4000,sourcePortionCostMinor:100,targetPortionCostMinor:200})).toMatchObject({reason:'relative_added_price_limit'})
  })
  it('does not hide poor target portion margin behind another profitable item',()=>{
    expect(qualifyCheckoutUpgrade({...rule,maximumAddBasisPoints:null},{...facts(),originalPayableMinor:100000,upgradedPayableMinor:103000,sourcePortionPayableMinor:1000,targetPortionPayableMinor:4000,sourcePortionCostMinor:100,targetPortionCostMinor:3900})).toMatchObject({reason:'contribution_or_margin_limit'})
  })
  it.each([{...core,productId:'different'},{...core,specificationId:'ml30'},{...core,optionKey:'with_ice'}])('preserves the exact core, specification and actual choice %j',changed=>{expect(qualifyCheckoutUpgrade(rule,{...facts(),upgradedComposition:[changed,snack]})).toMatchObject({reason:'core_or_option_changed'})})
  it('rejects missing portions context and meaningless repeated snacks rather than lowering rank',()=>{expect(qualifyCheckoutUpgrade(rule,{...facts(),otherTableComposition:null})).toMatchObject({reason:'table_portions_unknown'});expect(qualifyCheckoutUpgrade(rule,{...facts(),otherTableComposition:[{...snack,quantity:2}]})).toMatchObject({reason:'redundant_or_excessive_portions'})})
  it('needs explicit positive bounds for every added product and excludes restricted table products',()=>{expect(qualifyCheckoutUpgrade({...rule,maximumQuantitiesPerPerson:[]},facts())).toMatchObject({reason:'added_portion_rule_missing'});expect(qualifyCheckoutUpgrade(rule,{...facts(),otherTableComposition:[{...snack,productId:'allergen'}]})).toMatchObject({reason:'excluded_product_present'})})
  it('requires only the context actually declared by this rule',()=>{expect(qualifyCheckoutUpgrade({...rule,requiredOccasions:['birthday']},facts())).toMatchObject({reason:'occasion_missing_or_mismatch'});expect(qualifyCheckoutUpgrade({...rule,requiredAlcoholPreferences:['none']},facts())).toMatchObject({reason:'preference_missing_or_mismatch'})})
  it('does not charge more for identical composition',()=>{expect(qualifyCheckoutUpgrade(rule,{...facts(),upgradedComposition:[core]})).toMatchObject({reason:'no_meaningful_addition'})})
  it('rejects invalid or guessed policy defaults',()=>{expect(()=>parseUpgradeQualificationRule({...rule,maximumAddMinor:undefined})).toThrow();expect(()=>parseUpgradeQualificationRule({...rule,maximumQuantitiesPerPerson:[{productId:'snack',quantity:0}]})).toThrow();expect(()=>parseUpgradeQualificationRule({...rule,positiveFitReason:''})).toThrow()})
})
