import {z} from 'zod'
const integer=z.number().int().min(0).max(2147483647),positive=integer.min(1),text=z.string().trim().min(1).max(200),code=z.string().trim().regex(/^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$/),uuid=z.uuid(),date=z.iso.datetime({offset:true}),tier=z.enum(['member','silver','gold'])
export const membershipDomains=z.enum(['base_points','tier_policy','tier_benefits','redemption_catalog','promotion_points','membership_terms','wechat_notifications'])
export const nativeMembershipContent=z.discriminatedUnion('domain',[
 z.object({domain:z.literal('base_points'),pointsNumerator:integer,pointsDenominatorMinor:positive,growthNumerator:integer,growthDenominatorMinor:positive,roundingMode:z.enum(['floor','nearest']),pointsValidityMonths:positive.max(120)}).strict(),
 z.object({domain:z.literal('tier_policy'),evaluationWindowMonths:positive,tierPeriodMonths:positive,downgradeGraceDays:integer,silverUpgradeGrowth:integer,silverRetainGrowth:integer,goldUpgradeGrowth:integer,goldRetainGrowth:integer,silverPointsMultiplierNumerator:positive,silverPointsMultiplierDenominator:positive,goldPointsMultiplierNumerator:positive,goldPointsMultiplierDenominator:positive}).strict(),
 z.object({domain:z.literal('tier_benefits'),tierPolicyVersionId:uuid,rules:z.array(z.object({ruleCode:code,eligibleTier:tier,inheritToHigherTiers:z.boolean(),grantOnEntry:z.boolean(),grantOnRetention:z.boolean(),benefitDefinitionId:uuid,quantity:positive,validityDays:positive,revocationPolicy:z.enum(['revoke_unreserved','protect_until_expiry']),enabled:z.boolean()}).strict()).min(1).max(200)}).strict(),
 z.object({domain:z.literal('redemption_catalog'),items:z.array(z.object({publicId:code,itemCode:code,name:text,fulfillmentKind:z.enum(['product','benefit','activity','service']),productId:uuid.nullable(),benefitDefinitionId:uuid.nullable(),activityId:uuid.nullable(),pointsRequired:positive,costAmountMinor:integer,currency:z.literal('CNY'),totalInventory:integer.nullable(),dailyInventory:integer.nullable(),memberDailyLimit:positive,memberRolling30DayLimit:positive,memberLifetimeLimit:positive.nullable(),minimumTier:tier,requiresTableSession:z.boolean(),requiresEmployeeFulfillment:z.boolean(),cancellationAllowedBeforeFulfillment:z.boolean(),restoreExpiredPointsDays:integer,availableFrom:date,availableUntil:date.nullable(),fulfillmentTimeoutMinutes:positive,status:z.enum(['active','paused','retired'])}).strict()).min(1).max(200)}).strict(),
 z.object({domain:z.literal('promotion_points'),campaignCode:code,name:text,activityId:uuid,stackingGroup:code,stackingMode:z.enum(['stackable','exclusive_highest','exclusive_first']),priority:integer,storeBudgetPoints:positive,perMemberPointsLimit:positive,pointValidityDays:positive,refundPolicy:z.enum(['reverse_on_any_refund','reverse_on_full_refund']),budgetReuseAfterRefund:z.boolean(),memberLimitReuseAfterRefund:z.boolean(),eligibleMemberLevels:z.array(tier).min(1).max(3),rules:z.array(z.object({ruleCode:code,triggerKind:z.enum(['activity_payment','activity_check_in','activity_completion']),points:positive,perMemberAwardLimit:positive,minimumPaidAmountMinor:integer,enabled:z.boolean()}).strict()).min(1).max(200)}).strict(),
 z.object({domain:z.literal('membership_terms'),title:text,summary:z.string().trim().min(1).max(2000),content:z.string().trim().min(1).max(50000)}).strict(),
 z.object({domain:z.literal('wechat_notifications'),notificationType:z.enum(['loyalty_points_credited','loyalty_points_reversed','loyalty_points_expiring']),authorizationPurpose:z.enum(['loyalty_balance_change','loyalty_expiry_reminder']),authorizationContext:z.enum(['loyalty_accrual','loyalty_refund','loyalty_expiry']),templateId:text,pagePath:z.string().trim().min(1).max(500),pointsDataKey:text,balanceDataKey:text.nullable(),occurredAtDataKey:text,expiresAtDataKey:text.nullable(),expiryLeadDays:positive.nullable(),maxPerCustomerPer24h:positive,minimumIntervalMinutes:integer,quietHoursStart:z.string().regex(/^\d{2}:\d{2}(:\d{2})?$/).nullable(),quietHoursEnd:z.string().regex(/^\d{2}:\d{2}(:\d{2})?$/).nullable()}).strict(),
])
const reason=z.string().trim().min(2).max(500),target={domain:membershipDomains,configurationId:uuid,expectedRevision:positive}
export const nativeMembershipInput=z.discriminatedUnion('action',[
 z.object({action:z.literal('create'),content:nativeMembershipContent,reason}).strict(),
 z.object({action:z.literal('edit'),...target,content:nativeMembershipContent,reason}).strict(),
 z.object({action:z.literal('preview'),...target}).strict(),
 z.object({action:z.literal('approve'),...target,impactPreviewPublicId:code,reason}).strict(),
 z.object({action:z.literal('publish'),...target,effectiveFrom:date,effectiveUntil:date.nullable(),reason}).strict(),
 z.object({action:z.literal('control'),capability:z.enum(['points_accrual','points_redemption','wechat_notification']),operation:z.enum(['pause','resume']),expectedVersion:integer,reviewAt:date.nullable(),reason}).strict(),
])
export function nativeMembershipPermission(action:string,domain:string){
 if(action==='control')return 'loyalty.operations.control'
 if(action==='create')return domain==='redemption_catalog'?'loyalty.redemption.catalog.manage':domain==='promotion_points'?'loyalty.promotion.manage':domain==='membership_terms'?'membership.terms.manage':'loyalty.policy.manage'
 if(action==='publish')return domain==='redemption_catalog'?'loyalty.redemption.catalog.publish':domain==='promotion_points'?'loyalty.promotion.publish':domain==='membership_terms'?'membership.terms.publish':'loyalty.policy.publish'
 return 'loyalty.configuration.'+action
}
