import {createHash} from 'node:crypto'
import {z} from 'zod'
import type {FastifyPluginAsync,FastifyRequest} from 'fastify'
import {LoyaltyAnnualBenefitService,AnnualBenefitPolicyError,type AnnualBenefitStaffContext} from './loyalty-annual-benefit-service.js'
import {parseAnnualBenefitRule} from './loyalty-annual-benefit-api.js'
import {StaffAccessRepository,StaffAccessDeniedError,StaffNotFoundError} from './staff-access-repository.js'
import {nativeGuardedExecutor} from './native-guarded-executor.js'
import {nativePhysicalExecutor} from './native-physical-command.js'
import {NativeCommandNotCommittedError,IdempotencyConflictError,IdempotencyInProgressError,type NormalizedCommandExecutor,type IdempotentCommand,type CommandOutcome} from './command-executor.js'
import {isStaffAuthenticationRequiredError,STAFF_AUTHENTICATION_REQUIRED_ERROR} from './staff-api-authentication.js'
import type {ScopedPostgresTransactionRunner,ScopedTransaction} from './transaction-runner.js'
type Options={transactions:ScopedPostgresTransactionRunner;commands:Pick<NormalizedCommandExecutor,'execute'>;resolveContext(request:FastifyRequest):Promise<AnnualBenefitStaffContext>|AnnualBenefitStaffContext}
const root='/staff/native-annual-policies',uuid=z.string().uuid(),code=z.string().regex(/^[A-Z][A-Z0-9_]{2,63}$/),version=z.string().regex(/^[a-f0-9]{64}$/),reason=z.string().trim().min(2).max(500),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v})
const draft=z.object({policyCode:code,expectedLatest:z.number().int().nonnegative(),timezone:z.string().min(3).max(64),reason,rules:z.array(z.record(z.string(),z.unknown())).min(1).max(100).transform(a=>a.map(parseAnnualBenefitRule))}).strict()
const decision=z.object({policyId:uuid,expectedVersion:version,reason}).strict(),publish=decision.extend({effectiveFrom:z.string().datetime({offset:true}),effectiveUntil:z.string().datetime({offset:true}).nullable()}).strict(),occurrence=decision.extend({ruleId:uuid,cycleYear:z.number().int().min(2020).max(2200),startsOn:date,endsOn:date,confirmationReference:z.string().trim().min(2).max(240)}).strict()
const permissions={draft:'loyalty.annual-benefit.manage',approve:'loyalty.annual-benefit.approve',publish:'loyalty.annual-benefit.publish',occurrence:'loyalty.annual-benefit.occurrence.confirm'} as const
const fail=(message:string)=>new AnnualBenefitPolicyError('NATIVE_ANNUAL_CONFLICT',message)
function stamp(r:unknown):Record<string,unknown>&{nativeVersion:string}{const row=JSON.parse(JSON.stringify(r));return{...row,nativeVersion:createHash('sha256').update(JSON.stringify(row)).digest('hex')}}
type AnnualRule=Awaited<ReturnType<LoyaltyAnnualBenefitService['configuration']>>['rules'][number]
async function namedRules(tx:ScopedTransaction,rules:AnnualRule[]){
 const ids=[...new Set(rules.map(r=>r.benefitDefinitionId))],productIds=[...new Set(rules.flatMap(r=>(r.substitutes as Array<{productId:string}>).map(p=>p.productId)))];const definitions=ids.length?(await tx.query<{id:string;name:string}>('SELECT id,name FROM mbox.loyalty_benefit_definitions WHERE tenant_id=$1 AND store_id=$2 AND id=ANY($3::uuid[])',[tx.scope.tenantId,tx.scope.storeId,ids])).rows:[],products=productIds.length?(await tx.query<{id:string;name:string}>('SELECT id,name FROM mbox.products WHERE tenant_id=$1 AND store_id=$2 AND id=ANY($3::uuid[])',[tx.scope.tenantId,tx.scope.storeId,productIds])).rows:[];return rules.map(r=>({...r,benefitDefinitionName:definitions.find(d=>d.id===r.benefitDefinitionId)?.name??null,substitutes:(r.substitutes as Array<{productId:string}>).map(p=>({...p,productName:products.find(d=>d.id===p.productId)?.name??null}))}))
}
async function policy(tx:ScopedTransaction,ctx:AnnualBenefitStaffContext,commands:Options['commands'],id:string){const cfg=await new LoyaltyAnnualBenefitService({run:(_s,fn)=>fn(tx)},commands).configuration(ctx,{only:id}),r=cfg.policies[0];if(!r)throw fail('原年度权益配置不存在');return stamp({...r,rules:await namedRules(tx,cfg.rules.filter(x=>x.policyVersionId===r.id))})}
async function latest(tx:ScopedTransaction,code:string){return Number((await tx.query<{n:number}>('SELECT COALESCE(max(version),0) n FROM mbox.loyalty_annual_benefit_policy_versions WHERE tenant_id=$1 AND store_id=$2 AND policy_code=$3',[tx.scope.tenantId,tx.scope.storeId,code])).rows[0]!.n)}
export const nativeAnnualPolicyApiPlugin:FastifyPluginAsync<Options>=async(app,options)=>{
 app.addHook('onRequest',async(_r,reply)=>{reply.header('Cache-Control','private, no-store')})
 app.setErrorHandler((e,_r,reply)=>{
  if(isStaffAuthenticationRequiredError(e))return reply.code(401).send({error:STAFF_AUTHENTICATION_REQUIRED_ERROR})
  if(e instanceof StaffAccessDeniedError||e instanceof StaffNotFoundError)return reply.code(403).send({error:{code:'ANNUAL_POLICY_FORBIDDEN',message:'当前员工没有此年度权益权限'}})
  if(e instanceof NativeCommandNotCommittedError&&!(e.original instanceof IdempotencyConflictError)&&!(e.original instanceof IdempotencyInProgressError))return reply.code(409).send({error:{code:'NATIVE_BUSINESS_NOT_COMMITTED',message:e.original instanceof AnnualBenefitPolicyError?e.original.message:'原配置状态或履约条件已变化，请刷新核对',commitDisposition:'not_committed'}})
  if(e instanceof AnnualBenefitPolicyError||e instanceof z.ZodError)return reply.code(e instanceof AnnualBenefitPolicyError?e.statusCode:400).send({error:{code:'ANNUAL_POLICY_INVALID',message:e instanceof AnnualBenefitPolicyError?e.message:'请核对全部规则、日期与操作原因'}})
  if(e instanceof NativeCommandNotCommittedError||e instanceof IdempotencyConflictError||e instanceof IdempotencyInProgressError)return reply.code(409).send({error:{code:'ANNUAL_POLICY_UNCONFIRMED',message:'请保留原请求核对结果'}})
  throw e
 })
 app.get(root,async request=>{const q=z.object({cursor:uuid.optional(),code:code.optional()}).strict().parse(request.query),ctx=await options.resolveContext(request);return{data:await options.transactions.run(ctx.scope,async tx=>{await new StaffAccessRepository(tx).assertPermission(ctx.employeeId,'loyalty.annual-benefit.view');const cfg=await new LoyaltyAnnualBenefitService({run:(_s,fn)=>fn(tx)},options.commands).configuration(ctx,q),rules=await namedRules(tx,cfg.rules),rows=cfg.policies.slice(0,20).map(p=>stamp({...p,rules:rules.filter(r=>r.policyVersionId===p.id)}));return{employeeId:ctx.employeeId,protocol:1,durableCommands:true,rows,next:cfg.policies.length>20?rows[19]!.id:null,code:q.code??null,latest:q.code?await latest(tx,q.code):null}},{readOnly:true,isolation:'repeatable-read'})}})
 app.get(root+'/occurrences',async request=>{const q=z.object({ruleId:uuid,cursor:uuid.optional()}).strict().parse(request.query),ctx=await options.resolveContext(request);return{data:await options.transactions.run(ctx.scope,async tx=>{await new StaffAccessRepository(tx).assertPermission(ctx.employeeId,'loyalty.annual-benefit.view');const rows=(await tx.query<{id:string}>(`SELECT id,rule_id AS "ruleId",cycle_year AS "cycleYear",starts_on::text AS "startsOn",ends_on::text AS "endsOn",confirmed_by_employee_id AS "confirmedByEmployeeId",confirmation_reference AS "confirmationReference",confirmed_at::text AS "confirmedAt" FROM mbox.loyalty_annual_benefit_occurrences WHERE tenant_id=$1 AND store_id=$2 AND rule_id=$3 AND ($4::uuid IS NULL OR id>$4) ORDER BY id LIMIT 51`,[ctx.scope.tenantId,ctx.scope.storeId,q.ruleId,q.cursor??null])).rows;return{employeeId:ctx.employeeId,protocol:1,durableCommands:true,ruleId:q.ruleId,rows:rows.slice(0,50),next:rows.length>50?rows[49]!.id:null}},{readOnly:true})}})
 app.get(root+'/options',async request=>{const q=z.object({kind:z.enum(['definitions','products']),cursor:uuid.optional(),search:z.string().trim().max(80).default('')}).strict().parse(request.query),ctx=await options.resolveContext(request);return{data:await options.transactions.run(ctx.scope,async tx=>{await new StaffAccessRepository(tx).assertPermission(ctx.employeeId,'loyalty.annual-benefit.view');const from=q.kind==='definitions'?`loyalty_benefit_definitions p`:`products p`,extra=q.kind==='definitions'?`,p.benefit_kind AS "benefitKind",p.product_id AS "productId"`:'',filter=q.kind==='definitions'?'':`AND p.recommendation_beverage_family='non_alcoholic' AND EXISTS(SELECT 1 FROM mbox.recipes r JOIN mbox.recipe_items i ON i.tenant_id=r.tenant_id AND i.store_id=r.store_id AND i.recipe_id=r.id WHERE r.tenant_id=p.tenant_id AND r.store_id=p.store_id AND r.product_id=p.id AND r.status='active')`;const rows=(await tx.query<{id:string}>(`SELECT p.id,p.name,p.status ${extra} FROM mbox.${from} WHERE p.tenant_id=$1 AND p.store_id=$2 AND p.status='active' AND ($3::uuid IS NULL OR p.id>$3) AND p.name ILIKE $4 ${filter} ORDER BY p.id LIMIT 51`,[ctx.scope.tenantId,ctx.scope.storeId,q.cursor??null,'%'+q.search.replace(/[\\%_]/g,'\\$&')+'%'])).rows;return{employeeId:ctx.employeeId,protocol:1,durableCommands:true,rows:rows.slice(0,50),next:rows.length>50?rows[49]!.id:null}},{readOnly:true})}})
 app.post<{Params:{action:string}}>(root+'/:action',{bodyLimit:262144},async request=>{
  const action=z.enum(['draft','approve','publish','occurrence']).parse(request.params.action),b=action==='draft'?draft.parse(request.body):action==='publish'?publish.parse(request.body):action==='occurrence'?occurrence.parse(request.body):decision.parse(request.body),ctx=await options.resolveContext(request),key=z.string().regex(/^native-business-[a-f0-9-]{36}$/).parse(request.headers['idempotency-key']);uuid.parse(key.slice(16))
  const authorize=async(tx:ScopedTransaction)=>{const c=await options.resolveContext(request);if(c.employeeId!==ctx.employeeId||c.scope.tenantId!==ctx.scope.tenantId||c.scope.storeId!==ctx.scope.storeId)throw new StaffAccessDeniedError('身份变化');await new StaffAccessRepository(tx).assertPermission(ctx.employeeId,permissions[action])}
  const guarded=nativeGuardedExecutor(nativePhysicalExecutor(options.commands,ctx,authorize),{fingerprint:{employeeId:ctx.employeeId,action,b},authorize,guard:async tx=>{
   if(action==='draft'){const d=draft.parse(b);await tx.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[ctx.scope.tenantId+':'+ctx.scope.storeId+':annual:'+d.policyCode]);if(await latest(tx,d.policyCode)!==d.expectedLatest)throw fail('同编号已有新版本，请重新读取');return}
   const d=decision.parse({policyId:'policyId' in b?b.policyId:undefined,expectedVersion:'expectedVersion' in b?b.expectedVersion:undefined,reason:b.reason});await tx.query('SELECT id FROM mbox.loyalty_annual_benefit_policy_versions WHERE tenant_id=$1 AND store_id=$2 AND id=$3 FOR UPDATE',[ctx.scope.tenantId,ctx.scope.storeId,d.policyId]);const r=await policy(tx,ctx,options.commands,d.policyId);if(r.nativeVersion!==d.expectedVersion)throw fail('年度权益版本已变化，请重新读取');if(action==='occurrence'){const o=occurrence.parse(b);if(!(r.rules as Array<{id:string;ruleKind:string;enabled:boolean}>).some(r=>r.id===o.ruleId&&r.ruleKind==='festival'&&r.enabled))throw fail('仅可确认此原版本启用的节日规则')}
  }})
  const captured:Pick<NormalizedCommandExecutor,'execute'>={execute<Result>(c:Readonly<IdempotentCommand<Result>>,handler:(tx:ScopedTransaction)=>Promise<CommandOutcome<Result>>,beforeClaim?:(tx:ScopedTransaction)=>Promise<void>){return guarded.execute({...c,resultCodec:{encode:v=>v as never,decode:v=>v as Result}},async tx=>{const outcome=await handler(tx),v=outcome.result as {id:string};const row=action==='occurrence'?{...occurrence.parse(b),...(await tx.query(`SELECT id,rule_id AS "ruleId",cycle_year AS "cycleYear",starts_on::text AS "startsOn",ends_on::text AS "endsOn",confirmed_by_employee_id AS "confirmedByEmployeeId",confirmation_reference AS "confirmationReference",confirmed_at::text AS "confirmedAt" FROM mbox.loyalty_annual_benefit_occurrences WHERE tenant_id=$1 AND store_id=$2 AND id=$3`,[ctx.scope.tenantId,ctx.scope.storeId,v.id])).rows[0]}:await policy(tx,ctx,options.commands,v.id);if(action==='draft'&&(row as Record<string,unknown>).version!==draft.parse(b).expectedLatest+1)throw fail('网页同时起草了新版本，请重新读取，当前草稿未提交');return{...outcome,result:row as Result}},beforeClaim)}}
  const service=new LoyaltyAnnualBenefitService(options.transactions,captured),result=await(async()=>{if(action==='draft')return service.draft(ctx,{...draft.parse(b),idempotencyKey:key});if(action==='publish')return service.publish(ctx,{...publish.parse(b),idempotencyKey:key});if(action==='occurrence')return service.confirmFestivalOccurrence(ctx,{...occurrence.parse(b),idempotencyKey:key});return service.approve(ctx,{...decision.parse(b),idempotencyKey:key})})();return{data:{employeeId:ctx.employeeId,requestKey:key,action,accepted:b,row:result.value},meta:{protocol:1,replayed:result.replayed}}
 })
}
