import {PaymentCommandService} from './payment-command-service.js'
import {NormalizedPaymentCapabilityAuthorization} from './payment-security-policy.js'
import {NormalizedProviderObservationAuthority} from './provider-verification-observation.js'
import {RESERVING_REFUND_STATUSES} from './refund-repository.js'
import {createHash} from 'node:crypto'
import type {FastifyPluginAsync,FastifyRequest} from 'fastify'
import {z} from 'zod'
import {parseActivityDraft,ActivityOperationsApiRequestError} from './activity-operations-api.js'
import {ActivityOperationsService,type ActivityOperationsStaffContext} from './activity-operations-service.js'
import {ActivityOperationsRepository,ActivityOperationsError,type ActivityOperationsRegistration} from './activity-operations-repository.js'
import {CustomerExperienceService} from './customer-experience-service.js'
import {CustomerExperienceRequestError} from './customer-experience-repository.js'
import {CustomerCommandService} from './customer-repository.js'
import {StaffAccessRepository,StaffAccessDeniedError} from './staff-access-repository.js'
import {nativeGuardedExecutor} from './native-guarded-executor.js'
import {nativePhysicalExecutor} from './native-physical-command.js'
import {NativeCommandNotCommittedError,IdempotencyConflictError,IdempotencyInProgressError,type NormalizedCommandExecutor,type IdempotentCommand,type CommandOutcome} from './command-executor.js'
import {isStaffAuthenticationRequiredError,STAFF_AUTHENTICATION_REQUIRED_ERROR} from './staff-api-authentication.js'
import type {ScopedPostgresTransactionRunner,ScopedTransaction} from './transaction-runner.js'
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex')
const versioned=<T extends object>(v:T)=>({...v,nativeVersion:hash(v)})
const publicId=z.string().regex(/^[A-Za-z0-9][A-Za-z0-9_.:-]{7,127}$/),reason=z.string().trim().min(2).max(500),version=z.string().regex(/^[a-f0-9]{64}$/)
const actionSchema=z.enum(['create','update','publish','stop-registration','close','package-pause','package-resume','waitlist-retry','check-in','fulfill-package','no-show','cancel-registration','refund-request'])
const controlSchema=z.object({publicId,expectedVersion:version,reason,registrationPublicId:publicId.optional(),packagePublicId:publicId.optional(),status:z.enum(['cancelled','completed']).optional(),paymentId:z.string().uuid().optional(),expectedAmountMinor:z.number().int().positive().optional()}).strict()
async function registrationVersions(tx:ScopedTransaction,rows:ActivityOperationsRegistration[]){
 const ids=rows.flatMap(r=>r.paymentId?[r.paymentId]:[])
 const payments=ids.length?(await tx.query<{id:string;remaining:string}>(`SELECT p.id,GREATEST(0,p.amount_minor-COALESCE((SELECT sum(r.amount_minor) FROM mbox.refunds r WHERE r.tenant_id=p.tenant_id AND r.store_id=p.store_id AND r.payment_id=p.id AND r.status=ANY($4::text[])),0))::text AS remaining FROM mbox.payments p WHERE p.tenant_id=$1 AND p.store_id=$2 AND p.id=ANY($3::uuid[]) AND p.payable_kind='activity_registration'`,[tx.scope.tenantId,tx.scope.storeId,ids,RESERVING_REFUND_STATUSES])).rows:[]
 const amounts=new Map(payments.map(r=>[r.id,Number(r.remaining)]));return rows.map(r=>({...r,refundableAmountMinor:r.paymentId?amounts.get(r.paymentId)??null:null}))
}
type Options={transactions:ScopedPostgresTransactionRunner;commands:Pick<NormalizedCommandExecutor,'execute'>;providerConfigured:boolean;resolveContext(request:FastifyRequest):Promise<ActivityOperationsStaffContext>|ActivityOperationsStaffContext}
export const nativeActivityOperationsApiPlugin:FastifyPluginAsync<Options>=async(app,options)=>{
 app.addHook('onRequest',async(_request,reply)=>{reply.header('Cache-Control','private, no-store')})
 app.setErrorHandler((error,_req,reply)=>{
  if(isStaffAuthenticationRequiredError(error))return reply.code(401).send({error:STAFF_AUTHENTICATION_REQUIRED_ERROR})
  if(error instanceof StaffAccessDeniedError)return reply.code(403).send({error:{code:'ACTIVITY_FORBIDDEN',message:'当前岗位没有这项活动权限'}})
  if(error instanceof NativeCommandNotCommittedError)return reply.code(409).send({error:{code:'NATIVE_BUSINESS_NOT_COMMITTED',message:error.original instanceof ActivityOperationsError||error.original instanceof CustomerExperienceRequestError||error.original instanceof TypeError?error.original.message:'活动或报名状态已变化，请重新读取',commitDisposition:'not_committed'}})
  if(error instanceof z.ZodError||error instanceof ActivityOperationsApiRequestError||error instanceof TypeError)return reply.code(400).send({error:{code:'ACTIVITY_INVALID',message:error instanceof z.ZodError?'请核对活动信息、原版本和操作原因':error.message}})
  if(error instanceof ActivityOperationsError||error instanceof CustomerExperienceRequestError)return reply.code(error.statusCode).send({error:{code:error.code,message:error.message}})
  if(error instanceof IdempotencyConflictError||error instanceof IdempotencyInProgressError)return reply.code(409).send({error:{code:'ACTIVITY_CONFLICT',message:'原操作仍在处理或内容不一致，请保留原请求'}})
  throw error
 })
 const root='/staff/native-activity-operations'
 const readAccess=async(tx:ScopedTransaction,employeeId:string)=>{const access=await new StaffAccessRepository(tx).resolve(employeeId);if(!['community.activity.view','community.activity.manage','community.activity.publish'].some(p=>access.permissions.includes(p)))throw new StaffAccessDeniedError('无活动读取权');return access}
 app.get(root,async request=>{const ctx=await options.resolveContext(request),q=z.object({search:z.string().trim().max(80).default(''),cursor:publicId.optional()}).strict().parse(request.query);const data=await options.transactions.run(ctx.scope,async tx=>{await readAccess(tx,ctx.employeeId);return{employeeId:ctx.employeeId,protocol:1,durableCommands:true,...await new ActivityOperationsRepository(tx).nativeList(q.search,q.cursor??null)}},{readOnly:true});return{data}})
 app.get(root+'/components',async request=>{const ctx=await options.resolveContext(request),q=z.object({search:z.string().trim().max(80).default(''),cursor:z.string().uuid().optional()}).strict().parse(request.query);const data=await options.transactions.run(ctx.scope,async tx=>{await new StaffAccessRepository(tx).assertPermission(ctx.employeeId,'community.activity.manage');const rows=(await tx.query<{id:string;sku:string;name:string;baseUnit:string}>(`SELECT id,sku,name,base_unit AS "baseUnit" FROM mbox.inventory_items WHERE tenant_id=$1 AND store_id=$2 AND status='active' AND ($3::uuid IS NULL OR id>$3) AND (name ILIKE $4 OR sku ILIKE $4) ORDER BY id LIMIT 51`,[ctx.scope.tenantId,ctx.scope.storeId,q.cursor??null,`%${q.search.replace(/[\\%_]/g,'\\$&')}%`])).rows;return{employeeId:ctx.employeeId,protocol:1,durableCommands:true,rows:rows.slice(0,50),next:rows.length>50?rows[49]!.id:null}},{readOnly:true});return{data}})
 app.get<{Params:{publicId:string}}>(root+'/:publicId',async request=>{const ctx=await options.resolveContext(request),id=publicId.parse(request.params.publicId),q=z.object({cursor:publicId.optional(),registration:publicId.optional(),search:z.string().trim().max(80).default('')}).strict().parse(request.query);const data=await options.transactions.run(ctx.scope,async tx=>{const access=await readAccess(tx,ctx.employeeId);const d=await new ActivityOperationsRepository(tx).detail(id,{cursor:q.cursor,only:q.registration,search:q.search,limit:51});const itemIds=[...new Set(d.activity.packages.flatMap(p=>p.components.map(c=>c.inventoryItemId)))];const componentItems=access.permissions.includes('community.activity.manage')&&itemIds.length?(await tx.query('SELECT id,name,base_unit AS "baseUnit" FROM mbox.inventory_items WHERE tenant_id=$1 AND store_id=$2 AND id=ANY($3::uuid[])',[ctx.scope.tenantId,ctx.scope.storeId,itemIds])).rows:[];return{employeeId:ctx.employeeId,protocol:1,durableCommands:true,componentItems,activity:versioned(d.activity),rows:(await registrationVersions(tx,d.registrations.slice(0,50))).map(versioned),next:d.registrations.length>50?d.registrations[49]!.publicId:null}},{readOnly:true,isolation:'repeatable-read'});return{data}})
 app.post<{Params:{action:string}}>(root+'/commands/:action',{bodyLimit:512000},async request=>{
  const action=actionSchema.parse(request.params.action),raw=z.record(z.string(),z.unknown()).parse(request.body),draft=action==='create'||action==='update'?parseActivityDraft(raw):null
  const input=draft?{draft,reason:reason.parse(raw.reason),...(action==='update'?{publicId:publicId.parse(raw.publicId),expectedVersion:version.parse(raw.expectedVersion)}:{})}:controlSchema.parse(raw),ctx=await options.resolveContext(request),key=z.string().regex(/^native-business-[a-f0-9-]{36}$/).parse(request.headers['idempotency-key']),registrationAction=['check-in','fulfill-package','no-show','cancel-registration','refund-request'].includes(action)
  if(registrationAction&&!('registrationPublicId'in input&&input.registrationPublicId))throw new TypeError('请选择原报名记录')
  if(action.startsWith('package-')&&!('packagePublicId'in input&&input.packagePublicId))throw new TypeError('请选择原活动套餐')
  if(action==='refund-request'&&(!('paymentId'in input&&input.paymentId)||!('expectedAmountMinor'in input&&input.expectedAmountMinor)))throw new TypeError('请核对原付款和可退款金额')
  if(action==='close'&&!('status'in input&&input.status))throw new TypeError('请选择结束或取消')
  const permission=action==='publish'?'community.activity.publish':'community.activity.manage'
  const authorize=async(tx:ScopedTransaction)=>{const current=await options.resolveContext(request);if(current.employeeId!==ctx.employeeId||current.scope.tenantId!==ctx.scope.tenantId||current.scope.storeId!==ctx.scope.storeId)throw new StaffAccessDeniedError('身份已变化');await new StaffAccessRepository(tx).assertPermission(ctx.employeeId,permission);if(action==='refund-request')await new StaffAccessRepository(tx).assertPermission(ctx.employeeId,'refund.request')}
  const guarded=nativeGuardedExecutor(nativePhysicalExecutor(options.commands,ctx,authorize),{fingerprint:{employeeId:ctx.employeeId,action,input},authorize,guard:async tx=>{
   if(action==='create')return
   const v=controlSchema.parse(draft?{reason:raw.reason,publicId:raw.publicId,expectedVersion:raw.expectedVersion}:raw)
   if(action==='refund-request')await tx.query('SELECT id FROM mbox.payments WHERE tenant_id=$1 AND store_id=$2 AND id=$3 FOR UPDATE',[ctx.scope.tenantId,ctx.scope.storeId,v.paymentId])
   else if(registrationAction){await tx.query(`SELECT r.id FROM mbox.community_activity_registrations r JOIN mbox.community_activities a ON a.tenant_id=r.tenant_id AND a.store_id=r.store_id AND a.id=r.activity_id WHERE r.tenant_id=$1 AND r.store_id=$2 AND r.public_id=$3 AND a.public_id=$4 FOR UPDATE OF r,a`,[ctx.scope.tenantId,ctx.scope.storeId,v.registrationPublicId,v.publicId])}
   else{await tx.query('SELECT id FROM mbox.community_activities WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3 FOR UPDATE',[ctx.scope.tenantId,ctx.scope.storeId,v.publicId]);if(action.startsWith('package-'))await tx.query('SELECT id FROM mbox.community_activity_packages WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3 FOR UPDATE',[ctx.scope.tenantId,ctx.scope.storeId,v.packagePublicId])}
   const d=await new ActivityOperationsRepository(tx).detail(v.publicId,{only:v.registrationPublicId,limit:registrationAction?1:0});const current=registrationAction?(await registrationVersions(tx,d.registrations))[0]:d.activity
   if(action==='refund-request'&&(!d.registrations[0]||d.registrations[0].paymentId!==v.paymentId))throw new TypeError('报名对应付款已变化，请重新核对')
   if(!current||hash(current)!==v.expectedVersion)throw new TypeError('活动或原报名已变化，本次未提交，请重新读取')
  }})
  const captured:Pick<NormalizedCommandExecutor,'execute'>={execute<Result>(command:Readonly<IdempotentCommand<Result>>,handler:(tx:ScopedTransaction)=>Promise<CommandOutcome<Result>>,beforeClaim?:(tx:ScopedTransaction)=>Promise<void>){return guarded.execute({...command,resultCodec:{encode:v=>v as never,decode:v=>v as Result}},async tx=>{const outcome=await handler(tx);if(action==='refund-request'&&(outcome.result as {amountMinor:number}).amountMinor!==raw.expectedAmountMinor)throw new TypeError('原付款可退金额已变化，请重新核对');let full:object=outcome.result as object;if(action==='publish'){full=(await new ActivityOperationsRepository(tx).detail(String(raw.publicId),{limit:0})).activity}return{...outcome,result:versioned(full) as Result,auditEvents:outcome.auditEvents.map(e=>({...e,reason:input.reason}))}},beforeClaim)}}
  const svc=new ActivityOperationsService(options.transactions,captured),publisher=new CustomerExperienceService(options.transactions,captured,new CustomerCommandService(captured),options.providerConfigured),common={reason:input.reason,idempotencyKey:key}
  const result=await(async()=>{if(action==='create')return svc.createDraft(ctx,{...common,draft:draft!});if(action==='update')return svc.updateDraft(ctx,{...common,publicId:publicId.parse(raw.publicId),draft:draft!});const v=controlSchema.parse(raw);if(action==='refund-request')return new PaymentCommandService(captured,new NormalizedPaymentCapabilityAuthorization(),new NormalizedProviderObservationAuthority()).requestActivityRefund({scope:ctx.scope,actor:{type:'employee',employeeId:ctx.employeeId},businessDate:ctx.businessDate,...common,requestFingerprint:JSON.stringify(input),paymentId:v.paymentId!,publicId:'AR'+createHash('sha256').update(`${ctx.scope.storeId}:${key}`).digest('hex').slice(0,32),requestEvidence:{registrationPublicId:v.registrationPublicId!}});if(action==='publish')return publisher.publishActivity(ctx,{publicId:v.publicId,idempotencyKey:key});if(action==='stop-registration')return svc.stopRegistration(ctx,{...common,publicId:v.publicId});if(action==='close')return svc.closeActivity(ctx,{...common,publicId:v.publicId,status:v.status!});if(action.startsWith('package-'))return svc.setPackageAvailability(ctx,{...common,activityPublicId:v.publicId,packagePublicId:v.packagePublicId!,operation:action==='package-pause'?'pause':'resume'});if(action==='waitlist-retry')return svc.retryWaitlistPromotion(ctx,{...common,publicId:v.publicId});return svc.transitionRegistration(ctx,{...common,publicId:v.registrationPublicId!,operation:action==='check-in'?'check_in':action==='fulfill-package'?'fulfill_package':action==='no-show'?'no_show':'cancel'})})()
  return{data:{employeeId:ctx.employeeId,requestKey:key,action,row:result.value},meta:{protocol:1,replayed:result.replayed}}
 })
}
