import {createHash} from 'node:crypto'
import type {FastifyPluginAsync,FastifyRequest} from 'fastify'
import {z} from 'zod'
import {CheckoutUpgradeManagementRepository} from './checkout-upgrade-management-repository.js'
import {UpgradeQualificationError} from './checkout-upgrade-eligibility.js'
import {CustomerExperienceService,type StaffCustomerExperienceContext} from './customer-experience-service.js'
import {CustomerExperienceRequestError} from './customer-experience-repository.js'
import {CustomerCommandService} from './customer-repository.js'
import {StaffAccessRepository,StaffAccessDeniedError,StaffNotFoundError} from './staff-access-repository.js'
import {nativeGuardedExecutor} from './native-guarded-executor.js'
import {nativePhysicalExecutor} from './native-physical-command.js'
import {NativeCommandNotCommittedError,IdempotencyConflictError,IdempotencyInProgressError,type NormalizedCommandExecutor,type JsonObject,type IdempotentCommand,type CommandOutcome} from './command-executor.js'
import {isStaffAuthenticationRequiredError,STAFF_AUTHENTICATION_REQUIRED_ERROR} from './staff-api-authentication.js'
import type {ScopedPostgresTransactionRunner,ScopedTransaction} from './transaction-runner.js'
type Options={transactions:ScopedPostgresTransactionRunner;commands:Pick<NormalizedCommandExecutor,'execute'>;resolveContext(request:FastifyRequest):Promise<StaffCustomerExperienceContext>|StaffCustomerExperienceContext}
const root='/staff/native-checkout-management',uuid=z.string().uuid(),code=z.string().regex(/^[A-Z][A-Z0-9_-]{2,63}$/),reason=z.string().trim().min(2).max(240),version=z.string().regex(/^[a-f0-9]{64}$/),money=z.number().int().min(0).max(Number.MAX_SAFE_INTEGER),occasion=z.enum(['business','friends','date','birthday','music','relax','other']),alcohol=z.enum(['cocktail','wine','sparkling','beer','whisky','baijiu','non_alcoholic','mixed','undecided'])
const qualification=z.object({maximumAddMinor:money,maximumAddBasisPoints:z.number().int().nonnegative().max(1000000).nullable(),minimumContributionMinor:money,minimumIncrementalContributionMinor:money,positiveFitReason:z.string().trim().min(2).max(500),maximumQuantitiesPerPerson:z.array(z.object({productId:uuid,quantity:z.number().int().min(1).max(100)}).strict()).min(1).max(100),excludedProductIds:z.array(uuid).max(100)}).strict()
const rule=z.object({code,expectedLatest:z.number().int().nonnegative(),name:z.string().trim().min(2).max(80),sourceProductId:uuid,targetProductId:uuid,minimumPartySize:z.number().int().min(1).max(200),maximumPartySize:z.number().int().min(1).max(200),occasionTags:z.array(occasion).max(7),alcoholPreferenceTags:z.array(alcohol).max(9),promptTitle:z.string().trim().min(2).max(60),promptBody:z.string().trim().min(2).max(240),callToAction:z.string().trim().min(2).max(30),priority:z.number().int().min(0).max(10000),offerValidMinutes:z.number().int().min(2).max(30),minimumGrossMarginBasisPoints:z.number().int().min(0).max(9999),qualification,reason}).strict()
const decision=z.object({id:uuid,code:code.optional(),expectedVersion:version,reason}).strict(),capacity=z.object({stationCode:z.enum(['bar','kitchen','cashier']),windows:z.array(z.object({startsAt:z.string().datetime({offset:true}),endsAt:z.string().datetime({offset:true}),capacityLimitUnits:z.number().int().min(1).max(1000000)}).strict()).min(1).max(96),reason}).strict()
const permissions={'rule-draft':'checkout.upgrade.rule.draft','rule-approve':'checkout.upgrade.rule.approve','rule-publish':'checkout.upgrade.rule.publish','rule-rollback':'checkout.upgrade.rule.publish','capacity-draft':'fulfillment.capacity.draft','capacity-approve':'fulfillment.capacity.approve','capacity-publish':'fulfillment.capacity.publish'} as const
const json=(v:unknown)=>JSON.parse(JSON.stringify(v)) as JsonObject
function stamped(v:unknown):Record<string,unknown>&{nativeVersion:string}{const r=json(v);return{...r,nativeVersion:createHash('sha256').update(JSON.stringify(r)).digest('hex')}}
async function find(tx:ScopedTransaction,area:'rules'|'capacities',id:string){const repo=new CheckoutUpgradeManagementRepository(tx),r=area==='rules'?(await repo.listRules({only:id}))[0]:(await repo.listCapacityPolicies({only:id}))[0];if(!r)throw new CustomerExperienceRequestError('原配置不存在或不属于本店');return stamped(r)}
export const nativeCheckoutManagementApiPlugin:FastifyPluginAsync<Options>=async(app,options)=>{
 app.addHook('onRequest',async(_request,reply)=>{reply.header('Cache-Control','private, no-store')})
 app.setErrorHandler((e,_request,reply)=>{
  if(isStaffAuthenticationRequiredError(e))return reply.code(401).send({error:STAFF_AUTHENTICATION_REQUIRED_ERROR})
  if(e instanceof StaffAccessDeniedError||e instanceof StaffNotFoundError)return reply.code(403).send({error:{code:'CHECKOUT_MANAGEMENT_FORBIDDEN',message:'当前员工无此升级规则或产能权限'}})
  if(e instanceof NativeCommandNotCommittedError&&!(e.original instanceof IdempotencyConflictError))return reply.code(409).send({error:{code:'NATIVE_BUSINESS_NOT_COMMITTED',message:e.original instanceof CustomerExperienceRequestError||e.original instanceof UpgradeQualificationError?e.original.message:'原配置已变化或审批条件不满足，请刷新',commitDisposition:'not_committed'}})
  if(e instanceof z.ZodError||e instanceof CustomerExperienceRequestError||e instanceof UpgradeQualificationError)return reply.code(400).send({error:{code:'CHECKOUT_MANAGEMENT_INVALID',message:e instanceof CustomerExperienceRequestError||e instanceof UpgradeQualificationError?e.message:'请核对商品、人数、价格准入及产能时间窗'}})
  if(e instanceof NativeCommandNotCommittedError||e instanceof IdempotencyConflictError||e instanceof IdempotencyInProgressError)return reply.code(409).send({error:{code:'CHECKOUT_MANAGEMENT_UNCONFIRMED',message:'请保留原请求核对结果'}})
  throw e
 })
 app.get(root,async request=>{const q=z.object({area:z.enum(['rules','capacities','outcomes']),cursor:z.string().max(128).optional(),code:code.optional()}).strict().parse(request.query);if(q.area!=='outcomes'&&q.cursor)uuid.parse(q.cursor);const ctx=await options.resolveContext(request);return{data:await options.transactions.run(ctx.scope,async tx=>{await new StaffAccessRepository(tx).assertPermission(ctx.employeeId,q.area==='capacities'?'fulfillment.capacity.view':'checkout.upgrade.rule.view');const repo=new CheckoutUpgradeManagementRepository(tx);const raw=q.area==='rules'?await repo.listRules({cursor:q.cursor,code:q.code}):q.area==='capacities'?await repo.listCapacityPolicies({cursor:q.cursor}):await repo.listOutcomes({cursor:q.cursor});const rows=raw.slice(0,30).map(stamped),last=rows.at(-1);const latest=q.code?Number((await tx.query<{n:number}>('SELECT COALESCE(max(revision),0) n FROM mbox.checkout_upgrade_rules WHERE tenant_id=$1 AND store_id=$2 AND code=$3',[ctx.scope.tenantId,ctx.scope.storeId,q.code])).rows[0]!.n):null;const productIds=new Set<string>();if(q.area==='rules')for(const r of raw as Awaited<ReturnType<CheckoutUpgradeManagementRepository['listRules']>>){productIds.add(r.sourceProductId);productIds.add(r.targetProductId);for(const p of r.qualification?.maximumQuantitiesPerPerson??[])productIds.add(p.productId);for(const id of r.qualification?.excludedProductIds??[])productIds.add(id)}const products=productIds.size?(await tx.query('SELECT id,name,code,product_kind AS kind FROM mbox.products WHERE tenant_id=$1 AND store_id=$2 AND id=ANY($3::uuid[])',[ctx.scope.tenantId,ctx.scope.storeId,[...productIds]])).rows:[];return{employeeId:ctx.employeeId,protocol:1,durableCommands:true,area:q.area,products,rows,next:raw.length>30?String(last?.[q.area==='outcomes'?'offerPublicId':'id']):null,code:q.code??null,latest}},{readOnly:true,isolation:'repeatable-read'})}})
 app.get(root+'/products',async request=>{const q=z.object({cursor:uuid.optional(),search:z.string().trim().max(80).default('')}).strict().parse(request.query),ctx=await options.resolveContext(request);return{data:await options.transactions.run(ctx.scope,async tx=>{await new StaffAccessRepository(tx).assertPermission(ctx.employeeId,'checkout.upgrade.rule.draft');const r=(await tx.query<{id:string;name:string;code:string;kind:string}>("SELECT id,name,code,product_kind AS kind FROM mbox.products WHERE tenant_id=$1 AND store_id=$2 AND status='active' AND ($3::uuid IS NULL OR id>$3) AND (name ILIKE $4 OR code ILIKE $4) ORDER BY id LIMIT 51",[ctx.scope.tenantId,ctx.scope.storeId,q.cursor??null,'%'+q.search.replace(/[\\%_]/g,'\\$&')+'%'])).rows;return{employeeId:ctx.employeeId,protocol:1,durableCommands:true,rows:r.slice(0,50),next:r.length>50?r[49]!.id:null}},{readOnly:true})}})
 app.post<{Params:{action:string}}>(root+'/:action',{bodyLimit:65536},async request=>{
  const action=z.enum(['rule-draft','rule-approve','rule-publish','rule-rollback','capacity-draft','capacity-approve','capacity-publish']).parse(request.params.action),b=action==='rule-draft'?rule.parse(request.body):action==='capacity-draft'?capacity.parse(request.body):decision.parse(request.body),ctx=await options.resolveContext(request),key=z.string().regex(/^native-business-[a-f0-9-]{36}$/).parse(request.headers['idempotency-key']);uuid.parse(key.slice(16));const area=action.startsWith('rule')?'rules':'capacities'
  if(action==='rule-draft'){const r=rule.parse(b);if(r.minimumPartySize>r.maximumPartySize||new Set(r.occasionTags).size!==r.occasionTags.length||new Set(r.alcoholPreferenceTags).size!==r.alcoholPreferenceTags.length)throw new CustomerExperienceRequestError('人数区间或标签重复，请核对')}
  if(action==='capacity-draft'){const c=capacity.parse(b);c.windows.sort((a,b)=>Date.parse(a.startsAt)-Date.parse(b.startsAt));if(c.windows.some((w,i)=>Date.parse(w.endsAt)<=Date.parse(w.startsAt)||(i>0&&Date.parse(w.startsAt)<Date.parse(c.windows[i-1]!.endsAt))))throw new CustomerExperienceRequestError('产能窗口须正序且不能重叠');Object.assign(b,c)}
  const authorize=async(tx:ScopedTransaction)=>{const c=await options.resolveContext(request);if(c.employeeId!==ctx.employeeId||c.scope.tenantId!==ctx.scope.tenantId||c.scope.storeId!==ctx.scope.storeId)throw new StaffAccessDeniedError('身份变化');await new StaffAccessRepository(tx).assertPermission(ctx.employeeId,permissions[action])}
  const guarded=nativeGuardedExecutor(nativePhysicalExecutor(options.commands,ctx,authorize),{fingerprint:{employeeId:ctx.employeeId,action,b},authorize,guard:async tx=>{
   if(action==='capacity-draft')return
   if(action==='rule-draft'){const r=rule.parse(b);await tx.query("SELECT pg_advisory_xact_lock(hashtextextended($1||':'||$2||':'||$3,0))",[ctx.scope.tenantId,ctx.scope.storeId,r.code]);const latest=Number((await tx.query<{n:number}>('SELECT COALESCE(max(revision),0) n FROM mbox.checkout_upgrade_rules WHERE tenant_id=$1 AND store_id=$2 AND code=$3',[ctx.scope.tenantId,ctx.scope.storeId,r.code])).rows[0]!.n);if(latest!==r.expectedLatest)throw new CustomerExperienceRequestError('同编号已有新版本，请重新读取');return}
   const d=decision.parse(b);await tx.query(`SELECT id FROM mbox.${area==='rules'?'checkout_upgrade_rules':'fulfillment_capacity_policy_versions'} WHERE tenant_id=$1 AND store_id=$2 AND id=$3 ${action==='rule-rollback'?'FOR KEY SHARE':'FOR UPDATE'}`,[ctx.scope.tenantId,ctx.scope.storeId,d.id]);const current=await find(tx,area,d.id);if(current.nativeVersion!==d.expectedVersion)throw new CustomerExperienceRequestError('配置版本已变化，请刷新核对');if(action==='rule-approve'&&current.code!==d.code)throw new CustomerExperienceRequestError('原规则编号不一致')
  }})
  const captured:Pick<NormalizedCommandExecutor,'execute'>={execute<Result>(command:Readonly<IdempotentCommand<Result>>,handler:(tx:ScopedTransaction)=>Promise<CommandOutcome<Result>>,beforeClaim?:(tx:ScopedTransaction)=>Promise<void>){return guarded.execute({...command,resultCodec:{encode:v=>v as never,decode:v=>v as Result}},async tx=>{const outcome=await handler(tx);const value=outcome.result as {id:string};if(action==='rule-approve'&&value.id!==decision.parse(b).id)throw new CustomerExperienceRequestError('同编号待审草稿已变化，未审批其他版本');return{...outcome,result:await find(tx,area,value.id) as Result}},beforeClaim)}}
  const svc=new CustomerExperienceService(options.transactions,captured,new CustomerCommandService(captured)),common={reason:b.reason,idempotencyKey:key}
  const result=await(async()=>{if(action==='rule-draft'){const r=rule.parse(b);return svc.upsertCheckoutUpgradeRule(ctx,{...r,status:'draft',idempotencyKey:key})}if(action==='capacity-draft')return svc.draftFulfillmentCapacity(ctx,{...capacity.parse(b),idempotencyKey:key});const d=decision.parse(b);if(action==='rule-approve')return svc.approveCheckoutUpgradeRule(ctx,{code:code.parse(d.code),...common});if(action==='rule-publish')return svc.publishCheckoutUpgradeRule(ctx,{ruleId:d.id,...common});if(action==='rule-rollback')return svc.rollbackCheckoutUpgradeRule(ctx,{ruleId:d.id,...common});return svc.transitionFulfillmentCapacity(ctx,{policyId:d.id,action:action==='capacity-approve'?'approve':'publish',...common})})()
  return{data:{employeeId:ctx.employeeId,requestKey:key,action,accepted:b,row:result.value},meta:{protocol:1,replayed:result.replayed}}
 })
}
