import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const root = new URL('../../', import.meta.url)
const read = (path: string) => readFileSync(new URL(path, root), 'utf8')

describe('activity operations staff and customer contract', () => {
  it('keeps published promises immutable and exposes the full draft configuration surface', () => {
    const panel = read('src/normalized-ui/ActivityOperationsPanel.tsx')
    expect(panel).toContain('发布后不可静默修改')
    expect(panel).toContain('保存草稿并读回')
    expect(panel).toContain('费用、权益和客群')
    expect(panel).toContain('退款、安全和参与承诺')
    expect(panel).toContain('audienceMemberLevels')
    expect(panel).toContain('audienceLifecycleStages')
    expect(panel).toContain('memberBenefitText')
    expect(panel).toContain('pointsReward: 0')
    expect(panel).toContain("auth.permissions.includes('community.activity.publish')")
    expect(panel).toContain("'/api/staff/activity-operations'")
    expect(panel).toContain('建立草稿并读回')
    expect(panel).toContain('复核并发布')
  })

  it('keeps manager request and cashier review/execute visibly separated', () => {
    const panel = read('src/normalized-ui/ActivityOperationsPanel.tsx')
    expect(panel).toContain("auth.permissions.includes('refund.request')")
    expect(panel).toContain("auth.permissions.includes('refund.approve')")
    expect(panel).toContain("auth.permissions.includes('refund.execute')")
    expect(panel).toContain('店长发起退款取消')
    expect(panel).toContain('收银复核通过')
    expect(panel).toContain('退款已提交渠道，尚未确认成功前不会标记已退款')
    expect(panel).toContain('/provider-query`')
  })

  it('gives attendance, waitlist and payment recovery actions mobile touch targets', () => {
    const panel = read('src/normalized-ui/ActivityOperationsPanel.tsx')
    const css = read('src/normalized-ui/activity-operations-panel.css')
    expect(panel).toContain('报名与候补名单')
    expect(panel).toContain('收费候补不预扣款')
    expect(panel).toContain('requestedPaymentChoice')
    expect(panel).toContain('现在不预扣，递补后待付')
    expect(panel).toContain("registrationAction(registration,'check-in')")
    expect(panel).toContain("registrationAction(registration,'no-show')")
    expect(panel).toContain('先查支付')
    expect(css).toMatch(/\.activity-operations-panel button, \.activity-operations-panel input, \.activity-operations-panel select \{ min-height: 44px;/)
    expect(css).toContain('@media (max-width: 760px)')
    expect(css).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
    expect(css).toContain('@media (max-width: 380px)')
  })

  it('keeps contact masked by default and holds plaintext in memory for no more than the authorized window',()=>{
    const panel=read('src/normalized-ui/ActivityOperationsPanel.tsx')
    const repository=read('server/normalized/activity-operations-repository.ts')
    expect(repository).toContain('contactVersionPublicId: row.contact_version_public_id')
    expect(repository).toContain("COALESCE(contact.masked_contact,'已清除')")
    expect(panel).toContain('contactVersionPublicId:string(record.contactVersionPublicId)')
    expect(panel).toContain("auth.permissions.includes('community.activity.contact.reveal')")
    expect(panel).toContain('签到联系')
    expect(panel).toContain('候补联系')
    expect(panel).toContain('付款跟进')
    expect(panel).toContain('setRevealedContacts({})')
    expect(panel).toContain('expiresAt')
    expect(panel).not.toMatch(/localStorage|sessionStorage/)
  })

  it('does not promise the dead unversioned activity points field to customers', () => {
    const detail = read('miniprogram/pages/community-detail/index.wxml')
    const staff = read('src/normalized-ui/CustomerExperienceManagementPanel.tsx')
    const api = read('server/normalized/customer-experience-api.ts')
    expect(detail).not.toContain('完成积分')
    expect(detail).not.toContain('activity.pointsReward')
    expect(staff).toContain('旧字段没有规则版本、预算和发放状态机')
    expect(staff).toContain('pointsReward: 0')
    expect(api).not.toContain("app.post('/staff/community-activities'")
  })

  it('retires the duplicate activity editor and excludes unapproved black-tier targeting', () => {
    const panel = read('src/normalized-ui/ActivityOperationsPanel.tsx')
    const management = read('src/normalized-ui/CustomerExperienceManagementPanel.tsx')
    const api = read('server/normalized/activity-operations-api.ts')
    expect(management).toContain('const legacyActivityEditorEnabled = false')
    expect(management).toContain('legacyActivityEditorEnabled && canCreate')
    expect(management).toContain('legacyActivityEditorEnabled && <section className="activity-admin-list"')
    expect(management).not.toContain("'/api/staff/activity-operations'")
    expect(panel).not.toContain("['black'")
    expect(panel).not.toContain('value="black"')
    expect(management).not.toContain('value="black"')
    expect(api).toContain("['member','silver','gold'] as const")
    expect(api).not.toContain("['member','silver','gold','black']")
  })
})
