import {CustodyDepositCapture,CustodyFractionSelect,custodyFractions,type DepositEvidenceInput} from './CustodyDepositCapture'
import {CustodyReportPanel} from './CustodyReportPanel'
import {useEffect,useEffectEvent,useState} from 'react'
import type {NormalizedApiClient,StaffAuthView} from '../normalized-api'
import {executeRecoverableCommand} from './recoverable-command'
import {createIdempotencyKey} from './cashier-mutation'
interface Order{extra_fields:Record<string,string>;extra_field_snapshot:ExtraField[];id:string;public_id:string;member_no:string;category_name:string;item_name:string;unit:string;remaining_quantity:string;original_quantity:string;expires_at:string;status:string;location:string}
interface Detail{deposits:{id:string;quantity:string;fraction_label:string|null;phone_source:string;phone_masked:string;recorded_at:string}[];reminders:{days_before:number;due_at:string;status:string;provider_reference:string|null;error_code:string|null}[];order:Order;events:{event_type:string;quantity:string|null;employee_id:string;employee_name:string|null;occurred_at:string;reason:string}[];collections:{restored_order_id:string|null;id:string;quantity:string;returned_quantity:string;status:string}[];challenges:{id:string;quantity:string;delivery_status:string;verified_at:string|null;consumed_at:string|null;invalidated_at:string|null;expires_at:string}[]}
interface ExtraField{key:string;label:string;type:'text'|'number'|'date';required:boolean}
interface Policy{allowRestorage:boolean;requireOriginalOrder:boolean;archiveMode:'automatic'|'manual';extraFieldDefinitions:ExtraField[];printFields:string[];printFooter:string;reportDimensions:string[];serviceAccountId:string|null;enabled:boolean;defaultDays:number;remindersEnabled:boolean;reminderDays:number[];sendMinute:number;codeDigits:number;codeTtlSeconds:number;resendSeconds:number;maximumAttempts:number;allowPartial:boolean;numberPattern:string;printTitle:string;reminderText:string}
interface Category{id:string;code:string;name:string;default_days:number;active:boolean;sort_order:number}
const names:Record<string,string>={collection_closed:'确认不再存',stored:'在存',collected:'已取走，待确认再存',archived:'已归档',restored:'已再存',cancelled:'已取消',pending:'待发送',sending:'发送中',accepted:'已提交服务号',rejected:'发送失败',unknown:'发送结果未确认',code_requested:'发起验证码',code_verified:'验证通过',code_rejected:'验证未通过',expiry_changed:'修改到期日',printed:'生成存酒凭证'}
export function BottleCustodyPanel({api,auth}:{api:NormalizedApiClient;auth:StaffAuthView}){
 const allowed=auth.permissions.includes('bottle.manage.all'),manage=auth.permissions.includes('member.card.manage')
 const [orders,setOrders]=useState<Order[]>([]),[detail,setDetail]=useState<Detail|null>(null),[policy,setPolicy]=useState<Policy|null>(null),[version,setVersion]=useState(0),[categories,setCategories]=useState<Category[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[cursor,setCursor]=useState<string|null>(null)
 const [summary,setSummary]=useState<{count:string;stored:string;collected:string;archived:string;categoryCounts:{name:string;count:string}[]}|null>(null),[extraFields,setExtraFields]=useState<Record<string,string>>({}),[extraDefinition,setExtraDefinition]=useState<ExtraField>({key:'',label:'',type:'text',required:false}),[restorageMode,setRestorageMode]=useState('new'),[declaredValue,setDeclaredValue]=useState(''),[newExpiry,setNewExpiry]=useState(''),[accounts,setAccounts]=useState<{id:string;name:string}[]>([]),[from,setFrom]=useState(''),[to,setTo]=useState('')
 const [member,setMember]=useState(''),[category,setCategory]=useState(''),[status,setStatus]=useState(''),[search,setSearch]=useState(''),[code,setCode]=useState(''),[quantity,setQuantity]=useState(''),[returnQuantity,setReturnQuantity]=useState(''),[reason,setReason]=useState(''),[expiry,setExpiry]=useState('')
 const [form,setForm]=useState({memberNo:'',categoryId:'',itemName:'',unit:'瓶',quantity:'1',sourceReference:'',location:'',note:'',days:''})
 const [categoryForm,setCategoryForm]=useState<{id?:string;code:string;name:string;defaultDays:number;active:boolean;sortOrder:number}>({code:'',name:'',defaultDays:20,active:true,sortOrder:0})
 const [evidence,setEvidence]=useState<DepositEvidenceInput>({photoBase64:'',phone:null,fraction:null}),[depositKey,setDepositKey]=useState(0),[returnEvidence,setReturnEvidence]=useState<Record<string,DepositEvidenceInput>>({}),[photos,setPhotos]=useState<Record<string,string>>({})
 const path='/api/staff/bottle-custody'
 function withFraction(input:DepositEvidenceInput,amount:string,unit:string){return {...input,fraction:unit==='瓶'?(custodyFractions.find(f=>Number(f[2])===Number(amount))?.[0]??null):null}}
 async function command<T>(url:string,body:unknown){return executeRecoverableCommand(`${auth.employee.id}:${url}`,body,createIdempotencyKey('custody'),key=>api.postEndpoint<T>(url,body,{idempotencyKey:key}))}
 async function perform(fn:()=>Promise<void>){if(busy)return;setBusy(true);setMessage('');try{await fn()}catch(error){setMessage(error instanceof Error?error.message:'操作结果未确认，请刷新核对')}finally{setBusy(false)}}
 async function config(){const result=(await api.getEndpoint<{data:{policy:Policy;version:number;categories:Category[];accounts:{id:string;name:string}[]}}>(`${path}/policy`)).data;setPolicy(result.policy);setVersion(result.version);setCategories(result.categories);setAccounts(result.accounts)}
 async function list(more=false){const params=new URLSearchParams();if(member)params.set('memberNo',member);if(category)params.set('categoryId',category);if(status)params.set('status',status);if(search)params.set('query',search);if(from)params.set('from',`${from}T00:00:00+08:00`);if(to)params.set('to',new Date(Date.parse(`${to}T00:00:00+08:00`)+86400000).toISOString());if(more&&cursor)params.set('cursor',cursor);const result=(await api.getEndpoint<{data:{items:Order[];nextCursor:string|null;summary:{count:string;stored:string;collected:string;archived:string;categoryCounts:{name:string;count:string}[]}}}>(`${path}?${params}`)).data;setOrders(previous=>more?[...previous,...result.items]:result.items);setCursor(result.nextCursor);setSummary(result.summary)}
 async function inspect(id:string){const result=(await api.getEndpoint<{data:Detail}>(`${path}/${id}`)).data;setDetail(result);setQuantity(result.order.remaining_quantity);setCode('');setPhotos({})}
 const initialize=useEffectEvent(()=>{void perform(async()=>{await config();await list()})})
 useEffect(()=>{if(allowed)initialize()},[allowed,api,auth.employee.id])
 if(!allowed)return null
 const patch=(value:Partial<Policy>)=>setPolicy(previous=>previous?{...previous,...value}:previous)
 const challenge=detail?.challenges.find(item=>!item.consumed_at&&!item.invalidated_at)
 async function mutate(suffix:string,body:unknown){if(!detail)return;const id=detail.order.id;await command(`${path}/${id}/${suffix}`,body);await inspect(id);await list()}
 return <section className="bottle-custody-panel"><h3>会员存酒</h3><p>报会员号查存酒，验证码通过后再确认实物已取走。再存可沿用原单或新开单，不再存保留取走与归档记录。</p><CustodyReportPanel api={api} auth={auth}/>
 <div className="custody-fields"><label>会员号<input value={member} onChange={e=>setMember(e.target.value)}/></label><label>编号或酒名<input value={search} onChange={e=>setSearch(e.target.value)}/></label>{(!policy||policy.reportDimensions.includes('category'))&&<label>品类<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">全部</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}{(!policy||policy.reportDimensions.includes('status'))&&<label>状态<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部</option>{['stored','collected','archived'].map(s=><option key={s} value={s}>{names[s]}</option>)}</select></label>}{(!policy||policy.reportDimensions.includes('date'))&&<><label>开始日期<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>结束日期<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></>}<button disabled={busy} onClick={()=>void perform(()=>list())}>查询 / 刷新</button><button disabled={busy||!auth.permissions.includes('bottle.custody.export')} title={auth.permissions.includes('bottle.custody.export')?'导出当前筛选':'需配置存酒导出权限'} onClick={()=>void perform(async()=>{const result=await command<{base64:string;filename:string;count:number}>(`${path}/export`,{...(member?{memberNo:member}:{}),...(category?{categoryId:category}:{}),...(status?{status}:{}),...(search?{query:search}:{}),...(from?{from:`${from}T00:00:00+08:00`}:{}),...(to?{to:new Date(Date.parse(`${to}T00:00:00+08:00`)+86400000).toISOString()}:{})});const blob=new Blob([Uint8Array.from(atob(result.base64),c=>c.charCodeAt(0))],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=result.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage(`已导出 ${result.count} 笔；登记价值非实收收入。`)})}>按筛选导出 Excel</button></div>
 {message&&<p role="status">{message}</p>}
 <p>当前筛选共 {summary?.count??0} 单 · 在存 {summary?.stored??0} · 已取走待处理 {summary?.collected??0} · 归档 {summary?.archived??0}；登记价值非实收收入。</p>{policy?.reportDimensions.includes('category')&&<p>{summary?.categoryCounts.map(c=>`${c.name} ${c.count}单`).join('；')}</p>}<div className="custody-orders">{orders.map(order=><button key={order.id} disabled={busy} onClick={()=>void perform(()=>inspect(order.id))}><strong>{order.member_no} · {order.item_name}</strong><span>{names[order.status]} · 余 {Number(order.remaining_quantity)} {order.unit}</span><small>{order.public_id}</small><small>到期 {new Date(order.expires_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</small></button>)}</div>{cursor&&<button disabled={busy} onClick={()=>void perform(()=>list(true))}>加载更多存酒</button>}
 {detail&&<article className="custody-detail"><h4>{detail.order.public_id}</h4><button disabled={busy} onClick={()=>{const preview=window.open('','_blank');if(!preview){setMessage('请允许打开打印预览窗口');return}preview.opener=null;void perform(async()=>{const result=await command<{html:string}>(`${path}/${detail.order.id}/print`,{});preview.document.open();preview.document.write(result.html);preview.document.close();await inspect(detail.order.id)})}}>生成打印凭证</button><p>原存 {Number(detail.order.original_quantity)} {detail.order.unit}，当前剩余 {Number(detail.order.remaining_quantity)} {detail.order.unit}；位置：{detail.order.location||'未填写'}</p>
 <details><summary>存入照片与联系记录（{detail.deposits.length}）</summary>{detail.deposits.length===0&&<p>历史存酒单未留存照片或手机号；再次寄存时必须补齐。</p>}{detail.deposits.map(d=><div key={d.id}><p>{new Date(d.recorded_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})} · 本次存入 {d.fraction_label??Number(d.quantity)} {detail.order.unit} · 手机号 {d.phone_masked}（{d.phone_source==='membership'?'会员登记':'员工补录，未验证'}）</p><button type="button" disabled={busy} onClick={()=>void perform(async()=>{const r=await api.getEndpoint<{data:{base64:string}}>(`${path}/${detail.order.id}/photos/${d.id}`);setPhotos(previous=>({...previous,[d.id]:r.data.base64}))})}>查看带时间水印照片</button>{photos[d.id]&&<img className="custody-evidence-photo" src={`data:image/jpeg;base64,${photos[d.id]}`} alt="存入时的酒瓶、余量及服务器时间水印"/>}</div>)}</details>
 {detail.order.extra_field_snapshot.map(field=><p key={field.key}>{field.label}：{detail.order.extra_fields[field.key]||'未填写'}</p>)}
 {detail.order.status==='stored'&&<div className="custody-fields"><label>本次取酒数量<input value={quantity} inputMode="decimal" onChange={e=>setQuantity(e.target.value)}/></label><button disabled={busy} onClick={()=>void perform(()=>mutate('request-code',{quantity}))}>向会员服务号发验证码</button></div>}
 {challenge&&<div><p>验证码发送状态：{names[challenge.delivery_status]||challenge.delivery_status}；有效至 {new Date(challenge.expires_at).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai'})}</p><button disabled={busy} onClick={()=>void perform(()=>inspect(detail.order.id))}>刷新发送状态</button><label>会员出示的验证码<input value={code} inputMode="numeric" maxLength={8} autoComplete="off" onChange={e=>setCode(e.target.value)}/></label><button disabled={busy||challenge.delivery_status!=='accepted'} onClick={()=>void perform(async()=>{const result=await command<{verified:boolean;message:string}>(`${path}/${detail.order.id}/verify`,{challengeId:challenge.id,code});await inspect(detail.order.id);setMessage(result.message)})}>验证</button><button disabled={busy||!challenge.verified_at} onClick={()=>void perform(()=>mutate('collect',{challengeId:challenge.id}))}>确认实物已取走</button></div>}
 {detail.collections.filter(c=>c.status==='collected').map(c=><div key={c.id}><p>本次已取 {Number(c.quantity)} {detail.order.unit}</p>{policy?.allowRestorage&&<label>再存方式<select value={policy.requireOriginalOrder?'original':restorageMode} disabled={busy||policy.requireOriginalOrder} onChange={e=>setRestorageMode(e.target.value)}><option value="new">新建存酒单</option><option value="original">沿用原单</option></select></label>}<CustodyFractionSelect quantity={returnQuantity||c.quantity} unit={detail.order.unit} onChange={setReturnQuantity}/><label>再存数量<input value={returnQuantity} placeholder={c.quantity} inputMode="decimal" onChange={e=>setReturnQuantity(e.target.value)}/></label>{policy?.allowRestorage&&<CustodyDepositCapture key={c.id} api={api} memberNo={detail.order.member_no} disabled={busy} value={returnEvidence[c.id]??{photoBase64:'',phone:null,fraction:null}} onChange={value=>setReturnEvidence(previous=>({...previous,[c.id]:value}))}/>}<button disabled={busy||!policy?.allowRestorage||!returnEvidence[c.id]?.photoBase64} onClick={()=>void perform(()=>mutate('resolve-collection',{evidence:withFraction(returnEvidence[c.id]!,returnQuantity||c.quantity,detail.order.unit),collectionId:c.id,quantity:returnQuantity||c.quantity,restorageMode:policy?.requireOriginalOrder?'original':restorageMode,reason:reason||'顾客现场确认再存'}))}>确认再存</button><button disabled={busy} onClick={()=>void perform(()=>mutate('resolve-collection',{collectionId:c.id,quantity:null,reason:reason||'顾客现场确认不再存'}))}>确认不再存</button></div>)}
 {detail.order.status==='collected'&&detail.collections.every(c=>c.status!=='collected')&&<button disabled={busy} onClick={()=>void perform(()=>mutate('archive',{reason:reason||'人工确认所有取酒已处理，归档'}))}>归档此单</button>}
 {detail.collections.filter(c=>c.restored_order_id&&c.restored_order_id!==detail.order.id).map(c=><button key={c.id} disabled={busy} onClick={()=>void perform(()=>inspect(c.restored_order_id!))}>查看本次再存新单</button>)}
 <details><summary>调整到期时间</summary><label>新到期时间（北京时间）<input type="datetime-local" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><label>原因<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!expiry||reason.trim().length<2} onClick={()=>void perform(()=>mutate('expiry',{expiresAt:`${expiry}:00+08:00`,reason}))}>保存到期时间</button></details>
 <details><summary>存取与验证记录（{detail.events.length}）</summary>{detail.events.map((event,index)=><p key={index}>{new Date(event.occurred_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})} · {names[event.event_type]||event.event_type} · {event.quantity??''} · 操作人 {event.employee_name||event.employee_id} {event.reason}</p>)}</details><details><summary>到期提醒记录</summary>{detail.reminders.map((r,index)=><p key={index}>提前{r.days_before}天 · {new Date(r.due_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})} · {names[r.status]||r.status} {r.provider_reference?`回执：${r.provider_reference}`:''} {r.error_code}</p>)}</details></article>}
 <details><summary>录入新存酒</summary><form onSubmit={event=>{event.preventDefault();void perform(async()=>{if(declaredValue&&!/^(?:0|[1-9][0-9]{0,9})(?:\.[0-9]{1,2})?$/.test(declaredValue))throw new Error('登记价值须为最多两位小数的金额');const result=await command<Detail>(path,{...form,evidence:withFraction(evidence,form.quantity,form.unit),declaredValueMinor:declaredValue?Math.round(Number(declaredValue)*100):null,extraFields,days:newExpiry?null:(form.days?Number(form.days):null),expiresAt:newExpiry?`${newExpiry}:00+08:00`:null});setDetail(result);setQuantity(result.order.remaining_quantity);await list();setEvidence({photoBase64:'',phone:null,fraction:null});setDepositKey(key=>key+1);setMessage('存酒已登记，照片与手机号已保存；取酒须验证服务号验证码。')})}}><div className="custody-fields">
 <CustodyFractionSelect quantity={form.quantity} unit={form.unit} onChange={quantity=>setForm({...form,quantity})}/><label>存酒登记价值（元，选填，非收入）<input inputMode="decimal" value={declaredValue} onChange={e=>setDeclaredValue(e.target.value)}/></label>{(['memberNo','itemName','unit','quantity','sourceReference','location','note','days'] as const).map((field,index)=><label key={field}>{['会员号','酒名','单位','数量','原订单编号（外部凭证）','存放位置','备注','存期天数（留空用品类默认）'][index]}<input required={index<4} value={form[field]} onChange={e=>setForm({...form,[field]:e.target.value})}/></label>)}<label>品类<select required value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">请选择</option>{categories.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name} · {c.default_days}天</option>)}</select></label><label>指定到期时间（优先于天数，北京时间）<input type="datetime-local" value={newExpiry} onChange={e=>setNewExpiry(e.target.value)}/></label>{policy?.extraFieldDefinitions.map(field=><label key={field.key}>{field.label}<input type={field.type==='number'?'text':field.type} required={field.required} maxLength={500} value={extraFields[field.key]??''} onChange={e=>setExtraFields({...extraFields,[field.key]:e.target.value})}/></label>)}<CustodyDepositCapture key={depositKey} api={api} memberNo={form.memberNo} disabled={busy} value={evidence} onChange={setEvidence}/><button type="submit" disabled={busy||!policy?.enabled||!evidence.photoBase64}>登记存酒</button></div></form></details>
 {manage&&policy&&<details><summary>存酒配置与品类</summary><p>停用新建后，已有存酒仍可办理取走及归档。</p><form onSubmit={event=>{event.preventDefault();void perform(async()=>{await command(`${path}/policy`,{policy,version,reason:reason||'调整存酒规则'});await config();setMessage('存酒配置已保存')})}}><div className="custody-fields">
 {(['enabled','remindersEnabled','allowPartial','allowRestorage','requireOriginalOrder'] as const).map((key,index)=><label key={key}><input type="checkbox" checked={policy[key]} onChange={e=>patch({[key]:e.target.checked})}/>{['启用新存酒','启用到期提醒','允许部分取酒和再存','允许再存','强制再存沿用原单'][index]}</label>)}
 <label>归档方式<select value={policy.archiveMode} onChange={e=>patch({archiveMode:e.target.value as Policy['archiveMode']})}><option value="automatic">取酒全部处理后自动归档</option><option value="manual">取酒全部处理后人工归档</option></select></label>
 {(['defaultDays','codeDigits','codeTtlSeconds','resendSeconds','maximumAttempts'] as const).map((key,index)=><label key={key}>{['默认存期天数','验证码位数','验证码有效秒数','重发间隔秒数','最大错误尝试次数'][index]}<input type="number" value={policy[key]} onChange={e=>patch({[key]:Number(e.target.value)})}/></label>)}
 <label>提醒档位（逗号分隔天数）<input value={policy.reminderDays.join(',')} onChange={e=>patch({reminderDays:e.target.value.split(/[,，]/).map(Number)})}/></label><label>提醒时间<input type="time" min="16:00" max="17:00" value={`${Math.floor(policy.sendMinute/60).toString().padStart(2,'0')}:${(policy.sendMinute%60).toString().padStart(2,'0')}`} onChange={e=>{const [hour,minute]=e.target.value.split(':').map(Number);patch({sendMinute:hour!*60+minute!})}}/></label>
 <label>取酒与提醒服务号<select value={policy.serviceAccountId??''} onChange={e=>patch({serviceAccountId:e.target.value||null})}><option value="">请选择服务号</option>{accounts.map(account=><option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label>编号格式<input value={policy.numberPattern} onChange={e=>patch({numberPattern:e.target.value})}/></label><label>打印标题<input value={policy.printTitle} onChange={e=>patch({printTitle:e.target.value})}/></label><label>打印页脚<textarea maxLength={300} value={policy.printFooter} onChange={e=>patch({printFooter:e.target.value})}/></label>{['category','item','quantity','remaining','expiry','location','status','source'].map((key,i)=><label key={key}><input type="checkbox" checked={policy.printFields.includes(key)} onChange={e=>patch({printFields:e.target.checked?[...policy.printFields,key]:policy.printFields.filter(f=>f!==key)})}/>打印：{['品类','酒名','原存量','剩余量','到期时间','位置','状态','原购凭证'][i]}</label>)}{['category','status','date'].map((key,i)=><label key={key}><input type="checkbox" checked={policy.reportDimensions.includes(key)} onChange={e=>patch({reportDimensions:e.target.checked?[...policy.reportDimensions,key]:policy.reportDimensions.filter(f=>f!==key)})}/>报表筛选：{['品类','状态','日期'][i]}</label>)}<label>提醒内容<textarea value={policy.reminderText} onChange={e=>patch({reminderText:e.target.value})}/></label><button type="submit" disabled={busy}>保存存酒规则</button></div></form>
 <h4>扩展录入字段</h4><p>最多20项；删除字段只影响新表单，历史单据保留当时字段名称和值。编辑后需点击“保存存酒规则”。</p>{policy.extraFieldDefinitions.map(field=><p key={field.key}>{field.label} · {field.required?'必填':'选填'}<button disabled={busy} onClick={()=>patch({extraFieldDefinitions:policy.extraFieldDefinitions.filter(f=>f.key!==field.key)})}>移除字段</button></p>)}<div className="custody-fields"><label>字段编号<input value={extraDefinition.key} onChange={e=>setExtraDefinition({...extraDefinition,key:e.target.value})}/></label><label>字段名称<input value={extraDefinition.label} onChange={e=>setExtraDefinition({...extraDefinition,label:e.target.value})}/></label><label>字段类型<select value={extraDefinition.type} onChange={e=>setExtraDefinition({...extraDefinition,type:e.target.value as ExtraField['type']})}><option value="text">文字</option><option value="number">数字</option><option value="date">日期</option></select></label><label><input type="checkbox" checked={extraDefinition.required} onChange={e=>setExtraDefinition({...extraDefinition,required:e.target.checked})}/>必填</label><button disabled={busy||policy.extraFieldDefinitions.length>=20} onClick={()=>{if(!/^[a-z][a-z0-9_]{0,29}$/.test(extraDefinition.key)||!extraDefinition.label.trim()||policy.extraFieldDefinitions.some(f=>f.key===extraDefinition.key)){setMessage('字段编号须为小写字母开头且不重复，并填写名称');return}patch({extraFieldDefinitions:[...policy.extraFieldDefinitions,extraDefinition]});setExtraDefinition({key:'',label:'',type:'text',required:false})}}>添加到待保存规则</button></div><h4>品类管理</h4>{categories.map(c=><p key={c.id}>{c.name} · {c.default_days}天 · {c.active?'启用':'停用'}<button disabled={busy} onClick={()=>setCategoryForm({id:c.id,code:c.code,name:c.name,defaultDays:c.default_days,active:c.active,sortOrder:c.sort_order})}>编辑</button></p>)}<form onSubmit={event=>{event.preventDefault();void perform(async()=>{await command(`${path}/categories`,categoryForm);await config();setMessage('品类已保存')})}}><div className="custody-fields"><label>品类编号<input required value={categoryForm.code} onChange={e=>setCategoryForm({...categoryForm,code:e.target.value})}/></label><label>品类名称<input required value={categoryForm.name} onChange={e=>setCategoryForm({...categoryForm,name:e.target.value})}/></label><label>默认到期天数<input type="number" min="1" max="3660" value={categoryForm.defaultDays} onChange={e=>setCategoryForm({...categoryForm,defaultDays:Number(e.target.value)})}/></label><label>排序<input type="number" min="0" value={categoryForm.sortOrder} onChange={e=>setCategoryForm({...categoryForm,sortOrder:Number(e.target.value)})}/></label><label><input type="checkbox" checked={categoryForm.active} onChange={e=>setCategoryForm({...categoryForm,active:e.target.checked})}/>品类启用</label><button disabled={busy} type="submit">保存品类</button><button type="button" disabled={busy} onClick={()=>setCategoryForm({code:'',name:'',defaultDays:20,active:true,sortOrder:0})}>清空新增</button></div></form></details>}
 </section>
}
