import {businessStatus,businessCurrency} from '../shared/staff-business-labels'
import {useState} from 'react'
import type {NormalizedApiClient,StaffAuthView} from '../normalized-api'
import {executeRecoverableCommand} from './recoverable-command'
import {createIdempotencyKey} from './cashier-mutation'
interface Report{items:{id:string;type:string;public_id:string;member_no:string|null;category:string;occurred_at:string;status:string;amount_minor:string|null;amount_basis:string;currency:string}[];nextOffset:number|null;summary:{type:string;currency:string;count:string;amount_minor:string;unknown_amount_count:string}[]}
export function CustodyReportPanel({api,auth}:{api:NormalizedApiClient;auth:StaffAuthView}){
 const [scope,setScope]=useState('custody'),[member,setMember]=useState(''),[category,setCategory]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[result,setResult]=useState<Report|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const input=()=>({scope,...(member?{memberNo:member}:{}),...(category?{category}:{}),...(from?{from:`${from}T00:00:00+08:00`}:{}),...(to?{to:new Date(Date.parse(`${to}T00:00:00+08:00`)+86400000).toISOString()}: {})})
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setMessage('');try{await fn()}catch(e){setMessage(e instanceof Error?e.message:'查询失败')}finally{setBusy(false)}}
 async function query(offset=0){const data=(await api.getEndpoint<{data:Report}>(`/api/staff/bottle-custody/report?${new URLSearchParams({...input(),offset:String(offset)})}`)).data;setResult(data)}
 return <details><summary>数据中心：选择统计范围</summary><p>存酒登记价值与消费订单应付金额分别汇总；均不能作为实收收入。同一消费订单只计一次，筛选商品品类时计入符合条件的整笔订单金额。</p><div className="custody-fields">
 <label>统计范围<select disabled={busy} value={scope} onChange={e=>{setScope(e.target.value);setResult(null)}}><option value="custody">存酒单</option><option value="sales" disabled={!auth.permissions.includes('order.history.all')}>消费订单</option><option value="all" disabled={!auth.permissions.includes('order.history.all')}>全部（分别统计）</option></select></label>
 <label>报表会员号<input disabled={busy} value={member} onChange={e=>{setMember(e.target.value);setResult(null)}}/></label><label>报表品类名称或代码<input disabled={busy} value={category} onChange={e=>{setCategory(e.target.value);setResult(null)}}/></label><label>报表开始日期<input disabled={busy} type="date" value={from} onChange={e=>{setFrom(e.target.value);setResult(null)}}/></label><label>报表结束日期<input disabled={busy} type="date" value={to} onChange={e=>{setTo(e.target.value);setResult(null)}}/></label>
 <button disabled={busy} onClick={()=>void run(()=>query())}>查询统计</button><button disabled={busy||!auth.permissions.includes('bottle.custody.export')} onClick={()=>void run(async()=>{const url='/api/staff/bottle-custody/report-export',body=input(),data=await executeRecoverableCommand(`${auth.employee.id}:${url}`,body,createIdempotencyKey('custody-report'),key=>api.postEndpoint<{base64:string;filename:string}>(url,body,{idempotencyKey:key}));const link=document.createElement('a'),objectUrl=URL.createObjectURL(new Blob([Uint8Array.from(atob(data.base64),c=>c.charCodeAt(0))],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));link.href=objectUrl;link.download=data.filename;link.click();setTimeout(()=>URL.revokeObjectURL(objectUrl),1000);setMessage('报表已导出')})}>导出所选范围</button></div>
 {message&&<p role="status">{message}</p>}{result?.summary.map(s=><p key={`${s.type}:${s.currency}`}>{s.type==='custody'?'存酒':'消费'} {s.count} 单 · {s.type==='custody'?'登记价值':'应付金额'} {(Number(s.amount_minor)/100).toFixed(2)} {businessCurrency(s.currency)} · 未登记金额 {s.unknown_amount_count} 单</p>)}
 <div className="custody-orders">{result?.items.map(r=><article key={`${r.type}:${r.id}`}><strong>{r.type==='custody'?'存酒':'消费'} · {r.public_id}</strong><p>会员 {r.member_no||'未关联'} · {r.category} · {businessStatus(r.status,r.type==='custody'?'custody':'sales')}</p><p>{r.amount_basis}：{r.amount_minor==null?'未登记':`${(Number(r.amount_minor)/100).toFixed(2)} ${businessCurrency(r.currency)}`}</p></article>)}</div>{result?.nextOffset!=null&&<button disabled={busy} onClick={()=>void run(()=>query(result.nextOffset!))}>下一页报表</button>}</details>
}
