import {useEffect,useRef,useState} from 'react'
import type {NormalizedApiClient} from '../normalized-api'
export interface DepositEvidenceInput{photoBase64:string;phone:string|null;fraction:string|null}
export const custodyFractions=[['1','整瓶','1'],['1/2','二分之一（1/2）','0.5'],['2/5','五分之二（2/5）','0.4'],['1/5','五分之一（1/5）','0.2'],['3/5','五分之三（3/5）','0.6'],['4/5','五分之四（4/5）','0.8'],['1/4','四分之一（1/4）','0.25'],['3/4','四分之三（3/4）','0.75'],['1/10','十分之一（1/10）','0.1']] as const
export function CustodyFractionSelect({quantity,unit,onChange}:{quantity:string;unit:string;onChange:(quantity:string)=>void}){
 return unit==='瓶'?<label>瓶内剩余比例<select aria-label="瓶内剩余比例" value={custodyFractions.find(f=>Number(f[2])===Number(quantity))?.[0]??'custom'} onChange={e=>{const f=custodyFractions.find(f=>f[0]===e.target.value);if(f)onChange(f[2]);else onChange('')}}>{custodyFractions.map(f=><option key={f[0]} value={f[0]}>{f[1]}</option>)}<option value="custom">其他数量（手动填写）</option></select></label>:null
}
export function CustodyDepositCapture({api,memberNo,disabled,value,onChange}:{api:NormalizedApiClient;memberNo:string;disabled:boolean;value:DepositEvidenceInput;onChange:(value:DepositEvidenceInput)=>void}){
 const container=useRef<HTMLDivElement>(null),video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),generation=useRef(0)
 const [camera,setCamera]=useState(false),[ready,setReady]=useState(false),[starting,setStarting]=useState(false),[error,setError]=useState(''),[phone,setPhone]=useState<{memberNo:string;maskedPhone:string|null}|null>(null),[contactError,setContactError]=useState('')
 function stop(){generation.current++;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setCamera(false);setReady(false);setStarting(false)}
 useEffect(()=>{const details=container.current?.closest('details');const onToggle=()=>{if(details&&!details.open)stop()};const onVisibility=()=>{if(document.hidden)stop()};details?.addEventListener('toggle',onToggle);document.addEventListener('visibilitychange',onVisibility);return()=>{details?.removeEventListener('toggle',onToggle);document.removeEventListener('visibilitychange',onVisibility);generation.current++;stream.current?.getTracks().forEach(t=>t.stop())}},[])
 useEffect(()=>{const controller=new AbortController();if(!memberNo.trim())return()=>controller.abort();const timeout=setTimeout(()=>{void api.getEndpoint<{data:{memberNo:string;maskedPhone:string|null}}>(`/api/staff/bottle-custody/member-contact?memberNo=${encodeURIComponent(memberNo.trim())}`,{signal:controller.signal}).then(r=>{if(!controller.signal.aborted){setPhone(r.data);setContactError('')}}).catch(e=>{if(!controller.signal.aborted){setPhone(null);setContactError(e instanceof Error?e.message:'会员手机号读取失败')}})},250);return()=>{controller.abort();clearTimeout(timeout)}},[api,memberNo])
 useEffect(()=>{if(camera&&video.current&&stream.current){video.current.srcObject=stream.current;void video.current.play().catch(()=>setError('无法播放摄像头，请关闭后重试'))}},[camera])
 async function start(){setError('');setStarting(true);const current=++generation.current;try{if(!navigator.mediaDevices?.getUserMedia)throw Error('当前环境不能调用摄像头，请使用HTTPS页面或本机localhost，并允许摄像头访问');const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:960}},audio:false});if(current!==generation.current){media.getTracks().forEach(t=>t.stop());return}stream.current=media;setCamera(true)}catch(e){if(current===generation.current)setError(e instanceof Error?`摄像头未就绪：${e.message}`:'摄像头无法使用，请检查授权')}finally{if(current===generation.current)setStarting(false)}}
 function capture(){try{const source=video.current;if(!source?.videoWidth||!source.videoHeight)throw Error('摄像头尚未就绪');const canvas=document.createElement('canvas'),scale=Math.min(1,1024/Math.max(source.videoWidth,source.videoHeight));canvas.width=Math.round(source.videoWidth*scale);canvas.height=Math.round(source.videoHeight*scale);const context=canvas.getContext('2d');if(!context)throw Error('无法生成照片');context.drawImage(source,0,0,canvas.width,canvas.height);onChange({...value,photoBase64:canvas.toDataURL('image/jpeg',0.78).split(',')[1]!});stop()}catch(e){setError(e instanceof Error?e.message:'拍照失败')}}
 const currentPhone=phone?.memberNo===memberNo.trim()?phone.maskedPhone:null
 return <div ref={container} className="custody-capture"><h4>手机号与存入照片（必填）</h4>{currentPhone?<p>会员登记手机号：{currentPhone}，保存时由系统自动关联。需要变更时请先更新会员联系信息。</p>:<><label>存酒联系手机号<input type="tel" autoComplete="off" maxLength={32} value={value.phone??''} disabled={disabled} onChange={e=>onChange({...value,phone:e.target.value})}/></label><p>优先读取会员登记手机号；没有登记时在此补填，仅用于本次存酒联系，不视为已验证会员手机号。</p></>}{contactError&&<p role="status">{contactError}</p>}{value.phone&&currentPhone&&<button type="button" disabled={disabled} onClick={()=>onChange({...value,phone:null})}>使用会员登记手机号</button>}
 <p>请拍清酒瓶、瓶内余量和封口。保存后照片会添加服务器北京时间水印；每次再存都需重新拍摄。</p>{error&&<p role="alert">{error}</p>}
 {camera?<><video ref={video} muted autoPlay playsInline onLoadedMetadata={()=>setReady(true)}/><button type="button" disabled={disabled||!ready} onClick={capture}>拍摄并使用</button><button type="button" onClick={stop}>关闭摄像头</button></>:<button type="button" disabled={disabled||starting} onClick={()=>void start()}>{starting?'正在打开摄像头…':value.photoBase64?'重新拍照':'打开摄像头拍照'}</button>}
 {value.photoBase64&&<><img src={`data:image/jpeg;base64,${value.photoBase64}`} alt="本次存酒照片预览，保存后添加时间水印"/><p>照片已拍摄，待保存入单。</p></>}
 </div>
}
