import { readFileSync } from 'node:fs'
import { describe,expect,it } from 'vitest'

const root=new URL('../../',import.meta.url)
const read=(path:string)=>readFileSync(new URL(path,root),'utf8')

describe('mini-program home editorial content',()=>{
  it('uses already-published activity and content projections, with a single permanent M-BOX story entry',()=>{
    const page=read('miniprogram/pages/home/index.js')
    const view=read('miniprogram/pages/home/index.wxml')
    expect(page).toContain('bootstrap.activities')
    expect(page).toContain('bootstrap.content')
    expect(page).toContain("item.displayMode === 'pinned'")
    expect(page).toContain('CONTENT_ROTATION_WINDOW_MS')
    expect(page).toContain("item.type !== 'article'")
    expect(page).toContain('return [MBOX_STORY_CARD].concat(pinned, rotating[rotationIndex])')
    expect(view).toContain('wx:if="{{brandStoryCard || upcomingActivity || editorialCards.length}}"')
    expect(view).toContain('bindtap="openFeaturedActivity"')
    expect(view).toContain('bindtap="openEditorial"')
    expect(view).toContain('class="published-content-card')
    expect(view).toContain('class="brand-story-card"')
    expect(page).toContain("code: 'mbox-story-1999'")
    expect(page).toContain("wx.navigateTo({ url: '/pages/brand-story/index' })")
    const loadData = page.slice(page.indexOf('async loadData()'), page.indexOf('async loadTableState('))
    const onLoad = page.slice(page.indexOf('onLoad(options)'), page.indexOf('onShow()'))
    expect(loadData).toContain('const homepageCards = homepageContentCards(bootstrap.content)')
    expect(onLoad).not.toContain('homepageCards')
    expect(view).not.toContain('home-campaign-mask')
    expect(page).not.toContain('wx.showModal({ title: card.title')
    expect(view).toContain('brandStoryCard.title')
  })

  it('puts the compact low-contrast story entry first and opens a readable article with a normal close action',()=>{
    const homeView=read('miniprogram/pages/home/index.wxml')
    const homeStyle=read('miniprogram/pages/home/index.wxss')
    const app=read('miniprogram/app.json')
    const storyPage=read('miniprogram/pages/brand-story/index.js')
    const storyView=read('miniprogram/pages/brand-story/index.wxml')
    const storyConfig=read('miniprogram/pages/brand-story/index.json')
    expect(homeView.indexOf('class="brand-story-card"')).toBeLessThan(homeView.indexOf('class="featured-activity-card"'))
    expect(homeStyle).toContain('background: #efeae1')
    expect(homeStyle).toContain('min-height: 136rpx')
    expect(app).toContain('"pages/brand-story/index"')
    expect(storyConfig).toContain('"navigationBarTitleText": "M-BOX 故事"')
    expect(storyView).toContain('一座仍在演出的城市档案')
    expect(storyView).toContain('关闭文章')
    expect(storyPage).toContain('wx.navigateBack()')
    expect(storyView).not.toContain('editorial-panel__close')
  })

  it('keeps the customer journey primary, leaves menu access in the tab bar, and hides unpublished editorial content',()=>{
    const view=read('miniprogram/pages/home/index.wxml')
    const app=read('miniprogram/app.json')
    expect(view.indexOf('今晚现场')).toBeLessThan(view.indexOf('发现 M-BOX'))
    expect(view).not.toContain('当前状态')
    expect(view).not.toContain('home-menu-entry')
    expect(app).toContain('"pagePath": "pages/order/index"')
    expect(app).toContain('"text": "点单"')
    expect(view).toContain('wx:if="{{brandStoryCard || upcomingActivity || editorialCards.length}}"')
  })

  it('projects live status, the full evening schedule, performer profile and a compact monthly entry',()=>{
    const page=read('miniprogram/pages/home/index.js')
    const view=read('miniprogram/pages/home/index.wxml')
    expect(page).toContain('(view.schedules || [])')
    expect(page).toContain("current ? '正在演出' : '即将开始'")
    expect(page).toContain("item.type === 'show'")
    expect(view).toContain('bindtap="openTonightSchedule"')
    expect(view).toContain('bindtap="openPerformerProfile"')
    expect(view).toContain('bindtap="openMonthlyPerformance"')
    expect(view).toContain('wx:for="{{performance.schedules}}"')
    expect(view).toContain('performance-shortcuts')
  })

  it('carries the forest palette through ordering and account controls while preserving WeChat green for checkout',()=>{
    const appStyle=read('miniprogram/app.wxss')
    const orderStyle=read('miniprogram/pages/order/index.wxss')
    const accountStyle=read('miniprogram/pages/account/index.wxss')
    expect(appStyle).toContain('linear-gradient(145deg, #315d46, #214635)')
    expect(orderStyle).toContain('background: #315d46')
    expect(orderStyle).toContain('linear-gradient(145deg, #315d46, #214635)')
    expect(accountStyle).toContain('border: 1rpx solid #315d46')
  })

  it('lets authorized staff draft, publish and pause homepage content without a mini-program release',()=>{
    const panel=read('src/normalized-ui/HomeContentManagementPanel.tsx')
    const app=read('server/normalized/normalized-app.ts')
    expect(panel).toContain("auth.permissions.includes('community.activity.manage')")
    expect(panel).toContain("auth.permissions.includes('community.activity.publish')")
    expect(panel).toContain('/api/staff/home-content-cards')
    expect(panel).toContain("operation:'publish'|'pause'")
    expect(panel).toContain('常驻首页')
    expect(panel).toContain('轮换展示')
    expect(app).toContain('memberContentCardApiPlugin')
  })
})
