import {useEffect,useEffectEvent,useState} from 'react'
import type {NormalizedApiClient,StaffAuthView} from '../normalized-api'
import {executeRecoverableCommand} from './recoverable-command'
import {createIdempotencyKey} from './cashier-mutation'
interface Policy{enabled:boolean;title:string;content:string;frequency:'daily'|'session'|'always';productIds:string[];version:number}
export function LaunchPopupPanel({api,auth}:{api:NormalizedApiClient;auth:StaffAuthView}){
 const allowed=auth.permissions.includes('community.activity.manage'),[value,setValue]=useState<Policy|null>(null),[products,setProducts]=useState<{id:string;name:string}[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 async function loadProducts(){const all:{id:string;name:string}[]=[];let offset:number|null=0;do{const response:{data:{items:{id:string;name:string}[];nextOffset:number|null}}=await api.getEndpoint(`/api/staff/launch-popup/product-options?offset=${offset}`);all.push(...response.data.items);offset=response.data.nextOffset}while(offset!==null);setProducts(all)}
 async function load(){const response=await api.getEndpoint<{data:Policy}>('/api/staff/launch-popup');setValue(response.data);try{await loadProducts()}catch{setMessage('配置已读到，推荐商品暂未读到，请刷新商品选项')}}
 async function perform(fn:()=>Promise<void>){if(busy)return;setBusy(true);try{await fn()}catch(e){setMessage(e instanceof Error?e.message:'操作未确认，请刷新核对')}finally{setBusy(false)}}
 const initialize=useEffectEvent(()=>{void perform(load)})
 useEffect(()=>{if(allowed)initialize()},[allowed,api,auth.employee.id])
 if(!allowed)return null
 return <section className="bottle-custody-panel"><h3>小程序打开弹窗</h3><button type="button" disabled={busy} onClick={()=>void perform(loadProducts)}>刷新商品选项</button><button disabled={busy} onClick={()=>void perform(load)}>刷新配置</button>{message&&<p role="status">{message}</p>}{value&&<form onSubmit={e=>{e.preventDefault();void perform(async()=>{const body={enabled:value.enabled,title:value.title,content:value.content,frequency:value.frequency,productIds:value.productIds,version:value.version};await executeRecoverableCommand(`${auth.employee.id}:launch-popup`,body,createIdempotencyKey('popup'),key=>api.postEndpoint('/api/staff/launch-popup',body,{idempotencyKey:key}));await load();setMessage('弹窗配置已保存')})}}><div className="custody-fields"><label><input type="checkbox" checked={value.enabled} onChange={e=>setValue({...value,enabled:e.target.checked})}/>启用弹窗</label><label>标题<input required maxLength={80} value={value.title} onChange={e=>setValue({...value,title:e.target.value})}/></label><label>展示频次<select value={value.frequency} onChange={e=>setValue({...value,frequency:e.target.value as Policy['frequency']})}><option value="daily">每天首次打开</option><option value="session">本次小程序启动首次</option><option value="always">每次回到小程序</option></select></label><label>内容<textarea maxLength={1000} value={value.content} onChange={e=>setValue({...value,content:e.target.value})}/></label></div><p>最多推荐8款公共在售商品，按添加顺序展示。专属卡商品不在公共弹窗中展示。</p><ol>{value.productIds.map((id,index)=><li key={id}>{products.find(p=>p.id===id)?.name??'商品已下架'}<button type="button" disabled={busy||index===0} onClick={()=>{const ids=[...value.productIds];[ids[index-1],ids[index]]=[ids[index]!,ids[index-1]!];setValue({...value,productIds:ids})}}>上移</button><button type="button" disabled={busy} onClick={()=>setValue({...value,productIds:value.productIds.filter(p=>p!==id)})}>移除</button></li>)}</ol><label>添加推荐商品<select value="" disabled={busy||value.productIds.length>=8} onChange={e=>{if(e.target.value)setValue({...value,productIds:[...value.productIds,e.target.value]})}}><option value="">请选择商品</option>{products.filter(p=>!value.productIds.includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button disabled={busy} type="submit">保存弹窗</button></form>}</section>
}
