import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const projectRoot = new URL('../../', import.meta.url)
const read = (path: string) => readFileSync(new URL(path, projectRoot), 'utf8')

describe('mini-program mobile business flow contract', () => {
  it('keeps exactly five fixed customer tabs in the agreed order', () => {
    const app = JSON.parse(read('miniprogram/app.json')) as { tabBar: { list: Array<{ pagePath: string; text: string }> } }
    expect(app.tabBar.list).toEqual([
      { pagePath: 'pages/home/index', text: '首页' },
      { pagePath: 'pages/reservations/index', text: '预约' },
      { pagePath: 'pages/order/index', text: '点单' },
      { pagePath: 'pages/community/index', text: '超嗨' },
      { pagePath: 'pages/profile/index', text: '我的' },
    ])
  })

  it('does not expose ordering before a trusted table scan and can recover a waiting table', () => {
    const order = read('miniprogram/pages/order/index.js')
    const orderView = read('miniprogram/pages/order/index.wxml')
    const session = read('miniprogram/utils/session.js')
    expect(order).toContain("connectionState: 'needs_scan'")
    expect(order).toContain("connected.status === 'waiting_for_table'")
    expect(order).toContain('this.scheduleWaitingPoll()')
    expect(order).toContain("['active', 'already_active'].includes(connected.status)")
    expect(order).toContain('onlyFromCamera: true')
    expect(orderView).toContain('桌面上的 M-BOX 固定二维码')
    expect(session).toContain("connection.status === 'waiting_for_table'")
    expect(session).toContain('connectionAge <= 30 * 60 * 1000')
    expect(session).toContain("return { token: decoded }")
  })

  it('uses three reservation steps and requests performances by the selected date', () => {
    const reservation = read('miniprogram/pages/reservations/index.js')
    const view = read('miniprogram/pages/reservations/index.wxml')
    expect(reservation).toContain('step: 1')
    expect(reservation).toContain('step: Math.min(3, this.data.step + 1)')
    expect(reservation).toContain('getReservationPerformances(this.data.reservationDate)')
    expect(reservation).toContain('preferredScheduleId: show ? show.id : null')
    expect(view).toContain('STEP 01')
    expect(view).toContain('STEP 02')
    expect(view).toContain('STEP 03')
    expect(view).toContain('该日期暂无已发布演出，仍可正常预约。')
  })

  it('routes every Superhigh card to detail and separates free registration from blocked paid registration', () => {
    const list = read('miniprogram/pages/community/index.js')
    const listView = read('miniprogram/pages/community/index.wxml')
    const listCss = read('miniprogram/pages/community/index.wxss')
    const detail = read('miniprogram/pages/community-detail/index.js')
    const detailView = read('miniprogram/pages/community-detail/index.wxml')
    expect(list).toContain('/pages/community-detail/index?id=')
    expect(listView).toContain('class="activity-summary"')
    expect(listView).toContain('{{item.summary}}')
    expect(listCss).toContain('-webkit-line-clamp:2')
    expect(detail).toContain("choices.includes('none')")
    expect(detail).toContain("availablePaymentMethods).includes('jsapi')")
    expect(detail).toContain('registrationBlocked')
    expect(detail).toContain('本次不会提交报名')
    expect(detail).toContain("if (activity.registrationBlocked) return this.setData({ error: activity.paymentBlockedText })")
    expect(detail).toContain('本活动暂不接受报名，也不会提前占用名额')
    expect(detailView).toContain('费用包含')
    expect(detailView).toContain('会员权益与赠送')
    expect(detailView).toContain('安全与参加要求')
  })

  it('shows real benefit inventory and known reservation/activity states without exposing customer voice entry', () => {
    const profile = read('miniprogram/pages/profile/index.js')
    const profileView = read('miniprogram/pages/profile/index.wxml')
    expect(profile).toContain("refund_requested: '退款待审核'")
    expect(profile).toContain("unknown: '付款结果待核对'")
    expect(profile).toContain("|| '状态待确认'")
    expect(profileView).toContain('我的权益与赠送')
    expect(profileView).toContain('接下来的安排')
    expect(profileView).toContain('{{item.statusText}}')
    expect(profile).toContain('tierProgress')
    expect(profile).toContain('upgradeRemaining')
    expect(profile).toContain('retainRemaining')
    expect(profile).toContain('expiringWithin30Days')
    expect(profileView).toContain('{{membership.upgradeText}}')
    expect(profileView).toContain('{{membership.retainText}}')
    expect(profileView).toContain('{{membership.expiryText}}')
    expect(profileView).toContain('积分欠额；新到账积分会优先冲抵')
    expect(profileView).not.toContain('积分待回收')

    const customerPages = collectFiles(new URL('miniprogram/pages/', projectRoot).pathname, /\.(js|wxml)$/)
      .map((path) => readFileSync(path, 'utf8')).join('\n')
    expect(customerPages).not.toMatch(/语音记录|开始录音|voice\/transcribe|wx\.getRecorderManager|wx\.startRecord/)
    expect(read('src/normalized-ui/staff-actions/TableObservationSheet.tsx')).toContain('语音记录')
  })

  it('provides a compact points and growth ledger with distinct business event names', () => {
    const app = read('miniprogram/app.json')
    const profile = read('miniprogram/pages/profile/index.js')
    const profileView = read('miniprogram/pages/profile/index.wxml')
    const points = read('miniprogram/pages/points/index.js')
    const pointsView = read('miniprogram/pages/points/index.wxml')
    const pointsCss = read('miniprogram/pages/points/index.wxss')
    expect(app).toContain('pages/points/index')
    expect(profile).toContain("wx.navigateTo({ url: '/pages/points/index' })")
    expect(profileView).toContain('查看积分与成长值明细')
    expect(points).toContain('getMiniLoyaltyLedger()')
    expect(points).toContain("reverse: '退款积分冲回'")
    expect(points).toContain("expire: '积分到期'")
    expect(points).toContain("supplement: '审核补发'")
    expect(points).toContain('processing: (ledger.processing || []).slice(0, 5)')
    expect(points).toContain('item.description')
    expect(points).toContain('item.sourceReference')
    expect(pointsView).toContain('积分只兑换指定商品或权益，不抵现金')
    expect(pointsView).toContain('顾客不能自行填写补分金额')
    expect(pointsView).toContain('处理进度')
    expect(pointsView).toContain('仅显示本人订单')
    expect(pointsView).not.toContain('item.reason')
    expect(profileView).not.toContain('item.reason')
    expect(pointsCss).toMatch(/\.ledger-tabs button \{[^}]*min-height: 88rpx;/)
    expect(pointsCss).toContain('.progress-card')
    expect(pointsCss).toContain('overflow-wrap: anywhere')
    expect(pointsCss).toContain('@media (max-width: 350px)')
  })

  it('persists only explicit product restrictions and keeps controls compact and reversible', () => {
    const order = read('miniprogram/pages/order/index.js')
    const profile = read('miniprogram/pages/profile/index.js')
    const profileView = read('miniprogram/pages/profile/index.wxml')
    const profileCss = read('miniprogram/pages/profile/index.wxss')
    const api = read('miniprogram/utils/api.js')
    expect(order).toContain("{ code: 'not_now', label: '这次不需要', persistent: false }")
    expect(order).toContain("{ code: 'dislike', label: '不喜欢这个', persistent: true }")
    expect(order).toContain("{ code: 'allergy_or_cannot_consume', label: '过敏或不能饮用', persistent: true }")
    expect(order).toContain('保存为我的长期限制？')
    expect(order).toContain("selectedReason.persistent ? 'explicit_product_restriction' : 'dismiss_for_current_session'")
    expect(profile).toContain('getProductRestrictions()')
    expect(profile).toContain('withdrawProductRestriction(publicId')
    expect(profileView).toContain('wx:if="{{productRestrictions.length}}"')
    expect(profileView).toContain('本人可撤回')
    expect(profileView).toContain('不代替点单前的成分核对或医疗建议')
    expect(profileCss).toMatch(/\.restriction-row button \{[^}]*min-height: 88rpx;/)
    expect(api).toContain("publicRequest('/api/public/mini/product-restrictions'")
    expect(api).toContain('/withdraw`')
  })

  it('records only an explicit removal of the selected recommendation as ignored', () => {
    const order = read('miniprogram/pages/order/index.js')
    expect(order).toContain("recordRecommendationEvent(attribution.recommendationPublicId, 'ignored', productId")
    expect(order).toContain("action: 'removed_selected_recommendation'")
    expect(order).toContain("}, 'removed_from_cart')")
    expect(order).toContain('item && item.quantity <= 0 && attribution')
    expect(order).not.toMatch(/if \(item\) item\.quantity \+= delta\s*recordRecommendationEvent/)
  })

  it('gives authorized staff a fail-closed live phase control with mobile touch targets', () => {
    const panel = read('src/normalized-ui/StaffModulePanel.tsx')
    const catalog = read('src/normalized-ui/CatalogManagementPanel.tsx')
    const css = read('src/normalized-ui/staff-module-panel.css')
    expect(panel).toContain('/api/staff/customer-experience/performance-phases/current')
    expect(panel).toContain('performance.phase.manage')
    expect(panel).toContain('推荐阶段尚未确认')
    expect(panel).toContain('受阶段限制的商品当前不会进入推荐')
    expect(panel).toContain('发现未关闭的阶段记录')
    expect(panel).toContain('取消过期记录')
    expect(panel).toContain('isPerformancePhaseCode(entry.phaseCode)')
    expect(panel).not.toContain('entry as PerformancePhaseEvent')
    expect(catalog).toContain("auth.permissions.includes('recommendation.phase.configure')")
    expect(catalog).toContain('/performance-phases`')
    expect(catalog).toContain('未选择任何阶段表示不受演出阶段限制')
    expect(catalog).toContain('单独保存阶段配置')
    expect(catalog).toContain('performancePhaseReason.trim().length < 2')
    expect(catalog).toContain('{ phaseCodes: performancePhaseCodes, reason }')
    expect(css).toMatch(/\.staff-performance-phase select, \.staff-performance-phase button \{ min-height: 44px;/)
    expect(css).toMatch(/\.catalog-performance-phase > button \{ min-height: 44px;/)
    expect(css).toContain('@media (max-width: 640px)')
    expect(css).toContain('.staff-performance-phase { align-items: stretch; flex-direction: column; }')
    expect(css).toContain('.catalog-performance-phase-options { grid-template-columns: repeat(2, minmax(0, 1fr)); }')
  })

  it('uses formal WeChat login in release builds and never falls back to anonymous identity', () => {
    const auth = read('miniprogram/utils/auth.js')
    const request = read('miniprogram/utils/request.js')
    const example = JSON.parse(read('miniprogram/config/runtime-config.example.json')) as {
      mbox: Record<string, unknown>
    }
    expect(auth).toContain('wx.login({')
    expect(auth).toContain("request('/api/wechat/challenges'")
    expect(auth).toContain("request('/api/wechat/code-authentication'")
    expect(auth).toContain("provider = 'wechat'")
    expect(auth).toContain('正式小程序尚未启用微信身份，已停止匿名访问')
    expect(request).toContain('headers.authorization = `Bearer ${identityToken}`')
    expect(example.mbox).toMatchObject({
      wechatIdentityEnabled: true,
      identityTenantId: 'your-tenant-uuid',
      identityStoreId: 'your-store-uuid',
      wechatAppId: 'wx-your-mini-program-app-id',
    })
    expect(`${auth}\n${request}\n${JSON.stringify(example)}`).not.toMatch(/appSecret|MBOX_WECHAT_APP_SECRET|ENCRYPTION_KEY/)
  })

  it('keeps the menu membership invite optional, retry-safe, and separate from phone or notification consent', () => {
    const order = read('miniprogram/pages/order/index.js')
    const orderView = read('miniprogram/pages/order/index.wxml')
    const termsPage = read('miniprogram/pages/membership-terms/index.js')
    const api = read('miniprogram/utils/api.js')
    const config = read('miniprogram/config/index.js')
    expect(order).toContain('membershipInviteVisible')
    expect(order).toContain('membershipInviteCooldownHours')
    expect(order).toContain("/pages/membership-terms/index?source=mini_menu&action=enroll")
    expect(termsPage).toContain("enrollMembership(terms.version, this.data.acknowledgementSource)")
    expect(termsPage).not.toMatch(/(?:removeStorageSync|setStorageSync).*?(?:cart|table)/)
    expect(orderView).toContain('阅读并加入')
    expect(orderView).toContain('暂不加入')
    expect(orderView).toContain('已有会员，找回权益')
    expect(orderView).toContain('查看当前入会条款全文')
    expect(orderView).toContain('membershipTerms.version')
    expect(termsPage).toContain('手机号和通知仍需另行授权')
    expect(api).toContain("mbox.membership.enroll.attempt.v1")
    expect(api).toContain("error.code !== 'NETWORK_ERROR'")
    expect(config).toContain('membershipInviteCooldownHours: 720')
    const privacy = read('miniprogram/pages/privacy/index.wxml')
    expect(privacy).toContain('点单不以入会为条件')
    expect(privacy).toContain('顾客页面不提供语音或麦克风入口')
    expect(privacy).toContain('仍须由运营主体逐项核准后才能正式发布')
    expect(privacy).not.toContain('当前小程序不发起或模拟支付')
  })

  it('keeps key customer inputs and actions at least 44px and has a compact-width fallback', () => {
    const globalCss = read('miniprogram/app.wxss')
    const reservationCss = read('miniprogram/pages/reservations/index.wxss')
    expect(globalCss).toMatch(/\.primary-button, \.secondary-button, \.danger-button \{ min-height: 88rpx;/)
    expect(globalCss).toMatch(/\.field__input \{ height: 88rpx;/)
    expect(globalCss).toContain('@media (max-width: 350px)')
    expect(reservationCss).toMatch(/\.picker-field\{[^}]*min-height:88rpx/)
    expect(reservationCss).toContain('@media(max-width:350px)')
  })

  it('keeps verified phone and activity contact correction inside a compact privacy disclosure',()=>{
    const view=read('miniprogram/pages/privacy/index.wxml')
    const page=read('miniprogram/pages/privacy/index.js')
    const css=read('miniprogram/pages/privacy/index.wxss')
    const api=read('miniprogram/utils/api.js')
    expect(view).toContain('管理我的联系方式')
    expect(view).toContain('已验证手机号')
    expect(view).toContain('授权并更换微信手机号')
    expect(view).toContain('活动报名联系')
    expect(view).toContain('新的11位手机号')
    expect(page).toContain('getVerifiedPhones()')
    expect(page).toContain('replaceVerifiedPhone(code)')
    expect(page).toContain('revokeVerifiedPhone(publicId)')
    expect(page).toContain('updateActivityRegistrationContact(registrationPublicId, contactValue)')
    expect(api).toContain("'/api/public/mini/membership/verified-phones'")
    expect(api).toContain("item.status !== 'active'")
    expect(api).toContain("/^CVC[0-9A-F]{32}$/")
    expect(view).toContain("item.status === 'active' ? '当前可用' : '已停用'")
    expect(api).toContain('/membership/verified-phones/replace')
    expect(api).toContain('/contact`')
    expect(css).toMatch(/\.privacy-contact-row button,\.privacy-phone-replace \{ min-height: 88rpx;/)
    expect(css).toContain('@media (max-width: 390px)')
    expect(page).not.toMatch(/语音|录音|麦克风|Recorder/)
  })
})

function collectFiles(directory: string, expression: RegExp): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name)
    return entry.isDirectory() ? collectFiles(path, expression) : expression.test(entry.name) ? [path] : []
  })
}
