import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const projectRoot = new URL('../../', import.meta.url)
const read = (path: string) => readFileSync(new URL(path, projectRoot), 'utf8')

describe('mini-program mobile business flow contract', () => {
  it('keeps exactly five fixed customer tabs in the agreed order', () => {
    const app = JSON.parse(read('miniprogram/app.json')) as { tabBar: { list: Array<{ pagePath: string; text: string }> } }
    expect(app.tabBar.list.map(({ pagePath,text })=>({ pagePath,text }))).toEqual([
      { pagePath: 'pages/home/index', text: '首页' },
      { pagePath: 'pages/reservations/index', text: '预约' },
      { pagePath: 'pages/order/index', text: '点单' },
      { pagePath: 'pages/community/index', text: '超嗨' },
      { pagePath: 'pages/profile/index', text: '我的' },
    ])
  })

  it('does not expose ordering before a trusted table scan and can recover a waiting table', () => {
    const order = read('miniprogram/pages/order/index.js')
    const orderView = read('miniprogram/pages/order/index.wxml')
    const session = read('miniprogram/utils/session.js')
    expect(order).toContain("connectionState: 'needs_scan'")
    expect(order).toContain("connected.status === 'waiting_for_table'")
    expect(order).toContain('this.scheduleWaitingPoll(request)')
    expect(order).toContain("['active', 'already_active'].includes(connected.status)")
    expect(order).toContain('onlyFromCamera: true')
    expect(orderView).toContain('到店扫码点单')
    expect(session).toContain("connection.status === 'waiting_for_table'")
    expect(session).toContain('connectionAge <= 30 * 60 * 1000')
    expect(session).toContain("return { token: decoded }")
  })

  it('uses three reservation steps and requests performances by the selected date', () => {
    const reservation = read('miniprogram/pages/reservations/index.js')
    const view = read('miniprogram/pages/reservations/index.wxml')
    expect(reservation).toContain('step: 1')
    expect(reservation).toContain('step: Math.min(3, this.data.step + 1)')
    expect(reservation).toContain('getReservationPerformances(this.data.reservationDate)')
    expect(reservation).toContain('preferredScheduleId: show ? show.id : null')
    expect(view).toContain('第一步')
    expect(view).toContain('第二步')
    expect(view).toContain('第三步')
    expect(view).toContain('这天暂未发布演出，可直接选位置。')
    expect(view).toContain('更想坐在哪里？')
    expect(view).toContain('这次想怎样相聚？')
    expect(view).toContain('choice-picker')
    expect(view).toContain('bindchange="onSeatChange"')
    expect(view).toContain('bindchange="onOccasionChange"')
  })

  it('routes every Superhigh card to detail and separates free registration from blocked paid registration', () => {
    const list = read('miniprogram/pages/community/index.js')
    const listView = read('miniprogram/pages/community/index.wxml')
    const listCss = read('miniprogram/pages/community/index.wxss')
    const detail = read('miniprogram/pages/community-detail/index.js')
    const detailView = read('miniprogram/pages/community-detail/index.wxml')
    expect(list).toContain('/pages/community-detail/index?id=')
    expect(listView).toContain('class="activity-summary"')
    expect(listView).toContain('{{item.summary}}')
    expect(listCss).toMatch(/-webkit-line-clamp:\s*2/)
    expect(detail).toContain("choices.includes('none')")
    expect(detail).toContain("availablePaymentMethods).includes('jsapi')")
    expect(detail).toContain('registrationBlocked')
    expect(detail).toContain('线上付款暂时不可用')
    expect(detail).toContain('本次报名尚未提交')
    expect(detail).toContain("if (activity.registrationBlocked || pricing.paymentAvailability === 'blocked')")
    expect(detail).toContain("activity.paymentBlockedText || '线上付款暂时不可用，本次报名尚未提交。'")
    expect(detail).toContain('本次报名尚未提交，也不会占用名额')
    expect(detailView).toContain('费用包含')
    expect(detailView).toContain('会员权益与赠送')
    expect(detailView).toContain('安全与参加要求')
  })

  it('starts WeChat payment immediately after a paid Superhigh registration is created', () => {
    const detail = read('miniprogram/pages/community-detail/index.js')
    const detailView = read('miniprogram/pages/community-detail/index.wxml')
    expect(detailView).toContain("'提交报名并支付'")
    expect(detail).toContain('shouldAutoStartPayment = Boolean(registration && registration.canStartPayment && payload.paymentChoice !== \'none\')')
    expect(detail).toContain("this.setData({ success: '名额已暂留，正在打开微信支付。' })")
    expect(detail).toContain('if (shouldAutoStartPayment) await this.startPayment()')
    expect(detail).toContain('if (options.length === 1) return options[0]')
    expect(detail).not.toContain('if (options.length === 1) return await this.confirmPayment')
  })

  it('shows real benefit inventory and known reservation/activity states without exposing customer voice entry', () => {
    const profile = read('miniprogram/pages/profile/index.js')
    const profileView = read('miniprogram/pages/profile/index.wxml')
    expect(profile).toContain("refund_requested: '退款申请确认中'")
    expect(profile).toContain("unknown: '付款结果待确认'")
    expect(profile).toContain("|| '状态待确认'")
    expect(profileView).toContain('可用权益')
    expect(profileView).toContain('已报名的超嗨活动')
    expect(profileView).toContain('我的订单')
    expect(profileView).toContain('我的预约')
    expect(profileView).toContain('我的偏好')
    expect(profileView).toContain('联系我们')
    expect(profileView).toContain('会员权益')
    expect(profileView).toContain('超嗨活动')
    expect(profileView).toContain('bindtap="openSuperhighService"')
    expect(profile).toContain("wx.switchTab({ url: '/pages/community/index' })")
    expect(profileView).toContain('metric-label">积分')
    expect(profileView).toContain('metric-label">优惠券')
    expect(profileView).toContain('metric-label">成长值')
    expect(profileView).not.toContain('储值余额')
    expect(profile).not.toContain('openBalance()')
    expect(profileView).not.toContain('消息提醒')
    expect(profileView).not.toContain('我的资料')
    expect(profileView).not.toContain('了解个人信息处理范围')
    expect(profileView).toContain('{{item.statusText}}')
    expect(profile).toContain('tierProgress')
    expect(profile).toContain('upgradeRemaining')
    expect(profile).toContain('retainRemaining')
    expect(profile).toContain('expiringWithin30Days')
    expect(profileView).toContain('{{membership.upgradeText}}')
    expect(profileView).toContain('{{membership.retainText}}')
    expect(profileView).toContain('{{membership.expiryText}}')
    expect(profileView).toContain('积分欠额；新到账积分会优先冲抵')
    expect(profileView).not.toContain('积分待回收')

    const customerPages = collectFiles(new URL('miniprogram/pages/', projectRoot).pathname, /\.(js|wxml)$/)
      .map((path) => readFileSync(path, 'utf8')).join('\n')
    expect(customerPages).not.toMatch(/语音记录|开始录音|voice\/transcribe|wx\.getRecorderManager|wx\.startRecord/)
    expect(read('src/normalized-ui/staff-actions/TableObservationSheet.tsx')).not.toMatch(/语音记录|开始录音|voice\/transcribe|MediaRecorder|webkitSpeechRecognition/)
  })

  it('provides a compact points and growth ledger with distinct business event names', () => {
    const app = read('miniprogram/app.json')
    const profile = read('miniprogram/pages/profile/index.js')
    const profileView = read('miniprogram/pages/profile/index.wxml')
    const points = read('miniprogram/pages/points/index.js')
    const pointsView = read('miniprogram/pages/points/index.wxml')
    const pointsCss = read('miniprogram/pages/points/index.wxss')
    expect(app).toContain('pages/points/index')
    expect(profile).toContain("wx.navigateTo({ url: '/pages/points/index' })")
    expect(profileView).toContain('最近积分')
    expect(profileView).toContain('service-chip')
    expect(profileView).toContain('service-chip__face')
    expect(points).toContain('getMiniLoyaltyLedger()')
    expect(points).toContain("reverse: '退款积分冲回'")
    expect(points).toContain("expire: '积分到期'")
    expect(points).toContain("supplement: '补发积分'")
    expect(points).toContain('processing: (ledger.processing || []).slice(0, 5)')
    expect(points).toContain('item.description')
    expect(points).toContain('item.sourceReference')
    expect(pointsView).toContain('积分只兑换指定商品或权益，不抵现金')
    expect(pointsView).toContain('如对积分有疑问，请联系门店协助核对')
    expect(pointsView).toContain('积分与成长值进展')
    expect(pointsView).toContain('仅显示你的记录')
    expect(pointsView).not.toContain('顾客不能自行填写补分金额')
    expect(pointsView).not.toContain('item.reason')
    expect(profileView).not.toContain('item.reason')
    expect(pointsCss).toMatch(/\.ledger-tabs button \{[^}]*min-height: 88rpx;/)
    expect(pointsCss).toContain('.progress-card')
    expect(pointsCss).toContain('overflow-wrap: anywhere')
    expect(pointsCss).toContain('@media (max-width: 390px)')
  })

  it('opens a separate member center instead of treating the points ledger as the member center', () => {
    const app = read('miniprogram/app.json')
    const profile = read('miniprogram/pages/profile/index.js')
    const profileView = read('miniprogram/pages/profile/index.wxml')
    const center = read('miniprogram/pages/member-center/index.js')
    const centerView = read('miniprogram/pages/member-center/index.wxml')
    expect(app).toContain('pages/member-center/index')
    expect(profile).toContain("wx.navigateTo({ url: '/pages/member-center/index' })")
    expect(center).toContain('getMiniBootstrap')
    expect(center).not.toContain('getCustomerBenefits')
    expect(center).toContain('bootstrap.growth')
    expect(center).toContain('bootstrap.processing')
    expect(center).toContain('qualificationGrowthText')
    expect(center).toContain("{ value: 'available', name: '可使用' }")
    expect(center).toContain("{ value: 'redeemed', name: '已核销' }")
    expect(center).toContain("continuous_qualification")
    expect(center).toContain('item.qualificationGrowth !== null')
    expect(center).toContain('item.estimatedSpendToNextTierMinor !== null')
    expect(center).toContain('memberCodeQrDataUrl')
    expect(center).toContain('claimCodeQrDataUrl')
    expect(centerView).toContain('会员中心')
    expect(centerView).toContain('我的会员码')
    expect(centerView).toContain('每日点心核销码')
    expect(centerView).toContain('确认后即可为你准备点心；这不是付款码')
    expect(centerView).toContain('我的权益')
    expect(centerView).toContain('成长进度')
    expect(centerView).toContain('年度礼遇')
    expect(centerView).toContain('达到条件后才可使用')
    expect(centerView).toContain('<block wx:if="{{membership}}">')
    expect(profileView).toContain('profile-member-card')
    expect(profileView).toContain('membership.levelEnglish')
  })

  it('persists only explicit product restrictions and keeps controls compact and reversible', () => {
    const order = read('miniprogram/pages/order/index.js')
    const profile = read('miniprogram/pages/profile/index.js')
    const profileView = read('miniprogram/pages/profile/index.wxml')
    const profileCss = read('miniprogram/pages/profile/index.wxss')
    const api = read('miniprogram/utils/api.js')
    expect(order).toContain("{ code: 'not_now', label: '这次不需要', persistent: false }")
    expect(order).toContain("{ code: 'dislike', label: '不喜欢这个', persistent: true }")
    expect(order).toContain("{ code: 'allergy_or_cannot_consume', label: '过敏或不能饮用', persistent: true }")
    expect(order).toContain('保存为我的长期限制？')
    expect(order).toContain("selectedReason.persistent ? 'explicit_product_restriction' : 'dismiss_for_current_session'")
    expect(profile).toContain('getProductRestrictions()')
    expect(profile).toContain('withdrawProductRestriction(publicId')
    expect(profileView).toContain('wx:if="{{productRestrictions.length}}"')
    expect(profileView).toContain('本人可撤回')
    expect(profileView).toContain('不代替点单前的成分核对或医疗建议')
    expect(profileCss).toMatch(/\.restriction-row button \{[^}]*min-height: 88rpx;/)
    expect(api).toContain("publicRequest('/api/public/mini/product-restrictions'")
    expect(api).toContain('/withdraw`')
  })

  it('keeps birthday month-day behind its atomic purpose-consent command',()=>{
    const preferences=read('miniprogram/pages/profile-preferences/index.js')
    const api=read('server/normalized/customer-experience-api.ts')
    const service=read('server/normalized/customer-experience-service.ts')
    expect(preferences).toContain('const birthdayMonthDay =')
    expect(preferences).toContain('recordBirthdayBenefitConsent(birthdayMonthDay)')
    expect(preferences).not.toMatch(/const preferences = \{[\s\S]{0,500}birthdayMonthDay:/)
    expect(api).toContain("const allowed = ['preferredAlcohol', 'tasteNotes', 'musicStyles', 'serviceIntensity', 'seatPreference', 'dietaryNotes']")
    expect(service).toContain("'BIRTHDAY_CHANGE_TOO_FREQUENT'")
    expect(service).toContain("preference_key='birthdayMonthDay'")
  })

  it('does not turn a failed member or benefit read into stale cards or a false zero',()=>{
    const profile=read('miniprogram/pages/profile/index.js')
    const view=read('miniprogram/pages/profile/index.wxml')
    expect(profile).toContain('const benefitsAvailable = Array.isArray(results[1])')
    expect(profile).toContain('benefitCount:null')
    expect(profile).toContain('membership:null')
    expect(view).toContain("benefitError ? '—'")
    expect(view).toContain('<view wx:if="{{benefitError}}" class="warning">{{benefitError}}</view>')
  })

  it('records only an explicit removal of the selected recommendation as ignored', () => {
    const order = read('miniprogram/pages/order/index.js')
    expect(order).toContain("recordRecommendationEvent(attribution.recommendationPublicId, 'ignored', productId")
    expect(order).toContain("action: 'removed_selected_recommendation'")
    expect(order).toContain("}, 'removed_from_cart')")
    expect(order).toContain('item && item.quantity + delta <= 0 && attribution')
    expect(order).not.toMatch(/if \(item\) item\.quantity \+= delta\s*recordRecommendationEvent/)
  })

  it('gives authorized staff a fail-closed live phase control with mobile touch targets', () => {
    const panel = read('src/normalized-ui/StaffModulePanel.tsx')
    const catalog = read('src/normalized-ui/CatalogManagementPanel.tsx')
    const css = read('src/normalized-ui/staff-module-panel.css')
    expect(panel).toContain('/api/staff/customer-experience/performance-phases/current')
    expect(panel).toContain('performance.phase.manage')
    expect(panel).toContain('推荐阶段尚未确认')
    expect(panel).toContain('受阶段限制的商品当前不会进入推荐')
    expect(panel).toContain('发现未关闭的阶段记录')
    expect(panel).toContain('取消过期记录')
    expect(panel).toContain('isPerformancePhaseCode(entry.phaseCode)')
    expect(panel).not.toContain('entry as PerformancePhaseEvent')
    expect(catalog).toContain("auth.permissions.includes('recommendation.phase.configure')")
    expect(catalog).toContain('/performance-phases`')
    expect(catalog).toContain('未选择任何阶段表示不受演出阶段限制')
    expect(catalog).toContain('单独保存阶段配置')
    expect(catalog).toContain('performancePhaseReason.trim().length < 2')
    expect(catalog).toContain('{ phaseCodes: performancePhaseCodes, reason }')
    expect(css).toMatch(/\.staff-performance-phase select, \.staff-performance-phase button \{ min-height: 44px;/)
    expect(css).toMatch(/\.catalog-performance-phase > button \{ min-height: 44px;/)
    expect(css).toContain('@media (max-width: 640px)')
    expect(css).toContain('.staff-performance-phase { align-items: stretch; flex-direction: column; }')
    expect(css).toContain('.catalog-performance-phase-options { grid-template-columns: repeat(2, minmax(0, 1fr)); }')
  })

  it('uses formal WeChat login in release builds and never falls back to anonymous identity', () => {
    const auth = read('miniprogram/utils/auth.js')
    const request = read('miniprogram/utils/request.js')
    const example = JSON.parse(read('miniprogram/config/runtime-config.example.json')) as {
      mbox: Record<string, unknown>
    }
    expect(auth).toContain('wx.login({')
    expect(auth).toContain("request('/api/wechat/challenges'")
    expect(auth).toContain("request('/api/wechat/code-authentication'")
    expect(auth).toContain("provider = 'wechat'")
    expect(auth).toContain('正式小程序尚未启用微信身份，已停止匿名访问')
    expect(request).toContain('headers.authorization = `Bearer ${identityToken}`')
    expect(example.mbox).toMatchObject({
      wechatIdentityEnabled: true,
      identityTenantId: 'your-tenant-uuid',
      identityStoreId: 'your-store-uuid',
      wechatAppId: 'wx-your-mini-program-app-id',
    })
    expect(`${auth}\n${request}\n${JSON.stringify(example)}`).not.toMatch(/appSecret|MBOX_WECHAT_APP_SECRET|ENCRYPTION_KEY/)
  })

  it('keeps the menu membership invite optional, retry-safe, and enrolls with WeChat phone on the terms page', () => {
    const order = read('miniprogram/pages/order/index.js')
    const orderView = read('miniprogram/pages/order/index.wxml')
    const termsPage = read('miniprogram/pages/membership-terms/index.js')
    const termsView = read('miniprogram/pages/membership-terms/index.wxml')
    const api = read('miniprogram/utils/api.js')
    const config = read('miniprogram/config/index.js')
    expect(order).toContain('membershipInviteVisible')
    expect(order).toContain('membershipInviteCooldownHours')
    expect(order).toContain("/pages/membership-terms/index?source=mini_menu&action=enroll")
    expect(termsPage).toContain("enrollMembership(terms.version, this.data.acknowledgementSource, authorization.code)")
    expect(termsPage).not.toContain('replaceVerifiedPhone(authorization.code)')
    expect(termsPage).not.toMatch(/(?:removeStorageSync|setStorageSync).*?(?:cart|table)/)
    expect(orderView).toContain('加入会员')
    expect(orderView).toContain('稍后再说')
    expect(orderView).toContain('我已是会员')
    expect(orderView).toContain('查看会员权益说明')
    expect(termsView).toContain('open-type="getPhoneNumber"')
    expect(termsView).toContain('授权手机号并加入')
    expect(termsView).toContain('agreedToPolicies')
    expect(termsView).toContain('我已阅读并同意《用户服务协议》和《隐私政策》')
    expect(termsView).toContain('查看《隐私政策》')
    expect(termsView).not.toContain('点击即表示')
    expect(termsView).toContain('hover-class="none"')
    expect(termsPage).toContain('agreedToPolicies: false')
    expect(termsPage).toContain('onAgreementChange')
    expect(termsPage).not.toContain("confirmText: '同意并加入'")
    expect(api).toContain("mbox.membership.enroll.attempt.v1")
    expect(api).toContain("'/api/public/mini/membership/enroll-with-phone'")
    expect(api).toContain('phoneAuthorizationCode')
    expect(api).toContain("error.code !== 'NETWORK_ERROR'")
    expect(config).toContain('membershipInviteCooldownHours: 24')
    const privacy = read('miniprogram/pages/privacy/index.wxml')
    const privacyPage = read('miniprogram/pages/privacy/index.js')
    expect(privacy).toContain('政策全文')
    expect(privacy).not.toMatch(/等待正式发布|暂未展示政策|候选/)
    expect(privacyPage).not.toMatch(/尚未正式发布|候选/)
    expect(privacy).not.toContain('当前小程序不发起或模拟支付')
  })

  it('does not render internal song-request states to customers', () => {
    const songs = read('miniprogram/pages/songs/index.js')
    expect(songs).toContain('点歌意向已提交，舞台确认后会显示最新进展。')
    expect(songs).not.toContain('当前状态：${request.status}')
  })

  it('keeps membership join tappable so WeChat review is not a silent disabled button', () => {
    const profile = read('miniprogram/pages/profile/index.js')
    const profileView = read('miniprogram/pages/profile/index.wxml')
    const termsPage = read('miniprogram/pages/membership-terms/index.js')
    const communityView = read('miniprogram/pages/community-detail/index.wxml')
    expect(profileView).toContain('邀请加入 M-BOX 会员')
    expect(profileView).toContain('确定加入并授权手机号')
    expect(profileView).toContain('bindgetphonenumber="quickLoginAndEnroll"')
    expect(profileView).not.toContain('阅读入会条款')
    expect(profileView).toContain('agreedToPolicies')
    expect(profileView).toContain('我已阅读并同意')
    expect(profileView).toContain('《用户服务协议》')
    expect(profileView).toContain('《隐私政策》')
    expect(profileView).not.toContain('disabled="{{!membershipTerms}}"')
    expect(profileView).toContain('wx:if="{{agreedToPolicies}}"')
    expect(profileView).toContain('login-action-link--pending')
    expect(profile).toContain("enrollMembership(terms.version, 'mini_profile', authorization.code)")
    expect(profile).toContain('openLoginSheet()')
    expect(profile).toContain('pendingMembershipAction')
    expect(profile).toContain('continuePendingMembershipAction()')
    expect(profile).toContain("requireMembership('member-center')")
    expect(profile).toContain("requireMembership('reservations')")
    expect(profile).toContain("requireMembership('points')")
    expect(profile).toContain('onAgreementChange')
    expect(profile).toContain('请先勾选并同意会员协议')
    expect(termsPage).toContain('暂时无法加入')
    expect(communityView).not.toContain('disabled="{{activity.registrationBlocked || busy}}"')
  })

  it('uses one valid WeChat open-type per phone button without hover transform swallowing taps', () => {
    const profileView = read('miniprogram/pages/profile/index.wxml')
    const profile = read('miniprogram/pages/profile/index.js')
    const privacyView = read('miniprogram/pages/privacy/index.wxml')
    const helper = read('miniprogram/utils/wechat-phone.js')
    const css = read('miniprogram/app.wxss')
    const config = read('miniprogram/config/index.js')
    expect(profileView).toContain('open-type="getPhoneNumber"')
    expect(profileView).toContain('hover-class="none"')
    expect(profileView).toContain('找回原会员')
    expect(profileView).not.toContain('getPhoneNumber|agreePrivacyAuthorization')
    expect(privacyView).toContain('open-type="getPhoneNumber"')
    const termsView = read('miniprogram/pages/membership-terms/index.wxml')
    expect(termsView).toContain('open-type="getPhoneNumber"')
    const allViews = collectFiles(new URL('miniprogram/pages/', projectRoot).pathname, /\.wxml$/)
      .map((path) => readFileSync(path, 'utf8')).join('\n')
    expect(allViews).not.toMatch(/open-type="[^"]*\|[^"]*"/)
    expect((allViews.match(/bindgetphonenumber=/g) ?? []).length).toBe(
      (allViews.match(/open-type="getPhoneNumber"/g) ?? []).length,
    )
    expect(profile).toContain('readWechatPhoneAuthorization')
    expect(helper).toContain('1400001')
    expect(css).toContain('.wx-phone-button')
    expect(config).toContain("wechatAppId: 'wxdb9f2dc413484f2d'")
    expect(config).toContain("apiBaseUrl: 'https://mbox.shmbox.com'")
  })

  it('keeps key customer inputs and actions at least 44px and has a compact-width fallback', () => {
    const globalCss = read('miniprogram/app.wxss')
    const reservationCss = read('miniprogram/pages/reservations/index.wxss')
    expect(globalCss).toMatch(/\.primary-button, \.secondary-button, \.danger-button \{ min-height: 88rpx;/)
    expect(globalCss).toMatch(/\.field__input \{ height: 88rpx;/)
    expect(globalCss).toContain('@media (max-width: 390px)')
    expect(reservationCss).toMatch(/\.picker-field\{[^}]*min-height:88rpx/)
    expect(reservationCss).toContain('@media(max-width:390px)')
  })

  it('keeps every customer page usable in the expanded Mate X5 viewport', () => {
    const globalCss = read('miniprogram/app.wxss')
    const homeCss = read('miniprogram/pages/home/index.wxss')
    const customerViews = collectFiles(new URL('miniprogram/pages/', projectRoot).pathname, /\.wxml$/)
    const foldFrameClasses = [
      '.top-band', '.home-hero', '.community-hero', '.detail-hero', '.profile-hero', '.points-head',
      '.contact-hero', '.order-head',
      '.reservation-head', '.service-head', '.status-head', '.performance-hero',
      '.preferences-hero', '.coupons-hero', '.notifications-hero',
    ]
    const foldOverlayClasses = [
      '.editorial-panel-mask', '.performance-panel-mask', '.member-invite-mask',
      '.community-member-mask', '.detail-member-mask', '.login-sheet-mask', '.sheet-mask',
    ]

    expect(globalCss).toContain('@media (min-width: 700px)')
    expect(globalCss).toMatch(/\.page \{[\s\S]*max-width: 720px;/)
    expect(globalCss).toContain('padding-right: 32px;')
    expect(globalCss).toContain('width: 620px;')
    expect(globalCss).toContain('max-height: calc(100vh - 64px);')
    foldFrameClasses.forEach((className) => expect(globalCss).toContain(`page ${className}`))
    foldOverlayClasses.forEach((className) => expect(globalCss).toContain(`page ${className}`))
    expect(globalCss).toContain('page .detail-dock')
    expect(globalCss).toContain('page .terms-dock')
    expect(globalCss).toContain('page .cart-dock')
    expect(homeCss).toContain('@media (min-width: 700px)')
    expect(homeCss).toMatch(/\.published-content-card \{[\s\S]*flex-basis: 100%;/)
    customerViews.forEach((path) => expect(readFileSync(path, 'utf8')).toMatch(/^<view class="page(?:\s|\")/))
  })

  it('keeps verified phone and activity contact correction inside a compact privacy disclosure',()=>{
    const view=read('miniprogram/pages/privacy/index.wxml')
    const page=read('miniprogram/pages/privacy/index.js')
    const css=read('miniprogram/pages/privacy/index.wxss')
    const api=read('miniprogram/utils/api.js')
    expect(view).toContain('管理我的联系方式')
    expect(view).toContain('已验证手机号')
    expect(view).toContain('授权并更换微信手机号')
    expect(view).toContain('活动报名联系')
    expect(view).toContain('新的11位手机号')
    expect(page).toContain('getVerifiedPhones()')
    expect(page).toContain('replaceVerifiedPhone(authorization.code)')
    expect(page).toContain('revokeVerifiedPhone(publicId)')
    expect(page).toContain('updateActivityRegistrationContact(registrationPublicId, contactValue)')
    expect(api).toContain("'/api/public/mini/membership/verified-phones'")
    expect(api).toContain("item.status !== 'active'")
    expect(api).toContain("/^CVC[0-9A-F]{32}$/")
    expect(view).toContain("item.status === 'active' ? '当前可用' : '已停用'")
    expect(api).toContain('/membership/verified-phones/replace')
    expect(api).toContain('/contact`')
    expect(css).toMatch(/\.privacy-contact-row button,\.privacy-phone-replace \{ min-height: 88rpx;/)
    expect(css).toContain('@media (max-width: 390px)')
    expect(page).not.toMatch(/语音|录音|麦克风|Recorder/)
  })
})

function collectFiles(directory: string, expression: RegExp): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name)
    return entry.isDirectory() ? collectFiles(path, expression) : expression.test(entry.name) ? [path] : []
  })
}
