import {businessStatus} from '../shared/staff-business-labels'
import './social-account-panel.css'
import {useEffect,useEffectEvent,useState} from 'react'
import type {NormalizedApiClient,StaffAuthView} from '../normalized-api'
import {executeRecoverableCommand} from './recoverable-command'
import {createIdempotencyKey} from './cashier-mutation'
interface Account{id:string;kind:string;name:string;app_id:string;enabled:boolean;code_template_id:string|null;code_data_key:string;reminder_template_id:string|null;reminder_data_key:string}
interface Project{id:string;name:string;status:string;service_account_id:string|null;wecom_account_id:string|null;artist_name:string;auto_restore:boolean;icon_url:string|null}
interface MenuItem{product_id:string;name:string;exclusive:boolean;active:boolean;sort_order:number;exclusive_price_minor:string|null}
export function SocialAccountPanel({api,auth}:{api:NormalizedApiClient;auth:StaffAuthView}){
 const allowed=auth.permissions.includes('member.card.manage'),[events,setEvents]=useState<{id:string;account_name:string;event_type:string;status:string;received_at:string;error_code:string|null}[]>([]),[products,setProducts]=useState<{id:string;name:string}[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[projects,setProjects]=useState<Project[]>([]),[items,setItems]=useState<MenuItem[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const empty={id:'',kind:'service_account',name:'',appId:'',enabled:false,secret:'',token:'',encodingAesKey:'',codeTemplateId:'',codeDataKey:'number1',reminderTemplateId:'',reminderDataKey:'thing1'}
 const [form,setForm]=useState(empty),[accountEditorOpen,setAccountEditorOpen]=useState(false),[projectId,setProjectId]=useState(''),[rule,setRule]=useState({serviceAccountId:'',wecomAccountId:'',artistName:'',iconUrl:'',autoRestore:false}),[cardPrice,setCardPrice]=useState(''),[menu,setMenu]=useState({productId:'',exclusive:true,active:true,sortOrder:0})
 async function perform(fn:()=>Promise<void>){if(busy)return;setBusy(true);setMessage('');try{await fn()}catch(error){setMessage(error instanceof Error?error.message:'操作结果未确认，请刷新核对')}finally{setBusy(false)}}
 async function command(url:string,body:unknown){return executeRecoverableCommand(`${auth.employee.id}:${url}`,body,createIdempotencyKey('social'),key=>api.postEndpoint(url,body,{idempotencyKey:key}))}
 async function load(){const a=await api.getEndpoint<{data:Account[]}>('/api/staff/social-accounts');setAccounts(a.data);const all:Project[]=[];let cursor:string|null=null;do{const result:{data:{items:Project[];nextCursor:string|null}}=await api.getEndpoint<{data:{items:Project[];nextCursor:string|null}}>(`/api/staff/member-cards/projects${cursor?`?cursor=${cursor}`:''}`);all.push(...result.data.items);cursor=result.data.nextCursor}while(cursor);setProjects(all);setEvents((await api.getEndpoint<{data:typeof events}>('/api/staff/social-accounts/events')).data);await loadProducts()}
 async function loadProducts(){const products:{id:string;name:string}[]=[];let offset:number|null=0;do{const result:{data:{items:{id:string;name:string}[];nextOffset:number|null}}=await api.getEndpoint(`/api/staff/member-cards/product-options?offset=${offset}`);products.push(...result.data.items);offset=result.data.nextOffset}while(offset!==null);setProducts(products)}
 async function menuList(id=projectId){if(id)setItems((await api.getEndpoint<{data:MenuItem[]}>(`/api/staff/member-cards/projects/${id}/menu`)).data)}
 function beginEdit(a:Account){setForm({...empty,id:a.id,kind:a.kind,name:a.name,appId:a.app_id,enabled:a.enabled,codeTemplateId:a.code_template_id??'',codeDataKey:a.code_data_key,reminderTemplateId:a.reminder_template_id??'',reminderDataKey:a.reminder_data_key});setAccountEditorOpen(true)}
 function beginCreate(){setForm(empty);setAccountEditorOpen(true)}
 const initialize=useEffectEvent(()=>{void perform(load)})
 useEffect(()=>{if(allowed)initialize()},[allowed,api,auth.employee.id])
 if(!allowed)return null
 return <section className="bottle-custody-panel social-account-panel"><h3>服务号、企业微信与专属卡</h3><button disabled={busy} onClick={()=>void perform(load)}>刷新配置</button>{message&&<p role="status">{message}</p>}
 {accounts.map(a=><div key={a.id}><strong>{a.name} · {a.kind==='service_account'?'服务号':'企业微信'} · {a.enabled?'启用':'停用'}</strong><p>配置编号：{a.id}</p><p>回调路径：/api/social-accounts/{a.id}/callback</p><button disabled={busy} type="button" onClick={()=>beginEdit(a)}>编辑账号</button></div>)}
 <details open={accountEditorOpen} onToggle={event=>setAccountEditorOpen(event.currentTarget.open)}><summary>{form.id?'编辑微信账号':'新增微信账号'}</summary><p>回调地址需加本站正式域名。已有密钥不回显；留空保留原密钥。取酒验证码与存酒到期提醒均填服务号<strong>一次性订阅</strong>模板 ID：验证码用「验证码下放通知」（number1/thing3/thing2），到期提醒用「存酒到期提醒」（thing1/character_string2/thing3/time4/time5）。不要再填已拒审的模板消息 ID。</p><form onSubmit={event=>{event.preventDefault();void perform(async()=>{const credentials=form.secret||form.token||form.encodingAesKey?{secret:form.secret,token:form.token,encodingAesKey:form.encodingAesKey}:undefined;await command('/api/staff/social-accounts',{...(form.id?{id:form.id}:{}),kind:form.kind,name:form.name,appId:form.appId,enabled:form.enabled,...(credentials?{credentials}:{}),codeTemplateId:form.codeTemplateId||null,codeDataKey:form.codeDataKey,reminderTemplateId:form.reminderTemplateId||null,reminderDataKey:form.reminderDataKey});setForm(empty);setAccountEditorOpen(false);await load();setMessage('账号已保存，真实平台连接与送达需验证。')})}}><div className="custody-fields"><label>类型<select disabled={!!form.id} value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="service_account">微信服务号</option><option value="wecom">企业微信</option></select></label>
 {(['name','appId','secret','token','encodingAesKey','codeTemplateId','codeDataKey','reminderTemplateId','reminderDataKey'] as const).map((key,index)=><label key={key}>{['名称','AppID / CorpID','AppSecret / 客户联系Secret','回调Token','回调EncodingAESKey','取酒验证码订阅模板ID','验证码主字段(number1)','存酒到期订阅模板ID','提醒字段(保留)'][index]}<input type={['secret','token','encodingAesKey'].includes(key)?'password':'text'} autoComplete="off" disabled={key==='appId'&&!!form.id} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>启用</label><button disabled={busy} type="submit">保存账号</button><button type="button" onClick={()=>beginCreate()}>清空并新增</button></div></form></details>
 <h4>专属卡配置</h4><label>选择卡项目<select disabled={busy} value={projectId} onChange={e=>{const id=e.target.value,p=projects.find(p=>p.id===id);setProjectId(id);setRule({serviceAccountId:p?.service_account_id??'',wecomAccountId:p?.wecom_account_id??'',artistName:p?.artist_name??'',iconUrl:p?.icon_url??'',autoRestore:p?.auto_restore??false});void perform(()=>menuList(id))}}><option value="">请选择已有卡项目</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name} · {businessStatus(p.status,'project')}</option>)}</select></label>
 {projectId&&<><form onSubmit={event=>{event.preventDefault();void perform(async()=>{await command(`/api/staff/member-cards/projects/${projectId}/social-policy`,{...rule,iconUrl:rule.iconUrl||null});await load();setMessage('双条件门槛已保存；项目开放后缺少任一条件即失效。')})}}><div className="custody-fields"><label>艺人 / IP名称<input required value={rule.artistName} onChange={e=>setRule({...rule,artistName:e.target.value})}/></label><label>图标地址<input value={rule.iconUrl} onChange={e=>setRule({...rule,iconUrl:e.target.value})}/></label><label>绑定服务号<select required value={rule.serviceAccountId} onChange={e=>setRule({...rule,serviceAccountId:e.target.value})}><option value="">请选择</option>{accounts.filter(a=>a.kind==='service_account').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>绑定企业微信<select required value={rule.wecomAccountId} onChange={e=>setRule({...rule,wecomAccountId:e.target.value})}><option value="">请选择</option>{accounts.filter(a=>a.kind==='wecom').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label><input type="checkbox" checked={rule.autoRestore} onChange={e=>setRule({...rule,autoRestore:e.target.checked})}/>条件恢复后自动恢复（人工撤销不恢复）</label><button disabled={busy||projects.find(p=>p.id===projectId)?.status!=='draft'} type="submit">保存草稿加入门槛</button></div></form>
 <h4>专属菜单增量</h4><p>公共商品保持对所有人可见。专属增量请从商品管理新增非公共单品或套餐，可配持卡价；多卡取最低价，与优惠券等其他优惠互斥。公共商品配置持卡价时请取消“仅持卡可见”。</p>{items.map(item=><p key={item.product_id}>{item.name} · {item.active?'上架':'下架'} · 排序 {item.sort_order}<button disabled={busy} onClick={()=>{setMenu({productId:item.product_id,exclusive:item.exclusive,active:item.active,sortOrder:item.sort_order});setCardPrice(item.exclusive_price_minor==null?'':(Number(item.exclusive_price_minor)/100).toFixed(2))}}>编辑</button><button disabled={busy} onClick={()=>void perform(async()=>{await command(`/api/staff/member-cards/projects/${projectId}/menu/remove`,{productId:item.product_id});await menuList();setMessage('专属项已从本卡移除，历史订单保留')})}>移除此项</button></p>)}<form onSubmit={event=>{event.preventDefault();void perform(async()=>{if(cardPrice&&!/^(?:0|[1-9][0-9]{0,6})(?:\.[0-9]{1,2})?$/.test(cardPrice))throw new Error('持卡价须为最多两位小数的金额');await command(`/api/staff/member-cards/projects/${projectId}/menu`,{...menu,exclusivePriceMinor:cardPrice?Math.round(Number(cardPrice)*100):null});await menuList();setMessage('专属菜单已保存')})}}><div className="custody-fields"><label>选择商品<select required value={menu.productId} onChange={e=>setMenu({...menu,productId:e.target.value})}><option value="">请选择专属商品</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>持卡价（元，留空沿用标准价）<input inputMode="decimal" value={cardPrice} onChange={e=>setCardPrice(e.target.value)}/></label><label><input type="checkbox" checked={menu.exclusive} onChange={e=>setMenu({...menu,exclusive:e.target.checked})}/>仅持卡可见的增量商品</label><label>显示排序<input type="number" value={menu.sortOrder} onChange={e=>setMenu({...menu,sortOrder:Number(e.target.value)})}/></label><label><input type="checkbox" checked={menu.active} onChange={e=>setMenu({...menu,active:e.target.checked})}/>上架</label><button disabled={busy} type="submit">保存专属项</button></div></form></>}
 <details><summary>最近100条平台回调处理记录</summary>{events.map(event=><p key={event.id}>{event.account_name} · {event.event_type} · {businessStatus(event.status,'social')} · {new Date(event.received_at).toLocaleString('zh-CN')} {event.error_code}{event.status==='failed'&&<button disabled={busy} onClick={()=>void perform(async()=>{await command(`/api/staff/social-accounts/events/${event.id}/retry`,{});await load();setMessage('已登记重新处理，可刷新核对结果')})}>重新处理</button>}</p>)}</details></section>
}
