import {describe,it,expect} from 'vitest'
import {ReservationReception,canCompleteReservation,receptionTime,validateReceptionSeat,type ReceptionCreateInput,type ReceptionSeatInput,type ReceptionRequest,type ReceptionStorage} from './reservation-reception'
import {StaffActionsApi} from './staff-actions-api'
import {STAFF_SESSION_BINDING_HEADER} from '../../shared/staff-session-binding'
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`
const actor=id(1),other=id(2),reservationId=id(3),tableA=id(4),tableB=id(5),sessionA=id(6),sessionB=id(7)
const input:ReceptionCreateInput={customerName:'隔离预约顾客',contact:'13812345678',guestCount:6,arrivalAt:'2099-10-05T10:00:00.000Z',expectedEndAt:'2099-10-05T12:00:00.000Z',source:'phone',initialStatus:'confirmed',note:'电话确认',seatPreference:'no_preference',reservationPolicyVersion:1,preferredScheduleId:null}
const seat:ReceptionSeatInput={protocol:1,reservationVersion:2,sessions:[{tableSessionId:sessionA,expectedTableId:tableA,expectedLocationVersion:0,expectedGuestCount:3},{tableSessionId:sessionB,expectedTableId:tableB,expectedLocationVersion:1,expectedGuestCount:4}],reason:'实际多一人，核对本组两桌已全部安排'}
function createReceipt(body:Record<string,unknown>,key:string){return{data:{protocol:1,operation:'create',employeeId:actor,requestKey:key,reservation:{id:reservationId,publicId:body.publicId,customerId:id(9),customerName:body.customerName,guestCount:body.guestCount,arrivalAt:body.arrivalAt,expectedEndAt:body.expectedEndAt,source:body.source,seatPreference:body.seatPreference,note:body.note,status:body.initialStatus,aggregateVersion:1,ownerEmployeeId:actor,tableLocks:[],reservationSnapshot:{receptionProtocol:1,physicalTablesPreassigned:false},contactAvailable:true},maskedContact:'138****5678'},meta:{replayed:false}}}
function seatReceipt(body:ReceptionSeatInput,key:string){return{data:{protocol:1,operation:'seat',employeeId:actor,requestKey:key,reservation:{id:reservationId,publicId:'reception-existing',guestCount:6,status:'seated',aggregateVersion:body.reservationVersion+1},seating:{batchId:id(8),customerId:id(9),seatedAt:'2026-10-05T12:00:00Z',seatedByEmployeeId:actor,seatedGuestCount:body.sessions.reduce((n,s)=>n+s.expectedGuestCount,0),reservationGuestCount:6,reason:body.reason,sessions:body.sessions.map(s=>({tableSessionId:s.tableSessionId,tableIdAtSeating:s.expectedTableId,tableCodeAtSeating:s.expectedTableId===tableA?'A01':'A02',locationVersionAtSeating:s.expectedLocationVersion,guestCountAtSeating:s.expectedGuestCount}))}},meta:{replayed:false}}}
function harness(){
  const values=new Map<string,string>();let owner=actor,sequence=10,mode='ok',created:unknown=null,placed:unknown=null
  const calls:Array<{path:string;method:string;body?:string;key?:string}>=[]
  const storage:ReceptionStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>{values.set(k,v)},removeItem:k=>{values.delete(k)}}
  const request:ReceptionRequest=async(path,init)=>{
    calls.push({path,method:init?.method??'GET',body:init?.body,key:init?.key})
    if(path.endsWith('native-reservation-capabilities'))return{data:mode==='legacy'?{durableCreate:true}:{admissionCreateV1:true,receptionSeatV1:true}}
    if(path.includes('/by-public-id/')){if(mode==='missing')throw Object.assign(Error('原回执暂未查到'),{status:404,code:'RESERVATION_RECEIPT_NOT_FOUND'});if(mode==='unavailable')throw Object.assign(Error('暂时无法核对'),{status:503});return{...(created as object),meta:{replayed:true}}}
    if(init?.method==='POST'){
      if(mode==='definite')throw Object.assign(Error('名额已变化'),{status:409,code:'RESERVATION_CAPACITY_UNAVAILABLE',commitDisposition:'not_committed'})
      if(mode==='conflict')throw Object.assign(Error('原键冲突'),{status:409,code:'IDEMPOTENCY_CONFLICT'})
      const result=path.endsWith('/seat')?(placed??=seatReceipt(JSON.parse(init.body!),init.key!)):(created??=createReceipt(JSON.parse(init.body!),init.key!))
      if(mode==='lost')throw Object.assign(Error('网络中断'),{status:null,code:'NETWORK_ERROR'})
      if(mode==='wrong')return{...result as object,data:{...(result as {data:object}).data,employeeId:other}}
      return result
    }
    throw Error('Unexpected fixture path '+path)
  }
  const make=(scope='https://fixture.local',s:ReceptionStorage|undefined=storage,req=request)=>new ReservationReception(req,()=>owner,s,scope,()=>id(++sequence))
  return{values,storage,calls,request,make,setOwner:(v:string)=>{owner=v},setMode:(v:string)=>{mode=v}}
}
describe('reservation reception v1 original-request lifecycle',()=>{
  it('registers admission only and confirms the exact original public receipt',async()=>{const h=harness(),api=h.make();const receipt=await api.create(input);expect(receipt.operation).toBe('create');expect(api.pending()).toEqual([]);const sent=JSON.parse(h.calls.find(c=>c.method==='POST')!.body!);expect(sent.publicId).toMatch(/^reception-/);expect(sent).not.toHaveProperty('tableIds');expect(sent.contact).toBe(input.contact)})
  it('keeps only an opaque original reference on disk and retries the identical body/key within the page',async()=>{const h=harness(),api=h.make();h.setMode('lost');await expect(api.create(input)).rejects.toThrow('网络中断');const stored=[...h.values.values()].join('');expect(stored).not.toContain(input.contact);expect(stored).not.toContain(input.customerName);expect(stored).not.toContain(input.note!);expect(stored).not.toContain('fingerprint');await expect(api.create({...input,guestCount:8})).rejects.toThrow('原预约');h.setMode('ok');await api.recover('create');const posts=h.calls.filter(c=>c.method==='POST');expect(posts).toHaveLength(2);expect(posts[1]).toEqual(posts[0]);expect(api.pending()).toEqual([])})
  it('after reload queries only the original public ID and key, never re-creates a body',async()=>{const h=harness();h.setMode('lost');await expect(h.make().create(input)).rejects.toThrow();h.setMode('ok');const receipt=await h.make().recover('create');expect(receipt.reservation.id).toBe(reservationId);expect(h.calls.filter(c=>c.method==='POST')).toHaveLength(1);const post=h.calls.find(c=>c.method==='POST')!;expect(h.calls.at(-1)!.path).toContain(JSON.parse(post.body!).publicId);expect(h.calls.at(-1)!.path).toContain(encodeURIComponent(post.key!));expect(h.values.size).toBe(0)})
  it.each(['missing','unavailable'])('keeps a reload result unknown on %s and blocks a new public ID',async mode=>{const h=harness();h.setMode('lost');await expect(h.make().create(input)).rejects.toThrow();const before=[...h.values.values()];h.setMode(mode);const api=h.make();await expect(api.recover('create')).rejects.toThrow();await expect(api.create(input)).rejects.toThrow('原预约');expect([...h.values.values()]).toEqual(before);expect(h.calls.filter(c=>c.method==='POST')).toHaveLength(1)})
  it('never reads or replays an old employee or origin pending request',async()=>{const h=harness();h.setMode('lost');await expect(h.make().create(input)).rejects.toThrow();const count=h.calls.length;h.setOwner(other);const api=h.make();expect(api.pending()[0].canRecover).toBe(false);await expect(api.recover('create')).rejects.toThrow('原员工');h.setOwner(actor);await expect(h.make('https://another.local').recover('create')).rejects.toThrow('原门店');expect(h.calls).toHaveLength(count)})
  it('keeps a late successful receipt pending when the employee changed in flight',async()=>{const h=harness();const api=h.make(undefined,undefined,async(path,init)=>{const result=await h.request(path,init);if(init?.method==='POST')h.setOwner(other);return result});await expect(api.create(input)).rejects.toThrow('员工已切换');expect(h.values.size).toBe(1);h.setOwner(actor);await h.make().recover('create');expect(h.values.size).toBe(0)})
  it.each(['write','silent-write'])('blocks all mutation dispatch when reference storage %s fails',async failure=>{const h=harness();const storage={...h.storage,setItem:()=>{if(failure==='write')throw Error('storage full')}};await expect(h.make(undefined,storage).create(input)).rejects.toThrow('未能保存');expect(h.calls.some(c=>c.method==='POST')).toBe(false)})
  it('keeps confirmed state after removal failure and recovers read-only without another POST',async()=>{const h=harness();let fail=true;const storage={...h.storage,removeItem:(key:string)=>{if(fail)throw Error('blocked');h.storage.removeItem(key)}};const api=h.make(undefined,storage);await expect(api.create(input)).rejects.toThrow('未能清除');expect(JSON.parse([...h.values.values()][0]).confirmed).toBe(true);fail=false;await api.recover('create');expect(h.calls.filter(c=>c.method==='POST')).toHaveLength(1);expect(h.values.size).toBe(0)})
  it('does not discard the original when a foreign/malformed receipt arrives',async()=>{const h=harness();h.setMode('wrong');const api=h.make();await expect(api.create(input)).rejects.toThrow('回执');expect(api.pending()).toHaveLength(1)})
  it('allows editing after explicit authoritative not_committed, but retains idempotency conflict',async()=>{const h=harness(),api=h.make();h.setMode('definite');await expect(api.create(input)).rejects.toThrow('名额');expect(api.pending()).toEqual([]);h.setMode('conflict');await expect(api.create(input)).rejects.toThrow('原键冲突');expect(api.pending()).toHaveLength(1)})
  it('does not interpret an old durableCreate flag as admission/seat capability',async()=>{const h=harness(),api=h.make();h.setMode('legacy');await expect(api.create(input)).rejects.toThrow('后台');await expect(api.seat(reservationId,seat)).rejects.toThrow('后台');expect(h.calls.some(c=>c.method==='POST')).toBe(false)})
  it('associates the full multiple-session set with signed original versions and preserves it across reload',async()=>{const h=harness();h.setMode('lost');const api=h.make();await expect(api.seat(reservationId,seat)).rejects.toThrow();await expect(api.seat(reservationId,{...seat,sessions:[seat.sessions[0]]})).rejects.toThrow('原入座');h.setMode('ok');const result=await h.make().recover('seat');expect(result.seating?.seatedGuestCount).toBe(7);expect(result.seating?.reservationGuestCount).toBe(6);expect(result.seating?.sessions).toHaveLength(2);const posts=h.calls.filter(c=>c.method==='POST');expect(posts[1]).toEqual(posts[0]);expect(h.values.size).toBe(0)})
  it.each([
    {...seat,sessions:[]},{...seat,sessions:[seat.sessions[0],seat.sessions[0]]},
    {...seat,sessions:[seat.sessions[0],{...seat.sessions[1],expectedTableId:tableA}]},
    {...seat,sessions:[{...seat.sessions[0],expectedGuestCount:0}]},
    {...seat,sessions:[{...seat.sessions[0],expectedLocationVersion:-1}]},
    {...seat,reason:'短'},
  ])('rejects invalid/duplicated actual table selections before sending: %j',body=>{expect(()=>validateReceptionSeat(body)).toThrow()})
  it('serializes double creation clicks so one original request is sent',async()=>{const h=harness(),api=h.make();const results=await Promise.allSettled([api.create(input),api.create({...input,guestCount:8})]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(h.calls.filter(c=>c.method==='POST')).toHaveLength(1)})
  it.each(['wrong-session','wrong-total','wrong-version'])('retains the exact seating request after %s in a success response',async fault=>{const h=harness(),api=h.make(undefined,undefined,async(path,init)=>{const raw=await h.request(path,init);if(init?.method==='POST'&&path.endsWith('/seat')){const value=raw as ReturnType<typeof seatReceipt>;if(fault==='wrong-session')value.data.seating.sessions[0].tableSessionId=id(99);else if(fault==='wrong-total')value.data.seating.seatedGuestCount=999;else value.data.reservation.aggregateVersion=99}return raw});await expect(api.seat(reservationId,seat)).rejects.toThrow('回执');expect(api.pending()).toMatchObject([{kind:'seat',canRecover:true}]);expect(JSON.parse([...h.values.values()][0]).body).toEqual(seat)})
  it('preserves legacy completion while requiring actual seating for new admissions',()=>{expect(canCompleteReservation({status:'arrived'})).toBe(true);expect(canCompleteReservation({status:'arrived',reservationSnapshot:{receptionProtocol:1}})).toBe(false);expect(canCompleteReservation({status:'seated',reservationSnapshot:{receptionProtocol:1}})).toBe(true);expect(canCompleteReservation({status:'confirmed'})).toBe(false)})
  it('accepts the documented PostgreSQL timestamp without changing the time',()=>{expect(receptionTime('2026-10-05 12:00:00+00')).toBe(receptionTime('2026-10-05T12:00:00Z'))})
  it('uses the actual StaffActionsApi transport with session binding and original key',async()=>{const h=harness(),calls:Array<{path:string;init?:RequestInit}>=[];const fetcher:typeof fetch=async(url,init)=>{const path=String(url);calls.push({path,init});const result=path==='/api/operations'?{data:{actor:{id:actor},tables:[],tasks:[]}}:await h.request(path,{method:init?.method as 'GET'|'POST',body:init?.body as string|undefined,key:new Headers(init?.headers).get('idempotency-key')??undefined});return new Response(JSON.stringify(result),{status:200})};let n=100;const api=new StaffActionsApi({fetch:fetcher,staffSessionId:'staff-session-original',commandStorage:h.storage,createIdempotencyKey:()=>id(++n)});await api.loadOperations();await api.reservationReception.create(input);const sent=calls.find(c=>c.init?.method==='POST')!;expect(new Headers(sent.init?.headers).get(STAFF_SESSION_BINDING_HEADER)).toBe('staff-session-original');expect(new Headers(sent.init?.headers).get('idempotency-key')).toMatch(/^reception-create-/);expect(sent.init?.credentials).toBe('include')})
})
