import assert from 'node:assert/strict'
import test from 'node:test'
import {readFile,mkdir} from 'node:fs/promises'
import {resolve,dirname} from 'node:path'
import {chromium} from 'playwright'
const root=resolve(import.meta.dirname,'..'),out=resolve(root,'artifacts/requirements-v9-20260916/detail-popup')
async function css(file){let s=await readFile(file,'utf8');for(const m of [...s.matchAll(/@import\s+"([^"]+)";/g)])s=s.replace(m[0],await css(resolve(dirname(file),m[1])));return s}
const reset='html,body{margin:0}page,view,scroll-view{display:block}page{width:100%;min-height:100vh}button{box-sizing:border-box;font-family:inherit}scroll-view{overflow-y:auto}image{display:block;object-fit:contain}text{overflow-wrap:anywhere}'
const sizes=[[320,568],[360,640],[390,844],[540,720],[720,540]]
const scaled=(s,w)=>s.replace(/(-?[\d.]+)rpx\b/g,(_,n)=>`${Number(n)*w/750}px`)
test('long bundle keeps full-height hero, reachable close and footer while only body scrolls',async()=>{
 const browser=await chromium.launch({headless:true});await mkdir(out,{recursive:true})
 try{const page=await browser.newPage(),style=await css(root+'/miniprogram/app.wxss')+await css(root+'/miniprogram/pages/order/index.wxss')
 for(const [width,height] of sizes){await page.setViewportSize({width,height});await page.setContent(`<style>${reset}${scaled(style,width)}</style><page><view class="page order-page"><view class="product-detail-mask sheet-mask"><view class="product-detail-sheet is-bundle"><view class="product-detail-header"><text>套餐详情</text><button class="product-detail-close">关闭</button></view><scroll-view class="product-detail-scroll"><view class="product-detail-hero"><image></image></view><view class="product-detail-content"><text class="product-detail-description">${'很长的套餐说明、选项与组成。'.repeat(100)}</text><view class="product-detail-component"><text>${'完整显示的组成名称'.repeat(10)}</text><text>×1</text></view></view></scroll-view><view class="product-detail-footer"><view><text>当前售价</text><text>¥228</text></view><button>确认选择并加入</button></view></view></view></view></page>`)
 const close=page.locator('.product-detail-close'),hero=page.locator('.product-detail-hero'),footer=page.locator('.product-detail-footer'),scroll=page.locator('scroll-view'),before=await close.boundingBox(),image=await hero.boundingBox();assert.ok(before.height>=44&&before.x>=0&&before.x+before.width<=width,'close touch area must be inside viewport');assert.ok(image.height>=width*470/750-1,'bundle image must retain normal hero size');assert.ok((await footer.boundingBox()).y+(await footer.boundingBox()).height<=height+1,'footer inside viewport')
 await scroll.evaluate(n=>n.scrollTop=n.scrollHeight);assert.ok(await scroll.evaluate(n=>n.scrollTop>0),'long content scrolls');assert.deepEqual(await close.boundingBox(),before,'header remains fixed within sheet');assert.equal((await hero.boundingBox()).height,image.height,'scrolling never shrinks image');assert.ok(await close.evaluate(n=>{const r=n.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===n}),'close must be topmost and clickable');assert.ok(await page.locator('.product-detail-component text').first().evaluate(n=>n.scrollWidth<=n.clientWidth+1),'long component names wrap');
 }
 }finally{await browser.close()}
})
test('poster keeps its image and independent circular close visible while long captions scroll',async()=>{
 const browser=await chromium.launch({headless:true});try{const page=await browser.newPage(),style=await css(root+'/miniprogram/components/launch-popup/index.wxss')
 for(const [width,height] of sizes){await page.setViewportSize({width,height});await page.setContent(`<style>${reset}${scaled(style,width)}</style><view class="launch-popup-mask"><view class="launch-popup-shell"><view class="launch-popup-swiper"><view class="launch-popup-poster"><view class="launch-popup-hero"><image class="launch-popup-image"></image><view class="launch-popup-heading"><text class="launch-popup-title">${'长标题'.repeat(26)}</text></view></view><scroll-view class="launch-popup-caption"><view class="launch-popup-product-line"><text class="launch-popup-product-name">${'长名称'.repeat(40)}</text><text class="launch-popup-product-price">¥228.50</text></view><text class="launch-popup-copy">${'推荐内容'.repeat(250)}</text></scroll-view></view></view><view class="launch-popup-pagination"><view class="launch-popup-dot is-current"></view><view class="launch-popup-dot"></view></view><button class="launch-popup-close"><view class="launch-popup-close-ring"></view><view class="launch-popup-close-line launch-popup-close-line--first"></view><view class="launch-popup-close-line launch-popup-close-line--second"></view></button></view></view>`)
 const close=page.locator('.launch-popup-close'),hero=page.locator('.launch-popup-hero'),caption=page.locator('scroll-view'),b=await close.boundingBox(),image=await hero.boundingBox();assert.ok(b.height>=44&&b.width>=44&&b.x>=0&&b.x+b.width<=width+1&&b.y>=0&&b.y+b.height<=height+1,'close touch target reachable');assert.ok(image.y>=0&&Math.abs(image.height-height*.45)<1,'hero retains its size');assert.ok(await page.locator('.launch-popup-close-ring').evaluate(n=>parseFloat(getComputedStyle(n).borderTopLeftRadius)>=22),'close is circular');
 await caption.evaluate(n=>n.scrollTop=n.scrollHeight);assert.ok(await caption.evaluate(n=>n.scrollTop>0),'long copy can scroll');assert.deepEqual(await close.boundingBox(),b,'close stays fixed');assert.deepEqual(await hero.boundingBox(),image,'caption scrolling cannot squash image');assert.ok(await close.evaluate(n=>{const r=n.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===n}),'close is topmost');assert.ok(await page.evaluate(()=>document.body.scrollWidth<=innerWidth+1),'no horizontal overflow')
 }
 }finally{await browser.close()}
})
