import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { chmodSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import test from 'node:test'

const read = (path) => readFile(new URL(path, import.meta.url), 'utf8')

test('formal release freezes a main-reachable tag and builds exactly one deployable image', async () => {
  const ci = await read('../.github/workflows/ci.yml')
  const release = await read('../.github/workflows/release.yml')
  const manifest = await read('./write-release-bundle-manifest.mjs')
  assert.match(ci, /Build production image once/)
  assert.equal((ci.match(/docker\/build-push-action@/g) ?? []).length, 1)
  assert.match(ci, /Reject an off-main release tag before image construction[\s\S]{0,240}merge-base --is-ancestor "\$\{GITHUB_SHA\}" origin\/main/)
  assert.match(release, /merge-base --is-ancestor "\$\{GITHUB_SHA\}" origin\/main/)
  assert.match(manifest, /sourceBranch !== 'main'/)
  assert.match(manifest, /Date\.parse\(frozenAt\)/)
})

test('normalized HTTP acceptance uses the full duration on pull requests and tags', async () => {
  const ci = await read('../.github/workflows/ci.yml')
  assert.match(ci, /Run real normalized HTTP workflows against an isolated database[\s\S]*?DURATION_SECONDS:\s*60/)
  assert.doesNotMatch(ci, /DURATION_SECONDS:\s*\$\{\{\s*github\.event_name\s*==\s*'pull_request'/)
})

test('mini-program stages stay controlled while staff, service and database release is independent', async () => {
  const packageJson = JSON.parse(await read('../package.json'))
  const ci = await read('../.github/workflows/ci.yml')
  const release = await read('../.github/workflows/release.yml')
  const stages = await read('../.github/workflows/miniprogram-release-stage.yml')
  assert.match(packageJson.scripts.check, /release:miniprogram:test/)
  assert.match(packageJson.scripts.check, /check:miniprogram/)
  assert.match(packageJson.scripts['test:commercial'], /MBOX_MINIPROGRAM_RELEASE_STAGE=release npm run release:miniprogram:verify/)
  assert.match(ci, /Verify candidate, upload and release gate semantics[\s\S]{0,120}release:miniprogram:test/)
  assert.doesNotMatch(ci, /MBOX_MINIPROGRAM_RELEASE_EVIDENCE_PATH/)
  assert.doesNotMatch(release, /MBOX_MINIPROGRAM_RELEASE_EVIDENCE_PATH/)
  assert.match(stages, /options: \[candidate, upload, release\]/)
  assert.match(stages, /gh release download/)
  assert.match(stages, /MBOX_MINIPROGRAM_RELEASE_STAGE: \$\{\{ inputs\.stage \}\}/)
  assert.match(release, /environment:[\s\S]{0,80}name: production/)
  assert.match(release, /normalized-staff-service-database/)
  assert.match(release, /wechat-miniprogram/)
  assert.doesNotMatch(release, /miniprogram-(?:candidate|upload|release)-evidence/)
  assert.doesNotMatch(release, /MBOX_MINIPROGRAM_RELEASE_(?:STAGE|EVIDENCE|TRUSTED)/)
  assert.match(stages, /environment:[\s\S]{0,80}miniprogram-\$\{\{ inputs\.stage \}\}/)
})

test('deployment manifest and both activation boundaries enforce the backend-only scope', async () => {
  const manifest = await read('./write-release-bundle-manifest.mjs')
  const deploy = await read('../deploy/aliyun/deploy-release.sh')
  const activate = await read('../deploy/aliyun/activate-release.sh')
  for (const source of [manifest, deploy, activate]) {
    assert.match(source, /normalized-staff-service-database/)
    assert.match(source, /normalized-web/)
    assert.match(source, /normalized-server/)
    assert.match(source, /normalized-database/)
    assert.match(source, /wechat-miniprogram/)
  }
})

test('configuration and migration checks precede every database write and application candidate', async () => {
  const activate = await read('../deploy/aliyun/activate-release.sh')
  const deploy = await read('../deploy/aliyun/deploy-release.sh')
  const config = activate.indexOf('verify-normalized-runtime-config.js')
  const migrationCompatibility = activate.indexOf('verify-normalized-migration-compatibility.js')
  const candidateDatabaseIdentity = activate.indexOf('candidate_database_identity=$(jq', migrationCompatibility)
  const databaseIdentityGate = activate.indexOf('assert_backup_targets_application_database', candidateDatabaseIdentity)
  const writerDrain = activate.indexOf('migration_compatible writer_drained')
  const backup = activate.indexOf('backup_path=$(DATABASE_SERVICE=', writerDrain)
  const migrate = activate.indexOf('migrate-normalized.js')
  const provision = activate.indexOf('provision-normalized-release.js')
  const candidate = activate.indexOf('docker run -d',provision)
  assert.ok(config > 0 && config < migrationCompatibility)
  assert.ok(migrationCompatibility < candidateDatabaseIdentity
    && candidateDatabaseIdentity < databaseIdentityGate && databaseIdentityGate < writerDrain
    && writerDrain < backup
    && backup < migrate && migrate < provision && provision < candidate)
  assert.match(activate.slice(config - 500, config + 500), /store_config[^\n]*\/run\/mbox-config\/store\.json/)
  assert.match(activate.slice(config, config + 200), /--store=\/run\/mbox-config\/store\.json/)
  assert.match(activate, /release_state_require "\$\{state_file\}" migration_compatible/)
  assert.match(activate, /release_state_require "\$\{state_file\}" backup_verified/)
  assert.match(activate, /pg_stat_activity[\s\S]*backend_type='client backend'/)
  assert.match(activate, /MBOX_RUNTIME_ROLE=contract_candidate/)
  assert.match(activate, /default_transaction_read_only=on/)
  assert.match(activate, /CONTRACT_CANDIDATE_READ_ONLY|writeEnabled == false/)
  assert.match(activate, /contract-database-and-previous-release-restored/)
  assert.match(activate, /forward-recovery-required/)
  const activeRetry = activate.indexOf('fetch_active_ready_response()')
  const previousReady = activate.indexOf('fetch_active_ready_response "${previous_release_sha}"')
  const publicRetry = activate.indexOf('fetch_public_ready_response()')
  const maintenanceReady = activate.indexOf('fetch_public_ready_response 503')
  assert.ok(activeRetry > 0 && activeRetry < previousReady && previousReady < migrationCompatibility)
  assert.ok(publicRetry > 0 && publicRetry < maintenanceReady)
  assert.ok(maintenanceReady > migrationCompatibility && maintenanceReady < writerDrain)
  assert.match(activate.slice(activeRetry, previousReady), /docker exec "\$\{active_container\}"[\s\S]*127\.0\.0\.1:8787\/api\/ready[\s\S]*runtimeRole == "normal"[\s\S]*writeEnabled == true[\s\S]*workers\.status == "healthy"/)
  assert.doesNotMatch(activate.slice(previousReady, migrationCompatibility), /fetch_public_ready_response 200/)
  assert.match(activate.slice(publicRetry, maintenanceReady), /connect-timeout 3[\s\S]*max-time 8[\s\S]*sleep 2/)
  const externalPublicReady = deploy.indexOf('pre_activation_ready=')
  const remoteActivation = deploy.indexOf("'${remote_release_dir}/activate-release.sh'", externalPublicReady)
  assert.ok(externalPublicReady > 0 && externalPublicReady < remoteActivation)
  assert.match(deploy.slice(externalPublicReady, remoteActivation), /connect-timeout 3[\s\S]*max-time 8[\s\S]*\.status == "ready"[\s\S]*deploymentTier == \$tier/)
  const directOriginCheck = deploy.indexOf('public_origin_addresses=')
  const remoteReleaseWrite = deploy.indexOf('install -d -m 0700')
  assert.match(deploy, /MBOX_SSH_HOST is required for a production deployment/)
  assert.match(deploy, /MBOX_PUBLIC_URL is required for a production deployment/)
  assert.ok(directOriginCheck > 0 && directOriginCheck < remoteReleaseWrite)
  assert.match(deploy.slice(directOriginCheck, remoteReleaseWrite), /getent ahostsv4[\s\S]*deployment target mismatch/)
  const rollback=await read('../deploy/aliyun/rollback-activated-release.sh')
  assert.match(rollback,/forward_only_after_contract_cutover[\s\S]*application-only rollback is forbidden/)
  assert.match(rollback,/release\.lock[\s\S]*flock -n 8/)
  assert.ok(rollback.indexOf('flock -n 8') < rollback.indexOf('docker network inspect'))
})

test('database maintenance credentials stay root-only and the frozen backup preserves authority', async () => {
  const activate = await read('../deploy/aliyun/activate-release.sh')
  const backup = await read('../deploy/aliyun/backup-postgres.sh')
  const migrationPreflight = await read('../server/verify-normalized-migration-compatibility.ts')
  const ci = await read('../.github/workflows/ci.yml')
  assert.match(activate, /database_maintenance_env=\$\{install_root\}\/secrets\/database-maintenance\.env/)
  assert.match(activate, /stat -c '%u:%a'[^\n]*database_maintenance_env/)
  assert.match(activate, /\)" = 0:600/)
  assert.match(activate, /APPLICATION_DATABASE_SERVICE/)
  assert.match(activate, /BACKUP_DATABASE_SERVICE/)
  assert.match(activate, /ADMIN_DATABASE_SERVICE/)
  assert.match(activate, /PGSERVICEFILE[\s\S]*PGPASSFILE/)
  assert.doesNotMatch(activate, /BACKUP_DATABASE_URL|ADMIN_DATABASE_URL/)
  assert.doesNotMatch(activate, /MBOX_RESTORE_ADMIN_DATABASE_URL=.*release_env/)
  assert.match(activate, /docker exec -i "\$\{active_container\}" node[\s\S]*process\.env\.DATABASE_URL/)
  assert.match(activate, /application_database_identity[\s\S]*runtime_database_identity/)
  assert.match(activate, /application_database_identity[\s\S]*candidate_database_identity/)
  assert.match(migrationPreflight, /databaseIdentity:[\s\S]*serverAddress[\s\S]*serverPort/)
  assert.match(activate, /current_database\(\).*inet_server_addr[\s\S]*backup_database_identity/)
  assert.match(activate, /contract-restore-source\.json[\s\S]*previous-release-manifest\.json[\s\S]*SHA256SUMS/)
  assert.match(backup, /NOT role\.rolsuper AND role\.rolbypassrls/)
  assert.match(backup, /pg_read_all_data/)
  assert.match(backup, /provider_role\.rolname='pg_rds_superuser'[\s\S]*pg_has_role\(role\.oid,provider_role\.oid,'member'\)/)
  assert.match(backup, /default_transaction_read_only=on/)
  assert.match(backup, /--dbname="\$\{database_connection\}"/)
  assert.doesNotMatch(backup, /--no-owner/)
  const restore = await read('../deploy/aliyun/restore-postgres.sh')
  assert.match(restore, /localeProvider[\s\S]*= c/)
  assert.match(restore, /role\.rolsuper OR \([\s\S]*role\.rolcreatedb[\s\S]*role\.rolcreaterole[\s\S]*role\.rolbypassrls/)
  assert.match(restore, /provider_role\.rolname='pg_rds_superuser'[\s\S]*pg_has_role\(role\.oid,provider_role\.oid,'member'\)/)
  assert.match(restore, /NOT role\.rolsuper AND role\.rolbypassrls[\s\S]*pg_read_all_data[\s\S]*provider_role\.rolname='pg_rds_superuser'/)
  assert.match(restore, /SELECT current_user[\s\S]*\.database\.owner/)
  assert.doesNotMatch(`${backup}\n${restore}`, /--dbname="\$\{(?:DATABASE_URL|ADMIN_DATABASE_URL)\}"/)
  assert.doesNotMatch(`${backup}\n${restore}`, /passwordless DATABASE_URL|test-only/)
  assert.match(ci, /Run every normalized PostgreSQL transaction and RLS test\n\s+env:\n\s+TEST_POSTGRES_CONTAINER: \$\{\{ job\.services\.postgres\.id \}\}\n\s+run: npm run test:normalized:postgres/)
  const legacyBackup = await read('./backup-postgres.sh')
  const legacyRestore = await read('./restore-postgres.sh')
  const runbook = await read('../docs/operations-runbook.md')
  assert.match(legacyBackup, /retired[\s\S]*exit 64/)
  assert.match(legacyRestore, /retired[\s\S]*exit 64/)
  assert.doesNotMatch(`${legacyBackup}\n${legacyRestore}\n${runbook}`, /pg_dump[^\n]*--no-owner/)
  assert.doesNotMatch(`${legacyBackup}\n${legacyRestore}\n${runbook}`, /pg_restore[^\n]*--clean/)
})

test('production worker adapters are inherited as immutable read-only release evidence', async () => {
  const activate = await read('../deploy/aliyun/activate-release.sh')
  const prepare = activate.indexOf('prepare_worker_adapter_mount()')
  const invoke = activate.indexOf('prepare_worker_adapter_mount', prepare + 1)
  const migrationPreflight = activate.indexOf('verify-normalized-migration-compatibility.js')
  const firstCandidate = activate.indexOf('docker run -d', migrationPreflight)
  assert.ok(prepare > 0 && invoke > prepare && invoke < migrationPreflight && migrationPreflight < firstCandidate)
  assert.match(activate, /Destination == "\/app\/worker-adapters" and \.RW == false/)
  assert.match(activate, /\/opt\/mbox\/releases\/\*\/worker-adapters/)
  assert.match(activate, /find "\$\{active_mount_source\}" -type l/)
  assert.match(activate, /stat -c '%U:%G'[\s\S]*root:root/)
  assert.match(activate, /chmod -R a\+rX,go-w/)
  assert.match(activate, /8#444[\s\S]*8#022/)
  assert.match(activate, /worker_adapter_mount_args\[@\]/)
  assert.match(activate, /workerAdapterTreeSha256[\s\S]*readOnly:true/)
  assert.doesNotMatch(activate, /\[ "\$\{health\}" = unhealthy \] && exit 1/)
  assert.match(activate, /invalid_maintenance_keys=\$\(awk[\s\S]*test -z "\$\{invalid_maintenance_keys\}"/)
})

test('database maintenance clients receive only password-free service references in argv', () => {
  const root = mkdtempSync(join(tmpdir(), 'mbox-libpq-argv-'))
  const bin = join(root, 'bin')
  const backups = join(root, 'backups')
  const log = join(root, 'argv.log')
  const service = join(root, 'pg_service.conf')
  const pass = join(root, 'pgpass')
  const secret = 'do-not-leak-password-7b81'
  execFileSync('mkdir', ['-p', bin, backups])
  writeFileSync(service, '[backup]\nhost=127.0.0.1\nport=5432\ndbname=mbox\nuser=backup\n')
  writeFileSync(pass, `127.0.0.1:5432:mbox:backup:${secret}\n`)
  chmodSync(service, 0o600)
  chmodSync(pass, 0o600)
  writeFileSync(join(bin, 'psql'), `#!/bin/sh\nprintf 'psql %s\\n' "$*" >> "$ARGV_LOG"\ncat >/dev/null\nprintf 'authorized\\n'\n`)
  writeFileSync(join(bin, 'pg_dump'), `#!/bin/sh\nprintf 'pg_dump %s\\n' "$*" >> "$ARGV_LOG"\nfor argument in "$@"; do\n  case "$argument" in --file=*) : > "\${argument#--file=}" ;; esac\ndone\n`)
  chmodSync(join(bin, 'psql'), 0o700)
  chmodSync(join(bin, 'pg_dump'), 0o700)
  execFileSync(resolve('deploy/aliyun/backup-postgres.sh'), [], { env: {
    ...process.env, PATH: `${bin}:${process.env.PATH}`, ARGV_LOG: log,
    DATABASE_SERVICE: 'backup', PGSERVICEFILE: service, PGPASSFILE: pass, BACKUP_DIR: backups,
  } })
  const argv = readFileSync(log, 'utf8')
  assert.match(argv, /--dbname=service=backup/)
  assert.doesNotMatch(argv, new RegExp(secret))
  assert.doesNotMatch(argv, /postgres(?:ql)?:\/\//)
  assert.throws(() => execFileSync(resolve('deploy/aliyun/backup-postgres.sh'), [], { env: {
    ...process.env, PATH: `${bin}:${process.env.PATH}`, ARGV_LOG: log,
    DATABASE_URL: `postgresql://backup:${secret}@127.0.0.1:5432/mbox`, BACKUP_DIR: backups,
  }, stdio: 'pipe' }))
})

test('diagnostic GitHub artifacts cannot hide tests while formal OSS failures block release', async () => {
  const ci = await read('../.github/workflows/ci.yml')
  const release = await read('../.github/workflows/release.yml')
  const deploy = await read('../deploy/aliyun/deploy-release.sh')
  assert.match(ci, /continue-on-error: true[\s\S]{0,180}actions\/upload-artifact/)
  assert.match(release, /Upload short-lived OSS transfer bundle[\s\S]{0,180}continue-on-error: true/)
  assert.doesNotMatch(deploy, /stage-release-evidence\.sh[^\n]*\|\| true/)
  assert.match(deploy, /stage-release-evidence\.sh/)
})

test('public verification includes root, table QR, reservation and staff deep links', async () => {
  const smoke = await read('./verify-release-smoke.mjs')
  for (const route of ["'/'", "'/guest?table=W01'", "'/reserve'", "'/staff/live'"]) assert.ok(smoke.includes(route))
})

test('candidate deep routes are verified without routing public traffic before cutover', async () => {
  const activate = await read('../deploy/aliyun/activate-release.sh')
  const privateVerification = activate.indexOf('http://${candidate_ip}:8787')
  const cutover = activate.indexOf('candidate_deep_verified cutover_started')
  assert.ok(privateVerification > 0 && privateVerification < cutover)
  assert.doesNotMatch(activate.slice(0, cutover), /Caddyfile\.candidate|caddy reload --config \/tmp/)
})

test('cutover routes by verified candidate IP before the previous release is stopped', async () => {
  const activate = await read('../deploy/aliyun/activate-release.sh')
  const cutover = activate.indexOf('candidate_deep_verified cutover_started')
  const routedCutover = activate.indexOf('/tmp/Caddyfile.cutover-candidate --adapter caddyfile', cutover)
  const publicVerification = activate.indexOf('verify_release_at "${public_url}" 15', routedCutover)
  const stopPrevious = activate.indexOf('docker stop -t 30 "${active_container}"', publicVerification)
  assert.ok(cutover > 0 && cutover < routedCutover)
  assert.ok(routedCutover < publicVerification && publicVerification < stopPrevious)
  assert.match(activate.slice(0, cutover), /sed "s\/mbox-app:8787\/\$\{candidate_ip\}:8787\/g"/)

  const verifier = await read('../deploy/aliyun/verify-public-app.sh')
  assert.match(verifier, /target_route_failures[\s\S]*-ge "\$\{attempts\}"[\s\S]*sleep 2/)
  assert.doesNotMatch(verifier, /target_route_failures[\s\S]*-ge 2/)
})
