package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import org.junit.Test
import org.junit.Assert.*
class ActivityOperationsTest{
 private val actor=StaffIdentity("s","e","manager","主管","2099-01-01T00:00:00Z","2099-01-01T00:00:00Z",emptyList(),setOf("community.activity.manage","community.activity.publish","refund.request"),emptySet())
 private fun board()=CouponCalendarsBoard(JSONObject().put("employeeId","e").put("protocol",1).put("durableCommands",true).put("rows",JSONArray()).put("next",JSONObject.NULL))
 private fun draft():JSONObject{val f=activityEditor(null).put("title","会员夜晚").put("summary","已核对的活动内容").put("startsAt","2037-01-01 18:00").put("endsAt","2037-01-01 23:00").put("assemblyLocation","门店服务台").put("reason","核对内容与套餐承诺").put("paymentRuleText","无需预付").put("safetyPolicyVersion","safety-v1").put("safetyAcknowledgementText","遵守现场指引").put("refundPolicyVersion","refund-v1").put("refundPolicySummary","开始前可取消").put("activityDetails","包含现场时间、人数与安全规则的详情").put("contactInstructions","联系现场服务台").put("safetyRequirements","注意现场指引");val p=activityPackageEditor(null).put("name","体验套餐").put("paymentRuleText","无需付款").put("components",JSONArray(listOf(JSONObject().put("inventoryItemId","00000000-0000-4000-8000-000000000001").put("quantity","1.500").put("perParticipant",true))));return activityDraftFromEditor(f.put("packages",JSONArray(listOf(p))))}
 private fun receipt(c:LiveCommand,row:JSONObject)=JSONObject().put("meta",JSONObject().put("protocol",1).put("replayed",true)).put("data",JSONObject().put("employeeId","e").put("requestKey",c.steps[0].key).put("action",c.steps[0].activityOperationsProof!!.getString("action")).put("row",row)).toString()
 @Test fun fullPromisesAndInventoryQuantitySurviveReceipt(){val b=draft();val c=activityOperationsCommand(actor,board(),"create",null,null,b);assertEquals(c,LiveCommand.parse(c.json()));val row=JSONObject(b.toString()).put("publicId","activity-result-01").put("status","draft").put("nativeVersion","a".repeat(64)).put("startsAt","2037-01-01 18:00:00+08");row.getJSONArray("packages").getJSONObject(0).getJSONArray("components").getJSONObject(0).put("quantity","1.500000");validateActivityOperationsReply(receipt(c,row),c.steps[0]);row.put("refundPolicySummary","不同的退款承诺");assertThrows(IllegalArgumentException::class.java){validateActivityOperationsReply(receipt(c,row),c.steps[0])}}
 @Test fun rejectsContradictoryMoneyAndSelfPublication(){val b=draft().put("feeAmountMinor",100).put("depositAmountMinor",101);assertThrows(IllegalArgumentException::class.java){activityOperationsCommand(actor,board(),"create",null,null,b)};val a=draft().put("publicId","activity-result-01").put("status","draft").put("nativeVersion","a".repeat(64)).put("createdByEmployeeId","e");assertThrows(IllegalArgumentException::class.java){activityOperationsCommand(actor,board(),"publish",a,null,JSONObject().put("reason","发布不能由本人"))}}
 @Test fun refundMustRetainActualPaymentAmountAndRequester(){val a=draft().put("publicId","activity-result-01").put("nativeVersion","a".repeat(64));val reg=JSONObject().put("publicId","registration-one").put("customerLabel","测试顾客").put("partySize",2).put("paymentStatus","paid").put("authoritativePaymentStatus","succeeded").put("refundableAmountMinor",5000).put("paymentId","payment-original").put("currency","CNY").put("nativeVersion","b".repeat(64));assertThrows(IllegalArgumentException::class.java){activityOperationsCommand(actor,board(),"cancel-registration",a,reg,JSONObject().put("reason","已付款不能直接取消"))};val c=activityOperationsCommand(actor,board(),"refund-request",a,reg,JSONObject().put("reason","顾客申请原款退款"));val row=JSONObject().put("paymentId","payment-original").put("amountMinor",5000).put("status","requested").put("requestedByEmployeeId","e").put("reason","顾客申请原款退款").put("currency","CNY").put("nativeVersion","c".repeat(64));validateActivityOperationsReply(receipt(c,row),c.steps[0]);row.put("amountMinor",4900);assertThrows(IllegalArgumentException::class.java){validateActivityOperationsReply(receipt(c,row),c.steps[0])}}
}
