package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import org.junit.Assert.*
import org.junit.Test
import java.util.UUID
class AnnualPoliciesTest{
 private val actor=StaffIdentity("s","e","m","主管","2099-01-01T00:00:00Z","2099-01-01T00:00:00Z",emptyList(),setOf("loyalty.annual-benefit.manage","loyalty.annual-benefit.approve","loyalty.annual-benefit.publish","loyalty.annual-benefit.occurrence.confirm"),emptySet())
 private fun rule()=newAnnualRule().put("ruleCode","BIRTHDAY").put("title","生日服务礼遇").put("benefitDefinitionId",UUID.randomUUID().toString())
 private fun board(rows:List<JSONObject> = emptyList())=CouponCalendarsBoard(JSONObject().put("employeeId","e").put("protocol",1).put("durableCommands",true).put("rows",JSONArray(rows)).put("code","ANNUAL").put("latest",2).put("next",JSONObject.NULL))
 private fun draft(rules:List<JSONObject>)=JSONObject().put("policyCode","ANNUAL").put("timezone","Asia/Shanghai").put("reason","核对全部原规则").put("rules",JSONArray(rules))
 @Test fun preventsInvalidCalendarAndSnackShapes(){val bad=rule().put("ruleKind","daily_snack").put("feb29Policy",JSONObject.NULL).put("redemptionHoldMinutes",15);assertThrows(IllegalArgumentException::class.java){normalizeAnnualRule(bad)};assertThrows(IllegalArgumentException::class.java){normalizeAnnualRule(rule().put("feb29Policy",JSONObject.NULL))};assertThrows(IllegalArgumentException::class.java){annualPolicyCommand(actor,board(),"draft",null,draft(listOf(rule(),rule())))}}
 @Test fun birthdayPriorityAndDuplicatePrioritySeatingCannotPublishAsDraft(){val birthday=rule();val festival=rule().put("ruleCode","FESTIVAL").put("ruleKind","festival").put("feb29Policy",JSONObject.NULL);assertThrows(IllegalArgumentException::class.java){annualPolicyCommand(actor,board(),"draft",null,draft(listOf(birthday,festival)))};festival.put("priority",20);val c=annualPolicyCommand(actor,board(),"draft",null,draft(listOf(birthday,festival)));assertEquals(2,JSONObject(c.steps[0].body).getJSONArray("rules").length())}
 @Test fun receiptMustMatchOriginalCompleteRuleAndActor(){val c=annualPolicyCommand(actor,board(),"draft",null,draft(listOf(rule())));assertEquals(c,LiveCommand.parse(c.json()));val b=JSONObject(c.steps[0].body);val row=JSONObject(b.toString()).put("id",UUID.randomUUID().toString()).put("version",3).put("status","draft").put("draftedByEmployeeId","e").put("nativeVersion","a".repeat(64));val r=JSONObject().put("meta",JSONObject().put("protocol",1).put("replayed",true)).put("data",JSONObject().put("employeeId","e").put("requestKey",c.steps[0].key).put("action","draft").put("accepted",b).put("row",row));validateAnnualPolicyReply(r.toString(),c.steps[0]);row.getJSONArray("rules").getJSONObject(0).put("windowAfterDays",8);assertThrows(IllegalArgumentException::class.java){validateAnnualPolicyReply(r.toString(),c.steps[0])}}
 @Test fun independentReviewAndOriginalFestivalVersionAreRequired(){val r=JSONObject().put("id",UUID.randomUUID().toString()).put("nativeVersion","b".repeat(64)).put("status","draft").put("draftedByEmployeeId","e").put("rules",JSONArray());assertThrows(IllegalArgumentException::class.java){annualPolicyCommand(actor,board(listOf(r)),"approve",r,JSONObject().put("reason","自己审批不允许"))};val f=rule().put("id",UUID.randomUUID().toString()).put("ruleKind","festival").put("feb29Policy",JSONObject.NULL);r.put("policyCode","ANNUAL").put("version",1).put("rules",JSONArray(listOf(f)));val b=JSONObject().put("reason","登记节日安排").put("ruleId",f.getString("id")).put("cycleYear",2030).put("startsOn","2030-02-01").put("endsOn","2031-02-07").put("confirmationReference","核对确认依据");assertThrows(IllegalArgumentException::class.java){annualPolicyCommand(actor,board(listOf(r)),"occurrence",r,b)}}
}
