package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import org.junit.Test
import org.junit.Assert.*
class ContactGovernanceTest{
 private val actor=StaffIdentity("s","e","manager","主管","2099-01-01T00:00:00Z","2099-01-01T00:00:00Z",emptyList(),setOf("privacy.contact.retention.draft","privacy.contact.retention.approve","privacy.contact.retention.publish","privacy.contact.legal_hold"),emptySet())
 private fun board(rows:List<JSONObject> = emptyList())=CouponCalendarsBoard(JSONObject().put("employeeId","e").put("protocol",1).put("durableCommands",true).put("rows",JSONArray(rows)).put("next",JSONObject.NULL))
 private fun receipt(c:LiveCommand,row:JSONObject)=JSONObject().put("meta",JSONObject().put("protocol",1).put("replayed",true)).put("data",JSONObject().put("employeeId","e").put("requestKey",c.steps[0].key).put("accepted",JSONObject(c.steps[0].body)).put("action",c.steps[0].contactGovernanceProof!!.getString("action")).put("row",row)).toString()
 @Test fun retentionDaysAndLegalBasisMustMatchOriginalDraft(){val b=JSONObject().put("resourceKind","activity_registration_contact").put("retentionDaysAfterPurposeEnd",45).put("legalBasisReference","已核准的保留依据").put("reason","建立完整策略");val c=contactGovernanceCommand(actor,board(),"draft",null,b);assertEquals(c,LiveCommand.parse(c.json()));val r=JSONObject(b.toString()).put("draftReason",b.getString("reason")).put("draftedByEmployeeId","e").put("status","draft").put("nativeVersion","a".repeat(64));validateContactGovernanceReply(receipt(c,r),c.steps[0]);r.put("retentionDaysAfterPurposeEnd",0);assertThrows(IllegalArgumentException::class.java){validateContactGovernanceReply(receipt(c,r),c.steps[0])}}
 @Test fun separationAndStaleVersionAreChecked(){val row=JSONObject().put("publicId","PCRtest").put("nativeVersion","a".repeat(64)).put("status","draft").put("draftedByEmployeeId","e");assertThrows(IllegalArgumentException::class.java){contactGovernanceCommand(actor,board(listOf(row)),"approve",row,JSONObject().put("reason","不允许自行审批"))};row.put("status","approved").put("draftedByEmployeeId","other").put("approvedByEmployeeId","e");assertThrows(IllegalArgumentException::class.java){contactGovernanceCommand(actor,board(listOf(row)),"publish",row,JSONObject().put("reason","须第三人发布").put("effectiveFrom","2037-01-01T00:00:00Z"))};assertThrows(IllegalArgumentException::class.java){contactGovernanceCommand(actor,board(),"publish",row,JSONObject().put("reason","不允许旧记录"))}}
 @Test fun holdBindsTheExactContactVersionAndExpiry(){val row=JSONObject().put("publicId","CVCtest").put("nativeVersion","a".repeat(64)).put("resourceKind","verified_membership_phone").put("businessLabel","已验证会员手机号").put("maskedContact","138****1234");val b=JSONObject().put("resourceKind","verified_membership_phone").put("legalBasisReference","争议处理证据").put("reason","保留原版本").put("holdUntil","2037-01-01T00:00:00Z");val c=contactGovernanceCommand(actor,board(listOf(row)),"hold",row,b);val r=JSONObject(b.toString()).put("publicId","PCHtest").put("resourcePublicId","CVCtest").put("nativeVersion","a".repeat(64)).put("status","active").put("createdByEmployeeId","e").put("holdUntil","2037-01-01 08:00:00+08");validateContactGovernanceReply(receipt(c,r),c.steps[0]);r.put("resourcePublicId","different");assertThrows(IllegalArgumentException::class.java){validateContactGovernanceReply(receipt(c,r),c.steps[0])}}
}
