package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import org.junit.Test
import org.junit.Assert.*
import java.util.UUID
class CouponCalendarsTest{
 private val actor=StaffIdentity("s","e","manager","主管","2099-01-01T00:00:00Z","2099-01-01T00:00:00Z",emptyList(),setOf("loyalty.configuration.edit","loyalty.configuration.approve","loyalty.policy.publish"),emptySet())
 private fun form()=calendarEditor(null).put("code","CAL_TEST").put("dateFrom","2037-01-01").put("dateThrough","2037-03-31").put("validFrom","2037-01-01 00:00").put("validUntil","2037-04-01 06:00").put("dateBasis","business").put("cutoff","06:00").put("windows",JSONArray().put(JSONObject().put("from","21:00").put("to","02:00"))).put("relativeDays","3").put("relativeBasis","business_end").put("reason","实际规则已核对")
 @Test fun midnightAndUnknownLimitsKeepTheirMeaning(){val f=form();val b=calendarSaveBody(f);val r=b.getJSONObject("rule");assertEquals(360,r.getInt("businessDayStartMinute"));assertEquals(120,r.getJSONArray("windows").getJSONObject(0).getInt("endMinute"));assertEquals("2037-03-31T22:00:00Z",r.getString("validUntil"));assertTrue(b.getJSONObject("limits").isNull("perCustomerDay"));assertEquals(1440,calendarMinute("24:00",true));assertThrows(IllegalArgumentException::class.java){calendarMinute("24:00")};f.put("dateBasis","natural");assertThrows(IllegalArgumentException::class.java){calendarRuleFromEditor(f)};f.put("dateBasis","business").put("perCustomerDay","0");assertThrows(IllegalArgumentException::class.java){calendarSaveBody(f)}}
 @Test fun receiptValidatesFullOriginalRuleAndDoesNotAcceptChangedRelativeExpiry(){val body=calendarSaveBody(form());val b=CouponCalendarsBoard(JSONObject().put("employeeId","e").put("protocol",1).put("durableCommands",true).put("rows",JSONArray()));val c=couponCalendarCommand(actor,b,"save",body,"保存草稿");val row=JSONObject().put("id",UUID.randomUUID().toString()).put("code","CAL_TEST").put("version",1).put("status","draft").put("createdByEmployeeId","e").put("rule",JSONObject(body.getJSONObject("rule").toString())).put("limits",body.getJSONObject("limits"));row.getJSONObject("rule").put("validUntil","2037-03-31T22:00:00.000Z");val r=JSONObject().put("meta",JSONObject().put("protocol",1).put("replayed",true)).put("data",JSONObject().put("employeeId","e").put("requestKey",c.steps[0].key).put("action","save").put("row",row));assertEquals(c,LiveCommand.parse(c.json()));validateCouponCalendarReply(r.toString(),c.steps[0]);row.getJSONObject("rule").getJSONObject("relativeValidity").put("days",4);assertThrows(IllegalArgumentException::class.java){validateCouponCalendarReply(r.toString(),c.steps[0])}}
 @Test fun editorAndApproverCannotPublishTheirOwnPolicy(){val row=JSONObject().put("id",UUID.randomUUID().toString()).put("createdByEmployeeId","other").put("status","approved").put("decisions",JSONArray().put(JSONObject().put("action","approve").put("employeeId","e")));val b=CouponCalendarsBoard(JSONObject().put("employeeId","e").put("protocol",1).put("durableCommands",true).put("rows",JSONArray().put(row)));val body=JSONObject().put("versionId",row.getString("id")).put("expectedStatus","approved").put("action","publish").put("reason","核对准备发布");assertThrows(IllegalArgumentException::class.java){couponCalendarCommand(actor,b,"decision",body,"发布")};row.put("createdByEmployeeId","e").put("decisions",JSONArray());assertThrows(IllegalArgumentException::class.java){couponCalendarCommand(actor,b,"decision",body,"发布")}}
}
