package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import org.junit.Assert.*
import org.junit.Test
import java.util.UUID
class ExperiencePlansTest{
 private fun fixture():Triple<StaffIdentity,ExperiencePlansBoard,JSONObject>{val actor=StaffIdentity("s","e","manager","主管","2099-01-01T00:00:00Z","2099-01-01T00:00:00Z",emptyList(),setOf("customer.experience.manage","service.manage","service.execute"),emptySet());val row=JSONObject().put("id",UUID.randomUUID().toString()).put("table_session_id",UUID.randomUUID().toString()).put("plan_state","active").put("session_status","open").put("table_code","A01").put("plan_version",2).put("expectedVersion","a".repeat(64)).put("tasks",JSONArray()).put("cues",JSONArray());val board=ExperiencePlansBoard(JSONObject().put("employeeId","e").put("protocol",1).put("durableCommands",true).put("canManage",true).put("rows",JSONArray().put(row)));return Triple(actor,board,row)}
 @Test fun stopReceiptIsBoundToOriginalPlanAndPausedTasksCannotBeHidden(){val(a,b,r)=fixture();r.getJSONArray("tasks").put(JSONObject().put("status","in_progress"));assertThrows(IllegalArgumentException::class.java){experiencePlanCommand(a,b,r,"pause","客人暂时离席")};val c=experiencePlanCommand(a,b,r,"cancel","客人明确要求停止");assertEquals(c,LiveCommand.parse(c.json()));val p=c.steps[0].experiencePlanProof!!;val d=JSONObject(p.toString()).put("requestKey",c.steps[0].key);val receipt=JSONObject().put("data",d).put("meta",JSONObject().put("protocol",1).put("replayed",true));validateExperiencePlanReply(receipt.toString(),c.steps[0]);d.put("tableSessionId",UUID.randomUUID().toString());assertThrows(IllegalArgumentException::class.java){validateExperiencePlanReply(receipt.toString(),c.steps[0])}}
 @Test fun elapsedTimingRejectsAlreadyDispatchedNodesAndFreezesOriginalVersion(){val(a,b,r)=fixture();val cue=JSONObject().put("id",UUID.randomUUID().toString()).put("trigger_kind","elapsed").put("status","pending").put("service_task_id",JSONObject.NULL);r.getJSONArray("cues").put(cue);val c=experiencePlanCommand(a,b,r,"reschedule","客人要求稍后进行",cue,120);r.put("expectedVersion","b".repeat(64));assertEquals("a".repeat(64),JSONObject(c.steps[0].body).getString("expectedVersion"));cue.put("status","dispatched").put("service_task_id",UUID.randomUUID().toString());assertThrows(IllegalArgumentException::class.java){experiencePlanCommand(a,b,r,"reschedule","客人要求稍后进行",cue,180)}}
}
