package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import org.junit.Test
import org.junit.Assert.*
class HomeContentTest{
 private val actor=StaffIdentity("s","e","manager","主管","2099-01-01T00:00:00Z","2099-01-01T00:00:00Z",emptyList(),setOf("community.activity.manage","community.activity.publish"),emptySet())
 private fun draft()=JSONObject().put("code","HOME_TEST").put("type","show").put("title","演出时间").put("summary","已核对完整活动资料").put("imageUrl",JSONObject.NULL).put("ctaLabel","查看演出").put("targetPath","/pages/performances/index").put("priority",12).put("displayMode","pinned").put("visibility","segment").put("audienceMemberLevels",JSONArray(listOf("gold","member"))).put("audienceLifecycleStages",JSONArray(listOf("active"))).put("validFrom","2037-01-01T10:00:00Z").put("validUntil","2037-02-01T19:00:00Z").put("reason","已核对排期与客群")
 private fun board(rows:List<JSONObject> = emptyList())=CouponCalendarsBoard(JSONObject().put("employeeId","e").put("protocol",1).put("durableCommands",true).put("rows",JSONArray(rows)).put("next",JSONObject.NULL))
 private fun receipt(c:LiveCommand,row:JSONObject)=JSONObject().put("meta",JSONObject().put("protocol",1).put("replayed",true)).put("data",JSONObject().put("employeeId","e").put("requestKey",c.steps[0].key).put("action",c.steps[0].homeContentProof!!.getString("action")).put("row",row)).toString()
 @Test fun preservesCompleteCustomerSelectionAndPostgresTimestamps(){val c=homeContentCommand(actor,board(),"create",null,draft());assertEquals(c,LiveCommand.parse(c.json()));val row=draft().put("status","draft").put("nativeVersion","a".repeat(64)).put("publishedByEmployeeId",JSONObject.NULL).put("validFrom","2037-01-01 18:00:00+08").put("validUntil","2037-02-02 03:00:00+08");validateHomeContentReply(receipt(c,row),c.steps[0]);row.put("audienceMemberLevels",JSONArray(listOf("gold")));assertThrows(IllegalArgumentException::class.java){validateHomeContentReply(receipt(c,row),c.steps[0])}}
 @Test fun stateAndVersionCannotBeChangedByOldEditor(){val row=draft().put("status","published").put("nativeVersion","a".repeat(64)).put("publishedByEmployeeId","e");assertThrows(IllegalArgumentException::class.java){homeContentCommand(actor,board(listOf(row)),"update",row,draft())};val c=homeContentCommand(actor,board(listOf(row)),"pause",row,JSONObject().put("code","HOME_TEST").put("reason","编辑前暂停展示"));validateHomeContentReply(receipt(c,JSONObject(row.toString()).put("status","paused").put("nativeVersion","b".repeat(64))),c.steps[0]);assertThrows(IllegalArgumentException::class.java){homeContentCommand(actor,board(listOf(JSONObject(row.toString()).put("nativeVersion","c".repeat(64)))),"pause",row,draft())}}
 @Test fun rejectsEmptySegmentsWrongScheduleAndExternalImage(){for(f in listOf(draft().put("audienceMemberLevels",JSONArray()).put("audienceLifecycleStages",JSONArray()),draft().put("visibility","public"),draft().put("validUntil","2036-01-01T00:00:00Z"),draft().put("imageUrl","https://example.com/logo.png"))){assertThrows(IllegalArgumentException::class.java){homeContentCommand(actor,board(),"create",null,f)}}}
}
