package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import org.junit.Test
import org.junit.Assert.*
class MarketingTest{
 private fun actor(id:String="e")=StaffIdentity("s",id,"manager","主管","2099-01-01T00:00:00Z","2099-01-01T00:00:00Z",emptyList(),setOf("marketing.notice.edit","marketing.notice.approve","marketing.notice.publish","marketing.send","marketing.refusal.record"),emptySet())
 private fun rule()=JSONObject().put("operatorName","经营主体").put("operatorContact","门店服务台").put("summary","门店活动相关通知").put("withdrawalInstructions","顾客可以随时停止全部营销").put("channels",JSONArray(listOf("sms"))).put("purposes",JSONArray(listOf("own_activities"))).put("dataCategories",JSONArray(listOf("本人联系方式"))).put("validFrom","2037-01-01T00:00:00Z").put("validUntil","2037-02-01T00:00:00Z").put("consentDays",7).put("contactStartMinute",600).put("contactEndMinute",1200).put("weekdays",JSONArray(listOf(1,2,3))).put("maximumPerDay",1).put("maximumPerMonth",4).put("sharingMode","no_partner_list")
 private fun board(rows:List<JSONObject> = emptyList())=CouponCalendarsBoard(JSONObject().put("employeeId","e").put("protocol",1).put("durableCommands",true).put("rows",JSONArray(rows)).put("next",JSONObject.NULL).put("code","NOTICE").put("latestVersion",4))
 private fun receipt(c:LiveCommand,row:JSONObject)=JSONObject().put("meta",JSONObject().put("protocol",1).put("replayed",true)).put("data",JSONObject().put("employeeId","e").put("requestKey",c.steps[0].key).put("accepted",JSONObject(c.steps[0].body)).put("action",c.steps[0].marketingProof!!.getString("action")).put("row",row)).toString()
 @Test fun completeNoticeAndOriginalReplyAreVerified(){val b=JSONObject().put("code","NOTICE").put("rule",rule()).put("reason","完整范围核对");val c=marketingCommand(actor(),board(),"save",null,b);assertEquals(c,LiveCommand.parse(c.json()));val r=JSONObject().put("code","NOTICE").put("version",5).put("status","draft").put("createdByEmployeeId","e").put("reason","完整范围核对").put("nativeVersion","a".repeat(64)).put("rule",rule().put("validFrom","2037-01-01 08:00:00+08"));validateMarketingReply(receipt(c,r),c.steps[0]);r.getJSONObject("rule").put("maximumPerMonth",100);assertThrows(IllegalArgumentException::class.java){validateMarketingReply(receipt(c,r),c.steps[0])}}
 @Test fun invalidContactLimitsAndSelfApprovalAreBlocked(){for(r in listOf(rule().put("contactStartMinute",1300),rule().put("maximumPerDay",8),rule().put("channels",JSONArray()),rule().put("sharingMode","partner_list")))assertThrows(IllegalArgumentException::class.java){marketingNoticeRule(r)};val r=JSONObject().put("id","record").put("nativeVersion","a".repeat(64)).put("status","draft").put("createdByEmployeeId","e");assertThrows(IllegalArgumentException::class.java){marketingCommand(actor(),board(listOf(r)),"decision",r,JSONObject().put("decision","approve").put("reason","不允许自行审核"))}}
 @Test fun customerRefusalAndChannelHandoffRemainDistinct(){val id="00000000-0000-4000-8000-000000000001";val c=marketingCommand(actor(),board(),"refusal",null,JSONObject().put("customerId",id).put("reason","本人明确拒绝"));validateMarketingReply(receipt(c,JSONObject().put("customerId",id).put("stopped",true)),c.steps[0]);assertThrows(IllegalArgumentException::class.java){validateMarketingReply(receipt(c,JSONObject().put("customerId",id).put("stopped",false)),c.steps[0])};val r=JSONObject().put("id",id).put("nativeVersion","a".repeat(64)).put("status","dispatching");assertThrows(IllegalArgumentException::class.java){marketingCommand(actor(),board(listOf(r)),"cancel",r,JSONObject().put("reason","不可撤回已交渠道任务"))}}
}
