package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import org.junit.Test
import org.junit.Assert.*
import java.util.UUID
class MemberGiftsTest{
 private val actor=StaffIdentity("s","e","manager","主管","2099-01-01T00:00:00Z","2099-01-01T00:00:00Z",emptyList(),setOf("loyalty.configuration.edit","loyalty.configuration.approve","loyalty.policy.publish"),emptySet())
 private fun form()=giftEditor(null).put("code","GIFT_NATIVE").put("name","会员赠礼").put("couponCalendarVersionId",UUID.randomUUID().toString()).put("productIds",JSONArray().put(UUID.randomUUID().toString())).put("availableFrom","2037-01-01 00:00").put("availableUntil","2037-02-01 06:00").put("maximumQuantity","20").put("maximumDailyQuantity","10").put("maximumCostMinor","200.00").put("maximumDailyCostMinor","100").put("maximumUnitCostMinor","10.01").put("reason","核对预算及商品承诺")
 private fun board(rows:JSONArray=JSONArray())=MemberGiftsBoard(JSONObject().put("employeeId","e").put("protocol",1).put("durableCommands",true).put("rows",rows))
 @Test fun budgetsUseExactMinorAmountsAndNeverInterpretZeroAsUnlimited(){val f=form();val r=giftSaveBody(f).getJSONObject("rule");assertEquals(1001L,r.getLong("maximumUnitCostMinor"));assertTrue(r.isNull("fixedPriceMinor"));assertEquals("2037-01-31T22:00:00Z",r.getString("availableUntil"));f.put("maximumDailyCostMinor","0");assertEquals(0L,giftSaveBody(f).getJSONObject("rule").getLong("maximumDailyCostMinor"));f.put("maximumQuantity","1");assertThrows(IllegalArgumentException::class.java){giftSaveBody(f)};assertThrows(IllegalArgumentException::class.java){giftMoney("1.001")};f.put("maximumQuantity","20").put("dessertProductId",UUID.randomUUID().toString()).put("quantityPerCustomer","2");assertThrows(IllegalArgumentException::class.java){giftSaveBody(f)}}
 @Test fun savedReceiptMustContainExactProductPoolPriceAndBudget(){val body=giftSaveBody(form());val c=memberGiftCommand(actor,board(),"save",body,"保存赠礼草稿");assertEquals(c,LiveCommand.parse(c.json()));val row=JSONObject().put("id",UUID.randomUUID().toString()).put("code",body.getString("code")).put("name",body.getString("name")).put("version",1).put("status","draft").put("created_by_employee_id","e").put("rule",JSONObject(body.getJSONObject("rule").toString()));row.getJSONObject("rule").put("availableFrom","2036-12-31T16:00:00.000Z");val reply=JSONObject().put("meta",JSONObject().put("protocol",1).put("replayed",true)).put("data",JSONObject().put("employeeId","e").put("requestKey",c.steps[0].key).put("action","save").put("accepted",body).put("row",row));validateMemberGiftReply(reply.toString(),c.steps[0]);row.getJSONObject("rule").put("maximumUnitCostMinor",1002);assertThrows(IllegalArgumentException::class.java){validateMemberGiftReply(reply.toString(),c.steps[0])}}
 @Test fun queueReceiptCannotImplyIssuanceOrLoseRecipients(){val id=UUID.randomUUID().toString();val row=JSONObject().put("id",id).put("nativeVersion","snapshot");val b=JSONObject().put("versionId",id).put("expectedVersion","snapshot").put("customerIds",JSONArray().put(UUID.randomUUID().toString()).put(UUID.randomUUID().toString())).put("cycleKey","october").put("reason","两位会员已确认");val c=memberGiftCommand(actor,board(JSONArray().put(row)),"target",b,"安排发放");val jobs=JSONArray().put(JSONObject().put("jobId",UUID.randomUUID().toString()).put("status","pending").put("replayed",false)).put(JSONObject().put("jobId",UUID.randomUUID().toString()).put("status","issued").put("replayed",true));val reply=JSONObject().put("meta",JSONObject().put("protocol",1).put("replayed",false)).put("data",JSONObject().put("employeeId","e").put("action","target").put("requestKey",c.steps[0].key).put("accepted",b).put("row",JSONObject().put("items",jobs)));validateMemberGiftReply(reply.toString(),c.steps[0]);jobs.remove(1);assertThrows(IllegalArgumentException::class.java){validateMemberGiftReply(reply.toString(),c.steps[0])}}
 @Test fun authorAndReviewerCannotPublishOwnActivity(){val id=UUID.randomUUID().toString();val row=JSONObject().put("id",id).put("nativeVersion","snapshot").put("created_by_employee_id","e");val b=JSONObject().put("versionId",id).put("expectedVersion","snapshot").put("action","approve").put("reason","审核规则预算");assertThrows(IllegalArgumentException::class.java){memberGiftCommand(actor,board(JSONArray().put(row)),"decision",b,"审批")};row.put("created_by_employee_id","other").put("approved_by_employee_id","e");b.put("action","publish");assertThrows(IllegalArgumentException::class.java){memberGiftCommand(actor,board(JSONArray().put(row)),"decision",b,"发布")}}
 @Test fun refundReceiptBindsOriginalRefundEvidenceAndReplacementCoupon(){val refund=UUID.randomUUID().toString();val reservation=UUID.randomUUID().toString();val replacement=UUID.randomUUID().toString();val row=JSONObject().put("id","$refund:$reservation").put("nativeVersion","snapshot");val b=JSONObject().put("refundId",refund).put("reservationId",reservation).put("expectedVersion","snapshot").put("action","replacement_coupon").put("replacementBenefitId",replacement).put("reason","实际补偿已完成").put("evidenceReference","原活动发券凭证");val c=memberGiftCommand(actor,board(JSONArray().put(row)),"refund",b,"登记复核");val result=JSONObject().put("refund_id",refund).put("reservation_id",reservation).put("action","replacement_coupon").put("reason",b.getString("reason")).put("evidence_reference",b.getString("evidenceReference")).put("replacement_benefit_id",replacement).put("replacement_quantity",1);val response=JSONObject().put("meta",JSONObject().put("protocol",1).put("replayed",true)).put("data",JSONObject().put("employeeId","e").put("requestKey",c.steps[0].key).put("action","refund").put("accepted",b).put("row",result));validateMemberGiftReply(response.toString(),c.steps[0]);result.put("replacement_benefit_id",UUID.randomUUID().toString());assertThrows(IllegalArgumentException::class.java){validateMemberGiftReply(response.toString(),c.steps[0])}}

}
