package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import org.junit.Assert.*
import org.junit.Test
class MembershipRecoveryTest{
 private fun actor()=StaffIdentity("s","e","m","主管","2099-01-01T00:00:00Z","2099-01-01T00:00:00Z",emptyList(),membershipRecoveryPermissions.toSet(),emptySet())
 private fun board(rows:List<JSONObject> = emptyList())=CouponCalendarsBoard(JSONObject().put("employeeId","e").put("protocol",1).put("durableCommands",true).put("rows",JSONArray(rows)).put("next",JSONObject.NULL))
 private fun receipt(c:LiveCommand,b:JSONObject,row:JSONObject)=JSONObject().put("meta",JSONObject().put("protocol",1).put("replayed",true)).put("data",JSONObject().put("employeeId","e").put("requestKey",c.steps[0].key).put("action",c.steps[0].membershipRecoveryProof!!.getString("action")).put("accepted",JSONObject(b.toString()).apply{remove("phone")}).put("row",row)).toString()
 @Test fun phoneAndConfirmationNeverEnterPlaintextPendingJournal(){val b=JSONObject().put("memberNo","MBX123456").put("phone","+8613900012345").put("reason","已核对本人原始会员凭据");val original=membershipRecoveryCommand(actor(),board(),"contact",null,b);var saved="";val secured=secureMembershipRecoveryCommand(original){_,body->saved=body};assertEquals(b.toString(),saved);assertFalse(secured.json().toString().contains("+8613900012345"));assertFalse(secured.json().toString().contains("MBX123456"));assertEquals("{}",secured.steps[0].body);assertEquals(secured,LiveCommand.parse(secured.json()));val row=JSONObject().put("memberNo","MBX123456").put("maskedPhone","+8***45").put("verifiedAt","2026-09-30 01:06:06.09+08");validateMembershipRecoveryReply(receipt(secured,b,row),secured.steps[0],b);row.put("memberNo","WRONG");assertThrows(IllegalArgumentException::class.java){validateMembershipRecoveryReply(receipt(secured,b,row),secured.steps[0],b)}}
 @Test fun cannotApproveOwnSelectionOrAChangedCase(){val row=JSONObject().put("casePublicId","MMC-test").put("nativeVersion","a".repeat(64)).put("status","pending_review").put("selectedByEmployeeId","e");assertThrows(IllegalArgumentException::class.java){membershipRecoveryCommand(actor(),board(listOf(row)),"approve",row,JSONObject().put("reason","不可自己复核"))};row.put("selectedByEmployeeId","other");assertThrows(IllegalArgumentException::class.java){membershipRecoveryCommand(actor(),board(),"approve",row,JSONObject().put("reason","必须核对原申请"))}}
 @Test fun mergedReceiptMustMatchSelectedMembershipAndChecker(){val before=JSONObject().put("casePublicId","MMC-test").put("nativeVersion","a".repeat(64)).put("status","pending_review").put("selectedByEmployeeId","other").put("selectedCandidatePublicId","MRC-original");val c=membershipRecoveryCommand(actor(),board(listOf(before)),"approve",before,JSONObject().put("reason","独立核验并合并原会员"));val b=JSONObject(c.steps[0].body);val result=JSONObject(before.toString()).put("status","executed").put("approvedByEmployeeId","e").put("nativeVersion","b".repeat(64));validateMembershipRecoveryReply(receipt(c,b,result),c.steps[0],b);result.put("selectedCandidatePublicId","MRC-wrong");assertThrows(IllegalArgumentException::class.java){validateMembershipRecoveryReply(receipt(c,b,result),c.steps[0],b)}}
}
