package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import org.junit.Assert.*
import org.junit.Test
import java.util.UUID
class ProductOperationsTest{
 private val actor=StaffIdentity("s","e","manager","经理","2099-01-01T00:00:00Z","2099-01-01T00:00:00Z",emptyList(),setOf("catalog.product.manage","inventory.cost.view","recommendation.phase.configure"),emptySet())
 @Test fun sensoryUnknownStaysNullAndAutomaticCostsCannotBeOverridden(){val p=JSONObject().put("id",UUID.randomUUID().toString()).put("inventoryControlMode","not_managed").put("productKind","single");val form=JSONObject().put("searchText","测试商品").put("productSnapshot",JSONObject().put("salesSpecificationType","glass").put("tasteProfile",JSONObject().put("acidity",0).put("sweetness",JSONObject.NULL))).put("costAmountMinor",JSONObject.NULL).put("costChangeReason","原成本待核对").put("fulfillmentSlaSeconds",JSONObject.NULL).put("recommendationUpgradeProductId",JSONObject.NULL);for(k in productNumberBounds.keys)form.put(k,2);for(k in productTagOptions.keys)form.put(k,JSONArray());val patch=productOperationsPatch(p,form,actor);assertTrue(patch.isNull("costAmountMinor"));assertEquals(0,patch.getJSONObject("productSnapshot").getJSONObject("tasteProfile").getInt("acidity"));assertTrue(patch.getJSONObject("productSnapshot").getJSONObject("tasteProfile").isNull("sweetness"));p.put("inventoryControlMode","tracked");assertThrows(IllegalArgumentException::class.java){productOperationsPatch(p,form,actor)};p.put("inventoryControlMode","not_managed");form.put("recommendationMinGuests",4);assertThrows(IllegalArgumentException::class.java){productOperationsPatch(p,form,actor)}}
 @Test fun phaseReceiptsMatchOriginalProductAndConfiguration(){val b=ProductPhasesBoard(JSONObject().put("employeeId","e").put("productId",UUID.randomUUID().toString()).put("phaseCodes",JSONArray()).put("expectedVersion","a".repeat(64)).put("protocol",1).put("durableCommands",true));val c=productPhasesCommand(actor,b,listOf("acoustic"),"配合不插电现场","测试商品");assertEquals(c,LiveCommand.parse(c.json()));val d=JSONObject(c.steps[0].productPhasesProof.toString()).put("requestKey",c.steps[0].key);val r=JSONObject().put("data",d).put("meta",JSONObject().put("protocol",1).put("replayed",true));validateProductPhasesReply(r.toString(),c.steps[0]);d.put("phaseCodes",JSONArray());assertThrows(IllegalArgumentException::class.java){validateProductPhasesReply(r.toString(),c.steps[0])}}
 @Test fun companionStartsInactiveWithSeparatePriceAndNoCopiedCost(){val p=JSONObject().put("id",UUID.randomUUID().toString()).put("name","测试红酒").put("code","TEST_WINE").put("productKind","single").put("inventoryControlMode","tracked").put("status","active").put("standardPrice",JSONObject().put("amountMinor",12000)).put("costAmountMinor",8000).put("productSnapshot",JSONObject().put("salesSpecificationType","whole_bottle"));val c=companionProductDraft(p);assertEquals("new",c.getString("id"));assertEquals("inactive",c.getString("status"));assertEquals("glass",c.getJSONObject("productSnapshot").getString("salesSpecificationType"));assertTrue(c.isNull("standardPrice"));assertTrue(c.isNull("costAmountMinor"));assertEquals("whole_bottle",p.getJSONObject("productSnapshot").getString("salesSpecificationType"))}
}
