package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import org.junit.Test
import org.junit.Assert.*
class RecommendationPoliciesTest{
 private fun actor(id:String)=StaffIdentity("s",id,"manager","主管","2099-01-01T00:00:00Z","2099-01-01T00:00:00Z",emptyList(),setOf("recommendation.rule.draft","recommendation.rule.approve","recommendation.rule.publish"),emptySet())
 private fun draft()=JSONObject().put("code","DEFAULT").put("preferenceWeight",100).put("sceneWeight",60).put("marginWeight",50).put("priorityWeight",50).put("performanceWeight",0).put("inventoryWeight",0).put("capacityWeight",0).put("minimumGrossMarginBasisPoints",1500).put("preferenceHalfLifeDays",90).put("preferenceMaxAgeDays",730).put("preferenceMinEffectiveScore",1000).put("preferenceMinConfidenceBasisPoints",2500).put("explanationTemplate","根据明确偏好与当前可售状态推荐").put("displayConfiguration",JSONObject().put("preserved","原问卷配置")).put("reason","已核对规则与配置")
 private fun board(rows:List<JSONObject> = emptyList())=CouponCalendarsBoard(JSONObject().put("employeeId","e").put("protocol",1).put("durableCommands",true).put("rows",JSONArray(rows)).put("next",JSONObject.NULL).put("code","DEFAULT").put("latest",3).put("feature",JSONObject().put("nativeVersion","b".repeat(64))))
 private fun receipt(c:LiveCommand,row:JSONObject)=JSONObject().put("meta",JSONObject().put("protocol",1).put("replayed",true)).put("data",JSONObject().put("employeeId",c.employeeID).put("requestKey",c.steps[0].key).put("action",c.steps[0].recommendationPolicyProof!!.getString("action")).put("accepted",JSONObject(c.steps[0].body)).put("row",row)).toString()
 @Test fun preservesFullDraftAndRequiresExactResult(){val c=recommendationPolicyCommand(actor("e"),board(),"create",null,draft());assertEquals(c,LiveCommand.parse(c.json()));val row=draft().put("version",4).put("status","draft").put("createdByEmployeeId","e").put("draftReason","已核对规则与配置").put("nativeVersion","a".repeat(64));validateRecommendationPolicyReply(receipt(c,row),c.steps[0]);row.put("displayConfiguration",JSONObject());assertThrows(IllegalArgumentException::class.java){validateRecommendationPolicyReply(receipt(c,row),c.steps[0])}}
 @Test fun separationAndVersionGuardSurviveConfirmation(){val r=draft().put("publicId","policy-test-001").put("version",3).put("nativeVersion","a".repeat(64)).put("status","draft").put("createdByEmployeeId","e");assertThrows(IllegalArgumentException::class.java){recommendationPolicyCommand(actor("e"),board(listOf(r)),"approve",r,JSONObject().put("reason","不能自行审批"))};r.put("createdByEmployeeId","other").put("approvedByEmployeeId","e").put("status","approved");assertThrows(IllegalArgumentException::class.java){recommendationPolicyCommand(actor("e"),board(listOf(r)),"publish",r,JSONObject().put("reason","不能审批兼发布").put("effectiveFrom","2037-01-01T00:00:00Z"))};assertThrows(IllegalArgumentException::class.java){recommendationPolicyCommand(actor("e"),board(),"clone",r,JSONObject().put("reason","必须保持原版本"))}}
 @Test fun boundsAndRolloutReceiptAreIndependent(){assertThrows(IllegalArgumentException::class.java){recommendationPolicyCommand(actor("e"),board(),"create",null,draft().put("preferenceMaxAgeDays",30))};val c=recommendationPolicyCommand(actor("e"),board(),"rollout",null,JSONObject().put("rolloutState","shadow").put("reason","只做后台观察"));val r=JSONObject().put("rolloutState","shadow").put("reason","只做后台观察").put("nativeVersion","a".repeat(64));validateRecommendationPolicyReply(receipt(c,r),c.steps[0]);r.put("rolloutState","enabled");assertThrows(IllegalArgumentException::class.java){validateRecommendationPolicyReply(receipt(c,r),c.steps[0])}}
}
