package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import org.junit.Test
import org.junit.Assert.*
class SocialOperationsTest{
 private val actor=StaffIdentity("s","e","manager","主管","2099-01-01T00:00:00Z","2099-01-01T00:00:00Z",emptyList(),setOf("member.card.manage","community.activity.manage"),emptySet())
 private fun board(rows:List<JSONObject> = emptyList())=CouponCalendarsBoard(JSONObject().put("employeeId","e").put("protocol",1).put("durableCommands",true).put("rows",JSONArray(rows)).put("next",JSONObject.NULL))
 private fun account()=JSONObject().put("kind","service_account").put("appId","wxNativeAccount").put("name","本店服务号").put("enabled",false).put("codeTemplateId",JSONObject.NULL).put("codeDataKey","number1").put("reminderTemplateId",JSONObject.NULL).put("reminderDataKey","thing1").put("credentials",JSONObject().put("secret","secret-not-in-journal").put("token","TestToken").put("encodingAesKey","A".repeat(43))).put("reason","核对平台账号配置")
 private fun receipt(c:LiveCommand,row:JSONObject):String{val b=JSONObject(c.steps[0].body);if(c.steps[0].socialOperationsProof!!.getString("action")=="account"){b.put("credentialsChanged",b.has("credentials"));b.remove("credentials")};return JSONObject().put("meta",JSONObject().put("protocol",1).put("replayed",true)).put("data",JSONObject().put("employeeId","e").put("requestKey",c.steps[0].key).put("accepted",b).put("action",c.steps[0].socialOperationsProof!!.getString("action")).put("row",row)).toString()}
 @Test fun completeSecretPayloadIsEncryptedBeforeJournalAndReceiptContainsNoSecrets(){val c=socialCommand(actor,board(),"account",null,account());var saved="";val secured=secureSocialCommand(c){key,value->assertEquals(c.id,key);saved=value};assertEquals(c.steps[0].body,saved);assertFalse(secured.json().toString().contains("secret-not-in-journal"));assertFalse(secured.json().toString().contains("TestToken"));assertFalse(secured.json().toString().contains("A".repeat(43)));assertEquals(secured,LiveCommand.parse(secured.json()));val r=account().apply{remove("credentials");put("id","00000000-0000-4000-8000-000000000001");put("nativeVersion","a".repeat(64))};validateSocialReply(receipt(c,r),secured.steps[0],JSONObject(saved));r.put("enabled",true);assertThrows(IllegalArgumentException::class.java){validateSocialReply(receipt(c,r),secured.steps[0],JSONObject(saved))}}
 @Test fun schedulingRequiresFullAudienceConfirmationAndUnknownCannotCancel(){val row=JSONObject().put("id","job").put("nativeVersion","a".repeat(64)).put("status","draft");assertThrows(IllegalArgumentException::class.java){socialCommand(actor,board(listOf(row)),"transition",row,JSONObject().put("action","schedule").put("audienceConfirmed",false).put("reason","必须明确范围"))};row.put("status","unknown");assertThrows(IllegalArgumentException::class.java){socialCommand(actor,board(listOf(row)),"transition",row,JSONObject().put("action","cancel").put("audienceConfirmed",false).put("reason","不允许撤回未知结果"))};assertThrows(IllegalArgumentException::class.java){socialCommand(actor,board(),"account",null,account().put("credentials",JSONObject().put("secret","only-one-field").put("token","").put("encodingAesKey","")))}}
 @Test fun draftDoesNotMeanSentAndOriginalScheduleMustMatch(){val body=JSONObject().put("accountId","00000000-0000-4000-8000-000000000001").put("title","活动通知").put("content","已经核对的活动内容").put("scheduledAt","2037-01-01T00:00:00Z").put("reason","先保存待审核草稿");val c=socialCommand(actor,board(),"broadcast",null,body);val row=JSONObject(body.toString()).put("status","draft").put("createdByEmployeeId","e").put("nativeVersion","a".repeat(64)).put("scheduledAt","2037-01-01 08:00:00+08");validateSocialReply(receipt(c,row),c.steps[0],JSONObject(c.steps[0].body));row.put("status","delivered");assertThrows(IllegalArgumentException::class.java){validateSocialReply(receipt(c,row),c.steps[0],JSONObject(c.steps[0].body))}}
}
