package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import org.junit.Test
import org.junit.Assert.*
import java.util.UUID
class StackingPoliciesTest{
 @Test fun zeroDiscountCeilingDiffersFromNoCeilingAndOrderMustContainEachStage(){val f=stackingEditor(null).put("maximumDiscountMinor","0");assertEquals(0L,stackingPolicyFromEditor(f).getLong("maximumDiscountMinor"));f.put("maximumDiscountMinor","");assertTrue(stackingPolicyFromEditor(f).isNull("maximumDiscountMinor"));f.put("maxCoupons","2");assertThrows(IllegalArgumentException::class.java){stackingPolicyFromEditor(f)};f.put("allowOtherCoupons",true);assertEquals(2,stackingPolicyFromEditor(f).getInt("maxCoupons"));f.put("order","member,member,points");assertThrows(IllegalArgumentException::class.java){stackingPolicyFromEditor(f)}}
 @Test fun simulatorPreservesUnknownCostAndExactRatesAndChecksDeletedUnits(){val u=stackingUnitDraft().put("amount","10.01");val e=stackingEffectDraft().put("kind","rate").put("value","87.65").put("unitIds",JSONArray().put(u.getString("id")));val p=stackingScenario(listOf(u),listOf(e));assertEquals(1001L,p.getJSONArray("units").getJSONObject(0).getLong("amountMinor"));assertTrue(p.getJSONArray("units").getJSONObject(0).isNull("costMinor"));assertEquals(8765,p.getJSONArray("effects").getJSONObject(0).getInt("value"));u.put("cost","0");assertEquals(0,stackingScenario(listOf(u),listOf(e)).getJSONArray("units").getJSONObject(0).getInt("costMinor"));e.put("unitIds",JSONArray().put("removed"));assertThrows(IllegalArgumentException::class.java){stackingScenario(listOf(u),listOf(e))}}
 @Test fun savedReplyMustPreserveCalculationOrderAndFrozenPolicy(){val actor=StaffIdentity("s","e","manager","主管","2099-01-01T00:00:00Z","2099-01-01T00:00:00Z",emptyList(),setOf("loyalty.configuration.edit"),emptySet());val board=StackingPoliciesBoard(JSONObject().put("employeeId","e").put("protocol",1).put("durableCommands",true).put("rows",JSONArray()));val body=stackingSaveBody(stackingEditor(null).put("code","STACK_TEST").put("reason","规则预算已核对"));val c=stackingPolicyCommand(actor,board,"save",body,"保存草稿");assertEquals(c,LiveCommand.parse(c.json()));val row=JSONObject().put("id",UUID.randomUUID().toString()).put("code","STACK_TEST").put("version",1).put("status","draft").put("createdByEmployeeId","e").put("policy",JSONObject(body.getJSONObject("policy").toString()));val r=JSONObject().put("meta",JSONObject().put("protocol",1).put("replayed",true)).put("data",JSONObject().put("employeeId","e").put("requestKey",c.steps[0].key).put("action","save").put("row",row));validateStackingPolicyReply(r.toString(),c.steps[0]);row.getJSONObject("policy").put("calculationOrder",JSONArray(listOf("coupon","member","points")));assertThrows(IllegalArgumentException::class.java){validateStackingPolicyReply(r.toString(),c.steps[0])}}
}
