package com.mbox.staff
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import androidx.lifecycle.compose.LocalLifecycleOwner
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleEventObserver
import kotlinx.coroutines.launch
import kotlinx.coroutines.delay
import org.json.JSONObject
import org.json.JSONArray
@Composable fun LiveActivityOperationsView(m:AppModel,close:()->Unit){
 val access=remember{m.priorityAccessKey};val workspace=remember{m.workspaceVersion};var search by remember{mutableStateOf("")};var registrationSearch by remember{mutableStateOf("")};var creating by remember{mutableStateOf(false)};var editing by remember{mutableStateOf<JSONObject?>(null)};var selected by remember{mutableStateOf<String?>(null)};var action by remember{mutableStateOf("")};var reg by remember{mutableStateOf<JSONObject?>(null)};var packageId by remember{mutableStateOf<String?>(null)};var terminal by remember{mutableStateOf("cancelled")};var reason by remember{mutableStateOf("")};var error by remember{mutableStateOf("")};var proposed by remember{mutableStateOf<LiveCommand?>(null)};var cashier by remember{mutableStateOf<String?>(null)}
 LaunchedEffect(Unit){m.loadActivityOperations()};LaunchedEffect(m.priorityAccessKey,m.workspaceVersion){if(access!=m.priorityAccessKey||workspace!=m.workspaceVersion)close()};if(access!=m.priorityAccessKey||workspace!=m.workspaceVersion)return
 val detail=m.activityOperationsDetail?.data?.optJSONObject("activity")
 fun propose(kind:String,row:JSONObject?,registration:JSONObject?,body:JSONObject){try{proposed=activityOperationsCommand(m.identity!!,m.activityOperationsBoard?:error("请读取活动"),kind,row,registration,body);error=""}catch(e:Exception){error=e.message?:"请核对活动内容"}}
 fun control(kind:String,registration:JSONObject?=null,pack:String?=null){action=kind;reg=registration;packageId=pack;reason=""}
 Dialog(onDismissRequest=close,properties=DialogProperties(usePlatformDefaultWidth=false)){Surface(Modifier.fillMaxSize(),color=Paper){LazyColumn(Modifier.safeDrawingPadding().imePadding().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
 item{Row{Text("活动运营",Modifier.weight(1f),style=MaterialTheme.typography.titleLarge);TextButton(onClick=close){Text("关闭")}};LivePendingView(m);Text(m.activityOperationsState);if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error)}
 if(creating||editing!=null){item{key(creating,editing?.getString("nativeVersion")){ActivityDraftEditor(m,editing,{creating=false;editing=null}){propose(if(creating)"create"else "update",editing,null,it)}}}}
 else if(selected!=null){item{Row{TextButton(onClick={selected=null}){Text("返回活动列表")};TextButton(onClick={m.selectActivityOperations(selected!!)},enabled=!m.busy){Text("刷新活动与报名")}};detail?.takeIf{it.getString("publicId")==selected}?.let{a->Panel{Text(a.getString("title"),style=MaterialTheme.typography.titleLarge);Text(activityStates[a.getString("status")]?:a.getString("status"));Text("${calendarLocal(a.getString("startsAt"))} 至 ${calendarLocal(a.getString("endsAt"))}\n${a.getString("assemblyLocation")}");Text("已占 ${a.getInt("occupiedSeats")} / ${a.getInt("capacity")} 人 · 候补 ${a.getInt("waitlistedSeats")} 人");Text("费用 ${historyMoney(a.getLong("feeAmountMinor"))} · ${activityPaymentModes.toMap()[a.getString("paymentMode")]} · ${if(a.getString("feeBasis")=="per_person")"按人"else "按报名单"}");Text(a.getString("summary"));Foldout("活动承诺与参加条件"){for((k,label)in listOf("activityDetails" to "详情","paymentRuleText" to "付款说明","safetyAcknowledgementText" to "安全确认","refundPolicySummary" to "退款说明","contactInstructions" to "集合联系","memberBenefitText" to "会员权益"))a.textOrNull(k)?.let{Text("$label：$it")};for((k,label)in listOf("safetyRequirements" to "安全要求","includedItems" to "包含内容","participationRequirements" to "参加要求"))Text("$label："+a.getJSONArray(k).strings().joinToString("；"));Text("可见范围："+mapOf("public" to "公开","member" to "所有会员","segment" to "指定客群")[a.getString("visibility")]);Text("安全版本 ${a.textOrNull("safetyPolicyVersion")?:"未配置"} · 退款版本 ${a.textOrNull("refundPolicyVersion")?:"未配置"}")}
 if(m.identity?.allows("community.activity.manage")==true){if(a.getString("status")=="draft")TextButton(onClick={editing=a},enabled=m.canUseActivityOperations){Text("编辑完整草稿")};if(a.getString("status") in listOf("published","full")){if(a.textOrNull("registrationClosedAt")==null)TextButton(onClick={control("stop-registration")},enabled=m.canUseActivityOperations){Text("停止新报名")};TextButton(onClick={control("waitlist-retry")},enabled=m.canUseActivityOperations){Text("重试已有候补任务")}};if(a.getString("status") in listOf("draft","published","full"))TextButton(onClick={control("close")},enabled=m.canUseActivityOperations){Text("结束 / 取消活动")}}
 if(a.getString("status")=="draft"&&m.identity?.allows("community.activity.publish")==true)PrimaryAction(onClick={control("publish")},enabled=m.canUseActivityOperations&&a.getString("createdByEmployeeId")!=m.identity?.employeeId){Text("另一位员工核对并发布")};a.textOrNull("registrationClosedAt")?.let{Text("已停止新报名：${calendarLocal(it)}")}
 for(p in a.getJSONArray("packages").objects())Panel{Text(p.getString("name"),style=MaterialTheme.typography.titleMedium);Text("${historyMoney(p.getLong("feeAmountMinor"))} · ${p.getInt("capacity")}个名额 · "+mapOf("draft" to "草稿","published" to "可报名","paused" to "已暂停")[p.getString("status")]);Text(p.getString("description"));Text(p.getJSONArray("includedItems").strings().joinToString("、"));if(m.identity?.allows("community.activity.manage")==true&&a.getString("status") in listOf("published","full"))TextButton(onClick={control(if(p.getString("status")=="paused")"package-resume"else "package-pause",pack=p.getString("publicId"))},enabled=m.canUseActivityOperations){Text(if(p.getString("status")=="paused")"恢复此档报名"else "暂停此档报名")}}
 }}}
 if(detail?.getString("publicId")==selected){item{CustodyField("搜索顾客称呼或报名编号",registrationSearch,80){registrationSearch=it};TextButton(onClick={m.selectActivityOperations(selected!!,search=registrationSearch)},enabled=!m.busy){Text("查询报名")}};items(m.activityRegistrationRows,key={it.getString("publicId")}){r->ActivityRegistrationCard(m,r,{control(it,r)},{cashier=r.getString("publicId")})};if(m.activityOperationsDetail?.next!=null)item{TextButton(onClick={m.selectActivityOperations(selected!!,true)},enabled=!m.busy){Text("更多报名记录")}}}
 }
 else{item{CustodyField("搜索活动标题或编号",search,80){search=it};Row{TextButton(onClick={m.loadActivityOperations(search)},enabled=!m.busy){Text("查询 / 刷新")};if(m.identity?.allows("community.activity.manage")==true)TextButton(onClick={creating=true},enabled=m.canUseActivityOperations){Text("新建活动草稿")}}};items(m.activityOperationsRows,key={it.getString("publicId")}){a->Panel{Text(a.getString("title"),style=MaterialTheme.typography.titleMedium);Text("${activityStates[a.getString("status")]} · ${calendarLocal(a.getString("startsAt"))}");Text("${a.getInt("occupiedSeats")}人已占位 · ${a.getInt("waitlistedSeats")}人候补");PrimaryAction(onClick={selected=a.getString("publicId");registrationSearch="";m.selectActivityOperations(selected!!)},enabled=!m.busy){Text("查看活动与报名")}}};if(m.activityOperationsBoard?.next!=null)item{TextButton(onClick={m.loadActivityOperations(more=true)},enabled=!m.busy){Text("更多活动")}}}
 }}}
 if(action.isNotBlank())AlertDialog(onDismissRequest={action=""},title={Text(activityOperationsLabels.getValue(action))},text={Column{reg?.let{Text("${it.getString("customerLabel")} · ${it.getInt("partySize")}人")};if(action=="close")AssignmentChoice("活动结论",terminal,listOf("cancelled" to "取消活动","completed" to "活动已结束")){terminal=it};CustodyField("操作原因",reason,500){reason=it};if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error)}},confirmButton={TextButton(onClick={val b=JSONObject().put("reason",reason);if(action=="close")b.put("status",terminal);packageId?.let{b.put("packagePublicId",it)};propose(action,detail,reg,b);if(proposed!=null)action=""},enabled=m.canUseActivityOperations){Text("继续核对")}},dismissButton={TextButton(onClick={action=""}){Text("取消")}})
 proposed?.let{c->AlertDialog(onDismissRequest={proposed=null},title={Text("确认活动操作")},text={Text(c.steps[0].activityOperationsProof!!.getString("confirmation"))},confirmButton={TextButton(onClick={proposed=null;creating=false;editing=null;m.executeLive(c)},enabled=m.canExecuteLive(c)){Text("确认提交")}},dismissButton={TextButton(onClick={proposed=null}){Text("返回")}})}
 cashier?.let{q->Dialog(onDismissRequest={cashier=null;selected?.let{m.selectActivityOperations(it)}},properties=DialogProperties(usePlatformDefaultWidth=false)){Surface(Modifier.fillMaxSize(),color=Paper){Column(Modifier.safeDrawingPadding()){TextButton(onClick={cashier=null;selected?.let{m.selectActivityOperations(it)}}){Text("返回活动，重新读取报名")};LiveCashierView(m,q)}}}}
}
@Composable private fun ActivityRegistrationCard(m:AppModel,r:JSONObject,act:(String)->Unit,cashier:()->Unit){
 var contact by remember(r.getString("contactVersionPublicId")){mutableStateOf<JSONObject?>(null)};var clock by remember{mutableStateOf(java.time.Instant.now())};var loading by remember{mutableStateOf(false)};var error by remember{mutableStateOf("")};val scope=rememberCoroutineScope();LaunchedEffect(contact){while(contact!=null){clock=java.time.Instant.now();if(!serverInstant(contact!!.getString("expiresAt")).isAfter(clock)){contact=null;break};delay(1000)}}
 val lifecycle=LocalLifecycleOwner.current.lifecycle
 DisposableEffect(lifecycle){val observer=LifecycleEventObserver{_,event->if(event==Lifecycle.Event.ON_STOP)contact=null};lifecycle.addObserver(observer);onDispose{lifecycle.removeObserver(observer);contact=null}}
 Panel{Text("${r.getString("customerLabel")} · ${r.getInt("partySize")}人",style=MaterialTheme.typography.titleMedium);Text("${registrationStates[r.getString("status")]} · ${cashierStatus(r.getString("paymentStatus"))}");Text("报名 ${r.getString("publicId")}");Text("实收 ${historyMoney(r.getLong("paidAmountMinor"))} · 应付 ${historyMoney(r.getLong("amountDueMinor"))}");Text("联系："+(contact?.takeIf{serverInstant(it.getString("expiresAt")).isAfter(clock)}?.getString("contactValue")?:r.getString("maskedContact")));val purpose=when(r.getString("status")){"waitlisted"->"waitlist_coordination";"payment_pending"->"payment_followup";"confirmed","checked_in"->"attendance_coordination";else->null};if(purpose!=null&&m.identity?.allows("community.activity.contact.reveal")==true&&r.getString("maskedContact")!="已清除")TextButton(onClick={loading=true;scope.launch{try{val result=m.revealActivityContact(r.getString("contactVersionPublicId"),purpose);if(lifecycle.currentState.isAtLeast(Lifecycle.State.STARTED))contact=result;error=""}catch(e:Exception){error=e.message?:"联系方式暂不可查看"}finally{loading=false}}},enabled=!loading&&!m.busy){Text("按现场协调用途短暂查看联系")};if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error)
 if(m.identity?.allows("community.activity.manage")==true){if(r.getString("status")=="confirmed"){TextButton(onClick={act("check-in")},enabled=m.canUseActivityOperations){Text("确认到场")};TextButton(onClick={act("no-show")},enabled=m.canUseActivityOperations){Text("活动开始后标记未到")}};if(r.getString("packageFulfillmentStatus")=="pending"&&r.getString("status")=="checked_in")TextButton(onClick={act("fulfill-package")},enabled=m.canUseActivityOperations){Text("核对套餐实物已交付")};if(r.getString("packageFulfillmentStatus")=="delivered")Text("原套餐实物已领取");if(r.getString("status") in listOf("reserved","payment_pending","confirmed","waitlisted")&&r.getString("paymentStatus")!="paid")TextButton(onClick={act("cancel-registration")},enabled=m.canUseActivityOperations){Text("取消未付款报名")}}
 if(m.identity?.allows("community.activity.manage")==true&&m.identity?.allows("refund.request")==true&&r.optLong("refundableAmountMinor",0)>0&&r.textOrNull("authoritativePaymentStatus") in listOf("succeeded","partially_refunded"))TextButton(onClick={act("refund-request")},enabled=m.canUseActivityOperations){Text("申请原付款剩余退款 ${historyMoney(r.getLong("refundableAmountMinor"))}")}
 if(m.identity?.allows("community.activity.cashier")==true)TextButton(onClick=cashier,enabled=!m.busy){Text("本笔报名收款 / 原付款退款处理")}
 }
}
