package com.mbox.staff
import org.json.JSONObject
import java.util.UUID
const val experiencePlansRoot="/api/staff/native-experience-plans"
val experiencePlanStates=mapOf("planned" to "待原订单确认","active" to "服务中","paused" to "已暂停","completed" to "已完成","cancelled" to "已中止")
val experienceCueStates=mapOf("pending" to "等待触发","ready" to "待派出","dispatched" to "任务已派出","completed" to "已完成","skipped" to "已停止","failed" to "异常待核对")
val experienceActions=mapOf("welcome" to "迎宾","service" to "桌边服务","drink" to "酒水服务","food" to "餐食服务","music" to "音乐提醒","interaction" to "互动服务","checkin" to "到店关怀","upsell" to "加购建议","farewell" to "离店服务")
class ExperiencePlansBoard(val data:JSONObject){val actor=data.getString("employeeId");val rows=data.getJSONArray("rows").objects();val enabled=data.getInt("protocol")==1&&data.getBoolean("durableCommands");val canManage=data.getBoolean("canManage");val next=data.optJSONObject("next")}
fun experiencePlanCommand(actor:StaffIdentity,b:ExperiencePlansBoard,row:JSONObject,action:String,reason:String,cue:JSONObject?=null,minutes:Int?=null):LiveCommand{
 require(b.enabled&&b.canManage&&b.actor==actor.employeeId&&listOf("customer.experience.manage","service.manage","service.execute").all{actor.allows(it)}){"没有计划管理权限"};require(b.rows.any{it.getString("id")==row.getString("id")&&it.getString("expectedVersion")==row.getString("expectedVersion")}){"原计划已变化，请刷新"};require(reason.trim().length in 4..500){"请填写4至500字现场处理原因"}
 val state=row.getString("plan_state");require(state in listOf("active","paused")&&row.getString("session_status") in listOf("open","closing")){"该计划当前不能操作"}
 val tasks=row.getJSONArray("tasks").objects();val body=JSONObject().put("action",action).put("expectedVersion",row.getString("expectedVersion")).put("reason",reason.trim());val label=when(action){
 "cancel"->"中止计划";"pause"->{require(state=="active"&&tasks.none{it.getString("status") in listOf("pending","acknowledged","in_progress")}){"已有派出任务，请先完成任务或整体中止"};"暂停计划"};"resume"->{require(state=="paused");"恢复计划"};"reschedule"->{require(cue!=null&&minutes!=null&&minutes in 0..240);require(row.getJSONArray("cues").objects().any{it.getString("id")==cue.getString("id")&&it.getString("trigger_kind")=="elapsed"&&it.getString("status") in listOf("pending","ready")&&it.isNull("service_task_id")});body.put("cueId",cue.getString("id")).put("offsetMinutes",minutes);"调整服务时间"};else->error("未知计划操作")}
 val id=UUID.randomUUID().toString();val proof=JSONObject().put("employeeId",actor.employeeId).put("planId",row.getString("id")).put("tableSessionId",row.getString("table_session_id")).put("action",action).put("state",when(action){"cancel"->"cancelled";"pause"->"paused";"resume"->"active";else->state}).put("planVersion",row.getInt("plan_version")+1).put("cueId",cue?.getString("id")?:JSONObject.NULL).put("offsetMinutes",minutes?:JSONObject.NULL)
 proof.put("confirmation","${row.getString("table_code")} · $label\n"+when(action){"cancel"->"停止未完成节点并取消关联服务任务。已完成记录、原订单和付款保留；退款或补偿须另走原流程。";"pause"->"暂停后不再派出新节点。恢复时已经到期的节点可能立即派出。";"resume"->"恢复后已经到期的节点可能立即派出，请核对现场。";else->"将节点调整为计划激活后 $minutes 分钟；已派出任务不能在这里改时。"}+"\n原因：${reason.trim()}")
 return LiveCommand(id,actor.employeeId,label,"customer.experience.manage",listOf(LiveStep("$experiencePlansRoot/${row.getString("id")}",body.toString(),"idempotency-key","native-business-$id",JSONObject().put("experiencePlan",proof).toString())))
}
val LiveStep.experiencePlanProof:JSONObject? get()=recoveryBody?.let{JSONObject(it).optJSONObject("experiencePlan")}
fun validateExperiencePlanReply(text:String,step:LiveStep){val r=JSONObject(text);val d=r.getJSONObject("data");require(r.getJSONObject("meta").getInt("protocol")==1&&r.getJSONObject("meta").get("replayed") is Boolean);require(d.getString("requestKey")==step.key);val p=step.experiencePlanProof!!;for(k in listOf("employeeId","planId","tableSessionId","action","state","planVersion","cueId","offsetMinutes"))require(d.has(k)&&d.opt(k).toString()==p.opt(k).toString()){"原计划回执不一致，请保留原请求核对"}}
