package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import java.util.UUID
const val productPhaseRoot="/api/staff/native-product-phases"
val productPhaseLabels=linkedMapOf("before_show" to "演出前","acoustic" to "不插电","band_live" to "乐队现场","intermission" to "中场","after_show" to "演出后")
class ProductPhasesBoard(val data:JSONObject){val actor=data.getString("employeeId");val product=data.getString("productId");val phases=data.getJSONArray("phaseCodes").strings();val enabled=data.getInt("protocol")==1&&data.getBoolean("durableCommands")}
fun productPhasesCommand(actor:StaffIdentity,b:ProductPhasesBoard,phases:List<String>,reason:String,name:String):LiveCommand{require(b.enabled&&b.actor==actor.employeeId&&actor.allows("recommendation.phase.configure"));require(phases.distinct().size==phases.size&&phases.all{it in productPhaseLabels});require(reason.trim().length in 2..240){"请填写2至240字原因"};require(phases.toSet()!=b.phases.toSet()){"没有阶段变化"};val id=UUID.randomUUID().toString();val body=JSONObject().put("phaseCodes",JSONArray(phases)).put("expectedVersion",b.data.getString("expectedVersion")).put("reason",reason.trim());val proof=JSONObject().put("employeeId",actor.employeeId).put("productId",b.product).put("phaseCodes",JSONArray(phases)).put("confirmation","$name\n${if(phases.isEmpty())"取消演出阶段限制" else "仅在以下阶段供应："+phases.joinToString("、"){productPhaseLabels[it]!!}}\n原因：${reason.trim()}\n保存影响后续商品可售判断，已有订单保留原记录。");return LiveCommand(id,actor.employeeId,"核对商品演出阶段","recommendation.phase.configure",listOf(LiveStep("$productPhaseRoot/${b.product}",body.toString(),"idempotency-key","native-business-$id",JSONObject().put("productPhases",proof).toString())))}
val LiveStep.productPhasesProof:JSONObject? get()=recoveryBody?.let{JSONObject(it).optJSONObject("productPhases")}
fun validateProductPhasesReply(text:String,s:LiveStep){val r=JSONObject(text);val d=r.getJSONObject("data");val p=s.productPhasesProof!!;require(r.getJSONObject("meta").getInt("protocol")==1&&r.getJSONObject("meta").get("replayed") is Boolean);require(d.getString("employeeId")==p.getString("employeeId")&&d.getString("productId")==p.getString("productId")&&d.getString("requestKey")==s.key&&d.getJSONArray("phaseCodes").strings().toSet()==p.getJSONArray("phaseCodes").strings().toSet()){"阶段回执不匹配，请保留原请求核对"}}
