package com.mbox.staff
import java.util.UUID
import org.json.JSONObject
const val membershipRecoveryRoot="/api/staff/native-membership-recovery"
val membershipRecoveryPermissions=listOf("customer.membership.recovery.verify","customer.membership.merge.approve")
val membershipRecoveryStatuses=mapOf("manual_review" to "待核验候选","pending_review" to "待独立复核","approved" to "已批准待核对","executed" to "已合并并保留原历史","rejected" to "已驳回")
fun membershipRecoveryCommand(actor:StaffIdentity,board:CouponCalendarsBoard,action:String,row:JSONObject?,input:JSONObject):LiveCommand{
 require(board.enabled&&board.actor==actor.employeeId);require(action in listOf("contact","select","approve","reject"));val permission=if(action in listOf("contact","select"))membershipRecoveryPermissions[0]else membershipRecoveryPermissions[1];require(actor.allows(permission));val b=JSONObject(input.toString());val reason=b.getString("reason").trim();require(reason.length in 2..500){"请填写2至500字实际核验或处理依据"};b.put("reason",reason)
 if(action=="contact"){val member=b.getString("memberNo").trim();require(member.length in 1..64);b.put("memberNo",member);require(Regex("^\\+[1-9][0-9]{7,14}$").matches(b.getString("phone"))){"手机号请带国家代码，例如 +86"}}
 else{require(row!=null&&board.rows.any{it.getString("casePublicId")==row.getString("casePublicId")&&it.getString("nativeVersion")==row.getString("nativeVersion")}){"原申请已变化，请重新读取"};require(row.getString("status") in (if(action=="select")listOf("manual_review")else if(action=="approve")listOf("pending_review")else listOf("manual_review","pending_review")));if(action=="approve")require(row.textOrNull("selectedByEmployeeId")!=actor.employeeId){"核验人与合并复核人必须不同"};b.put("casePublicId",row.getString("casePublicId")).put("expectedVersion",row.getString("nativeVersion"));if(action=="select")require(Regex("^[A-Za-z0-9_-]{3,128}$").matches(b.getString("candidatePublicId")))}
 val label=mapOf("contact" to "登记已人工核验的联系方式","select" to "选择已核验的会员候选","approve" to "独立复核并合并会员","reject" to "驳回会员找回申请").getValue(action);val detail=if(action=="contact")"会员 ${b.getString("memberNo")} · 手机号尾号 ${b.getString("phone").takeLast(4)}\n必须已核对本人及原始会员凭据，不授予营销许可。"else "申请 ${row!!.getString("casePublicId")}\n${row.textOrNull("maskedMemberNo")?:"核验候选"} · ${row.textOrNull("maskedPhone")?:"联系方式待核对"}\n"+(if(action=="approve")"合并后保留原账户、积分流水和权益历史，不重复加积分或发券。"else "原申请和核验记录保留。")
 val id=UUID.randomUUID().toString();return LiveCommand(id,actor.employeeId,label,permission,listOf(LiveStep("$membershipRecoveryRoot/$action",b.toString(),"idempotency-key","native-business-$id",JSONObject().put("membershipRecovery",JSONObject().put("employeeId",actor.employeeId).put("action",action).put("before",row?:JSONObject.NULL).put("confirmation","$label\n$detail\n依据：$reason")).toString())))
}
val LiveStep.membershipRecoveryProof:JSONObject? get()=recoveryBody?.let{JSONObject(it).optJSONObject("membershipRecovery")}
fun secureMembershipRecoveryCommand(c:LiveCommand,store:(String,String)->Unit):LiveCommand{val s=c.steps.firstOrNull()?:return c;val p=s.membershipRecoveryProof?:return c;require(c.steps.size==1);if(p.has("payloadKey"))return c;store(c.id,s.body);p.remove("confirmation");return c.copy(title="待核对会员找回原请求",steps=listOf(s.copy(body="{}",recoveryBody=JSONObject().put("membershipRecovery",p.put("payloadKey",c.id)).toString())))}
fun validateMembershipRecoveryReply(text:String,s:LiveStep,b:JSONObject){val r=JSONObject(text);val d=r.getJSONObject("data");val p=s.membershipRecoveryProof!!;val action=p.getString("action");val accepted=JSONObject(b.toString()).apply{remove("phone")};require(r.getJSONObject("meta").getInt("protocol")==1&&r.getJSONObject("meta").get("replayed") is Boolean&&d.getString("employeeId")==p.getString("employeeId")&&d.getString("requestKey")==s.key&&d.getString("action")==action&&calendarJson(d.getJSONObject("accepted"))==calendarJson(accepted));val row=d.getJSONObject("row");if(action=="contact"){val masked=row.getString("maskedPhone");require(row.getString("memberNo")==b.getString("memberNo")&&masked.contains('*')&&masked.endsWith(b.getString("phone").takeLast(2)));serverInstant(row.getString("verifiedAt"))}else{require(row.getString("casePublicId")==b.getString("casePublicId")&&Regex("^[a-f0-9]{64}$").matches(row.getString("nativeVersion"))&&row.getString("status")==when(action){"select"->"pending_review";"approve"->"executed";else->"rejected"});if(action=="select")require(row.getString("selectedCandidatePublicId")==b.getString("candidatePublicId")&&row.getString("selectedByEmployeeId")==p.getString("employeeId"));if(action=="approve"){require(row.getString("approvedByEmployeeId")==p.getString("employeeId"));for(k in listOf("selectedCandidatePublicId","selectedByEmployeeId"))require(calendarJson(row.get(k))==calendarJson(p.getJSONObject("before").get(k)))}}}
