package com.mbox.staff
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import org.json.JSONObject
import org.json.JSONArray
@Composable fun LiveRecommendationPoliciesView(m:AppModel,close:()->Unit){
 val access=remember{m.priorityAccessKey};val workspace=remember{m.workspaceVersion};var code by remember{mutableStateOf("DEFAULT")};var editing by remember{mutableStateOf(false)};var source by remember{mutableStateOf<JSONObject?>(null)};var selected by remember{mutableStateOf<JSONObject?>(null)};var action by remember{mutableStateOf("")};var rollout by remember{mutableStateOf("disabled")};var reason by remember{mutableStateOf("")};var time by remember{mutableStateOf("")};var error by remember{mutableStateOf("")};var proposed by remember{mutableStateOf<LiveCommand?>(null)}
 LaunchedEffect(Unit){m.loadRecommendationPolicies()};LaunchedEffect(m.priorityAccessKey,m.workspaceVersion){if(access!=m.priorityAccessKey||workspace!=m.workspaceVersion)close()};if(access!=m.priorityAccessKey||workspace!=m.workspaceVersion)return
 fun propose(kind:String,row:JSONObject?,body:JSONObject){try{val b=m.recommendationPolicyBoard?:error("请读取原规则");proposed=recommendationPolicyCommand(m.identity!!,CouponCalendarsBoard(JSONObject(b.data.toString()).put("rows",JSONArray(m.recommendationPolicyRows))),kind,row,body);error=""}catch(e:Exception){error=e.message?:"请核对参数"}}
 Dialog(onDismissRequest=close,properties=DialogProperties(usePlatformDefaultWidth=false)){Surface(Modifier.fillMaxSize(),color=Paper){LazyColumn(Modifier.safeDrawingPadding().imePadding().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
 item{Row{Text("推荐规则与顾客开放",Modifier.weight(1f),style=MaterialTheme.typography.titleLarge);TextButton(onClick=close){Text("关闭")}};LivePendingView(m);Text(m.recommendationPolicyState);if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error)}
 if(editing){item{RecommendationDraft(m,source,{editing=false}){propose("create",null,it)}}}else{
 item{CustodyField("策略编号（常用 DEFAULT）",code,64){code=it};TextButton(onClick={if(Regex("^[A-Z][A-Z0-9_-]{2,63}$").matches(code))m.loadRecommendationPolicies(code)else error="请填写有效的大写策略编号"},enabled=!m.busy){Text("读取该策略")};m.recommendationPolicyBoard?.data?.getJSONObject("feature")?.let{f->Panel{Text("顾客推荐：${recommendationRollouts.toMap()[f.getString("rolloutState")]}",style=MaterialTheme.typography.titleMedium);Text(f.getString("reason"));Text("规则发布和顾客开放分别控制。正式开放需要当前生效的三人分离版本。",style=MaterialTheme.typography.bodySmall);if(m.identity?.allows("recommendation.rule.publish")==true)TextButton(onClick={action="rollout";rollout=f.getString("rolloutState");reason="";selected=null},enabled=m.canUseRecommendationPolicies){Text("调整顾客开放状态")}}};if(m.identity?.allows("recommendation.rule.draft")==true)TextButton(onClick={source=m.recommendationPolicyRows.firstOrNull();editing=true},enabled=m.canUseRecommendationPolicies){Text("新建规则草稿")};Text("演出阶段、库存和出品能力始终限制可推荐商品；修改权重不能绕过这些条件。",style=MaterialTheme.typography.bodySmall)}
 items(m.recommendationPolicyRows,key={it.getString("publicId")}){r->Panel{Text("${r.getString("code")} · 第${r.getInt("version")}版",style=MaterialTheme.typography.titleMedium);Text(mapOf("draft" to "草稿","approved" to "待发布","published" to "已发布","retired" to "历史版本")[r.getString("status")]?:r.getString("status"));Text(if(r.getString("publicationMode")=="legacy_unverified")"历史版本，未补造审批证据"else "三人分离受控版本");Text("偏好 / 场景：${r.getInt("preferenceWeight")} / ${r.getInt("sceneWeight")}\n毛利 / 优先级：${r.getInt("marginWeight")} / ${r.getInt("priorityWeight")}");Text("最低毛利 ${recommendationPercent(r.getInt("minimumGrossMarginBasisPoints"))}% · 最低匹配把握 ${recommendationPercent(r.getInt("preferenceMinConfidenceBasisPoints"))}%");Text(r.getString("explanationTemplate"));Text(r.textOrNull("effectiveFrom")?.let{"${calendarLocal(it)} 起"+(r.textOrNull("effectiveUntil")?.let{end->"，至 ${calendarLocal(end)}"}?:"")}?:"尚未安排生效");Foldout("衰减参数与审批依据"){Text("半衰期 ${r.getInt("preferenceHalfLifeDays")} 天；最长 ${r.getInt("preferenceMaxAgeDays")} 天；最低有效分 ${r.getInt("preferenceMinEffectiveScore")}");Text("起草：${r.optString("draftReason")}\n审批：${r.textOrNull("approvalReason")?:"待审批"}\n发布：${r.textOrNull("publicationReason")?:"待发布"}")};Row{if(m.identity?.allows("recommendation.rule.draft")==true){TextButton(onClick={source=r;editing=true},enabled=m.canUseRecommendationPolicies){Text("据此调整")};TextButton(onClick={action="clone";selected=r;reason=""},enabled=m.canUseRecommendationPolicies){Text("原样复制")}};if(r.getString("status")=="draft"&&m.identity?.allows("recommendation.rule.approve")==true)TextButton(onClick={action="approve";selected=r;reason=""},enabled=m.canUseRecommendationPolicies&&r.textOrNull("createdByEmployeeId")!=m.identity?.employeeId){Text("独立审批")};if(r.getString("status")=="approved"&&m.identity?.allows("recommendation.rule.publish")==true)TextButton(onClick={action="publish";selected=r;reason="";time=""},enabled=m.canUseRecommendationPolicies&&r.textOrNull("createdByEmployeeId")!=m.identity?.employeeId&&r.textOrNull("approvedByEmployeeId")!=m.identity?.employeeId){Text("第三人发布")}}}}
 if(m.recommendationPolicyBoard?.next!=null)item{TextButton(onClick={m.loadRecommendationPolicies(more=true)},enabled=!m.busy){Text("更早版本")}}
 }
 }}}
 if(action.isNotBlank())AlertDialog(onDismissRequest={action=""},title={Text(if(action=="rollout")"顾客开放状态"else "推荐规则操作")},text={Column{selected?.let{Text("${it.getString("code")} 第${it.getInt("version")}版")};if(action=="rollout")AssignmentChoice("开放状态",rollout,recommendationRollouts){rollout=it};if(action=="publish")CustodyField("生效时间（北京时间 YYYY-MM-DD HH:mm）",time,29){time=it};CustodyField("操作依据",reason,500){reason=it};if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error)}},confirmButton={TextButton(onClick={try{val b=JSONObject().put("reason",reason);if(action=="rollout")b.put("rolloutState",rollout);if(action=="publish")b.put("effectiveFrom",performanceTime(time));propose(action,selected,b);if(proposed!=null)action=""}catch(e:Exception){error=e.message?:"请输入有效时间"}}){Text("继续核对")}},dismissButton={TextButton(onClick={action=""}){Text("取消")}})
 proposed?.let{c->AlertDialog(onDismissRequest={proposed=null},title={Text("确认推荐规则操作")},text={Text(c.steps[0].recommendationPolicyProof!!.getString("confirmation"))},confirmButton={TextButton(onClick={proposed=null;editing=false;m.executeLive(c)},enabled=m.canExecuteLive(c)){Text("确认提交")}},dismissButton={TextButton(onClick={proposed=null}){Text("返回")}})}
}
private fun recommendationPercent(n:Int)=java.math.BigDecimal(n).movePointLeft(2).stripTrailingZeros().toPlainString()
@Composable private fun RecommendationDraft(m:AppModel,row:JSONObject?,back:()->Unit,save:(JSONObject)->Unit){
 val defaults=mapOf("preferenceWeight" to 100,"sceneWeight" to 60,"marginWeight" to 50,"priorityWeight" to 50,"performanceWeight" to 0,"inventoryWeight" to 0,"capacityWeight" to 0,"minimumGrossMarginBasisPoints" to 1500,"preferenceHalfLifeDays" to 90,"preferenceMaxAgeDays" to 730,"preferenceMinEffectiveScore" to 1000,"preferenceMinConfidenceBasisPoints" to 2500)
 var values by remember{mutableStateOf(defaults.mapValues{(k,v)->val n=row?.optInt(k,v)?:v;if(k.endsWith("BasisPoints"))recommendationPercent(n)else n.toString()})};var explanation by remember{mutableStateOf(row?.getString("explanationTemplate")?:"按明确偏好、价格与当前可售条件提供建议")};var reason by remember{mutableStateOf("")};var error by remember{mutableStateOf("")}
 Panel{Text("新版本草稿",style=MaterialTheme.typography.titleMedium);TextButton(onClick=back){Text("返回规则列表")};Text("${m.recommendationPolicyBoard?.data?.getString("code")}：保留原问卷与历史策略配置，保存后交由他人审批。")
 for((k,label)in recommendationWeights.take(4))CustodyField("$label（-1000至1000）",values.getValue(k),6){values=values+(k to it)}
 for((k,v)in recommendationLimits)CustodyField(v.first,values.getValue(k),8){values=values+(k to it)}
 OutlinedTextField(explanation,{explanation=it.take(500)},label={Text("顾客可见推荐解释")},minLines=3,maxLines=6,modifier=Modifier.fillMaxWidth());CustodyField("起草原因",reason,500){reason=it};Text("保存不会覆盖历史，也不会自动开放顾客推荐。",style=MaterialTheme.typography.bodySmall);if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error)
 PrimaryAction(onClick={try{val board=m.recommendationPolicyBoard?:error("请读取原规则");val body=JSONObject().put("code",board.data.getString("code")).put("explanationTemplate",explanation).put("reason",reason).put("displayConfiguration",row?.getJSONObject("displayConfiguration")?:board.data.getJSONObject("defaultDisplayConfiguration"));for((k,v)in values)body.put(k,if(k.endsWith("BasisPoints"))java.math.BigDecimal(v).movePointRight(2).intValueExact()else v.toInt());save(body);error=""}catch(e:Exception){error=e.message?:"请核对所有数值"}},enabled=m.canUseRecommendationPolicies){Text("核对并保存草稿")}}
}
