package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import java.util.UUID
import java.time.LocalDate
const val annualPolicyRoot="/api/staff/native-annual-policies"
val annualKinds=listOf("birthday" to "生日礼遇","festival" to "节日礼遇","priority_seating" to "优先订座","daily_snack" to "每日点心")
val annualTiers=listOf("member" to "普通会员","silver" to "银卡","gold" to "金卡")
val annualAlcohol=listOf("not_applicable" to "不涉及酒水","non_alcoholic_only" to "仅无酒精","staff_compliance_required" to "员工核验并配替代品")
val annualInventory=listOf("not_applicable" to "无需库存","strict_recipe" to "正式配方严格扣库")
val annualRevocation=listOf("cancel_before_redeem" to "核销前可取消","expire_only" to "仅到期失效","manual_compensation" to "人工补偿")
val annualFeb=listOf("feb28" to "2月28日","mar01" to "3月1日","leap_year_only" to "仅闰年")
val annualNumeric=linkedMapOf("quantity" to "份数（1至100）","validityDays" to "有效天数（1至366）","windowBeforeDays" to "提前可用天数（0至90）","windowAfterDays" to "延后可用天数（0至90）","memberDailyLimit" to "会员每日上限（1至100）","tableDailyLimit" to "每桌每日上限（1至100）","priority" to "优先级（1至32767，越小越优先）")
val annualBooleans=linkedMapOf("inheritToHigherTiers" to "高等级继承","onSiteOnly" to "仅到店使用","requiresTableSession" to "必须关联桌台","enabled" to "启用此规则")
val annualFields=listOf("ruleCode","title","ruleKind","eligibleTier","benefitDefinitionId","alcoholHandling","stackGroup","inventoryRequirement","revocationPolicy","feb29Policy","reservationHoldMinutes","redemptionHoldMinutes","substitutes")+annualNumeric.keys+annualBooleans.keys
fun newAnnualRule()=JSONObject().put("ruleCode","").put("title","").put("ruleKind","birthday").put("eligibleTier","member").put("benefitDefinitionId","").put("inheritToHigherTiers",true).put("onSiteOnly",true).put("requiresTableSession",true).put("enabled",true).put("quantity",1).put("validityDays",7).put("windowBeforeDays",0).put("windowAfterDays",6).put("memberDailyLimit",1).put("tableDailyLimit",1).put("priority",10).put("alcoholHandling","not_applicable").put("stackGroup","festival_gift").put("inventoryRequirement","not_applicable").put("revocationPolicy","expire_only").put("feb29Policy","feb28").put("reservationHoldMinutes",JSONObject.NULL).put("redemptionHoldMinutes",JSONObject.NULL).put("substitutes",JSONArray())
fun normalizeAnnualRule(raw:JSONObject):JSONObject{val r=JSONObject();for(k in annualFields)r.put(k,raw.get(k));for((k,max)in listOf("ruleCode" to 64,"title" to 120,"stackGroup" to 64)){val v=r.getString(k).trim();require(v.length in (if(k=="ruleCode")3 else 2)..max);r.put(k,v)};require(Regex("^[A-Z][A-Z0-9_]{2,63}$").matches(r.getString("ruleCode")));require(Regex("^[a-z][a-z0-9_.-]{1,63}$").matches(r.getString("stackGroup")));UUID.fromString(r.getString("benefitDefinitionId"))
 for(k in annualNumeric.keys){val n=r.get(k).toString().toInt();val min=if(k.startsWith("window"))0 else 1;val max=when(k){"validityDays"->366;"priority"->32767;"windowBeforeDays","windowAfterDays"->90;else->100};require(n in min..max){"${annualNumeric[k]}超出范围"};r.put(k,n)}
 for(k in annualBooleans.keys)require(r.get(k) is Boolean)
 for((k,choices)in listOf("ruleKind" to annualKinds,"eligibleTier" to annualTiers,"alcoholHandling" to annualAlcohol,"inventoryRequirement" to annualInventory,"revocationPolicy" to annualRevocation))require(r.getString(k) in choices.map{it.first})
 val kind=r.getString("ruleKind");if(kind=="birthday")require(!r.isNull("feb29Policy")&&r.getString("feb29Policy") in annualFeb.map{it.first}){"生日规则必须明确2月29日处理方式"}else require(r.isNull("feb29Policy"));if(kind in listOf("birthday","festival"))require(r.getString("stackGroup")=="festival_gift"){"生日和节日必须使用 festival_gift 叠加组"}
 for((k,requiredKind)in listOf("reservationHoldMinutes" to "priority_seating","redemptionHoldMinutes" to "daily_snack")){if(kind==requiredKind){val n=r.get(k).toString().toInt();require(n in 5..30);r.put(k,n)}else require(r.isNull(k))}
 val subs=r.getJSONArray("substitutes").objects();require(subs.size<=20&&subs.map{it.getString("productId")}.distinct().size==subs.size);r.put("substitutes",JSONArray(subs.map{val id=it.getString("productId");UUID.fromString(id);val n=it.get("priority").toString().toInt();val reason=it.getString("reason").trim();require(n in 1..32767&&reason.length in 2..240);JSONObject().put("productId",id).put("priority",n).put("reason",reason)}))
 if(kind=="priority_seating")require(!r.getBoolean("onSiteOnly")&&!r.getBoolean("requiresTableSession")&&r.getString("inventoryRequirement")=="not_applicable"&&subs.isEmpty()){"优先订座不得要求已到店、已开台或商品库存"}
 if(kind=="daily_snack")require(r.getBoolean("onSiteOnly")&&r.getBoolean("requiresTableSession")&&r.getString("alcoholHandling")=="not_applicable"&&r.getInt("validityDays")==1&&r.getString("inventoryRequirement")=="strict_recipe"&&r.getInt("windowBeforeDays")==0&&r.getInt("windowAfterDays")==0&&r.getInt("quantity")<=minOf(r.getInt("memberDailyLimit"),r.getInt("tableDailyLimit"))){"每日点心须当天到店并关联桌台，数量不得超过每日上限"}
 return r
}
fun annualPolicyCommand(actor:StaffIdentity,board:CouponCalendarsBoard,action:String,row:JSONObject?,input:JSONObject):LiveCommand{
 require(board.enabled&&board.actor==actor.employeeId);val permission="loyalty.annual-benefit."+mapOf("draft" to "manage","approve" to "approve","publish" to "publish","occurrence" to "occurrence.confirm").getValue(action);require(actor.allows(permission));val b=JSONObject(input.toString());val reason=b.getString("reason").trim();require(reason.length in 2..500){"请填写2至500字操作依据"};b.put("reason",reason)
 if(action=="draft"){val code=b.getString("policyCode");require(Regex("^[A-Z][A-Z0-9_]{2,63}$").matches(code)&&board.data.textOrNull("code")==code){"请先读取此政策编号最新版本"};b.put("expectedLatest",board.data.getInt("latest"));java.time.ZoneId.of(b.getString("timezone"));val rules=b.getJSONArray("rules").objects().map(::normalizeAnnualRule);require(rules.size in 1..100&&rules.any{it.getBoolean("enabled")}&&rules.map{it.getString("ruleCode")}.distinct().size==rules.size);val birthday=rules.filter{it.getBoolean("enabled")&&it.getString("ruleKind")=="birthday"};val festival=rules.filter{it.getBoolean("enabled")&&it.getString("ruleKind")=="festival"};require(birthday.isEmpty()||festival.isEmpty()||birthday.maxOf{it.getInt("priority")}<festival.minOf{it.getInt("priority")}){"生日规则须比所有节日规则优先"};require(rules.count{it.getBoolean("enabled")&&it.getString("ruleKind")=="priority_seating"}<=1);b.put("rules",JSONArray(rules))}
 else{require(row!=null&&board.rows.any{it.getString("id")==row.getString("id")&&it.getString("nativeVersion")==row.getString("nativeVersion")}){"原版本已变化，请刷新"};b.put("policyId",row.getString("id")).put("expectedVersion",row.getString("nativeVersion"));when(action){"approve"->require(row.getString("status")=="draft"&&row.getString("draftedByEmployeeId")!=actor.employeeId){"须由其他授权员工审批"};"publish"->{require(row.getString("status")=="approved"&&actor.employeeId !in listOf(row.getString("draftedByEmployeeId"),row.getString("approvedByEmployeeId"))){"发布须与起草、审批分离"};val from=serverInstant(b.getString("effectiveFrom"));require(from>java.time.Instant.now()){"必须安排未来生效时间"};if(!b.isNull("effectiveUntil"))require(serverInstant(b.getString("effectiveUntil"))>from)};"occurrence"->{require(row.getJSONArray("rules").objects().any{it.getString("id")==b.getString("ruleId")&&it.getString("ruleKind")=="festival"&&it.getBoolean("enabled")});val start=LocalDate.parse(b.getString("startsOn"));val end=LocalDate.parse(b.getString("endsOn"));require(b.getInt("cycleYear") in 2020..2200&&start.year==b.getInt("cycleYear")&&end.year==start.year&&end>=start);val ref=b.getString("confirmationReference").trim();require(ref.length in 2..240);b.put("confirmationReference",ref)}}}
 val title=mapOf("draft" to "保存年度权益草稿","approve" to "独立审批年度权益","publish" to "发布年度权益","occurrence" to "确认节日日期").getValue(action);val detail=if(action=="draft")"${b.getString("policyCode")} · ${b.getJSONArray("rules").length()} 条规则 · 新第${b.getInt("expectedLatest")+1}版"else "${row!!.getString("policyCode")} · 原第${row.getInt("version")}版";val extra=when(action){"publish"->"\n生效：${calendarLocal(b.getString("effectiveFrom"))}\n截止：${b.textOrNull("effectiveUntil")?.let(::calendarLocal)?:"长期"}";"occurrence"->"\n${b.getString("startsOn")} 至 ${b.getString("endsOn")}\n${b.getString("confirmationReference")}";else->""};val id=UUID.randomUUID().toString();return LiveCommand(id,actor.employeeId,title,permission,listOf(LiveStep("$annualPolicyRoot/$action",b.toString(),"idempotency-key","native-business-$id",JSONObject().put("annualPolicy",JSONObject().put("employeeId",actor.employeeId).put("action",action).put("before",row?:JSONObject.NULL).put("confirmation","$title\n$detail$extra\n原因：$reason\n生日授权、现场核验和库存条件仍按原规则执行。")).toString())))
}
val LiveStep.annualPolicyProof:JSONObject? get()=recoveryBody?.let{JSONObject(it).optJSONObject("annualPolicy")}
private fun annualComparable(r:JSONObject):String{val p=normalizeAnnualRule(r);p.put("substitutes",JSONArray(p.getJSONArray("substitutes").objects().sortedBy{it.getString("productId")}));return calendarJson(p)}
fun validateAnnualPolicyReply(text:String,s:LiveStep){val r=JSONObject(text);val d=r.getJSONObject("data");val p=s.annualPolicyProof!!;val b=JSONObject(s.body);val action=p.getString("action");val row=d.getJSONObject("row");require(r.getJSONObject("meta").getInt("protocol")==1&&r.getJSONObject("meta").get("replayed") is Boolean&&d.getString("employeeId")==p.getString("employeeId")&&d.getString("requestKey")==s.key&&d.getString("action")==action&&calendarJson(d.getJSONObject("accepted"))==calendarJson(b));UUID.fromString(row.getString("id"))
 if(action=="occurrence"){for(k in b.keys())require(calendarJson(b.get(k))==calendarJson(row.get(k)));require(row.getString("confirmedByEmployeeId")==p.getString("employeeId"));return}
 require(Regex("^[a-f0-9]{64}$").matches(row.getString("nativeVersion")));val before=if(action=="draft")b else p.getJSONObject("before");require(row.getString("policyCode")==before.getString("policyCode")&&row.getString("timezone")==before.getString("timezone"));val old=before.getJSONArray("rules").objects().associateBy{it.getString("ruleCode")};val current=row.getJSONArray("rules").objects();require(old.size==current.size&&current.map{it.getString("ruleCode")}.distinct().size==current.size);for(item in current)require(annualComparable(item)==annualComparable(old[item.getString("ruleCode")]?:error("未知规则")))
 require(row.getString("status")==when(action){"draft"->"draft";"approve"->"approved";else->"published"});if(action=="draft")require(row.getInt("version")==b.getInt("expectedLatest")+1&&row.getString("draftedByEmployeeId")==p.getString("employeeId"))else{require(row.getString("id")==b.getString("policyId")&&row.getInt("version")==before.getInt("version")&&row.getString(if(action=="approve")"approvedByEmployeeId"else "publishedByEmployeeId")==p.getString("employeeId"))};if(action=="publish"){require(serverInstant(row.getString("effectiveFrom"))==serverInstant(b.getString("effectiveFrom")));require(row.isNull("effectiveUntil")==b.isNull("effectiveUntil"));if(!b.isNull("effectiveUntil"))require(serverInstant(row.getString("effectiveUntil"))==serverInstant(b.getString("effectiveUntil")))}
}
