package com.mbox.staff
import org.json.JSONObject
import java.util.UUID
const val socialOperationsRoot="/api/staff/native-social"
val socialKinds=listOf("service_account" to "微信服务号","wecom" to "企业微信")
val socialStates=mapOf("draft" to "草稿","scheduled" to "已安排发送","sending" to "正在交给渠道","accepted" to "渠道已受理，等待送达回调","delivered" to "渠道确认送达","delivery_failed" to "渠道确认送达失败","rejected" to "渠道已拒绝","unknown" to "结果未知，禁止自动重发","cancelled" to "已取消","pending" to "等待处理","processed" to "已处理","failed" to "处理失败")
fun socialCommand(actor:StaffIdentity,board:CouponCalendarsBoard,action:String,row:JSONObject?,input:JSONObject):LiveCommand{
 require(board.enabled&&board.actor==actor.employeeId);require(action in listOf("account","retry","broadcast","transition"));val permission=if(action in listOf("account","retry"))"member.card.manage"else "community.activity.manage";require(actor.allows(permission));val b=JSONObject(input.toString());val reason=b.getString("reason").trim();require(reason.length in 2..500){"请填写操作原因"};b.put("reason",reason)
 if(row!=null){require(board.rows.any{it.getString("id")==row.getString("id")&&it.getString("nativeVersion")==row.getString("nativeVersion")}){"原账号或任务已变化"};b.put("id",row.getString("id")).put("expectedVersion",row.getString("nativeVersion"))}
 when(action){
 "account"->{if(row==null)b.put("expectedVersion",JSONObject.NULL);require(b.getString("kind") in socialKinds.map{it.first});val name=b.getString("name").trim();require(name.length in 1..80);b.put("name",name);require(Regex("^(wx|ww)[A-Za-z0-9_-]{4,126}$").matches(b.getString("appId"))){"请输入平台的正确账号AppID"};if(row!=null)require(b.getString("kind")==row.getString("kind")&&b.getString("appId")==row.getString("appId")){"已建账号不能更换主体"};val credentials=b.optJSONObject("credentials");require(row!=null||credentials!=null){"新账号必须配置完整密钥"};credentials?.let{require(it.getString("secret").length in 8..256&&Regex("^[A-Za-z0-9]{3,32}$").matches(it.getString("token"))&&Regex("^[A-Za-z0-9]{43}$").matches(it.getString("encodingAesKey"))){"密钥三项须完整，不可仅更新其中一项"}};for(k in listOf("codeDataKey","reminderDataKey"))require(Regex("^[a-z_]+[0-9]+$").matches(b.getString(k)));for(k in listOf("codeTemplateId","reminderTemplateId"))require((b.textOrNull(k)?.length?:0)<=128);b.getBoolean("enabled")}
 "retry"->require(row!=null&&row.getString("status")=="failed"){"只能重试失败回调事件"}
 "broadcast"->{UUID.fromString(b.getString("accountId"));val title=b.getString("title").trim();val content=b.getString("content").trim();require(title.length in 1..80&&content.length in 1..600&&content.toByteArray(Charsets.UTF_8).size<=1800){"标题最多80字，内容最多600字且不超过1800字节"};b.put("title",title).put("content",content);serverInstant(b.getString("scheduledAt"))}
 "transition"->{require(row!=null);when(b.getString("action")){"schedule"->require(row.getString("status")=="draft"&&b.getBoolean("audienceConfirmed")){"必须核对全部关注者范围"};"cancel"->require(row.getString("status") in listOf("draft","scheduled")){"任务已交给渠道，不能撤回"};else->error("未知群发操作")}}
 }
 val label=when(action){"account"->"保存微信账号配置";"retry"->"重试失败回调处理";"broadcast"->"建立群发草稿";else->if(b.getString("action")=="schedule")"安排服务号群发"else "取消未发送群发"};val details=when(action){"account"->"${b.getString("name")} · ${socialKinds.toMap()[b.getString("kind")]}\n${b.getString("appId")}\n${if(b.getBoolean("enabled"))"启用"else "停用"} · ${if(b.has("credentials"))"更新完整密钥"else "保留原密钥"}\n停用可能暂停相关歌迷卡权益；保存配置不等于平台连通。";"broadcast"->"${b.getString("title")}\n${b.getString("content")}\n${calendarLocal(b.getString("scheduledAt"))}\n保存草稿不会开始发送。";"retry"->"${row!!.getString("accountName")} · ${row.getString("eventType")}\n只重新处理这条平台回调，不能伪造关注或送达。";else->"${row!!.getString("accountName")} · ${row.getString("title")}\n${row.getString("content")}\n"+(if(b.getString("action")=="schedule")"${calendarLocal(row.getString("scheduledAt"))} 面向该服务号全部关注者。渠道受理与送达分别核对。"else "取消尚未交给渠道的原任务。")};val id=UUID.randomUUID().toString();return LiveCommand(id,actor.employeeId,label,permission,listOf(LiveStep("$socialOperationsRoot/$action",b.toString(),"idempotency-key","native-business-$id",JSONObject().put("socialOperations",JSONObject().put("employeeId",actor.employeeId).put("action",action).put("before",row?:JSONObject.NULL).put("confirmation","$label\n$details\n原因：$reason")).toString())))
}
val LiveStep.socialOperationsProof:JSONObject? get()=recoveryBody?.let{JSONObject(it).optJSONObject("socialOperations")}
fun secureSocialCommand(command:LiveCommand,store:(String,String)->Unit):LiveCommand{val step=command.steps.firstOrNull()?:return command;val p=step.socialOperationsProof?:return command;require(command.steps.size==1);if(p.has("payloadKey"))return command;store(command.id,step.body);p.remove("confirmation");return command.copy(title="待核对微信运营原请求",steps=listOf(step.copy(body="{}",recoveryBody=JSONObject().put("socialOperations",p.put("payloadKey",command.id)).toString())))}
fun validateSocialReply(text:String,s:LiveStep,body:JSONObject){val r=JSONObject(text);val d=r.getJSONObject("data");val p=s.socialOperationsProof!!;val action=p.getString("action");val expected=JSONObject(body.toString());if(action=="account"){expected.put("credentialsChanged",expected.has("credentials"));expected.remove("credentials")};require(r.getJSONObject("meta").getInt("protocol")==1&&r.getJSONObject("meta").get("replayed") is Boolean&&d.getString("employeeId")==p.getString("employeeId")&&d.getString("requestKey")==s.key&&d.getString("action")==action&&calendarJson(d.getJSONObject("accepted"))==calendarJson(expected));val row=d.getJSONObject("row");require(Regex("^[a-f0-9]{64}$").matches(row.getString("nativeVersion")));val before=p.optJSONObject("before");when(action){"account"->{UUID.fromString(row.getString("id"));if(body.has("id"))require(row.getString("id")==body.getString("id"));for(k in listOf("kind","name","appId","enabled","codeTemplateId","codeDataKey","reminderTemplateId","reminderDataKey"))require(calendarJson(row.get(k))==calendarJson(body.get(k)))};"retry"->{require(row.getString("id")==body.getString("id")&&row.getString("status")=="pending"&&row.isNull("errorCode"));for(k in listOf("accountId","eventType","receivedAt"))require(row.getString(k)==before!!.getString(k))};"broadcast"->{for(k in listOf("accountId","title","content"))require(row.getString(k)==body.getString(k));require(serverInstant(row.getString("scheduledAt"))==serverInstant(body.getString("scheduledAt"))&&row.getString("status")=="draft"&&row.getString("createdByEmployeeId")==p.getString("employeeId"))};"transition"->{require(row.getString("id")==body.getString("id")&&row.getString("status")==if(body.getString("action")=="schedule")"scheduled"else "cancelled");for(k in listOf("accountId","title","content","scheduledAt"))require(row.getString(k)==before!!.getString(k))}}}
