package com.mbox.staff
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import kotlinx.coroutines.launch
import org.json.JSONObject
import org.json.JSONArray
private val activityTextFields=listOf("title","summary","assemblyLocation","paymentRuleText","safetyPolicyVersion","safetyAcknowledgementText","refundPolicyVersion","refundPolicySummary","activityDetails","contactInstructions","memberBenefitText")
private val activityListFields=listOf("safetyRequirements","includedItems","participationRequirements")
fun activityEditor(row:JSONObject?):JSONObject{val f=JSONObject().put("kind",row?.getString("kind")?:"member_night").put("coverUrl",row?.textOrNull("coverUrl")?:"").put("capacity",(row?.getInt("capacity")?:30).toString()).put("feeYuan",row?.getLong("feeAmountMinor")?.let(::activityYuan)?:"0").put("depositYuan",row?.getLong("depositAmountMinor")?.let(::activityYuan)?:"0").put("paymentMode",row?.getString("paymentMode")?:"none").put("feeBasis",row?.getString("feeBasis")?:"per_person").put("paymentDeadlineMinutes",(row?.getInt("paymentDeadlineMinutes")?:30).toString()).put("visibility",row?.getString("visibility")?:"public").put("audienceMemberLevels",row?.getJSONArray("audienceMemberLevels")?:JSONArray()).put("audienceLifecycleStages",row?.getJSONArray("audienceLifecycleStages")?:JSONArray()).put("packageSelectionRequired",row?.getBoolean("packageSelectionRequired")?:false).put("packages",JSONArray(row?.getJSONArray("packages")?.objects()?.map(::activityPackageEditor)?:emptyList<JSONObject>())).put("reason","");for(k in activityTextFields)f.put(k,row?.textOrNull(k)?:"");for(k in activityListFields)f.put(k,row?.getJSONArray(k)?.strings()?.joinToString("\n")?:"");for(k in listOf("startsAt","endsAt"))f.put(k,row?.getString(k)?.let(::calendarLocal)?:"");return f}
private fun activityYuan(n:Long)=java.math.BigDecimal(n).movePointLeft(2).toPlainString()
private fun lines(text:String)=JSONArray(text.lines().map{it.trim()}.filter{it.isNotEmpty()})
fun activityDraftFromEditor(f:JSONObject):JSONObject{val b=JSONObject().put("kind",f.getString("kind")).put("coverUrl",f.getString("coverUrl").trim().ifBlank{null}?:JSONObject.NULL).put("capacity",f.getString("capacity").toInt()).put("feeAmountMinor",giftMoney(f.getString("feeYuan"))).put("depositAmountMinor",giftMoney(f.getString("depositYuan"))).put("feeBasis",f.getString("feeBasis")).put("paymentMode",f.getString("paymentMode")).put("paymentDeadlineMinutes",f.getString("paymentDeadlineMinutes").toInt()).put("pointsReward",0).put("visibility",f.getString("visibility")).put("audienceMemberLevels",JSONArray(f.getJSONArray("audienceMemberLevels").strings().distinct().sorted())).put("audienceLifecycleStages",JSONArray(f.getJSONArray("audienceLifecycleStages").strings().distinct().sorted())).put("packageSelectionRequired",f.getBoolean("packageSelectionRequired")).put("packages",JSONArray(f.getJSONArray("packages").objects().mapIndexed{i,p->activityPackageBody(p,i)})).put("reason",f.getString("reason").trim());for(k in activityTextFields){val v=f.getString(k).trim();b.put(k,if(k=="memberBenefitText"&&v.isEmpty())JSONObject.NULL else v)};for(k in activityListFields)b.put(k,lines(f.getString(k)));for(k in listOf("startsAt","endsAt"))b.put(k,performanceTime(f.getString(k)));return b}
private val packageStrings=listOf("name","description","paymentRuleText","redemptionPolicyVersion","refundPolicyVersion")
fun activityPackageEditor(row:JSONObject?):JSONObject{val f=JSONObject().put("capacity",(row?.getInt("capacity")?:1).toString()).put("memberPurchaseLimit",(row?.getInt("memberPurchaseLimit")?:1).toString()).put("feeYuan",row?.getLong("feeAmountMinor")?.let(::activityYuan)?:"0").put("depositYuan",row?.getLong("depositAmountMinor")?.let(::activityYuan)?:"0").put("feeBasis",row?.getString("feeBasis")?:"per_person").put("paymentMode",row?.getString("paymentMode")?:"none").put("paymentDeadlineMinutes",(row?.getInt("paymentDeadlineMinutes")?:30).toString()).put("includedItems",row?.getJSONArray("includedItems")?.strings()?.joinToString("\n")?:"").put("imageUrl",row?.textOrNull("imageUrl")?:"").put("components",row?.getJSONArray("components")?:JSONArray());for(k in packageStrings)f.put(k,row?.textOrNull(k)?:"");for(k in listOf("availableFrom","availableUntil"))f.put(k,row?.textOrNull(k)?.let(::calendarLocal)?:"");return f}
private fun activityPackageBody(f:JSONObject,index:Int):JSONObject{val b=JSONObject().put("imageUrl",f.getString("imageUrl").trim().ifBlank{null}?:JSONObject.NULL).put("includedItems",lines(f.getString("includedItems"))).put("capacity",f.getString("capacity").toInt()).put("memberPurchaseLimit",f.getString("memberPurchaseLimit").toInt()).put("feeAmountMinor",giftMoney(f.getString("feeYuan"))).put("depositAmountMinor",giftMoney(f.getString("depositYuan"))).put("feeBasis",f.getString("feeBasis")).put("paymentMode",f.getString("paymentMode")).put("paymentDeadlineMinutes",f.getString("paymentDeadlineMinutes").toInt()).put("sortOrder",index).put("components",JSONArray(f.getJSONArray("components").objects().map{val qty=java.math.BigDecimal(it.getString("quantity").trim());require(qty.signum()>0&&qty.scale()<=6){"物料数量须为正数，最多六位小数"};JSONObject().put("inventoryItemId",it.getString("inventoryItemId")).put("quantity",qty.stripTrailingZeros().toPlainString()).put("perParticipant",it.getBoolean("perParticipant"))}));for(k in packageStrings){val v=f.getString(k).trim();b.put(k,if(k.endsWith("Version")&&v.isBlank())JSONObject.NULL else v)};for(k in listOf("availableFrom","availableUntil"))b.put(k,if(f.getString(k).isBlank())JSONObject.NULL else performanceTime(f.getString(k)));return b}
@Composable fun ActivityDraftEditor(m:AppModel,row:JSONObject?,back:()->Unit,save:(JSONObject)->Unit){
 var f by remember{mutableStateOf(activityEditor(row))};var error by remember{mutableStateOf("")};var image by remember{mutableStateOf(false)};var pack by remember{mutableStateOf<Int?>(null)};fun change(k:String,v:Any){f=JSONObject(f.toString()).put(k,v)}
 if(image)LiveMediaAssetPicker(m,"community_activity",{image=false}){change("coverUrl",it);image=false}
 pack?.let{i->ActivityPackageEditor(m,f.getJSONArray("packages").getJSONObject(i),{pack=null}){p->change("packages",JSONArray(f.getJSONArray("packages").objects().mapIndexed{j,old->if(i==j)p else old}));pack=null}}
 Panel{Text(if(row==null)"新建活动草稿"else "编辑未发布活动",style=MaterialTheme.typography.titleLarge);TextButton(onClick=back){Text("返回活动")};AssignmentChoice("活动类型",f.getString("kind"),activityKinds){change("kind",it)};CustodyField("活动名称",f.getString("title"),120){change("title",it)};ActivityMultiline("列表摘要",f.getString("summary"),600){change("summary",it)};ActivityImage(m,f.getString("coverUrl"),{image=true}){change("coverUrl","")};for((k,label)in listOf("startsAt" to "开始时间","endsAt" to "结束时间"))CustodyField("$label（北京时间 YYYY-MM-DD HH:mm）",f.getString(k),29){change(k,it)};CustodyField("集合地点",f.getString("assemblyLocation"),240){change("assemblyLocation",it)};CustodyField("人数上限（1至1000）",f.getString("capacity"),4){change("capacity",it)}
 ActivityPaymentEditor(f,::change)
 AssignmentChoice("可见范围",f.getString("visibility"),listOf("public" to "公开","member" to "所有会员","segment" to "指定客群")){change("visibility",it);if(it!="segment"){change("audienceMemberLevels",JSONArray());change("audienceLifecycleStages",JSONArray())}}
 if(f.getString("visibility")=="segment")for((k,choices)in listOf("audienceMemberLevels" to homeContentLevels,"audienceLifecycleStages" to homeContentStages)){Text(if(k=="audienceMemberLevels")"会员等级"else "会员阶段");for((value,label)in choices){val selected=f.getJSONArray(k).strings();Row{Checkbox(value in selected,{checked->change(k,JSONArray(if(checked)selected+value else selected-value))});Text(label)}}}
 ActivityMultiline("活动详情（至少10字）",f.getString("activityDetails"),4000){change("activityDetails",it)};ActivityMultiline("费用包含（每行一项）",f.getString("includedItems"),50100){change("includedItems",it)};ActivityMultiline("参与条件（每行一项）",f.getString("participationRequirements"),50100){change("participationRequirements",it)};ActivityMultiline("联系与集合说明",f.getString("contactInstructions"),1200){change("contactInstructions",it)};ActivityMultiline("会员权益与赠送（可留空）",f.getString("memberBenefitText"),1000){change("memberBenefitText",it)}
 Text("安全与退款承诺",style=MaterialTheme.typography.titleMedium);CustodyField("安全规则版本",f.getString("safetyPolicyVersion"),64){change("safetyPolicyVersion",it)};ActivityMultiline("顾客需要确认的安全文案",f.getString("safetyAcknowledgementText"),1000){change("safetyAcknowledgementText",it)};ActivityMultiline("安全要求（至少一项，每行一项）",f.getString("safetyRequirements"),25050){change("safetyRequirements",it)};CustodyField("退款规则版本",f.getString("refundPolicyVersion"),64){change("refundPolicyVersion",it)};ActivityMultiline("退款说明",f.getString("refundPolicySummary"),500){change("refundPolicySummary",it)}
 Text("活动套餐（最多20档）",style=MaterialTheme.typography.titleMedium);Row{Checkbox(f.getBoolean("packageSelectionRequired"),{change("packageSelectionRequired",it)});Text("报名必须选择套餐")};for((i,p)in f.getJSONArray("packages").objects().withIndex()){Text("${i+1}. ${p.optString("name").ifBlank{"未命名套餐"}} · ${p.getString("feeYuan")} 元");Row{TextButton(onClick={pack=i}){Text("编辑套餐")};TextButton(onClick={val rows=f.getJSONArray("packages").objects().toMutableList();val prev=rows[i-1];rows[i-1]=rows[i];rows[i]=prev;change("packages",JSONArray(rows))},enabled=i>0){Text("上移")};TextButton(onClick={change("packages",JSONArray(f.getJSONArray("packages").objects().filterIndexed{j,_->i!=j}))}){Text("移除")}}};TextButton(onClick={val all=f.getJSONArray("packages").objects();change("packages",JSONArray(all+activityPackageEditor(null)));pack=all.size},enabled=f.getJSONArray("packages").length()<20){Text("增加一档套餐")};Text("活动积分奖励当前停用。保存草稿不发布；发布后不能直接改写原承诺。",style=MaterialTheme.typography.bodySmall);CustodyField("起草 / 修改原因",f.getString("reason"),500){change("reason",it)};if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error);PrimaryAction(onClick={try{save(activityDraftFromEditor(f));error=""}catch(e:Exception){error=e.message?:"请核对时间、人数与金额"}},enabled=m.canUseActivityOperations){Text("核对并保存草稿")}}
}
@Composable private fun ActivityPaymentEditor(f:JSONObject,change:(String,Any)->Unit){
 CustodyField("费用（元，最多两位小数）",f.getString("feeYuan"),12){change("feeYuan",it)};AssignmentChoice("计价方式",f.getString("feeBasis"),listOf("per_person" to "每位顾客","per_registration" to "每笔报名")){change("feeBasis",it)};AssignmentChoice("预付方式",f.getString("paymentMode"),activityPaymentModes){change("paymentMode",it)};CustodyField("订金（元，无需订金填0）",f.getString("depositYuan"),12){change("depositYuan",it)};CustodyField("付款时限（5至1440分钟）",f.getString("paymentDeadlineMinutes"),4){change("paymentDeadlineMinutes",it)};ActivityMultiline("付款说明",f.getString("paymentRuleText"),240){change("paymentRuleText",it)}
}
@Composable private fun ActivityMultiline(label:String,value:String,max:Int,change:(String)->Unit){OutlinedTextField(value,{change(it.take(max))},label={Text(label)},minLines=2,maxLines=6,modifier=Modifier.fillMaxWidth())}
@Composable private fun ActivityImage(m:AppModel,url:String,choose:()->Unit,remove:()->Unit){if(url.isNotBlank())url.substringAfterLast('/').takeIf{Regex("^MA[0-9A-F]{32}$").matches(it)}?.let{MediaAssetThumbnail(m,it)};Row{TextButton(onClick=choose){Text("选择或上传图片")};if(url.isNotBlank())TextButton(onClick=remove){Text("移除图片")}}}
@Composable private fun ActivityPackageEditor(m:AppModel,original:JSONObject,close:()->Unit,save:(JSONObject)->Unit){
 var f by remember{mutableStateOf(JSONObject(original.toString()))};var image by remember{mutableStateOf(false)};var search by remember{mutableStateOf("")};var options by remember{mutableStateOf<List<JSONObject>>(emptyList())};var next by remember{mutableStateOf<String?>(null)};var loading by remember{mutableStateOf(false)};var generation by remember{mutableStateOf(0)};var error by remember{mutableStateOf("")};var names by remember{mutableStateOf<Map<String,String>>(m.activityOperationsDetail?.data?.optJSONArray("componentItems")?.objects()?.associate{it.getString("id") to "${it.getString("name")}（${it.getString("baseUnit")}）"}?:emptyMap())};val scope=rememberCoroutineScope()
 fun change(k:String,v:Any){f=JSONObject(f.toString()).put(k,v)}
 fun load(more:Boolean=false){if(loading)return;loading=true;val ticket=generation;scope.launch{try{val b=m.activityComponentOptions(search,if(more)next else null);if(ticket==generation){options=(if(more)options+b.rows else b.rows).distinctBy{it.getString("id")};next=b.next;names=names+b.rows.associate{it.getString("id") to "${it.getString("name")}（${it.getString("baseUnit")}）"};error=""}}catch(e:Exception){if(ticket==generation)error=e.message?:"物料读取失败"}finally{loading=false}}}
 if(image)LiveMediaAssetPicker(m,"community_activity",{image=false}){change("imageUrl",it);image=false}
 Dialog(onDismissRequest=close,properties=DialogProperties(usePlatformDefaultWidth=false)){Surface(Modifier.fillMaxSize(),color=Paper){LazyColumn(Modifier.safeDrawingPadding().imePadding().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Row{Text("活动套餐",Modifier.weight(1f),style=MaterialTheme.typography.titleLarge);TextButton(onClick=close){Text("返回")}};CustodyField("套餐名称",f.getString("name"),120){change("name",it)};ActivityMultiline("套餐说明",f.getString("description"),1000){change("description",it)};ActivityImage(m,f.getString("imageUrl"),{image=true}){change("imageUrl","")};ActivityMultiline("套餐包含（每行一项）",f.getString("includedItems"),50100){change("includedItems",it)};CustodyField("套餐名额（不能超过活动总人数）",f.getString("capacity"),4){change("capacity",it)};CustodyField("每会员限购（1至20）",f.getString("memberPurchaseLimit"),2){change("memberPurchaseLimit",it)};ActivityPaymentEditor(f,::change);CustodyField("取用规则版本（可留空）",f.getString("redemptionPolicyVersion"),64){change("redemptionPolicyVersion",it)};CustodyField("退款规则版本（可留空）",f.getString("refundPolicyVersion"),64){change("refundPolicyVersion",it)};for((k,label)in listOf("availableFrom" to "开售时间","availableUntil" to "停售时间"))CustodyField("$label（北京时间，可留空）",f.getString(k),29){change(k,it)};Text("实物物料：报名占用，原套餐交付时扣减；未关联物料的套餐不产生库存领取记录。",style=MaterialTheme.typography.bodySmall)}
 for((i,c)in f.getJSONArray("components").objects().withIndex())item{Panel{Text(names[c.getString("inventoryItemId")]?:"原物料 ${c.getString("inventoryItemId").takeLast(8)}");fun patch(k:String,v:Any){change("components",JSONArray(f.getJSONArray("components").objects().mapIndexed{j,r->if(i==j)JSONObject(r.toString()).put(k,v)else r}))};CustodyField("数量（基本单位）",c.getString("quantity"),20){patch("quantity",it)};Row{Checkbox(c.getBoolean("perParticipant"),{patch("perParticipant",it)});Text("按参加人数计量")};TextButton(onClick={change("components",JSONArray(f.getJSONArray("components").objects().filterIndexed{j,_->j!=i}))}){Text("移除此物料")}}}
 item{CustodyField("查找物料名称或SKU",search,80){search=it;generation++;options=emptyList();next=null};TextButton(onClick={load()},enabled=!loading&&!m.busy){Text(if(loading)"查询中"else "查询物料")};for(o in options)TextButton(onClick={change("components",JSONArray(f.getJSONArray("components").objects()+JSONObject().put("inventoryItemId",o.getString("id")).put("quantity","1").put("perParticipant",true)))},enabled=f.getJSONArray("components").length()<100&&f.getJSONArray("components").objects().none{it.getString("inventoryItemId")==o.getString("id")}){Text("${o.getString("name")} · ${o.getString("sku")} · ${o.getString("baseUnit")}")};if(next!=null)TextButton(onClick={load(true)},enabled=!loading){Text("更多物料")};if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error);PrimaryAction(onClick={try{activityPackageBody(f,0);save(f);error=""}catch(e:Exception){error=e.message?:"请核对套餐输入"}},enabled=!loading&&!m.busy){Text("保留到活动草稿")}}
 }}}
}
