package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import java.util.UUID
const val activityOperationsRoot="/api/staff/native-activity-operations"
val activityKinds=listOf("member_night" to "会员之夜","hike" to "徒步","camping" to "露营","city_walk" to "城市漫步","music_picnic" to "音乐野餐","proposal" to "活动提案","other" to "其他")
val activityPaymentModes=listOf("none" to "无需预付","deposit_optional" to "可选订金","deposit_required" to "必须付订金","full_required" to "必须全额预付")
val activityOperationsLabels=mapOf("create" to "新建活动草稿","update" to "修改活动草稿","publish" to "独立发布活动","stop-registration" to "停止新报名","close" to "结束或取消活动","package-pause" to "暂停套餐报名","package-resume" to "恢复套餐报名","waitlist-retry" to "重试原候补任务","check-in" to "确认顾客到场","fulfill-package" to "登记套餐实物已领取","no-show" to "标记未到","cancel-registration" to "取消未付款报名","refund-request" to "申请原活动付款退款")
val activityStates=mapOf("draft" to "草稿","published" to "已发布","full" to "名额已满","cancelled" to "已取消","completed" to "已结束")
val registrationStates=mapOf("reserved" to "已预留","payment_pending" to "待付款","confirmed" to "已确认","waitlisted" to "候补中","cancelled" to "已取消","checked_in" to "已到场","no_show" to "未到场","refunded" to "已退款")
fun activityOperationsCommand(actor:StaffIdentity,board:CouponCalendarsBoard,action:String,activity:JSONObject?,registration:JSONObject?,input:JSONObject):LiveCommand{
 require(board.enabled&&board.actor==actor.employeeId&&activityOperationsLabels.containsKey(action));val permission=if(action=="publish")"community.activity.publish"else "community.activity.manage";require(actor.allows(permission)){"当前岗位无此项活动权限"};val b=JSONObject(input.toString());val reason=b.getString("reason").trim();require(reason.length in 2..500){"请输入操作原因"};b.put("reason",reason)
 if(action!="create"){require(activity!=null);b.put("publicId",activity.getString("publicId"));val target=if(action in listOf("check-in","fulfill-package","no-show","cancel-registration","refund-request"))registration?:error("请选择原报名")else activity;b.put("expectedVersion",target.getString("nativeVersion"));if(registration!=null)b.put("registrationPublicId",registration.getString("publicId"));if(action=="update")require(activity.getString("status")=="draft"){"活动已发布，不能改写原承诺"};if(action=="publish")require(activity.getString("status")=="draft"&&activity.getString("createdByEmployeeId")!=actor.employeeId){"必须由另一位授权员工发布"}}
 if(action in listOf("create","update")){require(b.getString("title").trim().length in 2..120&&b.getString("summary").trim().length in 2..600);require(b.getInt("capacity") in 1..1000);require(serverInstant(b.getString("endsAt"))>serverInstant(b.getString("startsAt"))){"结束时间必须晚于开始"};require(b.getJSONArray("packages").length()<=20);if(b.getBoolean("packageSelectionRequired"))require(b.getJSONArray("packages").length()>0){"套餐必选时至少建立一档"};activityValidateMoney(b);for(p in b.getJSONArray("packages").objects()){activityValidateMoney(p);require(p.getInt("capacity") in 1..b.getInt("capacity"));require(p.getJSONArray("components").length()<=100)}}
 if(action=="refund-request"){require(actor.allows("refund.request")&&registration!=null&&registration.getLong("refundableAmountMinor")>0&&registration.textOrNull("authoritativePaymentStatus") in listOf("succeeded","partially_refunded")){"请核对原付款、可退金额和申请权限"};b.put("paymentId",registration.getString("paymentId")).put("expectedAmountMinor",registration.getLong("refundableAmountMinor"))}
 if(action=="cancel-registration")require(registration!!.getString("paymentStatus")!="paid"&&registration.textOrNull("authoritativePaymentStatus") !in listOf("succeeded","partially_refunded")){"已付款报名请走原退款流程"}
 val id=UUID.randomUUID().toString();val label=activityOperationsLabels.getValue(action);return LiveCommand(id,actor.employeeId,label,permission,listOf(LiveStep("$activityOperationsRoot/commands/$action",b.toString(),"idempotency-key","native-business-$id",JSONObject().put("activityOperations",JSONObject().put("employeeId",actor.employeeId).put("action",action).put("before",activity?:JSONObject.NULL).put("registration",registration?:JSONObject.NULL).put("confirmation","$label：${activity?.getString("title")?:b.getString("title")}\n"+(registration?.let{"顾客：${it.getString("customerLabel")} · ${it.getInt("partySize")}人\n"}?:"")+"原因：$reason"+when(action){"refund-request"->"\n申请原付款剩余可退 ${historyMoney(b.getLong("expectedAmountMinor"))}；之后还须由其他授权人复核和执行，不表示已退到账。";"fulfill-package"->"\n确认实物已经交付，将按原套餐物料扣减库存，不可重复领取。";"waitlist-retry"->"\n仅推进既有候补任务，不保证有可用名额。";"publish"->"\n发布后费用、时间、权益、安全与退款承诺不能直接改写。";else->""})).toString())))
}
private fun activityValidateMoney(b:JSONObject){val fee=b.getLong("feeAmountMinor");val deposit=b.getLong("depositAmountMinor");require(fee in 0..100000000&&deposit in 0..fee){"费用/订金无效或订金超过费用"};require(b.getInt("paymentDeadlineMinutes") in 5..1440);when(b.getString("paymentMode")){"none"->require(deposit==0L);"deposit_optional","deposit_required"->require(fee>0&&deposit>0);"full_required"->require(fee>0&&deposit==0L);else->error("请选择预付方式")}}
val LiveStep.activityOperationsProof:JSONObject? get()=recoveryBody?.let{JSONObject(it).optJSONObject("activityOperations")}
private fun activityCompare(expected:JSONObject,actual:JSONObject){for(k in expected.keys()){if(k in listOf("reason","expectedVersion","publicId","nativeVersion"))continue;val e=expected.get(k);val a=actual.get(k);if(k in listOf("startsAt","endsAt","availableFrom","availableUntil")&&e!=JSONObject.NULL)require(serverInstant(e.toString())==serverInstant(a.toString())){"活动排期回执不符"}else if(k=="quantity")require(java.math.BigDecimal(e.toString()).compareTo(java.math.BigDecimal(a.toString()))==0)else if(e is JSONArray&&k in listOf("packages","components")){val rows=e.objects();val other=(a as JSONArray).objects();require(rows.size==other.size);for(i in rows.indices)activityCompare(rows[i],other[i])}else require(calendarJson(e)==calendarJson(a)){"活动回执字段 $k 与原提交不符"}}}
fun validateActivityOperationsReply(text:String,s:LiveStep){val r=JSONObject(text);val d=r.getJSONObject("data");val p=s.activityOperationsProof!!;val b=JSONObject(s.body);val action=p.getString("action");require(r.getJSONObject("meta").getInt("protocol")==1&&r.getJSONObject("meta").get("replayed") is Boolean&&d.getString("employeeId")==p.getString("employeeId")&&d.getString("action")==action&&d.getString("requestKey")==s.key);val row=d.getJSONObject("row");require(Regex("^[a-f0-9]{64}$").matches(row.getString("nativeVersion")));when(action){"refund-request"->{require(row.getString("paymentId")==b.getString("paymentId")&&row.getLong("amountMinor")==b.getLong("expectedAmountMinor")&&row.getString("status")=="requested"&&row.getString("requestedByEmployeeId")==p.getString("employeeId")&&row.getString("reason")==b.getString("reason")&&row.getString("currency")==p.getJSONObject("registration").getString("currency"))};"create","update"->{activityCompare(b,row);require(row.getString("status")=="draft");if(action=="update")require(row.getString("publicId")==b.getString("publicId"))};"waitlist-retry"->{require(row.getString("activityPublicId")==b.getString("publicId")&&row.getString("state") in listOf("queued","not_required"));if(row.getString("state")=="queued")serverInstant(row.getString("nextAttemptAt"))};"check-in","fulfill-package","no-show","cancel-registration"->{val before=p.getJSONObject("registration");require(row.getString("publicId")==b.getString("registrationPublicId")&&row.getString("customerPublicId")==before.getString("customerPublicId")&&row.getInt("partySize")==before.getInt("partySize"));require(if(action=="fulfill-package")row.getString("packageFulfillmentStatus")=="delivered"else row.getString("status")==mapOf("check-in" to "checked_in","no-show" to "no_show","cancel-registration" to "cancelled")[action])};else->{require(row.getString("publicId")==b.getString("publicId"));when(action){"publish"->require(row.getString("status")=="published"&&row.getString("approvedByEmployeeId")==p.getString("employeeId"));"stop-registration"->serverInstant(row.getString("registrationClosedAt"));"close"->require(row.getString("status")==b.getString("status"));"package-pause","package-resume"->require(row.getJSONArray("packages").objects().single{it.getString("publicId")==b.getString("packagePublicId")}.getString("status")==if(action=="package-pause")"paused"else "published")}}}}
