package com.mbox.staff
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import kotlinx.coroutines.launch
import org.json.JSONObject
import org.json.JSONArray
@Composable fun LiveHomeContentView(m:AppModel,close:()->Unit){
 val access=remember{m.priorityAccessKey};val workspace=remember{m.workspaceVersion};var search by remember{mutableStateOf("")};var edit by remember{mutableStateOf<JSONObject?>(null)};var creating by remember{mutableStateOf(false)};var decision by remember{mutableStateOf<JSONObject?>(null)};var reason by remember{mutableStateOf("")};var error by remember{mutableStateOf("")};var proposed by remember{mutableStateOf<LiveCommand?>(null)}
 LaunchedEffect(Unit){m.loadHomeContent()};LaunchedEffect(m.priorityAccessKey,m.workspaceVersion){if(access!=m.priorityAccessKey||workspace!=m.workspaceVersion)close()};if(access!=m.priorityAccessKey||workspace!=m.workspaceVersion)return
 fun propose(action:String,row:JSONObject?,body:JSONObject){try{val b=m.homeContentBoard?:error("请读取原内容");proposed=homeContentCommand(m.identity!!,CouponCalendarsBoard(JSONObject(b.data.toString()).put("rows",JSONArray(m.homeContentRows))),action,row,body);error=""}catch(e:Exception){error=e.message?:"请核对输入"}}
 Dialog(onDismissRequest=close,properties=DialogProperties(usePlatformDefaultWidth=false)){Surface(Modifier.fillMaxSize(),color=Paper){LazyColumn(Modifier.safeDrawingPadding().imePadding().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
 item{Row{Text("首页内容",Modifier.weight(1f),style=MaterialTheme.typography.titleLarge);TextButton(onClick=close){Text("关闭")}};LivePendingView(m);Text(m.homeContentState);if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error)}
 if(creating||edit!=null){item{key(edit?.getString("nativeVersion"),creating){HomeContentEditor(m,edit,{edit=null;creating=false}){body->propose(if(creating)"create"else "update",edit,body)}}}}
 else{
 item{CustodyField("搜索标题或内容编号",search,80){search=it};Row{TextButton(onClick={m.loadHomeContent(search)},enabled=!m.busy){Text("查询 / 刷新")};if(m.identity?.allows("community.activity.manage")==true)TextButton(onClick={creating=true},enabled=m.canUseHomeContent){Text("新建内容草稿")}};Text("发布内容先暂停再编辑。排期按北京时间；所有操作均留下原记录。",style=MaterialTheme.typography.bodySmall)}
 items(m.homeContentRows,key={it.getString("code")}){row->Panel{Text(row.getString("title"),style=MaterialTheme.typography.titleMedium);Text("${homeContentStatuses[row.getString("status")]?:row.getString("status")} · ${homeContentTypes.toMap()[row.getString("type")]} · ${row.getString("code")}");Text(row.getString("summary"));Text("${calendarLocal(row.getString("validFrom"))} 至 ${calendarLocal(row.getString("validUntil"))}");Text("${if(row.getString("displayMode")=="pinned")"固定展示"else "轮播展示"} · 顺序 ${row.getInt("priority")} · "+mapOf("public" to "公开","member" to "所有会员","segment" to "指定客群")[row.getString("visibility")]);if(row.getString("visibility")=="segment")Text((row.getJSONArray("audienceMemberLevels").strings().map{homeContentLevels.toMap()[it]?:it}+row.getJSONArray("audienceLifecycleStages").strings().map{homeContentStages.toMap()[it]?:it}).joinToString("、"));row.textOrNull("imageUrl")?.substringAfterLast('/')?.takeIf{Regex("^MA[0-9A-F]{32}$").matches(it)}?.let{MediaAssetThumbnail(m,it)};Text("按键：${row.getString("ctaLabel")} · 目标：${homeContentTargetLabel(row.getString("targetPath"))}");Row{if(m.identity?.allows("community.activity.manage")==true&&row.getString("status") in listOf("draft","paused"))TextButton(onClick={edit=row},enabled=m.canUseHomeContent){Text("编辑草稿")};if(m.identity?.allows("community.activity.publish")==true&&row.getString("status")!="retired")TextButton(onClick={decision=row;reason=""},enabled=m.canUseHomeContent){Text(if(row.getString("status")=="published")"暂停展示"else "核对发布")}}}}
 if(m.homeContentBoard?.next!=null)item{TextButton(onClick={m.loadHomeContent(more=true)},enabled=!m.busy){Text("加载更多内容")}}
 }
 }}}
 decision?.let{row->AlertDialog(onDismissRequest={decision=null},title={Text(if(row.getString("status")=="published")"暂停展示"else "发布所选内容")},text={Column{Text(row.getString("title"));CustodyField("操作原因",reason,500){reason=it}}},confirmButton={TextButton(onClick={propose(if(row.getString("status")=="published")"pause"else "publish",row,JSONObject().put("code",row.getString("code")).put("reason",reason));if(proposed!=null)decision=null}){Text("继续核对")}},dismissButton={TextButton(onClick={decision=null}){Text("返回")}})}
 proposed?.let{c->AlertDialog(onDismissRequest={proposed=null},title={Text("确认首页内容操作")},text={Text(c.steps[0].homeContentProof!!.getString("confirmation"))},confirmButton={TextButton(onClick={proposed=null;creating=false;edit=null;m.executeLive(c)},enabled=m.canExecuteLive(c)){Text("确认提交")}},dismissButton={TextButton(onClick={proposed=null}){Text("返回核对")}})}
}
private val contentTargets=listOf("home" to "首页","reservations" to "预约","order" to "点单","community" to "活动列表","profile" to "会员中心","songs" to "点歌","privacy" to "隐私说明","performances" to "演出","points" to "积分","account" to "账号设置").map{("/pages/${it.first}/index") to it.second}
private fun homeContentTargetLabel(path:String)=contentTargets.toMap()[path]?:if(path.startsWith("/pages/community-detail/index?id="))"指定活动详情"else "已保存目标页面"
@Composable private fun HomeContentEditor(m:AppModel,row:JSONObject?,back:()->Unit,save:(JSONObject)->Unit){
 var f by remember{mutableStateOf(row?.let{JSONObject(it.toString())}?:JSONObject().put("code","").put("type","article").put("title","").put("summary","").put("imageUrl",JSONObject.NULL).put("ctaLabel","查看详情").put("targetPath","/pages/community/index").put("priority",100).put("displayMode","rotation").put("visibility","public").put("audienceMemberLevels",JSONArray()).put("audienceLifecycleStages",JSONArray()))};var start by remember{mutableStateOf(row?.getString("validFrom")?.let(::calendarLocal)?:"")};var end by remember{mutableStateOf(row?.getString("validUntil")?.let(::calendarLocal)?:"")};var priority by remember{mutableStateOf(f.getInt("priority").toString())};var reason by remember{mutableStateOf("")};var error by remember{mutableStateOf("")};var images by remember{mutableStateOf(false)};var activitySearch by remember{mutableStateOf("")};var activityRows by remember{mutableStateOf<List<JSONObject>>(emptyList())};var next by remember{mutableStateOf<String?>(null)};var loading by remember{mutableStateOf(false)};var generation by remember{mutableStateOf(0)};val scope=rememberCoroutineScope()
 fun change(k:String,v:Any){f=JSONObject(f.toString()).put(k,v)}
 fun loadActivities(more:Boolean=false){if(loading)return;loading=true;val ticket=generation;scope.launch{try{val result=m.homeContentActivityOptions(activitySearch,if(more)next else null);if(ticket==generation){activityRows=(if(more)activityRows+result.rows else result.rows).distinctBy{it.getString("id")};next=result.next;error=""}}catch(e:Exception){if(ticket==generation)error=e.message?:"活动查询失败"}finally{loading=false}}}
 if(images)LiveMediaAssetPicker(m,"home_content",{images=false}){change("imageUrl",it);images=false}
 Panel{Text(if(row==null)"新建首页内容"else "编辑：${row.getString("code")}",style=MaterialTheme.typography.titleMedium);TextButton(onClick=back){Text("返回列表")};if(row==null)CustodyField("内容编号",f.getString("code"),64){change("code",it)};AssignmentChoice("内容类型",f.getString("type"),homeContentTypes){change("type",it)};CustodyField("标题",f.getString("title"),120){change("title",it)};OutlinedTextField(f.getString("summary"),{change("summary",it.take(400))},label={Text("摘要，2至400字")},minLines=3,maxLines=6,modifier=Modifier.fillMaxWidth());f.textOrNull("imageUrl")?.substringAfterLast('/')?.takeIf{Regex("^MA[0-9A-F]{32}$").matches(it)}?.let{MediaAssetThumbnail(m,it)};Row{TextButton(onClick={images=true}){Text("从图片库选择 / 上传图片")};if(f.textOrNull("imageUrl")!=null)TextButton(onClick={change("imageUrl",JSONObject.NULL)}){Text("移除图片")}};CustodyField("按键文字",f.getString("ctaLabel"),20){change("ctaLabel",it)};val current=f.getString("targetPath");AssignmentChoice("打开页面",current,contentTargets+(if(current !in contentTargets.map{it.first})listOf(current to "已绑定活动详情，保留原选择")else emptyList())){change("targetPath",it)}
 Foldout("绑定具体活动详情"){CustodyField("活动名称",activitySearch,80){activitySearch=it;generation++;activityRows=emptyList();next=null};TextButton(onClick={loadActivities()},enabled=!loading&&!m.busy){Text(if(loading)"查询中"else "查询可展示活动")};for(a in activityRows)TextButton(onClick={change("targetPath","/pages/community-detail/index?id="+LiveCommand.part(a.getString("id")))}){Text(a.getString("name"))};if(next!=null)TextButton(onClick={loadActivities(true)},enabled=!loading&&!m.busy){Text("更多活动")}}
 AssignmentChoice("展示方式",f.getString("displayMode"),listOf("pinned" to "固定展示","rotation" to "轮播展示")){change("displayMode",it)};CustodyField("展示顺序（0至10000，数值小在前）",priority,5){priority=it};AssignmentChoice("可见范围",f.getString("visibility"),listOf("public" to "公开","member" to "所有会员","segment" to "指定会员客群")){change("visibility",it);if(it!="segment"){change("audienceMemberLevels",JSONArray());change("audienceLifecycleStages",JSONArray())}}
 if(f.getString("visibility")=="segment"){for((k,choices)in listOf("audienceMemberLevels" to homeContentLevels,"audienceLifecycleStages" to homeContentStages)){Text(if(k=="audienceMemberLevels")"会员等级"else "会员阶段");for((value,label)in choices){val selected=f.getJSONArray(k).strings();Row{Checkbox(value in selected,{checked->change(k,JSONArray(if(checked)selected+value else selected-value))});Text(label)}}}}
 CustodyField("开始展示（北京时间 YYYY-MM-DD HH:mm）",start,29){start=it};CustodyField("结束展示（北京时间 YYYY-MM-DD HH:mm）",end,29){end=it};CustodyField("保存原因",reason,500){reason=it};Text("保存为草稿，不自动发布。只有有发布权限的员工能发布，过期内容不能发布。",style=MaterialTheme.typography.bodySmall);if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error);PrimaryAction(onClick={try{save(JSONObject(f.toString()).put("priority",priority.toInt()).put("validFrom",performanceTime(start)).put("validUntil",performanceTime(end)).put("reason",reason));error=""}catch(e:Exception){error=e.message?:"请核对时间和顺序"}},enabled=m.canUseHomeContent&&!loading){Text("核对并保存草稿")}}
}
