package com.mbox.staff
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import kotlinx.coroutines.launch
import org.json.JSONObject
import org.json.JSONArray
@Composable fun LiveStackingPoliciesView(m:AppModel,close:()->Unit){
 val access=remember{m.priorityAccessKey};val version=remember{m.workspaceVersion};var search by remember{mutableStateOf("")};var editing by remember{mutableStateOf<JSONObject?>(null)};var creating by remember{mutableStateOf(false)};var decision by remember{mutableStateOf<JSONObject?>(null)};var decisionAction by remember{mutableStateOf("")};var reason by remember{mutableStateOf("")};var error by remember{mutableStateOf("")};var proposed by remember{mutableStateOf<LiveCommand?>(null)}
 LaunchedEffect(Unit){m.loadStackingPolicies()};LaunchedEffect(m.priorityAccessKey,m.workspaceVersion){if(access!=m.priorityAccessKey||version!=m.workspaceVersion)close()};if(access!=m.priorityAccessKey||version!=m.workspaceVersion)return
 fun propose(action:String,body:JSONObject,confirmation:String){try{val b=m.stackingPoliciesBoard?:error("请刷新叠加规则");proposed=stackingPolicyCommand(m.identity!!,StackingPoliciesBoard(JSONObject(b.data.toString()).put("rows",JSONArray(m.stackingPolicyRows))),action,body,confirmation);error=""}catch(e:Exception){error=e.message.orEmpty()}}
 Dialog(onDismissRequest=close,properties=DialogProperties(usePlatformDefaultWidth=false)){Surface(Modifier.fillMaxSize(),color=Paper){LazyColumn(Modifier.safeDrawingPadding().imePadding().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
 item{Row{Text("优惠叠加与价格试算",Modifier.weight(1f),style=MaterialTheme.typography.titleLarge);TextButton(onClick=close){Text("关闭")}};LivePendingView(m);Text(m.stackingPoliciesState);if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error)}
 if(creating||editing!=null)item{key(editing?.getString("id")?:"new"){StackingPolicyEditor(m,editing,{editing=null;creating=false}){body->propose("save",body,"保存 ${body.getString("code")} 的第${body.getInt("expectedVersion")+1}版草稿\n按本页叠加开关、顺序和金额限制保存。已有券继续保留发放时规则，新草稿需独立审批及发布。")}}}
 else{
 item{CustodyField("按规则编号搜索",search,40){search=it};Row{TextButton(onClick={m.loadStackingPolicies(search)},enabled=!m.busy){Text("查询 / 刷新")};if(m.identity?.allows("loyalty.configuration.edit")==true)TextButton(onClick={creating=true;editing=null},enabled=m.canUseStackingPolicies){Text("新建规则草稿")}}}
 items(m.stackingPolicyRows,key={it.getString("id")}){row->Panel{Text("${row.getString("code")} · 第${row.getInt("version")}版 · ${couponCalendarStatuses[row.getString("status")]?:"待核对"}",style=MaterialTheme.typography.titleMedium);StackingRuleSummary(row);TextButton(onClick={editing=row;creating=false},enabled=m.canUseStackingPolicies){Text(if(m.identity?.allows("loyalty.configuration.edit")==true)"读取规则 / 修订新版本 / 预览" else "读取完整规则与预览")};val actor=m.identity;val status=row.getString("status");for((a,label)in listOf("approve" to "独立审批","publish" to "独立发布","stop_issuing" to "停止新发券")){val permission=if(a=="approve")"loyalty.configuration.approve" else "loyalty.policy.publish";val matches=status==mapOf("approve" to "draft","publish" to "approved","stop_issuing" to "published")[a];val independent=a=="stop_issuing"||row.getString("createdByEmployeeId")!=actor?.employeeId&&(a!="publish"||row.getJSONArray("decisions").objects().none{it.getString("action")=="approve"&&it.getString("employeeId")==actor?.employeeId});if(actor?.allows(permission)==true&&matches&&independent)TextButton(onClick={decision=row;decisionAction=a;reason=""},enabled=m.canUseStackingPolicies){Text(label)}}}}
 if(m.stackingPoliciesBoard?.next!=null)item{SecondaryAction(onClick={m.loadMoreStackingPolicies()},enabled=!m.busy){Text("加载后续版本")}}
 if(m.stackingPoliciesBoard!=null&&m.stackingPolicyRows.isEmpty())item{Text("当前查询范围没有叠加规则")}
 }
 }}}
 decision?.let{row->AlertDialog(onDismissRequest={decision=null},title={Text("核对叠加规则${if(decisionAction=="approve")"审批"else if(decisionAction=="publish")"发布"else "停发"}")},text={Column{Text("${row.getString("code")} 第${row.getInt("version")}版\n${if(decisionAction=="stop_issuing")"停止后不再向新券绑定这个版本，已发券承诺保留。"else "请先阅读完整叠加开关、计算顺序和金额限制；编辑、审批、发布须分别由独立员工完成。"}");CustodyField("实际核对原因",reason,500){reason=it}}},confirmButton={TextButton(onClick={propose("decision",JSONObject().put("versionId",row.getString("id")).put("expectedStatus",row.getString("status")).put("action",decisionAction).put("reason",reason.trim()),"${row.getString("code")} 第${row.getInt("version")}版\n${if(decisionAction=="stop_issuing")"停止新发券，已发券保留原规则"else if(decisionAction=="approve")"完成独立审批"else "正式发布券使用规则"}");decision=null}){Text("核对提交")}},dismissButton={TextButton(onClick={decision=null}){Text("返回")}})}
 proposed?.let{c->AlertDialog(onDismissRequest={proposed=null},title={Text("确认叠加规则操作")},text={Text(c.steps[0].stackingPolicyProof!!.getString("confirmation"))},confirmButton={TextButton(onClick={proposed=null;editing=null;creating=false;m.executeLive(c)},enabled=m.canExecuteLive(c)){Text("确认提交")}},dismissButton={TextButton(onClick={proposed=null}){Text("返回")}})}
}
@Composable private fun StackingRuleSummary(row:JSONObject){val p=row.getJSONObject("policy");for((key,label)in stackingSwitches)Text(label+"："+if(p.getBoolean(key))"是"else "否");Text("最多 ${p.getInt("maxCoupons")} 张券 · 计算顺序 "+p.getJSONArray("calculationOrder").strings().joinToString(" → "){stackingStages[it]?:it});Text("优惠上限："+(p.textOrNull("maximumDiscountMinor")?.let{"¥${java.math.BigDecimal(it).movePointLeft(2)}"}?:"不另设上限")+" · 最低实付 ¥${java.math.BigDecimal(p.getLong("minimumPayableMinor")).movePointLeft(2)}")}
@Composable private fun StackingPolicyEditor(m:AppModel,row:JSONObject?,back:()->Unit,save:(JSONObject)->Unit){
 var f by remember{mutableStateOf(stackingEditor(row))};var error by remember{mutableStateOf("")};fun change(k:String,v:Any){f=JSONObject(f.toString()).put(k,v)}
 Panel{Text(if(row==null)"新叠加规则草稿"else "读取第${row.getInt("version")}版；修改将建立新版本",style=MaterialTheme.typography.titleMedium);TextButton(onClick=back){Text("返回列表")};CustodyField("规则编号",f.getString("code"),40){change("code",it);change("expectedVersion",if(it==row?.getString("code"))row.getInt("version")else 0)};for((k,label)in stackingSwitches)Row{Checkbox(f.getBoolean(k),{change(k,it)});Text(label)};CustodyField("最多使用优惠券张数",f.getString("maxCoupons"),2){change("maxCoupons",it)};AssignmentChoice("优惠计算顺序",f.getString("order"),stackingOrders.map{it.joinToString(",") to it.joinToString(" → "){stage->stackingStages[stage]!!}}){change("order",it)};CustodyField("总优惠上限（元，留空不额外限制）",f.getString("maximumDiscountMinor"),16){change("maximumDiscountMinor",it)};CustodyField("最低实付（元）",f.getString("minimumPayableMinor"),16){change("minimumPayableMinor",it)};Text("固定兑换价或免费承诺与最低实付冲突时会拒绝核价，不会悄悄改变承诺价格。已发券保留原规则版本。");CustodyField("保存原因",f.getString("reason"),500){change("reason",it)};if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error);if(m.identity?.allows("loyalty.configuration.edit")==true)PrimaryAction(onClick={try{save(stackingSaveBody(f));error=""}catch(e:Exception){error=e.message?:"请核对规则"}},enabled=m.canUseStackingPolicies){Text("核对并保存新草稿")}}
 if(m.identity?.allows("loyalty.configuration.preview")==true)StackingScenarioPreview(m,f)
}
@Composable private fun StackingScenarioPreview(m:AppModel,f:JSONObject){
 var units by remember{mutableStateOf(listOf(stackingUnitDraft()))};var effects by remember{mutableStateOf<List<JSONObject>>(emptyList())};var generation by remember{mutableStateOf(0)};var preview by remember{mutableStateOf<JSONObject?>(null)};var error by remember{mutableStateOf("")};var loading by remember{mutableStateOf(false)};val scope=rememberCoroutineScope()
 fun invalidate(){generation++;preview=null};LaunchedEffect(f.toString()){invalidate()}
 fun unit(i:Int,k:String,v:Any){units=units.mapIndexed{j,r->if(i==j)JSONObject(r.toString()).put(k,v)else r};invalidate()}
 fun effect(i:Int,k:String,v:Any){effects=effects.mapIndexed{j,r->if(i==j)JSONObject(r.toString()).put(k,v)else r};invalidate()}
 Panel{Text("模拟报价，不修改订单",style=MaterialTheme.typography.titleMedium);Text("每行代表一份可独立退款的商品。金额为人工模拟值，真实下单会由后台重新核价。成本留空表示未知，不按零估算利润。")
 for((i,u)in units.withIndex())Foldout("模拟商品第${i+1}份"){CustodyField("原价（元）",u.getString("amount"),16){unit(i,"amount",it)};CustodyField("成本（元，可留空）",u.getString("cost"),16){unit(i,"cost",it)};for((k,label)in listOf("bundle" to "套餐价商品","upgraded" to "升级套餐"))Row{Checkbox(u.getBoolean(k),{unit(i,k,it)});Text(label)};if(units.size>1)TextButton(onClick={units=units.filterIndexed{n,_->n!=i};invalidate()}){Text("删除此份；相关优惠需重新选择份次")}}
 TextButton(onClick={units=units+stackingUnitDraft();invalidate()},enabled=units.size<100){Text("添加商品份次（${units.size}/100）")}
 for((i,e)in effects.withIndex())Foldout("第${i+1}项优惠 · ${stackingStages[e.getString("stage")]}"){
 AssignmentChoice("优惠来源",e.getString("stage"),stackingStages.toList()){effect(i,"stage",it)};AssignmentChoice("优惠方式",e.getString("kind"),listOf("fixed_price" to "固定兑换价","amount_off" to "减免金额","rate" to "折扣比例","free" to "免费")){effect(i,"kind",it)};if(e.getString("kind")!="free")CustodyField(if(e.getString("kind")=="rate")"实付比例（%，80表示八折）"else "金额（元）",e.getString("value"),16){effect(i,"value",it)};CustodyField("本步骤适用金额门槛（元）",e.getString("minimumSpend"),16){effect(i,"minimumSpend",it)};Text("适用商品份次（免费或固定价只能一份）");val selected=e.getJSONArray("unitIds").strings();for((n,u)in units.withIndex())Row{val id=u.getString("id");Checkbox(id in selected,{checked->effect(i,"unitIds",JSONArray(if(checked)selected+id else selected-id))});Text("第${n+1}份 · ¥${u.getString("amount").ifBlank{"未填写"}}")};if(selected.any{id->units.none{it.getString("id")==id}})TextButton(onClick={effect(i,"unitIds",JSONArray(selected.filter{id->units.any{it.getString("id")==id}}))}){Text("清除已删除商品的选择")};TextButton(onClick={effects=effects.filterIndexed{n,_->n!=i};invalidate()}){Text("移除此优惠")}
 }
 TextButton(onClick={effects=effects+stackingEffectDraft();invalidate()},enabled=effects.size<20){Text("添加模拟优惠（${effects.size}/20）")};Text("同类优惠按上方顺序计算；改变计算顺序可能改变结果。会员价和积分各最多一项。")
 if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error);SecondaryAction(onClick={try{val body=JSONObject().put("policy",stackingPolicyFromEditor(f)).put("scenario",stackingScenario(units,effects));val ticket=generation;loading=true;scope.launch{try{val result=m.previewStackingPolicy(body);if(ticket==generation){preview=result;error=""}}catch(e:Exception){if(ticket==generation){preview=null;error=e.message?:"试算失败"}}finally{loading=false}}}catch(e:Exception){preview=null;error=e.message?:"请核对模拟内容"}},enabled=!loading&&!m.busy){Text(if(loading)"正在试算"else "试算此规则")}
 preview?.let{p->val money:(String)->String={k->p.textOrNull(k)?.let{"¥${java.math.BigDecimal(it).movePointLeft(2)}"}?:"未知"};Text("模拟应付 ${money("payableMinor")} · 优惠 ${money("discountMinor")}",style=MaterialTheme.typography.titleMedium);Text("原价 ${money("subtotalMinor")} · 成本 ${money("costMinor")} · 模拟毛利 ${money("grossProfitMinor")}");for((n,step)in p.getJSONArray("steps").objects().withIndex()){Text("第${n+1}步 ${stackingStages[step.getString("stage")]}：减免 ¥${java.math.BigDecimal(step.getLong("discountMinor")).movePointLeft(2)}，剩余 ¥${java.math.BigDecimal(step.getLong("payableMinor")).movePointLeft(2)}")};for((n,u)in p.getJSONArray("units").objects().withIndex())Text("商品第${n+1}份应付 ¥${java.math.BigDecimal(u.getLong("payableMinor")).movePointLeft(2)}")}
 }
}
