package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import java.util.UUID
const val homeContentRoot="/api/staff/native-home-content"
val homeContentTypes=listOf("activity" to "活动","presale" to "预售","benefit" to "会员权益","article" to "资讯","return_offer" to "回店礼遇","show" to "演出")
val homeContentStatuses=mapOf("draft" to "草稿","published" to "已发布","paused" to "已暂停","retired" to "已退役")
val homeContentLevels=listOf("member" to "普通会员","silver" to "银卡会员","gold" to "金卡会员")
val homeContentStages=listOf("new" to "新会员","active" to "活跃会员","high_value" to "高价值会员","at_risk" to "待唤回会员","dormant" to "沉睡会员")
fun homeContentCommand(actor:StaffIdentity,board:CouponCalendarsBoard,action:String,row:JSONObject?,input:JSONObject):LiveCommand{
 require(board.enabled&&board.actor==actor.employeeId);require(action in listOf("create","update","publish","pause"));val permission=if(action in listOf("create","update"))"community.activity.manage"else "community.activity.publish";require(actor.allows(permission)){"当前岗位没有此项权限"}
 val b=JSONObject(input.toString());val code=b.getString("code").trim();require(Regex("^[A-Za-z0-9][A-Za-z0-9_.-]{2,63}$").matches(code)){"编号须为3至64位字母、数字、点、横线或下划线"};b.put("code",code);val reason=b.getString("reason").trim();require(reason.length in 2..500){"请输入2至500字的操作原因"};b.put("reason",reason)
 if(action=="create"){require(row==null);b.put("expectedVersion",JSONObject.NULL)}else{require(row!=null&&row.getString("code")==code);require(board.rows.any{it.getString("code")==code&&it.getString("nativeVersion")==row.getString("nativeVersion")}){"原内容已经变化，请重新读取"};b.put("expectedVersion",row.getString("nativeVersion"));require(if(action=="pause")row.getString("status")=="published"else row.getString("status") in listOf("draft","paused")){"当前状态不允许此操作，发布内容须先暂停"}}
 if(action in listOf("create","update")){
  for((k,range)in listOf("title" to 2..120,"summary" to 2..400,"ctaLabel" to 1..20)){val value=b.getString(k).trim();require(value.length in range){"请核对标题、摘要与按键文字长度"};b.put(k,value)}
  require(b.getString("type") in homeContentTypes.map{it.first});require(b.getString("displayMode") in listOf("pinned","rotation"));require(b.getInt("priority") in 0..10000)
  val visibility=b.getString("visibility");val levels=b.getJSONArray("audienceMemberLevels").strings().distinct().sorted();val stages=b.getJSONArray("audienceLifecycleStages").strings().distinct().sorted();require(visibility in listOf("public","member","segment")&&levels.all{it in homeContentLevels.map{p->p.first}}&&stages.all{it in homeContentStages.map{p->p.first}});require(if(visibility=="segment")levels.isNotEmpty()||stages.isNotEmpty()else levels.isEmpty()&&stages.isEmpty()){"指定客群至少选择一个等级或阶段"};b.put("audienceMemberLevels",JSONArray(levels)).put("audienceLifecycleStages",JSONArray(stages))
  require(serverInstant(b.getString("validUntil"))>serverInstant(b.getString("validFrom"))){"结束展示时间必须晚于开始时间"};require(b.getString("targetPath").startsWith("/pages/")&&b.getString("targetPath").length<=256){"请选择目标页面"};val image=b.textOrNull("imageUrl");require(image==null||Regex("^/api/public/media-assets/MA[0-9A-F]{32}$").matches(image)){"请从站内图片库选择图片"}
 }
 val id=UUID.randomUUID().toString();val title=if(action in listOf("create","update"))b.getString("title")else row!!.getString("title");val label=mapOf("create" to "建立首页内容草稿","update" to "保存首页内容草稿","publish" to "发布首页内容","pause" to "暂停首页内容").getValue(action)
 return LiveCommand(id,actor.employeeId,label,permission,listOf(LiveStep("$homeContentRoot/$action",b.toString(),"idempotency-key","native-business-$id",JSONObject().put("homeContent",JSONObject().put("employeeId",actor.employeeId).put("action",action).put("before",row?:JSONObject.NULL).put("confirmation","$label：$title\n编号：$code\n原因：$reason"+(if(action=="publish")"\n将在所设排期内向指定范围顾客展示。"else ""))).toString())))
}
val LiveStep.homeContentProof:JSONObject? get()=recoveryBody?.let{JSONObject(it).optJSONObject("homeContent")}
fun validateHomeContentReply(text:String,s:LiveStep){val r=JSONObject(text);val d=r.getJSONObject("data");val proof=s.homeContentProof!!;val b=JSONObject(s.body);val row=d.getJSONObject("row");val action=proof.getString("action");require(r.getJSONObject("meta").getInt("protocol")==1&&r.getJSONObject("meta").get("replayed") is Boolean&&d.getString("employeeId")==proof.getString("employeeId")&&d.getString("requestKey")==s.key&&d.getString("action")==action);require(Regex("^[a-f0-9]{64}$").matches(row.getString("nativeVersion")));require(row.getString("code")==b.getString("code")&&row.getString("status")==when(action){"publish"->"published";"pause"->"paused";else->"draft"});val expected=if(action in listOf("create","update"))b else proof.getJSONObject("before");for(k in listOf("type","title","summary","imageUrl","ctaLabel","targetPath","priority","displayMode","visibility","audienceMemberLevels","audienceLifecycleStages"))require(calendarJson(expected.get(k))==calendarJson(row.get(k))){"内容回执与原提交不一致"};for(k in listOf("validFrom","validUntil"))require(serverInstant(expected.getString(k))==serverInstant(row.getString(k))){"展示排期不一致"};require(row.textOrNull("publishedByEmployeeId")==when(action){"publish"->proof.getString("employeeId");"pause"->expected.textOrNull("publishedByEmployeeId");else->null})}
