package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import java.time.LocalDate
import java.time.Instant
import java.util.UUID
const val couponCalendarRoot="/api/staff/native-coupon-calendars"
val couponCalendarStatuses=mapOf("draft" to "草稿","approved" to "待发布","published" to "已发布","stopped" to "已停发")
class CouponCalendarsBoard(val data:JSONObject){val actor=data.getString("employeeId");val rows=data.getJSONArray("rows").objects();val enabled=data.getInt("protocol")==1&&data.getBoolean("durableCommands");val next=data.textOrNull("next")}
fun calendarMinute(s:String,end:Boolean=false):Int{if(end&&s=="24:00")return 1440;require(Regex("^(?:[01]\\d|2[0-3]):[0-5]\\d$").matches(s)){"时刻须为HH:mm，结束可以为24:00"};return s.take(2).toInt()*60+s.takeLast(2).toInt()}
fun calendarClock(n:Int)="%02d:%02d".format(n/60,n%60)
fun calendarLocal(s:String)=serverInstant(s).atZone(java.time.ZoneId.of("Asia/Shanghai")).toLocalDateTime().toString().replace('T',' ')
fun calendarEditor(row:JSONObject?):JSONObject{val rule=row?.getJSONObject("rule");val today=LocalDate.now(java.time.ZoneId.of("Asia/Shanghai"));return JSONObject().put("code",row?.getString("code")?:"").put("expectedVersion",row?.getInt("version")?:0).put("dateFrom",rule?.getString("dateFrom")?:today.toString()).put("dateThrough",rule?.getString("dateThrough")?:today.plusDays(30).toString()).put("validFrom",rule?.getString("validFrom")?.let(::calendarLocal)?:"$today 00:00").put("validUntil",rule?.getString("validUntil")?.let(::calendarLocal)?:"${today.plusDays(31)} 00:00").put("dateBasis",rule?.getString("dateBasis")?:"natural").put("cutoff",calendarClock(rule?.getInt("businessDayStartMinute")?:0)).put("weekStartsOn",(rule?.getInt("weekStartsOn")?:1).toString()).put("weekdays",rule?.getJSONArray("weekdays")?:JSONArray((1..7).toList())).put("windows",JSONArray(rule?.getJSONArray("windows")?.objects()?.map{JSONObject().put("from",calendarClock(it.getInt("startMinute"))).put("to",calendarClock(it.getInt("endMinute")))}?:listOf(JSONObject().put("from","00:00").put("to","24:00")))).put("excludedDates",rule?.getJSONArray("excludedDates")?.strings()?.joinToString("\n")?:"").put("relativeDays",rule?.optJSONObject("relativeValidity")?.getInt("days")?.toString()?:"").put("relativeBasis",rule?.optJSONObject("relativeValidity")?.getString("basis")?:"elapsed").put("perCustomerDay",row?.getJSONObject("limits")?.textOrNull("perCustomerDay")?:"").put("perCustomerWeek",row?.getJSONObject("limits")?.textOrNull("perCustomerWeek")?:"").put("perCustomerCampaign",row?.getJSONObject("limits")?.textOrNull("perCustomerCampaign")?:"").put("reason","")}
fun calendarRuleFromEditor(f:JSONObject):JSONObject{val start=LocalDate.parse(f.getString("dateFrom"));val end=LocalDate.parse(f.getString("dateThrough"));require(!end.isBefore(start)&&java.time.temporal.ChronoUnit.DAYS.between(start,end)<=3660){"日期范围须正序且不超过3661天"};val validFrom=performanceTime(f.getString("validFrom"));val validUntil=performanceTime(f.getString("validUntil"));require(Instant.parse(validUntil)>Instant.parse(validFrom)){"绝对截止时间必须晚于开始"};val weekdays=f.getJSONArray("weekdays").objectsOrInts();require(weekdays.isNotEmpty()&&weekdays.all{it in 1..7}&&weekdays.distinct().size==weekdays.size){"至少选一个星期"};val windows=f.getJSONArray("windows").objects().map{val a=calendarMinute(it.getString("from"));val b=calendarMinute(it.getString("to"),true);require(a!=b){"起止不能相同；全天请选00:00至24:00"};JSONObject().put("startMinute",a).put("endMinute",b)};require(windows.size in 1..12);val excluded=f.getString("excludedDates").split(Regex("[\\s,，]+ ".trim())).filter{it.isNotBlank()}.distinct().sorted();require(excluded.size<=3661);for(day in excluded){val d=LocalDate.parse(day);require(!d.isBefore(start)&&!d.isAfter(end)){"排除日期须在活动范围内"}}
 val basis=f.getString("dateBasis");require(basis in listOf("natural","business"));val week=f.getString("weekStartsOn").toInt();require(week in 1..7);val r=JSONObject().put("timezone","Asia/Shanghai").put("dateBasis",basis).put("businessDayStartMinute",if(basis=="natural")0 else calendarMinute(f.getString("cutoff"))).put("dateFrom",start.toString()).put("dateThrough",end.toString()).put("validFrom",validFrom).put("validUntil",validUntil).put("weekdays",JSONArray(weekdays.sorted())).put("weekStartsOn",week).put("windows",JSONArray(windows)).put("excludedDates",JSONArray(excluded));val relative=f.getString("relativeDays");if(relative.isNotBlank()){val days=relative.toInt();val mode=f.getString("relativeBasis");require(days in 1..3660&&mode in listOf("elapsed","natural_end","business_end")&&(mode!="business_end"||basis=="business")){"发放后期限须为1至3660天；营业日结束口径须选择营业日"};r.put("relativeValidity",JSONObject().put("days",days).put("basis",mode))};return r}
private fun JSONArray.objectsOrInts()=(0 until length()).map{getInt(it)}
fun calendarSaveBody(f:JSONObject):JSONObject{val code=f.getString("code").trim();require(Regex("^[A-Z][A-Z0-9_]{1,39}$").matches(code)){"编号须2至40位大写字母、数字或下划线"};val limits=JSONObject();for(k in listOf("perCustomerDay","perCustomerWeek","perCustomerCampaign")){val text=f.getString(k).trim();val n=text.toIntOrNull();require(text.isEmpty()||n!=null&&n in 1..1000000){"使用次数须1至1000000，空白表示不额外限制"};limits.put(k,n?:JSONObject.NULL)};return JSONObject().put("code",code).put("expectedVersion",f.getInt("expectedVersion")).put("rule",calendarRuleFromEditor(f)).put("limits",limits).put("reason",f.getString("reason").trim())}
fun couponCalendarCommand(actor:StaffIdentity,b:CouponCalendarsBoard,action:String,body:JSONObject,confirmation:String):LiveCommand{val permission=if(action=="save")"loyalty.configuration.edit" else if(body.getString("action")=="approve")"loyalty.configuration.approve" else "loyalty.policy.publish";require(b.enabled&&b.actor==actor.employeeId&&actor.allows(permission));require(body.getString("reason").trim().length in 2..500){"请填写2至500字原因"};if(action=="decision"){val row=b.rows.find{it.getString("id")==body.getString("versionId")}?:error("原规则不可见，请重新查询");require(row.getString("status")==body.getString("expectedStatus"));val a=body.getString("action");require(a in listOf("approve","publish","stop_issuing"));if(a!="stop_issuing")require(row.getString("createdByEmployeeId")!=actor.employeeId){"编辑人不能审批或发布本人规则"};if(a=="publish")require(row.getJSONArray("decisions").objects().none{it.getString("action")=="approve"&&it.getString("employeeId")==actor.employeeId}){"须由审批人之外的员工发布"}}
 val id=UUID.randomUUID().toString();val proof=JSONObject().put("employeeId",actor.employeeId).put("action",action).put("confirmation",confirmation+"\n原因：${body.getString("reason")}");return LiveCommand(id,actor.employeeId,"核对券日历规则",permission,listOf(LiveStep("$couponCalendarRoot/$action",body.toString(),"idempotency-key","native-business-$id",JSONObject().put("couponCalendar",proof).toString())))}
val LiveStep.couponCalendarProof:JSONObject? get()=recoveryBody?.let{JSONObject(it).optJSONObject("couponCalendar")}
private fun canonicalCalendar(r:JSONObject):String{val copy=JSONObject(r.toString());for(k in listOf("validFrom","validUntil"))copy.put(k,serverInstant(copy.getString(k)).toString());return calendarJson(copy)}
fun calendarJson(v:Any?):String=when(v){is JSONObject->v.keys().asSequence().toList().sorted().joinToString(",","{","}"){JSONObject.quote(it)+":"+calendarJson(v.opt(it))};is JSONArray->(0 until v.length()).joinToString(",","[","]"){calendarJson(v.opt(it))};null,JSONObject.NULL->"null";is String->JSONObject.quote(v);else->v.toString()}
fun validateCouponCalendarReply(text:String,s:LiveStep){val r=JSONObject(text);val d=r.getJSONObject("data");val p=s.couponCalendarProof!!;val body=JSONObject(s.body);require(r.getJSONObject("meta").getInt("protocol")==1&&r.getJSONObject("meta").get("replayed") is Boolean);require(d.getString("employeeId")==p.getString("employeeId")&&d.getString("action")==p.getString("action")&&d.getString("requestKey")==s.key);val row=d.getJSONObject("row");UUID.fromString(row.getString("id"));if(p.getString("action")=="save")require(row.getString("code")==body.getString("code")&&row.getInt("version")==body.getInt("expectedVersion")+1&&row.getString("status")=="draft"&&row.getString("createdByEmployeeId")==p.getString("employeeId")&&canonicalCalendar(row.getJSONObject("rule"))==canonicalCalendar(body.getJSONObject("rule"))&&calendarJson(row.getJSONObject("limits"))==calendarJson(body.getJSONObject("limits"))){"保存的券规则与原请求不一致"}else{val a=body.getString("action");require(row.getString("id")==body.getString("versionId")&&row.getString("status")==mapOf("approve" to "approved","publish" to "published","stop_issuing" to "stopped")[a]&&row.getJSONArray("decisions").objects().any{it.getString("action")==a&&it.getString("employeeId")==p.getString("employeeId")}){"券规则审核回执不一致"}}}
