package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import java.util.UUID
const val checkoutManagementRoot="/api/staff/native-checkout-management"
val checkoutOccasions=listOf("business" to "商务","friends" to "朋友聚会","date" to "约会","birthday" to "生日","music" to "音乐","relax" to "放松","other" to "其他")
val checkoutAlcohol=listOf("cocktail" to "鸡尾酒","wine" to "葡萄酒","sparkling" to "起泡酒","beer" to "啤酒","whisky" to "威士忌","baijiu" to "白酒","non_alcoholic" to "无酒精","mixed" to "混合偏好","undecided" to "未决定")
val checkoutStations=listOf("bar" to "吧台","kitchen" to "厨房","cashier" to "收银")
val checkoutRuleFields=listOf("code","name","sourceProductId","targetProductId","minimumPartySize","maximumPartySize","occasionTags","alcoholPreferenceTags","promptTitle","promptBody","callToAction","priority","offerValidMinutes","minimumGrossMarginBasisPoints")
val checkoutQualificationFields=listOf("maximumAddMinor","maximumAddBasisPoints","minimumContributionMinor","minimumIncrementalContributionMinor","positiveFitReason","maximumQuantitiesPerPerson","excludedProductIds")
fun checkoutMoney(v:String):Long{val n=java.math.BigDecimal(v.trim()).movePointRight(2).longValueExact();require(n in 0..9007199254740991L){"金额须为非负且最多两位小数"};return n}
fun checkoutManagementCommand(actor:StaffIdentity,board:CouponCalendarsBoard,action:String,row:JSONObject?,input:JSONObject):LiveCommand{
 require(board.enabled&&board.actor==actor.employeeId);require(action in listOf("rule-draft","rule-approve","rule-publish","rule-rollback","capacity-draft","capacity-approve","capacity-publish"));val rule=action.startsWith("rule");val permission=if(rule)"checkout.upgrade.rule."+(if(action=="rule-rollback")"publish"else action.substringAfter('-'))else "fulfillment.capacity."+action.substringAfter('-');require(actor.allows(permission));val b=JSONObject(input.toString());val reason=b.getString("reason").trim();require(reason.length in 2..240){"请填写2至240字原因"};b.put("reason",reason)
 if(!action.endsWith("draft")){require(row!=null&&board.rows.any{it.getString("id")==row.getString("id")&&it.getString("nativeVersion")==row.getString("nativeVersion")}){"原配置已变化，请重新读取"};b.put("id",row.getString("id")).put("expectedVersion",row.getString("nativeVersion"));if(action=="rule-approve")b.put("code",row.getString("code"));if(action.endsWith("approve"))require(row.getString("status")=="draft"&&row.textOrNull("draftedByEmployeeId")!=actor.employeeId){"须由另一位授权员工审批"};if(action.endsWith("publish"))require(row.getString("status")=="approved"&&row.textOrNull("draftedByEmployeeId")!=actor.employeeId&&row.textOrNull("approvedByEmployeeId")!=actor.employeeId){"发布须与起草、审批分离"}}
 if(action=="rule-draft"){
  require(Regex("^[A-Z][A-Z0-9_-]{2,63}$").matches(b.getString("code"))&&b.getString("code")==board.data.textOrNull("code")){"先读取此编号的最新版本"};b.put("expectedLatest",board.data.getInt("latest"));UUID.fromString(b.getString("sourceProductId"));UUID.fromString(b.getString("targetProductId"));require(b.getString("sourceProductId")!=b.getString("targetProductId"));for((k,min,max)in listOf(Triple("name",2,80),Triple("promptTitle",2,60),Triple("promptBody",2,240),Triple("callToAction",2,30))){val t=b.getString(k).trim();require(t.length in min..max);b.put(k,t)};require(b.getInt("minimumPartySize") in 1..200&&b.getInt("maximumPartySize") in b.getInt("minimumPartySize")..200&&b.getInt("priority") in 0..10000&&b.getInt("offerValidMinutes") in 2..30&&b.getInt("minimumGrossMarginBasisPoints") in 0..9999)
  for((k,options)in listOf("occasionTags" to checkoutOccasions,"alcoholPreferenceTags" to checkoutAlcohol)){val choices=b.getJSONArray(k).strings();require(choices.distinct().size==choices.size&&choices.all{it in options.map{p->p.first}})}
  val q=b.getJSONObject("qualification");for(k in listOf("maximumAddMinor","minimumContributionMinor","minimumIncrementalContributionMinor"))require(q.getLong(k) in 0..9007199254740991L);if(!q.isNull("maximumAddBasisPoints"))require(q.getInt("maximumAddBasisPoints") in 0..1000000);val fit=q.getString("positiveFitReason").trim();require(fit.length in 2..500);q.put("positiveFitReason",fit);val portions=q.getJSONArray("maximumQuantitiesPerPerson").objects();require(portions.size in 1..100&&portions.map{it.getString("productId")}.distinct().size==portions.size);for(p in portions){UUID.fromString(p.getString("productId"));require(p.getInt("quantity") in 1..100)};val excluded=q.getJSONArray("excludedProductIds").strings();require(excluded.size<=100&&excluded.distinct().size==excluded.size);excluded.forEach{UUID.fromString(it)}
 }
 if(action=="capacity-draft"){require(b.getString("stationCode") in checkoutStations.map{it.first});val windows=b.getJSONArray("windows").objects().sortedBy{serverInstant(it.getString("startsAt"))};require(windows.size in 1..96);for((i,w)in windows.withIndex()){require(serverInstant(w.getString("endsAt"))>serverInstant(w.getString("startsAt"))&&w.getInt("capacityLimitUnits") in 1..1000000){"窗口时间须正序，产能须为1至1000000的整数"};if(i>0)require(serverInstant(w.getString("startsAt"))>=serverInstant(windows[i-1].getString("endsAt"))){"同一产能策略的时间窗不能重叠"}};b.put("windows",JSONArray(windows))}
 val label=mapOf("rule-draft" to "保存升级规则草稿","rule-approve" to "独立审批升级规则","rule-publish" to "发布升级规则","rule-rollback" to "历史规则复制为回滚草稿","capacity-draft" to "保存产能时间窗草稿","capacity-approve" to "独立审批产能","capacity-publish" to "发布产能时间窗").getValue(action);val id=UUID.randomUUID().toString();val detail=if(rule)"${if(action=="rule-draft")b.getString("code")else row!!.getString("code")}\n"+(if(action=="rule-draft")"${b.getString("name")} · 下一版本 ${b.getInt("expectedLatest")+1}"else "原第${row!!.getInt("revision")}版 · ${row.getString("sourceProductName")} → ${row.getString("targetProductName")}")+"\n规则发布不会自动开放顾客付款前升级；仍需营业验收。"else "${checkoutStations.toMap()[if(action=="capacity-draft")b.getString("stationCode")else row!!.getString("stationCode")]} · ${(if(action=="capacity-draft")b else row!!).getJSONArray("windows").length()} 个时间窗\n发布将影响新的出品准入，已占用的产能事实保留。"
 return LiveCommand(id,actor.employeeId,label,permission,listOf(LiveStep("$checkoutManagementRoot/$action",b.toString(),"idempotency-key","native-business-$id",JSONObject().put("checkoutManagement",JSONObject().put("employeeId",actor.employeeId).put("action",action).put("before",row?:JSONObject.NULL).put("confirmation","$label\n$detail\n原因：$reason")).toString())))
}
val LiveStep.checkoutManagementProof:JSONObject? get()=recoveryBody?.let{JSONObject(it).optJSONObject("checkoutManagement")}
private fun qualificationComparable(q:JSONObject):String{val r=JSONObject();for(k in checkoutQualificationFields)r.put(k,q.get(k));r.put("maximumQuantitiesPerPerson",JSONArray(q.getJSONArray("maximumQuantitiesPerPerson").objects().sortedBy{it.getString("productId")}));r.put("excludedProductIds",JSONArray(q.getJSONArray("excludedProductIds").strings().sorted()));return calendarJson(r)}
fun validateCheckoutManagementReply(text:String,s:LiveStep){val r=JSONObject(text);val d=r.getJSONObject("data");val p=s.checkoutManagementProof!!;val b=JSONObject(s.body);val action=p.getString("action");val row=d.getJSONObject("row");require(r.getJSONObject("meta").getInt("protocol")==1&&r.getJSONObject("meta").get("replayed") is Boolean&&d.getString("employeeId")==p.getString("employeeId")&&d.getString("requestKey")==s.key&&d.getString("action")==action&&calendarJson(d.getJSONObject("accepted"))==calendarJson(b)&&Regex("^[a-f0-9]{64}$").matches(row.getString("nativeVersion")));val before=p.optJSONObject("before");val expected=if(action.endsWith("draft"))b else before!!;val status=when(action){"rule-draft","rule-rollback","capacity-draft"->"draft";"rule-approve","capacity-approve"->"approved";"rule-publish"->"active";else->"published"};require(row.getString("status")==status)
 if(action.startsWith("rule")){for(k in checkoutRuleFields)require(calendarJson(row.get(k))==calendarJson(expected.get(k))){"规则字段与原提交不同"};expected.optJSONObject("qualification")?.let{require(qualificationComparable(it)==qualificationComparable(row.getJSONObject("qualification")))};if(action=="rule-draft")require(row.getInt("revision")==b.getInt("expectedLatest")+1);if(action=="rule-rollback")require(row.getInt("revision")>before!!.getInt("revision")&&row.getString("id")!=before.getString("id"))}
 else{require(row.getString("stationCode")==expected.getString("stationCode"));val old=expected.getJSONArray("windows").objects().sortedBy{serverInstant(it.getString("startsAt"))};val current=row.getJSONArray("windows").objects().sortedBy{serverInstant(it.getString("startsAt"))};require(old.size==current.size);for(i in old.indices){for(k in listOf("startsAt","endsAt"))require(serverInstant(old[i].getString(k))==serverInstant(current[i].getString(k)));require(old[i].getInt("capacityLimitUnits")==current[i].getInt("capacityLimitUnits"))}}
 if(action.endsWith("draft")||action=="rule-rollback")require(row.getString("draftedByEmployeeId")==p.getString("employeeId"))else{require(row.getString("id")==b.getString("id"));require(row.getString(if(action.endsWith("approve"))"approvedByEmployeeId"else "publishedByEmployeeId")==p.getString("employeeId"))}
}

fun checkoutDecimal(n:Int)=java.math.BigDecimal(n).movePointLeft(2).stripTrailingZeros().toPlainString()
fun checkoutDecimal(n:Long)=java.math.BigDecimal(n).movePointLeft(2).stripTrailingZeros().toPlainString()
