package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import java.util.UUID
const val contactGovernanceRoot="/api/staff/native-contact-governance"
val contactResourceKinds=listOf("activity_registration_contact" to "活动报名联系方式","verified_membership_phone" to "已验证会员手机号")
fun contactGovernanceCommand(actor:StaffIdentity,board:CouponCalendarsBoard,action:String,row:JSONObject?,input:JSONObject):LiveCommand{
 require(board.enabled&&board.actor==actor.employeeId);require(action in listOf("draft","approve","publish","hold","release"));val permission=if(action in listOf("hold","release"))"privacy.contact.legal_hold"else "privacy.contact.retention.$action";require(actor.allows(permission));val b=JSONObject(input.toString());val reason=b.getString("reason").trim();require(reason.length in 2..500){"请填写2至500字操作依据"};b.put("reason",reason)
 if(action!="draft"){require(row!=null&&board.rows.any{it.getString("publicId")==row.getString("publicId")&&it.getString("nativeVersion")==row.getString("nativeVersion")}){"原策略或保留对象已变化，请重新读取"};b.put("expectedVersion",row.getString("nativeVersion")).put(if(action=="hold")"resourcePublicId"else "publicId",row.getString("publicId"))}
 if(action in listOf("draft","hold")){val basis=b.getString("legalBasisReference").trim();require(basis.length in 3..500){"请填写已核实的保留依据"};b.put("legalBasisReference",basis);require(b.getString("resourceKind") in contactResourceKinds.map{it.first})}
 when(action){"draft"->require(b.getInt("retentionDaysAfterPurposeEnd") in 0..36500){"天数须为0至36500的整数"};"approve"->require(row!!.getString("status")=="draft"&&row.getString("draftedByEmployeeId")!=actor.employeeId){"审批人必须与起草人不同"};"publish"->{require(row!!.getString("status")=="approved"&&row.getString("draftedByEmployeeId")!=actor.employeeId&&row.getString("approvedByEmployeeId")!=actor.employeeId){"发布人必须与起草、审批人不同"};serverInstant(b.getString("effectiveFrom"))};"hold"->{require(row!!.getString("resourceKind")==b.getString("resourceKind"));b.textOrNull("holdUntil")?.let{serverInstant(it)}};"release"->require(row!!.getString("status")=="active"){"原保留已经释放"}}
 val label=mapOf("draft" to "建立保留策略草稿","approve" to "独立审批保留策略","publish" to "发布保留策略","hold" to "建立法定保留","release" to "释放法定保留").getValue(action);val id=UUID.randomUUID().toString();val details=when(action){"draft"->"${contactResourceKinds.toMap()[b.getString("resourceKind")]}\n目的结束后保留 ${b.getInt("retentionDaysAfterPurposeEnd")} 天\n依据：${b.getString("legalBasisReference")}";"hold"->"${row!!.getString("businessLabel")} · ${row.getString("maskedContact")}\n原版本：${row.getString("publicId")}\n依据：${b.getString("legalBasisReference")}\n保留至：${b.textOrNull("holdUntil")?.let{calendarLocal(it)}?:"无预定截止，须有相应保留依据"}\n仅阻止旧版本清除，不影响顾客更正联系方式。";"release"->"${row!!.getString("resourcePublicId")} · ${row.getString("maskedContact")}\n释放后，符合已发布期限的旧版本将由清除任务处理。";else->"${contactResourceKinds.toMap()[row!!.getString("resourceKind")]} 第${row.getInt("version")}版\n目的结束后保留 ${row.getInt("retentionDaysAfterPurposeEnd")} 天\n${row.getString("legalBasisReference")}"+(if(action=="publish")"\n生效：${calendarLocal(b.getString("effectiveFrom"))}"else "")}
 return LiveCommand(id,actor.employeeId,label,permission,listOf(LiveStep("$contactGovernanceRoot/$action",b.toString(),"idempotency-key","native-business-$id",JSONObject().put("contactGovernance",JSONObject().put("employeeId",actor.employeeId).put("action",action).put("before",row?:JSONObject.NULL).put("confirmation","$label\n$details\n原因：$reason")).toString())))
}
val LiveStep.contactGovernanceProof:JSONObject? get()=recoveryBody?.let{JSONObject(it).optJSONObject("contactGovernance")}
fun validateContactGovernanceReply(text:String,s:LiveStep){val r=JSONObject(text);val d=r.getJSONObject("data");val p=s.contactGovernanceProof!!;val b=JSONObject(s.body);val action=p.getString("action");val row=d.getJSONObject("row");require(r.getJSONObject("meta").getInt("protocol")==1&&r.getJSONObject("meta").get("replayed") is Boolean&&d.getString("employeeId")==p.getString("employeeId")&&d.getString("action")==action&&d.getString("requestKey")==s.key&&calendarJson(d.getJSONObject("accepted"))==calendarJson(b)&&Regex("^[a-f0-9]{64}$").matches(row.getString("nativeVersion")));val before=p.optJSONObject("before")
 if(action in listOf("draft","approve","publish")){val expected=if(action=="draft")b else before!!;for(k in listOf("resourceKind","retentionDaysAfterPurposeEnd","legalBasisReference"))require(calendarJson(row.get(k))==calendarJson(expected.get(k)));require(row.getString("status")==mapOf("draft" to "draft","approve" to "approved","publish" to "published")[action]);if(action=="draft")require(row.getString("draftedByEmployeeId")==p.getString("employeeId")&&row.getString("draftReason")==b.getString("reason"))else require(row.getString("publicId")==b.getString("publicId")&&row.getInt("version")==before!!.getInt("version"));if(action=="approve")require(row.getString("approvedByEmployeeId")==p.getString("employeeId")&&row.getString("approvalReason")==b.getString("reason"));if(action=="publish")require(row.getString("publishedByEmployeeId")==p.getString("employeeId")&&row.getString("publicationReason")==b.getString("reason")&&serverInstant(row.getString("effectiveFrom"))==serverInstant(b.getString("effectiveFrom")))}else if(action=="hold"){for(k in listOf("resourceKind","resourcePublicId","legalBasisReference","reason"))require(row.getString(k)==b.getString(k));require(row.getString("status")=="active"&&row.getString("createdByEmployeeId")==p.getString("employeeId"));require(row.textOrNull("holdUntil")?.let{serverInstant(it)}==b.textOrNull("holdUntil")?.let{serverInstant(it)})}else{require(row.getString("publicId")==b.getString("publicId")&&row.getString("status")=="released"&&row.getString("releasedByEmployeeId")==p.getString("employeeId")&&row.getString("releaseReason")==b.getString("reason"));for(k in listOf("resourceKind","resourcePublicId","legalBasisReference","reason"))require(row.getString(k)==before!!.getString(k))}
}
