package com.mbox.staff
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import kotlinx.coroutines.launch
import org.json.JSONObject
import org.json.JSONArray

@Composable fun LiveMemberGiftsView(m:AppModel,close:()->Unit){
 var tab by remember{mutableStateOf("campaigns")};var editing by remember{mutableStateOf<JSONObject?>(null)};var creating by remember{mutableStateOf(false)};var operation by remember{mutableStateOf("")};var selected by remember{mutableStateOf<JSONObject?>(null)};var reason by remember{mutableStateOf("")};var cycle by remember{mutableStateOf("")};var customers by remember{mutableStateOf<List<JSONObject>>(emptyList())};var pickCustomers by remember{mutableStateOf(false)};var proposed by remember{mutableStateOf<LiveCommand?>(null)};var error by remember{mutableStateOf("")};val access=remember{m.priorityAccessKey};val workspace=remember{m.workspaceVersion}
 LaunchedEffect(Unit){m.loadMemberGifts(tab)};LaunchedEffect(m.priorityAccessKey,m.workspaceVersion){if(access!=m.priorityAccessKey||workspace!=m.workspaceVersion)close()};if(access!=m.priorityAccessKey||workspace!=m.workspaceVersion)return
 fun propose(action:String,b:JSONObject,summary:String){try{val board=m.memberGiftsBoard?:error("请读取活动");proposed=memberGiftCommand(m.identity!!,MemberGiftsBoard(JSONObject(board.data.toString()).put("rows",JSONArray(m.memberGiftRows))),action,b,summary);error=""}catch(e:Exception){error=e.message.orEmpty()}}
 Dialog(onDismissRequest=close,properties=DialogProperties(usePlatformDefaultWidth=false)){Surface(Modifier.fillMaxSize(),color=Paper){LazyColumn(Modifier.safeDrawingPadding().imePadding().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
 item{Row{Text("会员活动与赠礼",Modifier.weight(1f),style=MaterialTheme.typography.titleLarge);TextButton(onClick=close){Text("关闭")}};LivePendingView(m);Text(m.memberGiftsState);if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error)}
 if(creating||editing!=null)item{key(editing?.getString("id")?:"new"){MemberGiftEditor(m,editing,{creating=false;editing=null}){b->propose("save",b,"${b.getString("name")} · 第${b.getInt("expectedVersion")+1}版\n保存当前商品池、资格、时间及预算。草稿不发券，须独立审批和发布。")}}}
 else if(selected!=null)item{val row=selected!!;Panel{Text(row.optString("name","赠礼任务"),style=MaterialTheme.typography.titleMedium);TextButton(onClick={selected=null}){Text("返回列表")};Text(mapOf("approve" to "独立审批活动","publish" to "正式发布活动","stop" to "停止新发券","target" to "向指定会员安排发券","retry" to "重新安排受阻任务","cancel" to "取消尚未发券任务")[operation]?:"")
 if(operation=="target"){Text("只安排后台发放任务，不表示已经发券。后台会再次核对会员资格、预算和规则。相同活动、批次和会员不会重复发放。");CustodyField("发放批次编号",cycle,100){cycle=it};if(row.getJSONObject("rule").textOrNull("dessertProductId")!=null)Text("组合甜点活动每位会员只赠一次，填写不同批次不会再次赠送。");TextButton(onClick={pickCustomers=true}){Text("查询并选择会员（已选${customers.size}/50）")};for(c in customers)Row{Text(c.getString("name")+" · "+c.getString("code"),Modifier.weight(1f));TextButton(onClick={customers=customers.filter{it.getString("id")!=c.getString("id")}}){Text("移除")}}}else Text(if(operation=="stop")"停止新发券不会撤销已经发出的券；待发任务会按后台活动状态受阻。"else if(operation=="retry")"重试只调整原任务的下次检查时间；已发券任务不能重发。"else if(operation=="cancel")"取消原待发任务，不撤销已经发出的券，也不会为同一批次生成新的资格。"else "请核对完整规则。创建、审批、发布由不同授权员工操作。")
 CustodyField("实际核对原因",reason,500){reason=it};PrimaryAction(onClick={val kind=if(operation=="target")"target"else if(operation in listOf("retry","cancel"))"control"else "decision";val b=JSONObject().put(if(kind=="control")"jobId"else "versionId",row.getString("id")).put("expectedVersion",row.getString("nativeVersion")).put("reason",reason.trim());if(kind=="target")b.put("customerIds",JSONArray(customers.map{it.getString("id")})).put("cycleKey",cycle.trim())else b.put("action",operation);propose(kind,b,row.optString("name","赠礼任务")+"\n"+when(operation){"target"->"为${customers.size}名会员安排发放，批次${cycle.trim()}";"approve"->"独立审批";"publish"->"正式发布";"stop"->"停止新发券";"retry"->"重试原任务";else->"取消原任务"})},enabled=m.canUseMemberGifts){Text("核对提交")}}}
 else{
 item{AssignmentChoice("查看",tab,listOf("campaigns" to "活动版本","jobs" to "发放任务")){if(m.loadMemberGifts(it))tab=it};Row{TextButton(onClick={m.loadMemberGifts(tab)},enabled=!m.busy){Text("刷新")};if(tab=="campaigns"&&m.identity?.allows("loyalty.configuration.edit")==true)TextButton(onClick={creating=true;editing=null},enabled=m.canUseMemberGifts){Text("新建活动")}}}
 items(m.memberGiftRows.filter{if(tab=="campaigns")it.has("rule")else it.has("customer_reference")},key={it.getString("id")}){row->Panel{val status=row.getString("status");Text(row.getString("name")+" · "+(memberGiftStatuses[status]?:"待核对"),style=MaterialTheme.typography.titleMedium)
 if(tab=="campaigns"){Text("${row.getString("code")} · 第${row.getInt("version")}版");GiftRuleSummary(row);TextButton(onClick={editing=row;creating=false},enabled=m.canUseMemberGifts){Text("查看全部规则 / 修订新版本")};val actor=m.identity;for((action,label)in listOf("approve" to "独立审批","publish" to "正式发布","stop" to "停止新发券","target" to "定向发放")){val permission=if(action=="approve")"loyalty.configuration.approve"else "loyalty.policy.publish";val match=if(action=="target")status=="published"&&row.getJSONObject("rule").getString("trigger")=="targeted"else status==mapOf("approve" to "draft","publish" to "approved","stop" to "published")[action];val independent=action in listOf("stop","target")||row.getString("created_by_employee_id")!=actor?.employeeId&&(action!="publish"||row.textOrNull("approved_by_employee_id")!=actor?.employeeId);if(match&&independent&&actor?.allows(permission)==true)TextButton(onClick={selected=row;operation=action;reason="";customers=emptyList();cycle=""},enabled=m.canUseMemberGifts){Text(label)}}
 }else{Text("会员 ${row.getString("customer_reference")} · ${row.getInt("quantity")}份");Text("已尝试 ${row.getInt("attempts")} 次 · 创建 ${calendarLocal(row.getString("created_at"))}");row.textOrNull("next_attempt_at")?.let{if(status in listOf("pending","blocked"))Text("下次检查 ${calendarLocal(it)}")};row.textOrNull("last_error_code")?.let{Text("受阻原因："+(giftBlockedReasons[it]?:"需核对后台，原因编号 $it"))};if(row.textOrNull("benefit_id")!=null)Text("券已生成，可在会员权益钱包核对使用情况。");row.textOrNull("completed_at")?.let{Text("结束 ${calendarLocal(it)}")};if(status in listOf("pending","blocked")&&m.identity?.allows("loyalty.policy.publish")==true)for((a,label)in listOf("retry" to "重试原任务","cancel" to "取消待发任务"))TextButton(onClick={selected=row;operation=a;reason=""},enabled=m.canUseMemberGifts){Text(label)}}}}
 if(m.memberGiftsBoard?.next!=null)item{SecondaryAction(onClick={m.loadMoreMemberGifts()},enabled=!m.busy){Text("加载后续记录")}};if(m.memberGiftsBoard!=null&&m.memberGiftRows.isEmpty())item{Text("当前范围没有记录")}
 }
 }}}
 if(pickCustomers)GiftOptionPicker(m,"customers",customers,50,{pickCustomers=false}){chosen->customers=chosen;pickCustomers=false}
 proposed?.let{command->AlertDialog(onDismissRequest={proposed=null},title={Text("确认赠礼操作")},text={Text(command.steps[0].memberGiftProof!!.getString("confirmation"))},confirmButton={TextButton(onClick={proposed=null;creating=false;editing=null;selected=null;m.executeLive(command)},enabled=m.canExecuteLive(command)){Text("确认提交")}},dismissButton={TextButton(onClick={proposed=null}){Text("返回核对")}})}
}
val giftBlockedReasons=mapOf("campaign_closed" to "活动已结束或停止","coupon_calendar_closed" to "券日历已停止发放","campaign_quantity_exceeded" to "活动总份数不足","daily_quantity_exceeded" to "每日份数不足","campaign_cost_exceeded" to "活动成本预算不足","daily_cost_exceeded" to "每日成本预算不足","unit_cost_exceeded" to "单份成本超过上限","cost_unknown" to "商品成本未知","audience_changed" to "当前会员资格不符","product_unavailable_or_cost_unknown" to "商品停用、缺少售价或成本未知","stacking_policy_closed" to "叠加价格规则已停止发放","same_family_already_issued" to "同一会员家庭已经发过")
@Composable private fun GiftRuleSummary(row:JSONObject){val r=row.getJSONObject("rule");Text((if(r.getString("trigger")=="card_entry")"入卡礼"else "定向发放")+" · "+if(r.getString("pricingKind")=="free")"免费赠品"else "固定兑换价 ¥${java.math.BigDecimal(r.getLong("fixedPriceMinor")).movePointLeft(2)}");Text("每人${r.getInt("quantityPerCustomer")}份 · 每日最多${r.getInt("maximumDailyQuantity")}份 · 活动最多${r.getInt("maximumQuantity")}份");Text("发放 ${calendarLocal(r.getString("availableFrom"))} 至 ${calendarLocal(r.getString("availableUntil"))}");Text("商品池："+row.getJSONArray("products").objects().joinToString("、"){it.getString("name")});val h=row.optJSONObject("highlights");if(h!=null)for((k,label)in listOf("issued" to "已发份数","redeemed" to "已核销甜点份数","remaining" to "剩余份数","cost" to "已发承诺成本")){if(h.has(k))Text("$label："+if(k=="cost")"¥${java.math.BigDecimal(h.getString(k)).movePointLeft(2)}"else h.getString(k))}}
@Composable private fun MemberGiftEditor(m:AppModel,row:JSONObject?,back:()->Unit,save:(JSONObject)->Unit){
 var f by remember{mutableStateOf(giftEditor(row))};var error by remember{mutableStateOf("")};var picker by remember{mutableStateOf<Pair<String,String>?>(null)};var names by remember{mutableStateOf(buildMap<String,String>{row?.getJSONArray("products")?.objects()?.forEach{put(it.getString("product_id"),it.getString("name"))};row?.getJSONObject("rule")?.let{r->put(r.getString("couponCalendarVersionId"),"${row.optString("calendar_code")} · 第${row.optInt("calendar_version")}版");r.textOrNull("cardProjectId")?.let{put(it,row.optString("card_project_name"))}}})}
 fun change(k:String,v:Any){f=JSONObject(f.toString()).put(k,v)}
 Panel{Text(if(row==null)"新活动草稿"else "第${row.getInt("version")}版完整规则；保存将新建版本",style=MaterialTheme.typography.titleMedium);TextButton(onClick=back){Text("返回列表")};for((k,l)in listOf("code" to "活动编号","name" to "活动名称"))CustodyField(l,f.getString(k),if(k=="code")40 else 120){change(k,it);if(k=="code")change("expectedVersion",if(it==row?.getString("code"))row.getInt("version")else 0)}
 AssignmentChoice("触发方式",f.getString("trigger"),listOf("targeted" to "选择会员定向发放","card_entry" to "真实入卡审核后触发")){change("trigger",it)};Text("同一活动的触发方式、卡项目、预算换日口径不能改写，调整这些内容请另建活动编号。",style=MaterialTheme.typography.bodySmall)
 val picks=mutableListOf(Triple("couponCalendarVersionId","calendars","券日历版本"),Triple("productIds","products","可兑换商品池"),Triple("dessertProductId","products","组合甜点（可选）"),Triple("cardCodes","audience-cards","人群兴趣卡（可选）"));if(f.getString("trigger")=="card_entry")picks.add(Triple("cardProjectId","projects","入卡项目"));if(f.getString("pricingKind")=="fixed_price")picks.add(Triple("stackingVersionId","stacking","叠加价格规则"))
 for((key,kind,label)in picks){val ids=if(key in listOf("productIds","cardCodes"))f.getJSONArray(key).strings()else listOfNotNull(f.getString(key).takeIf{it.isNotBlank()});Text("$label："+if(ids.isEmpty())"未选择"else ids.joinToString("、"){names[it]?:if(key=="cardCodes")it else "已绑定版本（保留原选择）"});TextButton(onClick={picker=key to kind}){Text("查询并选择$label")};if(key in listOf("dessertProductId","cardCodes")&&ids.isNotEmpty())TextButton(onClick={change(key,if(key=="cardCodes")JSONArray()else "")}){Text("清除$label")}}
 AssignmentChoice("券价格",f.getString("pricingKind"),listOf("free" to "免费赠品","fixed_price" to "固定兑换价")){change("pricingKind",it)};if(f.getString("pricingKind")=="fixed_price")CustodyField("每份兑换价（元）",f.getString("fixedPriceMinor"),16){change("fixedPriceMinor",it)}
 AssignmentChoice("最低会员等级",f.getString("minimumTier"),listOf("" to "不限制等级","member" to "会员","silver" to "银卡","gold" to "金卡","black" to "黑卡")){change("minimumTier",it)};AssignmentChoice("兴趣卡匹配",f.getString("cardMatch"),listOf("any" to "任一张","all" to "全部")){change("cardMatch",it)};AssignmentChoice("等级与兴趣卡关系",f.getString("tierAndCards"),listOf("and" to "同时满足","or" to "满足任一")){change("tierAndCards",it)}
 for((k,l)in listOf("availableFrom" to "开始发放（北京时间）","availableUntil" to "结束发放（北京时间）","quantityPerCustomer" to "每人份数","maximumDailyQuantity" to "每日总份数上限","maximumQuantity" to "活动总份数上限","maximumUnitCostMinor" to "每份最高成本（元）","maximumDailyCostMinor" to "每日成本预算（元）","maximumCostMinor" to "活动总成本预算（元）"))CustodyField(l,f.getString(k),if(k.startsWith("available"))29 else 16){change(k,it)}
 Text("预算为待兑现的商品成本承诺，不是销售额；零预算不会被当成不限额。商品成本未知时后台拒绝发券。")
 AssignmentChoice("预算按哪天计算",f.getString("budgetDateBasis"),listOf("natural" to "自然日","business" to "营业日")){change("budgetDateBasis",it)};if(f.getString("budgetDateBasis")=="business")CustodyField("预算换日时刻 HH:mm",f.getString("budgetCutoff"),5){change("budgetCutoff",it)}
 Text("展示统计");for((k,label)in listOf("issued" to "已发份数","redeemed" to "甜点核销份数","remaining" to "剩余份数","cost" to "已发承诺成本")){val values=f.getJSONArray("highlightMetrics").strings();Row{Checkbox(k in values,{checked->change("highlightMetrics",JSONArray(if(checked)values+k else values-k))});Text(label)}}
 CustodyField("保存原因",f.getString("reason"),500){change("reason",it)};if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error);if(m.identity?.allows("loyalty.configuration.edit")==true)PrimaryAction(onClick={try{save(giftSaveBody(f));error=""}catch(e:Exception){error=e.message?:"请核对活动规则"}},enabled=m.canUseMemberGifts){Text("核对并保存草稿")}
 }
 picker?.let{(key,kind)->GiftOptionPicker(m,kind,emptyList(),if(key=="productIds")100 else if(key=="cardCodes")100 else 1,{picker=null}){chosen->val ids=chosen.map{it.getString(if(key=="cardCodes")"code"else "id")};if(ids.isNotEmpty()){change(key,if(key in listOf("productIds","cardCodes"))JSONArray(ids)else ids.first());names=names+chosen.associate{it.getString(if(key=="cardCodes")"code"else "id") to it.getString("name")}};picker=null}}
}
@Composable private fun GiftOptionPicker(m:AppModel,kind:String,initial:List<JSONObject>,max:Int,close:()->Unit,done:(List<JSONObject>)->Unit){
 var search by remember{mutableStateOf("")};var rows by remember{mutableStateOf<List<JSONObject>>(emptyList())};var chosen by remember{mutableStateOf(initial.associateBy{it.getString("id")})};var next by remember{mutableStateOf<String?>(null)};var loading by remember{mutableStateOf(false)};var error by remember{mutableStateOf("")};val scope=rememberCoroutineScope();var generation by remember{mutableStateOf(0)}
 fun load(more:Boolean=false){if(loading)return;val ticket=generation;scope.launch{loading=true;try{val board=m.memberGiftOptions(kind,search,if(more)next else null);if(ticket==generation){rows=(if(more)rows+board.rows else board.rows).distinctBy{it.getString("id")};next=board.next;error=""}}catch(e:Exception){if(ticket==generation)error=e.message?:"查询失败"}finally{loading=false}}}
 LaunchedEffect(Unit){if(kind!="customers")load()}
 Dialog(onDismissRequest=close,properties=DialogProperties(usePlatformDefaultWidth=false)){Surface(Modifier.fillMaxSize(),color=Paper){LazyColumn(Modifier.safeDrawingPadding().imePadding().padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
 item{Text("查询并选择",style=MaterialTheme.typography.titleLarge);TextButton(onClick=close){Text("返回，保留原选择")};Text("确认后替换原选择，已选${chosen.size}/$max");CustodyField(if(kind=="customers")"会员号或客户编号（至少2字）"else "名称或编号",search,80){search=it;generation++;rows=emptyList();next=null};TextButton(onClick={load()},enabled=!loading&&(kind!="customers"||search.trim().length>=2)){Text(if(loading)"查询中"else "查询")};if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error);for(r in chosen.values)Row{Text(r.getString("name"),Modifier.weight(1f));TextButton(onClick={chosen=chosen-r.getString("id")}){Text("移除")}}}
 items(rows,key={it.getString("id")}){r->val id=r.getString("id");Row{Checkbox(id in chosen,{check->chosen=if(!check)chosen-id else if(max==1)mapOf(id to r)else if(chosen.size<max)chosen+(id to r)else chosen});Text(r.getString("name")+" · "+r.getString("code"))}}
 if(next!=null)item{TextButton(onClick={load(true)},enabled=!loading){Text("加载更多")}};item{PrimaryAction(onClick={done(chosen.values.toList())},enabled=chosen.isNotEmpty()&&!loading){Text("确认选择 ${chosen.size} 项")}}
 }}}
}
