package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import java.util.UUID
const val launchPopupRoot="/api/staff/native-launch-popup"
class LaunchPopupBoard(val data:JSONObject){val actor=data.getString("employeeId");val enabled=data.getInt("protocol")==1&&data.getBoolean("durableCommands");val row=data.getJSONObject("row")}
fun launchPopupCommand(actor:StaffIdentity,b:LaunchPopupBoard,draft:JSONObject,reason:String):LiveCommand{require(b.enabled&&b.actor==actor.employeeId&&actor.allows("community.activity.manage"));val title=draft.getString("title").trim();require(title.length in 1..80&&draft.getString("content").length<=1000&&reason.trim().length in 2..500){"请核对标题、正文和调整原因"};require(draft.getString("frequency") in listOf("daily","session","always"));val ids=draft.getJSONArray("productIds").strings();require(ids.size<=8&&ids.distinct().size==ids.size){"最多8款商品，不能重复"};ids.forEach{UUID.fromString(it)};val body=JSONObject().put("enabled",draft.getBoolean("enabled")).put("title",title).put("content",draft.getString("content")).put("frequency",draft.getString("frequency")).put("productIds",JSONArray(ids)).put("version",b.row.getInt("version")).put("reason",reason.trim());val id=UUID.randomUUID().toString();return LiveCommand(id,actor.employeeId,"调整小程序打开弹窗","community.activity.manage",listOf(LiveStep(launchPopupRoot,body.toString(),"idempotency-key","native-business-$id",JSONObject().put("launchPopup",JSONObject().put("employeeId",actor.employeeId).put("confirmation","${if(body.getBoolean("enabled"))"启用"else "停用"}小程序弹窗：$title\n推荐 ${ids.size} 款商品，按当前顺序展示。\n原因：${reason.trim()}" )).toString())))}
val LiveStep.launchPopupProof:JSONObject? get()=recoveryBody?.let{JSONObject(it).optJSONObject("launchPopup")}
fun validateLaunchPopupReply(text:String,s:LiveStep){val reply=JSONObject(text);val d=reply.getJSONObject("data");val b=JSONObject(s.body);val row=d.getJSONObject("row");require(reply.getJSONObject("meta").getInt("protocol")==1&&reply.getJSONObject("meta").get("replayed") is Boolean&&d.getString("employeeId")==s.launchPopupProof!!.getString("employeeId")&&d.getString("requestKey")==s.key);require(row.getInt("version")==if(b.getInt("version")==0)2 else b.getInt("version")+1);for(k in listOf("enabled","title","content","frequency","productIds"))require(calendarJson(row.get(k))==calendarJson(b.get(k))){"弹窗回执与原内容或商品顺序不一致"}}
