package com.mbox.staff
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import org.json.JSONObject
import org.json.JSONArray
@Composable fun LiveProductOperationsView(m:AppModel,p:JSONObject,close:()->Unit){
 val access=remember{m.priorityAccessKey};val version=remember{m.workspaceVersion};val snapshot=p.optJSONObject("productSnapshot")?:JSONObject();var spec by remember{mutableStateOf(snapshot.optString("salesSpecificationType","custom"))};var acidity by remember{mutableStateOf(snapshot.optJSONObject("tasteProfile")?.textOrNull("acidity")?:"")};var sweetness by remember{mutableStateOf(snapshot.optJSONObject("tasteProfile")?.textOrNull("sweetness")?:"")};var enabled by remember{mutableStateOf(p.getBoolean("recommendationEnabled"))};var single by remember{mutableStateOf(p.getBoolean("recommendationSingleWaveEligible"))};var numbers by remember{mutableStateOf(productNumberBounds.keys.associateWith{p.getInt(it).toString()})};var tags by remember{mutableStateOf(productTagOptions.keys.associateWith{p.getJSONArray(it).strings()})};var search by remember{mutableStateOf(p.getString("searchText"))};var sla by remember{mutableStateOf(p.textOrNull("fulfillmentSlaSeconds")?:"")};var upgrade by remember{mutableStateOf(p.textOrNull("recommendationUpgradeProductId")?:"")};var upgradeName by remember{mutableStateOf(m.productBoard?.products?.find{it.getString("id")==upgrade}?.getString("name")?:if(upgrade.isBlank())"无" else "已配置原商品")};var picker by remember{mutableStateOf(false)}
 val canCost=m.identity?.allows("inventory.cost.view")==true&&p.getString("inventoryControlMode")=="not_managed"&&p.getString("productKind")=="single";val originalCost=p.textOrNull("costAmountMinor")?.toLongOrNull()?.let{java.math.BigDecimal(it).movePointLeft(2).setScale(2).toPlainString()}?:"";var cost by remember{mutableStateOf(originalCost)};var reason by remember{mutableStateOf("")};var error by remember{mutableStateOf("")};var proposed by remember{mutableStateOf<LiveCommand?>(null)}
 LaunchedEffect(m.priorityAccessKey,m.workspaceVersion){if(access!=m.priorityAccessKey||version!=m.workspaceVersion)close()};if(access!=m.priorityAccessKey||version!=m.workspaceVersion)return
 if(picker)ProductConfigurationPicker(m,p.getString("id"),singleOnly=false,close={picker=false}){upgrade=it.getString("id");upgradeName=it.getString("name");picker=false}
 Dialog(onDismissRequest=close,properties=DialogProperties(usePlatformDefaultWidth=false)){Surface(Modifier.fillMaxSize(),color=Paper){LazyColumn(Modifier.safeDrawingPadding().imePadding().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
 item{Row{Text("规格、推荐与出品",Modifier.weight(1f),style=MaterialTheme.typography.titleLarge);TextButton(onClick=close){Text("关闭")}};Text(p.getString("name"));LivePendingView(m);if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error)}
 item{Panel{Text("销售形态与口味",style=MaterialTheme.typography.titleMedium);AssignmentChoice("销售规格",spec,productSpecificationOptions.toList()){spec=it};Text("规格只描述售卖形态，耗料仍以原配方为准。口味是门店主观等级，不代表含糖量或酸碱值。");AssignmentChoice("酸度",acidity,listOf("" to "未评价")+(0..5).map{it.toString() to "$it 级"}){acidity=it};AssignmentChoice("甜度",sweetness,listOf("" to "未评价")+(0..5).map{it.toString() to "$it 级"}){sweetness=it};CustodyField("菜单搜索别名",search,2000){search=it}}}
 item{Panel{Text("推荐与出品规则",style=MaterialTheme.typography.titleMedium);Row{Checkbox(enabled,{enabled=it});Text("参与推荐")};Row{Checkbox(single,{single=it});Text("可以一次出齐")};for((key,label)in listOf("recommendationMinGuests" to "最少人数 1—200","recommendationMaxGuests" to "最多人数 1—200","recommendationPriority" to "推荐优先级 0—1000","recommendationExpectedPrepMinutes" to "预计准备分钟 0—240","recommendationHoldMinutes" to "推荐保留分钟 0—240","kdsPriority" to "出品优先级 0—1000"))CustodyField(label,numbers[key]?:"",4){numbers=numbers+(key to it)};CustodyField("出品时限秒数 30—14400，留空用默认",sla,5){sla=it};Text("升级推荐：$upgradeName");Row{TextButton(onClick={picker=true}){Text("选择原商品")};TextButton(onClick={upgrade="";upgradeName="无"}){Text("取消升级推荐")}}}}
 for((key,options)in productTagOptions)item{Panel{Text(mapOf("recommendationSceneTags" to "适用场景","recommendationIntentTags" to "顾客意图","recommendationTasteTags" to "口味偏好","recommendationDwellTags" to "停留时长")[key]!!,style=MaterialTheme.typography.titleMedium);for((code,label)in options)Row{Checkbox(code in tags[key].orEmpty(),{checked->tags=tags+(key to if(checked)(tags[key].orEmpty()+code).distinct()else tags[key].orEmpty()-code)});Text(label)}}}
 if(canCost)item{Panel{Text("非库存单品成本",style=MaterialTheme.typography.titleMedium);CustodyField("每份成本（元，留空为未知）",cost,12){cost=it};Text("未知成本不会作为0。成本变化影响新订单；库存商品和套餐请到配方页面核对。");if(cost!=originalCost)CustodyField("成本变化原因",reason,500){reason=it}}}
 item{PrimaryAction(onClick={try{val form=JSONObject().put("productSnapshot",JSONObject(snapshot.toString()).put("salesSpecificationType",spec).put("tasteProfile",JSONObject().put("acidity",acidity.toIntOrNull()?:JSONObject.NULL).put("sweetness",sweetness.toIntOrNull()?:JSONObject.NULL))).put("recommendationEnabled",enabled).put("recommendationSingleWaveEligible",single).put("searchText",search.trim().ifBlank{p.getString("code")+" "+p.getString("name")}).put("fulfillmentSlaSeconds",if(sla.isBlank())JSONObject.NULL else sla.toIntOrNull()?:-1).put("recommendationUpgradeProductId",upgrade.ifBlank{null}?:JSONObject.NULL);for((k,v)in numbers)form.put(k,v.toIntOrNull()?:-1);for((k,v)in tags)form.put(k,JSONArray(v));if(canCost&&cost!=originalCost)form.put("costAmountMinor",if(cost.isBlank())JSONObject.NULL else nativeNonnegativeMoney(cost)?:error("成本金额格式不正确")).put("costChangeReason",reason.trim());val patch=productOperationsPatch(p,form,m.identity!!);proposed=productConfigurationCommand(m.identity!!,m.productBoard!!,p,patch,"${p.getString("name")}\n规格：${productSpecificationOptions[spec]} · 酸度${acidity.ifBlank{"未评价"}} · 甜度${sweetness.ifBlank{"未评价"}}\n${if(enabled)"参与" else "不参与"}推荐 · ${numbers["recommendationMinGuests"]}—${numbers["recommendationMaxGuests"]}人\n升级推荐：$upgradeName\n出品时限：${sla.ifBlank{"岗位默认"}}\n${if(canCost&&cost!=originalCost)"新成本：${cost.ifBlank{"未知"}}元\n原因：$reason\n" else ""}其他推荐标签与优先级请按本页清单核对。仅影响后续业务。");error=""}catch(e:Exception){error=e.message?:"请核对内容"}},enabled=m.canUseProducts&&m.productBoard?.data?.optInt("operationalProtocol")==1){Text("核对保存")}}
 }}}
 proposed?.let{c->AlertDialog(onDismissRequest={proposed=null},title={Text("确认商品规则")},text={Text(c.steps[0].productManagementProof!!.getString("confirmation"))},confirmButton={TextButton(onClick={proposed=null;m.executeLive(c);close()},enabled=m.canExecuteLive(c)){Text("确认保存")}},dismissButton={TextButton(onClick={proposed=null}){Text("返回")}})}
}
