package com.mbox.staff
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import kotlinx.coroutines.launch
import org.json.JSONObject
import org.json.JSONArray
@Composable fun LiveCouponCalendarsView(m:AppModel,close:()->Unit){
 val access=remember{m.priorityAccessKey};val version=remember{m.workspaceVersion};var search by remember{mutableStateOf("")};var editing by remember{mutableStateOf<JSONObject?>(null)};var creating by remember{mutableStateOf(false)};var decision by remember{mutableStateOf<JSONObject?>(null)};var decisionAction by remember{mutableStateOf("")};var reason by remember{mutableStateOf("")};var error by remember{mutableStateOf("")};var proposed by remember{mutableStateOf<LiveCommand?>(null)}
 LaunchedEffect(Unit){m.loadCouponCalendars()};LaunchedEffect(m.priorityAccessKey,m.workspaceVersion){if(access!=m.priorityAccessKey||version!=m.workspaceVersion)close()};if(access!=m.priorityAccessKey||version!=m.workspaceVersion)return
 fun propose(action:String,body:JSONObject,confirmation:String){try{val b=m.couponCalendarsBoard?:error("请刷新券规则");proposed=couponCalendarCommand(m.identity!!,CouponCalendarsBoard(JSONObject(b.data.toString()).put("rows",JSONArray(m.couponCalendarRows))),action,body,confirmation);error=""}catch(e:Exception){error=e.message.orEmpty()}}
 Dialog(onDismissRequest=close,properties=DialogProperties(usePlatformDefaultWidth=false)){Surface(Modifier.fillMaxSize(),color=Paper){LazyColumn(Modifier.safeDrawingPadding().imePadding().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
 item{Row{Text("券日历与使用次数",Modifier.weight(1f),style=MaterialTheme.typography.titleLarge);TextButton(onClick=close){Text("关闭")}};LivePendingView(m);Text(m.couponCalendarsState);if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error)}
 if(creating||editing!=null)item{key(editing?.getString("id")?:"new"){CouponCalendarEditor(m,editing,{editing=null;creating=false}){body->propose("save",body,"保存 ${body.getString("code")} 的第${body.getInt("expectedVersion")+1}版草稿\n按本页日期、时段、排除日和使用次数保存。已有券继续保留发放时规则，新草稿需独立审批及发布。")}}}
 else{
 item{CustodyField("按规则编号搜索",search,40){search=it};Row{TextButton(onClick={m.loadCouponCalendars(search)},enabled=!m.busy){Text("查询 / 刷新")};if(m.identity?.allows("loyalty.configuration.edit")==true)TextButton(onClick={creating=true;editing=null},enabled=m.canUseCouponCalendars){Text("新建规则草稿")}}}
 items(m.couponCalendarRows,key={it.getString("id")}){row->Panel{Text("${row.getString("code")} · 第${row.getInt("version")}版 · ${couponCalendarStatuses[row.getString("status")]?:"待核对"}",style=MaterialTheme.typography.titleMedium);CalendarRuleSummary(row);TextButton(onClick={editing=row;creating=false},enabled=m.canUseCouponCalendars){Text(if(m.identity?.allows("loyalty.configuration.edit")==true)"读取规则 / 修订新版本 / 预览" else "读取完整规则与预览")};val actor=m.identity;val status=row.getString("status");for((a,label)in listOf("approve" to "独立审批","publish" to "独立发布","stop_issuing" to "停止新发券")){val permission=if(a=="approve")"loyalty.configuration.approve" else "loyalty.policy.publish";val matches=status==mapOf("approve" to "draft","publish" to "approved","stop_issuing" to "published")[a];val independent=a=="stop_issuing"||row.getString("createdByEmployeeId")!=actor?.employeeId&&(a!="publish"||row.getJSONArray("decisions").objects().none{it.getString("action")=="approve"&&it.getString("employeeId")==actor?.employeeId});if(actor?.allows(permission)==true&&matches&&independent)TextButton(onClick={decision=row;decisionAction=a;reason=""},enabled=m.canUseCouponCalendars){Text(label)}}}}
 if(m.couponCalendarsBoard?.next!=null)item{SecondaryAction(onClick={m.loadMoreCouponCalendars()},enabled=!m.busy){Text("加载更早版本")}}
 if(m.couponCalendarsBoard!=null&&m.couponCalendarRows.isEmpty())item{Text("当前查询范围没有券规则")}
 }
 }}}
 decision?.let{row->AlertDialog(onDismissRequest={decision=null},title={Text("核对券规则${if(decisionAction=="approve")"审批"else if(decisionAction=="publish")"发布"else "停发"}")},text={Column{Text("${row.getString("code")} 第${row.getInt("version")}版\n${if(decisionAction=="stop_issuing")"停止后不再向新券绑定这个版本，已发券承诺保留。"else "请先阅读完整使用日期、时段和次数；编辑、审批、发布须分别由独立员工完成。"}");CustodyField("实际核对原因",reason,500){reason=it}}},confirmButton={TextButton(onClick={propose("decision",JSONObject().put("versionId",row.getString("id")).put("expectedStatus",row.getString("status")).put("action",decisionAction).put("reason",reason.trim()),"${row.getString("code")} 第${row.getInt("version")}版\n${if(decisionAction=="stop_issuing")"停止新发券，已发券保留原规则"else if(decisionAction=="approve")"完成独立审批"else "正式发布券使用规则"}");decision=null}){Text("核对提交")}},dismissButton={TextButton(onClick={decision=null}){Text("返回")}})}
 proposed?.let{c->AlertDialog(onDismissRequest={proposed=null},title={Text("确认券规则操作")},text={Text(c.steps[0].couponCalendarProof!!.getString("confirmation"))},confirmButton={TextButton(onClick={proposed=null;editing=null;creating=false;m.executeLive(c)},enabled=m.canExecuteLive(c)){Text("确认提交")}},dismissButton={TextButton(onClick={proposed=null}){Text("返回")}})}
}
@Composable private fun CalendarRuleSummary(row:JSONObject){val r=row.getJSONObject("rule");Text("${r.getString("dateFrom")} 至 ${r.getString("dateThrough")} · 北京时间");Text((if(r.getString("dateBasis")=="business")"按营业日，${calendarClock(r.getInt("businessDayStartMinute"))}换日"else "按自然日，零点换日")+" · 每周${r.getInt("weekStartsOn")}起算");Text("时段："+r.getJSONArray("windows").objects().joinToString("；"){calendarClock(it.getInt("startMinute"))+" 至 "+(if(it.getInt("endMinute")<it.getInt("startMinute"))"次日"else "")+calendarClock(it.getInt("endMinute"))});Text("绝对有效期：${calendarLocal(r.getString("validFrom"))} 至 ${calendarLocal(r.getString("validUntil"))}");val l=row.getJSONObject("limits");Text("每人每日${l.textOrNull("perCustomerDay")?:"不限"}次 · 每周${l.textOrNull("perCustomerWeek")?:"不限"}次 · 活动总${l.textOrNull("perCustomerCampaign")?:"不限"}次");Text("排除${r.getJSONArray("excludedDates").length()}天；可展开核对星期、日期及发放后期限。")}
@Composable private fun CouponCalendarEditor(m:AppModel,row:JSONObject?,back:()->Unit,save:(JSONObject)->Unit){
 var f by remember{mutableStateOf(calendarEditor(row))};var error by remember{mutableStateOf("")};var preview by remember{mutableStateOf<JSONObject?>(null)};var loading by remember{mutableStateOf(false)};var issuedAt by remember{mutableStateOf("")};var at by remember{mutableStateOf(calendarLocal(java.time.Instant.now().toString()))};var generation by remember{mutableStateOf(0)};val scope=rememberCoroutineScope()
 fun change(k:String,v:Any){f=JSONObject(f.toString()).put(k,v);generation++;preview=null}
 fun calculate(from:String?=null){if(loading)return;try{val body=JSONObject().put("rule",calendarRuleFromEditor(f)).put("at",performanceTime(at));if(issuedAt.isNotBlank())body.put("issuedAt",performanceTime(issuedAt));if(from!=null)body.put("from",from);val ticket=generation;scope.launch{loading=true;try{val result=m.previewCouponCalendar(body);if(ticket==generation){preview=result;error=""}}catch(e:Exception){if(ticket==generation){preview=null;error=e.message?:"预览失败"}}finally{loading=false}}}catch(e:Exception){error=e.message?:"请核对日期和时段"}}
 Panel{Text(if(row==null)"新规则草稿"else "读取第${row.getInt("version")}版，修订将另建新版本",style=MaterialTheme.typography.titleMedium);TextButton(onClick=back){Text("返回规则列表")};CustodyField("规则编号（新活动使用新编号）",f.getString("code"),40){change("code",it);f.put("expectedVersion",if(it==row?.getString("code"))(row?.getInt("version")?:0)else 0)};Text("同编号换日时刻与周起点不能改写，避免重置既有使用计数。");for((k,label)in listOf("dateFrom" to "起始日期 YYYY-MM-DD","dateThrough" to "最后日期 YYYY-MM-DD","validFrom" to "绝对开始 YYYY-MM-DD HH:mm:ss","validUntil" to "绝对截止 YYYY-MM-DD HH:mm:ss"))CustodyField(label,f.getString(k),29){change(k,it)};AssignmentChoice("日期归属",f.getString("dateBasis"),listOf("natural" to "自然日","business" to "营业日")){change("dateBasis",it)};if(f.getString("dateBasis")=="business")CustodyField("换日时刻 HH:mm",f.getString("cutoff"),5){change("cutoff",it)};AssignmentChoice("每周使用次数从哪天起算",f.getString("weekStartsOn"),(1..7).map{it.toString() to "周"+listOf("一","二","三","四","五","六","日")[it-1]}){change("weekStartsOn",it)}
  Text("可用星期");for(n in 1..7){val days=(0 until f.getJSONArray("weekdays").length()).map{f.getJSONArray("weekdays").getInt(it)};Row{Checkbox(n in days,{checked->change("weekdays",JSONArray(if(checked)(days+n).sorted()else days-n))});Text("周"+listOf("一","二","三","四","五","六","日")[n-1])}}
  Text("每日时段，结束早于开始表示跨午夜；全天为00:00至24:00。",style=MaterialTheme.typography.bodySmall)
  for((i,w)in f.getJSONArray("windows").objects().withIndex()){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(w.getString("from"),{v->change("windows",JSONArray(f.getJSONArray("windows").objects().mapIndexed{j,r->if(i==j)JSONObject(r.toString()).put("from",v)else r}))},label={Text("开始")},modifier=Modifier.weight(1f));OutlinedTextField(w.getString("to"),{v->change("windows",JSONArray(f.getJSONArray("windows").objects().mapIndexed{j,r->if(i==j)JSONObject(r.toString()).put("to",v)else r}))},label={Text("结束")},modifier=Modifier.weight(1f))};if(f.getJSONArray("windows").length()>1)TextButton(onClick={change("windows",JSONArray(f.getJSONArray("windows").objects().filterIndexed{j,_->j!=i}))}){Text("移除此时段")}}
  TextButton(onClick={change("windows",JSONArray(f.getJSONArray("windows").objects()+JSONObject().put("from","18:00").put("to","20:00")))},enabled=f.getJSONArray("windows").length()<12){Text("添加时段，最多12段")};OutlinedTextField(f.getString("excludedDates"),{change("excludedDates",it.take(40271))},label={Text("排除日期，逗号或换行分隔")},minLines=2,maxLines=6,modifier=Modifier.fillMaxWidth());CustodyField("发放后有效天数（可留空）",f.getString("relativeDays"),4){change("relativeDays",it)};if(f.getString("relativeDays").isNotBlank())AssignmentChoice("发放后截止口径",f.getString("relativeBasis"),listOf("elapsed" to "连续满24小时","natural_end" to "最后一个自然日结束","business_end" to "最后一个营业日结束")){change("relativeBasis",it)};Text("相对期限与绝对有效期取交集，发券时不会沿用模拟时间。",style=MaterialTheme.typography.bodySmall)
  for((k,label)in listOf("perCustomerDay" to "每人每日次数","perCustomerWeek" to "每人每周次数","perCustomerCampaign" to "每人活动总次数"))CustodyField("$label（空白不限）",f.getString(k),7){change(k,it)};CustodyField("保存原因",f.getString("reason"),500){change("reason",it)}
  Foldout("模拟时间与发放后期限"){CustodyField("预览当前时间（北京时间）",at,29){at=it;generation++;preview=null};CustodyField("模拟发放时间（留空不模拟）",issuedAt,29){issuedAt=it;generation++;preview=null}}
  Text(error,color=MaterialTheme.colorScheme.error);SecondaryAction(onClick={calculate()},enabled=!loading&&!m.busy){Text(if(loading)"计算中"else "预览可用日历")};if(m.identity?.allows("loyalty.configuration.edit")==true)PrimaryAction(onClick={try{save(calendarSaveBody(f));error=""}catch(e:Exception){error=e.message?:"请核对规则"}},enabled=m.canUseCouponCalendars&&!loading){Text("核对并保存新草稿")}
  preview?.let{p->Text("仅预览，不发券。",style=MaterialTheme.typography.titleSmall);Text("下一可用：${p.textOrNull("nextAvailableAt")?.let(::calendarLocal)?:"没有后续可用时段"}");Text("最后截止：${p.textOrNull("lastAvailableUntil")?.let(::calendarLocal)?:"没有可用时段"}");for(day in p.getJSONArray("calendar").objects()){Text(day.getString("date"),style=MaterialTheme.typography.titleSmall);val windows=day.getJSONArray("windows").objects();Text(if(windows.isEmpty())day.optJSONArray("reasons")?.strings()?.joinToString("；")?:"无可用时段"else windows.joinToString("；"){calendarLocal(it.getString("from"))+" 至 "+calendarLocal(it.getString("until"))})};p.textOrNull("nextCalendarDate")?.let{next->TextButton(onClick={calculate(next)},enabled=!loading){Text("预览后续日期")}}}
 }
}
