package com.mbox.staff
import org.json.JSONObject
import java.util.UUID
const val publicationRoot="/api/staff/native-publication"
val publicationPermissions=mapOf("profile-draft" to "customer.public-profile.manage","profile-publish" to "customer.public-profile.publish","profile-withdraw" to "customer.public-profile.publish","privacy-draft" to "privacy.policy.manage","privacy-publish" to "privacy.policy.publish","privacy-withdraw" to "privacy.policy.publish","contact" to "customer.experience.feature.manage")
class PublicationBoard(val data:JSONObject){val actor=data.getString("employeeId");val enabled=data.getInt("protocol")==1&&data.getBoolean("durableCommands");val profiles=data.getJSONArray("profiles").objects();val policies=data.getJSONArray("policies").objects();val employees=data.getJSONArray("employees").objects();val permissions=data.getJSONArray("permissions").strings()}
fun publicationCommand(actor:StaffIdentity,b:PublicationBoard,action:String,body:JSONObject,confirmation:String):LiveCommand{
 val permission=publicationPermissions[action]?:error("未知操作");require(b.enabled&&b.actor==actor.employeeId&&permission in b.permissions&&actor.allows(permission));require(body.getString("reason").trim().length in 2..500){"请填写2至500字原因"}
 val section=if(action.startsWith("profile"))"profile" else if(action.startsWith("privacy"))"privacy" else "contact";body.put("expectedVersion",b.data.getJSONObject("versions").getString(section))
 if(action=="profile-draft"){require(b.employees.any{it.getString("id")==body.getString("employeeId")});require(body.getString("publicDisplayName").trim().length in 1..80)}
 if(action=="privacy-draft"){for((k,bounds) in mapOf("operatorName" to (2..200),"contact" to (2..500),"dataRetentionPolicyVersion" to (2..80),"thirdPartyRegisterVersion" to (2..80)))require(body.getString(k).trim().length in bounds){"请完整填写运营主体、联系渠道和引用规则版本"};require(body.getString("content").trim().length in 80..50000){"政策正文须为80至50000字"};require(Regex("^[A-Za-z0-9][A-Za-z0-9._-]{1,63}$").matches(body.getString("policyVersion"))){"政策版本编号格式不正确"}}
 if(action=="privacy-publish")require(body.getString("approvedBy").trim().length in 2..200){"请填写实际批准人"}
 if(action=="contact"){val c=body.getJSONObject("configuration");require(Regex("^[+0-9][0-9 -]{5,30}$").matches(c.getString("phone"))){"电话格式不正确"};for(k in listOf("phoneLabel","wecomName"))require(c.getString(k).trim().length in 2..40){"电话名称和企业微信名称须为2至40字"};c.textOrNull("wecomQrImageUrl")?.let{require(Regex("^/api/public/media-assets/MA[0-9A-F]{32}$").matches(it)){"请从图片库选择二维码"}}}
 if(action.endsWith("publish")||action.endsWith("withdraw")){
  val row=if(section=="profile")b.profiles.find{it.getString("id")==body.getString("profileId")} else b.policies.find{it.getString("policyVersion")==body.getString("policyVersion")};require(row!=null){"原内容不存在，请刷新"};require(row.getString("status")==if(action.endsWith("publish"))"draft" else "published"){"原发布状态已变化"}
  if(action.endsWith("publish")){require(row.textOrNull("draftedByEmployeeId")!=actor.employeeId&&(section!="profile"||row.getString("employeeId")!=actor.employeeId)){"必须由独立员工发布"};require(body.getString("approvalReference").trim().length in 8..240){"请填写真实批准材料编号"}}
 }
 val id=UUID.randomUUID().toString();return LiveCommand(id,actor.employeeId,"顾客公开内容变更",permission,listOf(LiveStep("$publicationRoot/$action",body.toString(),"idempotency-key","native-business-$id",JSONObject().put("publication",JSONObject().put("action",action).put("employeeId",actor.employeeId).put("confirmation",confirmation)).toString())))
}
val LiveStep.publicationProof:JSONObject? get()=recoveryBody?.let{JSONObject(it).optJSONObject("publication")}
fun securePublicationCommand(c:LiveCommand,store:(String,String)->Unit):LiveCommand{val s=c.steps.firstOrNull()?:return c;val p=s.publicationProof?:return c;require(c.steps.size==1);if(p.has("payloadKey"))return c;store(c.id,s.body);p.remove("confirmation");return c.copy(title="待核对公开内容原请求",steps=listOf(s.copy(body="{}",recoveryBody=JSONObject().put("publication",p.put("payloadKey",c.id)).toString())))}
fun validatePublicationReply(text:String,step:LiveStep,body:JSONObject){val root=JSONObject(text);val d=root.getJSONObject("data");val p=step.publicationProof!!;val action=p.getString("action");val r=d.getJSONObject("result");require(root.getJSONObject("meta").getInt("protocol")==1&&root.getJSONObject("meta").get("replayed") is Boolean);require(d.getString("employeeId")==p.getString("employeeId")&&d.getString("requestKey")==step.key&&d.getString("action")==action)
 if(action=="contact")require(r.getString("featureCode")=="customer.support.contact"&&r.getString("rolloutState")==body.getString("rolloutState"))else{UUID.fromString(r.getString("id"));require(r.getString("status")==when{action.endsWith("draft")->"draft";action.endsWith("publish")->"published";else->"withdrawn"});if(body.has("profileId"))require(r.getString("id")==body.getString("profileId"));if(body.has("policyVersion"))require(r.getString("policyVersion")==body.getString("policyVersion"));if(action=="profile-draft")require(r.getString("employeeId")==body.getString("employeeId")&&r.getString("publicDisplayName")==body.getString("publicDisplayName"));if(action=="privacy-draft")require(r.getString("contentSha256")==java.security.MessageDigest.getInstance("SHA-256").digest(body.getString("content").trim().toByteArray(Charsets.UTF_8)).joinToString(""){"%02x".format(it)})}
}
