package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import java.util.UUID
import java.time.LocalDate
const val memberGiftRoot="/api/staff/native-member-gifts"
val memberGiftStatuses=mapOf("draft" to "草稿","approved" to "待发布","published" to "已发布","stopped" to "已停发","pending" to "等待发放","blocked" to "暂时受阻","issued" to "已发券","duplicate" to "已处理过","cancelled" to "已取消")
class MemberGiftsBoard(val data:JSONObject){val actor=data.getString("employeeId");val rows=data.getJSONArray("rows").objects();val enabled=data.getInt("protocol")==1&&data.getBoolean("durableCommands");val next=data.textOrNull("next")}
fun giftEditor(row:JSONObject?):JSONObject{val r=row?.getJSONObject("rule");val a=r?.getJSONObject("audience");val today=LocalDate.now(java.time.ZoneId.of("Asia/Shanghai"));val f=JSONObject().put("code",row?.getString("code")?:"").put("name",row?.getString("name")?:"").put("expectedVersion",row?.getInt("version")?:0).put("trigger",r?.getString("trigger")?:"targeted").put("pricingKind",r?.getString("pricingKind")?:"free").put("budgetDateBasis",r?.getString("budgetDateBasis")?:"natural").put("budgetCutoff",calendarClock(r?.getInt("budgetDayStartMinute")?:0)).put("availableFrom",r?.getString("availableFrom")?.let(::calendarLocal)?:"$today 00:00").put("availableUntil",r?.getString("availableUntil")?.let(::calendarLocal)?:"${today.plusDays(30)} 00:00").put("minimumTier",a?.textOrNull("minimumTier")?:"").put("cardMatch",a?.getString("cardMatch")?:"any").put("tierAndCards",a?.getString("tierAndCards")?:"and").put("cardCodes",a?.getJSONArray("cardCodes")?:JSONArray()).put("productIds",r?.getJSONArray("productIds")?:JSONArray()).put("highlightMetrics",r?.optJSONArray("highlightMetrics")?:JSONArray(listOf("issued","redeemed","remaining"))).put("reason","")
 for(k in listOf("couponCalendarVersionId","stackingVersionId","cardProjectId","dessertProductId"))f.put(k,r?.textOrNull(k)?:"")
 for(k in listOf("quantityPerCustomer","maximumQuantity","maximumDailyQuantity"))f.put(k,r?.getInt(k)?.toString()?:if(k=="quantityPerCustomer")"1"else "")
 for(k in listOf("fixedPriceMinor","maximumCostMinor","maximumDailyCostMinor","maximumUnitCostMinor"))f.put(k,r?.textOrNull(k)?.toLongOrNull()?.let{java.math.BigDecimal(it).movePointLeft(2).toPlainString()}?:"")
 return f
}
fun giftMoney(s:String):Long{require(Regex("^\\d{1,12}(?:\\.\\d{1,2})?$").matches(s.trim())){"金额须为非负人民币金额，最多两位小数"};return java.math.BigDecimal(s.trim()).movePointRight(2).longValueExact()}
fun giftSaveBody(f:JSONObject):JSONObject{
 val code=f.getString("code").trim();require(Regex("^[A-Z][A-Z0-9_]{1,39}$").matches(code)){"编号须2至40位大写字母、数字或下划线"};val name=f.getString("name").trim();require(name.length in 2..120){"活动名称须2至120字"};val trigger=f.getString("trigger");val pricing=f.getString("pricingKind");val basis=f.getString("budgetDateBasis");require(trigger in listOf("targeted","card_entry")&&pricing in listOf("free","fixed_price")&&basis in listOf("natural","business"))
 fun selected(k:String):String{val id=f.getString(k);UUID.fromString(id);return id}
 val r=JSONObject().put("trigger",trigger).put("pricingKind",pricing).put("cardProjectId",if(trigger=="card_entry")selected("cardProjectId") else JSONObject.NULL).put("couponCalendarVersionId",selected("couponCalendarVersionId")).put("fixedPriceMinor",if(pricing=="fixed_price")giftMoney(f.getString("fixedPriceMinor")).also{require(it>0){"固定兑换价必须大于零"}}else JSONObject.NULL).put("stackingVersionId",if(pricing=="fixed_price")selected("stackingVersionId")else JSONObject.NULL).put("currency","CNY").put("budgetDateBasis",basis).put("budgetDayStartMinute",if(basis=="natural")0 else calendarMinute(f.getString("budgetCutoff")))
 val from=performanceTime(f.getString("availableFrom"));val until=performanceTime(f.getString("availableUntil"));require(serverInstant(until)>serverInstant(from)){"结束时间须晚于开始"};r.put("availableFrom",from).put("availableUntil",until)
 for(k in listOf("quantityPerCustomer","maximumQuantity","maximumDailyQuantity")){val n=f.getString(k).toIntOrNull();require(n!=null&&n in 1..if(k=="quantityPerCustomer")100 else 1000000){"请填写有效份数上限"};r.put(k,n)}
 for(k in listOf("maximumCostMinor","maximumDailyCostMinor","maximumUnitCostMinor"))r.put(k,giftMoney(f.getString(k)))
 require(r.getInt("quantityPerCustomer")<=r.getInt("maximumDailyQuantity")&&r.getInt("maximumDailyQuantity")<=r.getInt("maximumQuantity")&&r.getLong("maximumDailyCostMinor")<=r.getLong("maximumCostMinor")){"每人、每日和活动总上限不能矛盾"}
 val products=f.getJSONArray("productIds").strings().sorted();require(products.size in 1..100&&products.distinct().size==products.size){"请选择1至100种商品"};products.forEach{UUID.fromString(it)};r.put("productIds",JSONArray(products));if(f.getString("dessertProductId").isNotBlank()){require(r.getInt("quantityPerCustomer")==1){"组合甜点每人限一套"};r.put("dessertProductId",selected("dessertProductId"))}
 val tier=f.getString("minimumTier");require(tier in listOf("","member","silver","gold","black"));val match=f.getString("cardMatch");val relation=f.getString("tierAndCards");require(match in listOf("any","all")&&relation in listOf("and","or"));r.put("audience",JSONObject().put("minimumTier",if(tier.isBlank())JSONObject.NULL else tier).put("cardCodes",JSONArray(f.getJSONArray("cardCodes").strings().distinct().sorted())).put("cardMatch",match).put("tierAndCards",relation));r.put("highlightMetrics",f.getJSONArray("highlightMetrics"));return JSONObject().put("code",code).put("name",name).put("rule",r).put("expectedVersion",f.getInt("expectedVersion")).put("reason",f.getString("reason").trim())
}
fun memberGiftCommand(actor:StaffIdentity,b:MemberGiftsBoard,action:String,body:JSONObject,confirmation:String):LiveCommand{
 require(action in listOf("save","decision","target","control","refund"));val permission=if(action=="save")"loyalty.configuration.edit" else if(action=="decision"&&body.getString("action")=="approve")"loyalty.configuration.approve" else "loyalty.policy.publish";require(b.enabled&&b.actor==actor.employeeId&&actor.allows(permission));require(body.getString("reason").trim().length in 2..500){"请输入2至500字原因"}
 if(action!="save"){val row=b.rows.find{it.getString("id")==(if(action=="refund")body.getString("refundId")+":"+body.getString("reservationId")else body.getString(if(action=="control")"jobId"else "versionId"))}?:error("原记录已不可见，请重新读取");require(row.getString("nativeVersion")==body.getString("expectedVersion"));if(action=="decision"&&body.getString("action")!="stop"){require(row.getString("created_by_employee_id")!=actor.employeeId){"创建人不能审批或发布本人活动"};if(body.getString("action")=="publish")require(row.textOrNull("approved_by_employee_id")!=actor.employeeId){"审批人不能发布本人审批的活动"}}}
 if(action=="refund"){require(body.getString("evidenceReference").trim().length in 2..200){"请填写原规则或实际补偿凭证"};if(body.getString("action")=="replacement_coupon")UUID.fromString(body.getString("replacementBenefitId"))}
 if(action=="target"){val ids=body.getJSONArray("customerIds").strings();require(ids.size in 1..50&&ids.distinct().size==ids.size);ids.forEach{UUID.fromString(it)};require(Regex("^[A-Za-z0-9][A-Za-z0-9_.:-]{0,99}$").matches(body.getString("cycleKey"))){"批次须为1至100位字母数字或 . _ : -"}}
 val id=UUID.randomUUID().toString();val proof=JSONObject().put("employeeId",actor.employeeId).put("action",action).put("confirmation",confirmation+"\n原因：${body.getString("reason")}");return LiveCommand(id,actor.employeeId,"会员赠礼操作",permission,listOf(LiveStep("$memberGiftRoot/$action",body.toString(),"idempotency-key","native-business-$id",JSONObject().put("memberGift",proof).toString())))
}
val LiveStep.memberGiftProof:JSONObject? get()=recoveryBody?.let{JSONObject(it).optJSONObject("memberGift")}
private fun canonicalGift(r:JSONObject):String{val c=JSONObject(r.toString());for(k in listOf("availableFrom","availableUntil"))c.put(k,serverInstant(c.getString(k)).toString());if(c.isNull("dessertProductId"))c.remove("dessertProductId");c.put("productIds",JSONArray(c.getJSONArray("productIds").strings().sorted()));return calendarJson(c)}
fun validateMemberGiftReply(text:String,s:LiveStep){val r=JSONObject(text);val d=r.getJSONObject("data");val p=s.memberGiftProof!!;val b=JSONObject(s.body);require(r.getJSONObject("meta").getInt("protocol")==1&&r.getJSONObject("meta").get("replayed") is Boolean);require(d.getString("employeeId")==p.getString("employeeId")&&d.getString("action")==p.getString("action")&&d.getString("requestKey")==s.key&&calendarJson(d.getJSONObject("accepted"))==calendarJson(b)){"赠礼回执不属于原请求"};val row=d.getJSONObject("row");when(p.getString("action")){
 "save"->{UUID.fromString(row.getString("id"));require(row.getString("code")==b.getString("code")&&row.getString("name")==b.getString("name")&&row.getInt("version")==b.getInt("expectedVersion")+1&&row.getString("status")=="draft"&&row.getString("created_by_employee_id")==p.getString("employeeId")&&canonicalGift(row.getJSONObject("rule"))==canonicalGift(b.getJSONObject("rule"))){"保存的活动与原规则不一致"}}
 "decision"->{val a=b.getString("action");val state=mapOf("approve" to "approved","publish" to "published","stop" to "stopped")[a]?:error("未知决策");require(row.getString("id")==b.getString("versionId")&&row.getString("status")==state&&row.getString(state+"_by_employee_id")==p.getString("employeeId")){"活动审核回执不一致"}}
 "target"->{val jobs=row.getJSONArray("items").objects();require(jobs.size==b.getJSONArray("customerIds").length()&&jobs.all{UUID.fromString(it.getString("jobId"));it.getString("status") in listOf("pending","blocked","issued","duplicate","cancelled")&&it.get("replayed") is Boolean}){"发放任务回执不完整"}}
 "refund"->{require(row.getString("refund_id")==b.getString("refundId")&&row.getString("reservation_id")==b.getString("reservationId")&&row.getString("action")==b.getString("action")&&row.getString("reason")==b.getString("reason")&&row.getString("evidence_reference")==b.getString("evidenceReference")&&row.textOrNull("replacement_benefit_id")==b.textOrNull("replacementBenefitId")){"退款券权益复核回执不一致"};if(b.getString("action")=="replacement_coupon")require(row.getInt("replacement_quantity")>0)}
 "control"->require(row.getString("jobId")==b.getString("jobId")&&if(b.getString("action")=="cancel")row.getString("status")=="cancelled"&&!row.getBoolean("scheduled")else row.getBoolean("scheduled")&&row.getString("status") in listOf("pending","blocked")){"任务处理回执不一致"}
 else->error("未知操作")
}}
