package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import java.util.UUID
const val marketingRoot="/api/staff/native-marketing"
val marketingChannels=listOf("wechat" to "微信","sms" to "短信","phone" to "电话")
val marketingPurposes=listOf("own_activities" to "本店活动","mbox_joint_activities" to "本店联系的联合活动")
val marketingStates=mapOf("draft" to "待审核","approved" to "待发布","published" to "已发布","stopped" to "已停止","queued" to "等待核验","blocked" to "暂不能发送","dispatching" to "正在交给渠道","submitted" to "渠道已受理，尚未确认送达","sent" to "渠道确认送达","unknown" to "结果未知，禁止自动重发","cancelled" to "已取消","failed" to "渠道确认失败")
val marketingReasons=mapOf("channel_not_configured" to "渠道尚未配置","recipient_not_verified" to "收件身份尚未核实","channel_authority_missing" to "缺少渠道授权","outside_contact_window" to "不在允许联系时段","frequency_limit" to "已到联系频次上限","previous_delivery_unknown" to "此前任务结果未知","verification_unavailable" to "暂时无法完成核验","consent_changed" to "本人许可已变化","notice_stopped" to "告知已停用","task_expired" to "任务已过期","sender_permission_revoked" to "发起人权限已撤销","not_consented" to "没有本人许可","consent_changed_since_queue" to "排队后许可已变化","consent_expired_or_scope_changed" to "许可已过期或范围变化","staff_cancelled" to "员工已取消","notice_unavailable" to "告知不可用")
fun marketingNoticeRule(input:JSONObject):JSONObject{
 val r=JSONObject(input.toString());for((key,max)in listOf("operatorName" to 200,"operatorContact" to 300,"summary" to 3000,"withdrawalInstructions" to 1000)){val v=r.getString(key).trim();require(v.length in 2..max){"请完整填写经营主体、用途和停止方法"};r.put(key,v)}
 for((key,choices)in listOf("channels" to marketingChannels,"purposes" to marketingPurposes)){val v=r.getJSONArray(key).strings();require(v.isNotEmpty()&&v.distinct().size==v.size&&v.all{it in choices.map{p->p.first}});r.put(key,JSONArray(v.sorted()))}
 val categories=r.getJSONArray("dataCategories").strings().map{it.trim()};require(categories.size in 1..20&&categories.distinct().size==categories.size&&categories.all{it.length in 2..80}){"资料类型须为1至20项且不重复"};r.put("dataCategories",JSONArray(categories));val days=r.getJSONArray("weekdays");val values=(0 until days.length()).map{days.getInt(it)};require(values.isNotEmpty()&&values.distinct().size==values.size&&values.all{it in 1..7});r.put("weekdays",JSONArray(values.sorted()));require(serverInstant(r.getString("validUntil"))>serverInstant(r.getString("validFrom"))){"告知结束须晚于开始"};require(r.getInt("consentDays") in 1..3660);require(r.getInt("contactStartMinute") in 0..1439&&r.getInt("contactEndMinute") in 1..1440&&r.getInt("contactStartMinute")<r.getInt("contactEndMinute")){"联系时段须正序且不能跨午夜"};require(r.getInt("maximumPerDay") in 1..100&&r.getInt("maximumPerMonth") in 1..1000&&r.getInt("maximumPerDay")<=r.getInt("maximumPerMonth"));require(r.getString("sharingMode")=="no_partner_list");return r
}
fun marketingCommand(actor:StaffIdentity,board:CouponCalendarsBoard,action:String,row:JSONObject?,input:JSONObject):LiveCommand{
 require(board.enabled&&board.actor==actor.employeeId);require(action in listOf("save","decision","refusal","queue","cancel"));val b=JSONObject(input.toString());val permission=when(action){"save"->"marketing.notice.edit";"decision"->if(b.getString("decision")=="approve")"marketing.notice.approve"else "marketing.notice.publish";"refusal"->"marketing.refusal.record";else->"marketing.send"};require(actor.allows(permission)){"无此营销操作权限"}
 if(action!="queue"){val reason=b.getString("reason").trim();require(reason.length in 2..500){"填写2至500字原因"};b.put("reason",reason)}
 if(action in listOf("decision","queue","cancel")){require(row!=null&&board.rows.any{it.getString("id")==row.getString("id")&&it.getString("nativeVersion")==row.getString("nativeVersion")}){"原记录已变化，请重新读取"};b.put("expectedVersion",row.getString("nativeVersion"));b.put(if(action=="cancel")"jobId"else "noticeId",row.getString("id"))}
 when(action){
 "save"->{require(Regex("^[A-Z][A-Z0-9_]{1,39}$").matches(b.getString("code"))&&b.getString("code")==board.data.textOrNull("code")){"先读取此编号的最新版本"};b.put("expectedVersion",board.data.getInt("latestVersion"));b.put("rule",marketingNoticeRule(b.getJSONObject("rule")))}
 "decision"->{val decision=b.getString("decision");require(decision in listOf("approve","publish","stop")&&row!!.getString("status")==mapOf("approve" to "draft","publish" to "approved","stop" to "published")[decision]);if(decision!="stop")require(row!!.getString("createdByEmployeeId")!=actor.employeeId){"编辑与审核、发布须分离"};if(decision=="publish")require(row!!.getJSONArray("decisions").let{d->(0 until d.length()).none{d.getJSONObject(it).getString("action")=="approve"&&d.getJSONObject(it).getString("employee_id")==actor.employeeId}}){"发布人不能是审核人"}}
 "queue"->{UUID.fromString(b.getString("customerId"));require(row!!.getString("status")=="published");require(b.getString("channel") in row.getJSONObject("rule").getJSONArray("channels").strings()&&b.getString("purpose") in row.getJSONObject("rule").getJSONArray("purposes").strings());require(Regex("^[A-Za-z0-9][A-Za-z0-9:_-]{7,127}$").matches(b.getString("campaignKey")));val content=b.getString("content").trim();require(content.length in 2..2000);b.put("content",content);serverInstant(b.getString("expiresAt"))}
 "cancel"->require(row!!.getString("status") in listOf("queued","blocked")){"仅未交给渠道的任务可以取消"}
 "refusal"->UUID.fromString(b.getString("customerId"))
 }
 val label=mapOf("save" to "保存营销告知草稿","decision" to "审核 / 发布营销告知","refusal" to "记录顾客拒绝全部营销","queue" to "建立联系任务","cancel" to "取消未发送任务").getValue(action);val id=UUID.randomUUID().toString()
 return LiveCommand(id,actor.employeeId,label,permission,listOf(LiveStep("$marketingRoot/$action",b.toString(),"idempotency-key","native-business-$id",JSONObject().put("marketing",JSONObject().put("employeeId",actor.employeeId).put("action",action).put("before",row?:JSONObject.NULL).put("confirmation","$label\n"+when(action){"save"->"${b.getString("code")} 第${b.getInt("expectedVersion")+1}版";"decision"->"${row!!.getString("code")} 第${row.getInt("version")}版 · ${mapOf("approve" to "审核","publish" to "发布","stop" to "停止")[b.getString("decision")]}";"queue"->"顾客 ${b.getString("customerId")}\n${marketingChannels.toMap()[b.getString("channel")]} · ${marketingPurposes.toMap()[b.getString("purpose")]}\n${b.getString("content")}\n截至 ${calendarLocal(b.getString("expiresAt"))}\n排队仍须核验本人许可与渠道；不表示已送达。";"refusal"->"顾客 ${b.getString("customerId")}\n确认顾客明确拒绝全部营销。此操作不代替顾客授予许可。";else->"原任务 ${row!!.getString("campaignKey")}"}+(b.textOrNull("reason")?.let{"\n原因：$it"}?:""))).toString())))
}
val LiveStep.marketingProof:JSONObject? get()=recoveryBody?.let{JSONObject(it).optJSONObject("marketing")}
fun validateMarketingReply(text:String,s:LiveStep){val r=JSONObject(text);val d=r.getJSONObject("data");val p=s.marketingProof!!;val b=JSONObject(s.body);val action=p.getString("action");require(r.getJSONObject("meta").getInt("protocol")==1&&r.getJSONObject("meta").get("replayed") is Boolean&&d.getString("employeeId")==p.getString("employeeId")&&d.getString("requestKey")==s.key&&d.getString("action")==action&&calendarJson(d.getJSONObject("accepted"))==calendarJson(b));val row=d.getJSONObject("row");if(action=="refusal"){require(row.getBoolean("stopped")&&row.getString("customerId")==b.getString("customerId"));return};require(Regex("^[a-f0-9]{64}$").matches(row.getString("nativeVersion")));val before=p.optJSONObject("before")
 when(action){"save"->{require(row.getString("code")==b.getString("code")&&row.getInt("version")==b.getInt("expectedVersion")+1&&row.getString("status")=="draft"&&row.getString("createdByEmployeeId")==p.getString("employeeId")&&row.getString("reason")==b.getString("reason"));val a=JSONObject(b.getJSONObject("rule").toString());val c=JSONObject(row.getJSONObject("rule").toString());for(k in listOf("validFrom","validUntil")){require(serverInstant(a.getString(k))==serverInstant(c.getString(k)));a.remove(k);c.remove(k)};require(calendarJson(a)==calendarJson(c))};"decision"->{require(row.getString("id")==b.getString("noticeId")&&row.getString("status")==mapOf("approve" to "approved","publish" to "published","stop" to "stopped")[b.getString("decision")]&&calendarJson(row.getJSONObject("rule"))==calendarJson(before!!.getJSONObject("rule")));require(row.getJSONArray("decisions").let{a->(0 until a.length()).any{a.getJSONObject(it).getString("action")==b.getString("decision")&&a.getJSONObject(it).getString("employee_id")==p.getString("employeeId")}})};"queue"->{for(k in listOf("customerId","noticeId","channel","purpose","campaignKey","content"))require(row.getString(k)==b.getString(k));require(serverInstant(row.getString("expiresAt"))==serverInstant(b.getString("expiresAt"))&&row.getString("status") in marketingStates.keys)};"cancel"->{require(row.getString("id")==b.getString("jobId")&&row.getString("status")=="cancelled");for(k in listOf("customerId","noticeId","campaignKey","content","channel","purpose","expiresAt"))require(row.getString(k)==before!!.getString(k))}}
}
