package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import java.util.UUID
const val stackingPolicyRoot="/api/staff/native-stacking-policies"
typealias StackingPoliciesBoard=CouponCalendarsBoard
val stackingSwitches=listOf("allowMemberPrice" to "允许与会员价叠加","allowBundlePrice" to "允许用于套餐价商品","allowCheckoutUpgrade" to "允许用于升级套餐","allowOtherCoupons" to "允许多张优惠券叠加","allowPoints" to "允许与积分抵扣叠加")
val stackingStages=mapOf("member" to "会员价","coupon" to "优惠券","points" to "积分")
val stackingOrders=listOf(listOf("member","coupon","points"),listOf("member","points","coupon"),listOf("coupon","member","points"),listOf("coupon","points","member"),listOf("points","member","coupon"),listOf("points","coupon","member"))
fun stackingEditor(row:JSONObject?):JSONObject{val p=row?.getJSONObject("policy");val f=JSONObject().put("code",row?.getString("code")?:"").put("expectedVersion",row?.getInt("version")?:0).put("maxCoupons",(p?.getInt("maxCoupons")?:1).toString()).put("order",p?.getJSONArray("calculationOrder")?.strings()?.joinToString(",")?:"member,coupon,points").put("maximumDiscountMinor",p?.textOrNull("maximumDiscountMinor")?.toLongOrNull()?.let{java.math.BigDecimal(it).movePointLeft(2).toPlainString()}?:"").put("minimumPayableMinor",p?.getLong("minimumPayableMinor")?.let{java.math.BigDecimal(it).movePointLeft(2).toPlainString()}?:"0").put("reason","");for((k,_)in stackingSwitches)f.put(k,p?.getBoolean(k)?:false);return f}
fun stackingPolicyFromEditor(f:JSONObject):JSONObject{val p=JSONObject();for((k,_)in stackingSwitches)p.put(k,f.getBoolean(k));val max=f.getString("maxCoupons").toIntOrNull();require(max!=null&&max in 1..10&&(f.getBoolean("allowOtherCoupons")||max==1)){"最多1至10张券；禁止叠券时须为1张"};val order=f.getString("order").split(',');require(order in stackingOrders);p.put("maxCoupons",max).put("calculationOrder",JSONArray(order)).put("maximumDiscountMinor",if(f.getString("maximumDiscountMinor").isBlank())JSONObject.NULL else giftMoney(f.getString("maximumDiscountMinor"))).put("minimumPayableMinor",giftMoney(f.getString("minimumPayableMinor")));return p}
fun stackingSaveBody(f:JSONObject):JSONObject{val code=f.getString("code").trim();require(Regex("^[A-Z][A-Z0-9_]{1,39}$").matches(code)){"编号须2至40位大写字母、数字或下划线"};return JSONObject().put("code",code).put("expectedVersion",f.getInt("expectedVersion")).put("policy",stackingPolicyFromEditor(f)).put("reason",f.getString("reason").trim())}
fun stackingUnitDraft()=JSONObject().put("id",UUID.randomUUID().toString()).put("amount","").put("cost","").put("bundle",false).put("upgraded",false)
fun stackingEffectDraft()=JSONObject().put("id",UUID.randomUUID().toString()).put("stage","coupon").put("kind","amount_off").put("value","").put("minimumSpend","0").put("unitIds",JSONArray())
fun stackingScenario(units:List<JSONObject>,effects:List<JSONObject>):JSONObject{require(units.size in 1..100&&effects.size<=20);val parsed=units.map{JSONObject().put("id",it.getString("id")).put("amountMinor",giftMoney(it.getString("amount"))).put("costMinor",if(it.getString("cost").isBlank())JSONObject.NULL else giftMoney(it.getString("cost"))).put("bundle",it.getBoolean("bundle")).put("upgraded",it.getBoolean("upgraded"))};val ids=units.map{it.getString("id")}.toSet();val discounts=effects.map{e->val stage=e.getString("stage");val kind=e.getString("kind");require(stage in stackingStages.keys&&kind in listOf("amount_off","fixed_price","free","rate"));require(stage!="points"||kind=="amount_off"){"积分只能输入抵扣金额"};require(stage!="member"||kind in listOf("rate","fixed_price")){"会员价须选折扣或固定价"};val targets=e.getJSONArray("unitIds").strings();require(targets.isNotEmpty()&&targets.distinct().size==targets.size&&targets.all{it in ids}){"请选择仍存在的适用商品份次"};require(kind !in listOf("free","fixed_price")||targets.size==1){"免费或固定价须对应一份商品"};val value=if(kind=="free")0L else if(kind=="rate"){val v=giftMoney(e.getString("value"));require(v<=10000){"折扣比例须0至100%，80表示八折"};v}else giftMoney(e.getString("value"));JSONObject().put("id",e.getString("id")).put("stage",stage).put("kind",kind).put("value",value).put("unitIds",JSONArray(targets)).put("minimumSpendMinor",giftMoney(e.getString("minimumSpend")))};return JSONObject().put("units",JSONArray(parsed)).put("effects",JSONArray(discounts))}
fun stackingPolicyCommand(actor:StaffIdentity,b:StackingPoliciesBoard,action:String,body:JSONObject,confirmation:String):LiveCommand{val permission=if(action=="save")"loyalty.configuration.edit" else if(body.getString("action")=="approve")"loyalty.configuration.approve" else "loyalty.policy.publish";require(b.enabled&&b.actor==actor.employeeId&&actor.allows(permission));require(body.getString("reason").trim().length in 2..500){"请填写2至500字原因"};if(action=="decision"){val row=b.rows.find{it.getString("id")==body.getString("versionId")}?:error("原规则不可见，请重新查询");require(row.getString("status")==body.getString("expectedStatus"));val a=body.getString("action");require(a in listOf("approve","publish","stop_issuing"));if(a!="stop_issuing")require(row.getString("createdByEmployeeId")!=actor.employeeId){"编辑人不能审批或发布本人规则"};if(a=="publish")require(row.getJSONArray("decisions").objects().none{it.getString("action")=="approve"&&it.getString("employeeId")==actor.employeeId}){"须由审批人之外的员工发布"}}
 val id=UUID.randomUUID().toString();val proof=JSONObject().put("employeeId",actor.employeeId).put("action",action).put("confirmation",confirmation+"\n原因：${body.getString("reason")}");return LiveCommand(id,actor.employeeId,"核对叠加价格规则",permission,listOf(LiveStep("$stackingPolicyRoot/$action",body.toString(),"idempotency-key","native-business-$id",JSONObject().put("stackingPolicy",proof).toString())))}
val LiveStep.stackingPolicyProof:JSONObject? get()=recoveryBody?.let{JSONObject(it).optJSONObject("stackingPolicy")}
fun validateStackingPolicyReply(text:String,s:LiveStep){val r=JSONObject(text);val d=r.getJSONObject("data");val p=s.stackingPolicyProof!!;val body=JSONObject(s.body);require(r.getJSONObject("meta").getInt("protocol")==1&&r.getJSONObject("meta").get("replayed") is Boolean);require(d.getString("employeeId")==p.getString("employeeId")&&d.getString("action")==p.getString("action")&&d.getString("requestKey")==s.key);val row=d.getJSONObject("row");UUID.fromString(row.getString("id"));if(p.getString("action")=="save")require(row.getString("code")==body.getString("code")&&row.getInt("version")==body.getInt("expectedVersion")+1&&row.getString("status")=="draft"&&row.getString("createdByEmployeeId")==p.getString("employeeId")&&calendarJson(row.getJSONObject("policy"))==calendarJson(body.getJSONObject("policy"))){"保存的叠加价格规则与原请求不一致"}else{val a=body.getString("action");require(row.getString("id")==body.getString("versionId")&&row.getString("status")==mapOf("approve" to "approved","publish" to "published","stop_issuing" to "stopped")[a]&&row.getJSONArray("decisions").objects().any{it.getString("action")==a&&it.getString("employeeId")==p.getString("employeeId")}){"叠加价格规则审核回执不一致"}}}
