package com.mbox.staff
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import org.json.JSONObject
private val publicationStates=mapOf("draft" to "草稿","published" to "已发布","withdrawn" to "已撤下")
@Composable fun LivePublicationView(m:AppModel,close:()->Unit){
 val access=remember{m.priorityAccessKey};val version=remember{m.workspaceVersion};var tab by remember{mutableStateOf("profiles")};var row by remember{mutableStateOf<JSONObject?>(null)};var action by remember{mutableStateOf("")};var proposed by remember{mutableStateOf<LiveCommand?>(null)};var error by remember{mutableStateOf("")}
 LaunchedEffect(Unit){m.loadPublication()};LaunchedEffect(m.priorityAccessKey,m.workspaceVersion){if(access!=m.priorityAccessKey||version!=m.workspaceVersion)close()};if(access!=m.priorityAccessKey||version!=m.workspaceVersion)return
 fun choose(a:String,r:JSONObject?){action=a;row=r}
 Dialog(onDismissRequest=close,properties=DialogProperties(usePlatformDefaultWidth=false)){Surface(Modifier.fillMaxSize(),color=Paper){LazyColumn(Modifier.safeDrawingPadding().imePadding().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
  item{Row{Text("顾客公开内容",Modifier.weight(1f),style=MaterialTheme.typography.titleLarge);TextButton(onClick=close){Text("关闭")}};LivePendingView(m);Text(m.publicationState);Text(error,color=MaterialTheme.colorScheme.error);AssignmentChoice("内容类别",tab,listOf("profiles" to "公开服务名","privacy" to "隐私政策","contact" to "门店联系")){tab=it;action="";row=null};TextButton(onClick={action="";row=null;m.loadPublication()},enabled=!m.busy){Text("刷新原内容")}}
  m.publicationBoard?.let{b->
   if(tab=="profiles"){
    if(m.identity?.allows("customer.public-profile.manage")==true)item{SecondaryAction(onClick={choose("profile-draft",null)},enabled=m.canUsePublication){Text("新建服务名草稿")}}
    for(p in b.profiles)item{Panel{Text(p.getString("publicDisplayName"),style=MaterialTheme.typography.titleMedium);Text("${p.getString("employeeDisplayName")} · ${publicationStates[p.getString("status")]}");p.textOrNull("effectiveAt")?.let{Text("生效 $it")};Row{if(p.getString("status")=="draft"){if(m.identity?.allows("customer.public-profile.manage")==true)TextButton(onClick={choose("profile-draft",p)}){Text("编辑草稿")};if(m.identity?.allows("customer.public-profile.publish")==true)TextButton(onClick={choose("profile-publish",p)}){Text("独立发布")}}else if(p.getString("status")=="published"&&m.identity?.allows("customer.public-profile.publish")==true)TextButton(onClick={choose("profile-withdraw",p)}){Text("撤下")}}}}
   }else if(tab=="privacy"){
    if(m.identity?.allows("privacy.policy.manage")==true)item{SecondaryAction(onClick={choose("privacy-draft",null)},enabled=m.canUsePublication){Text("新建政策草稿")}}
    for(p in b.policies)item{Panel{Text(p.getString("policyVersion"),style=MaterialTheme.typography.titleMedium);Text("${publicationStates[p.getString("status")]} · ${p.getString("operatorName")}");Text("${p.getString("contact")}\n内容摘要 ${p.getString("contentSha256").take(12)}");Foldout("阅读此版本全文"){Text(p.getString("content"))};Row{if(p.getString("status")=="draft"){if(m.identity?.allows("privacy.policy.manage")==true)TextButton(onClick={choose("privacy-draft",p)}){Text("编辑草稿")};if(m.identity?.allows("privacy.policy.publish")==true)TextButton(onClick={choose("privacy-publish",p)}){Text("独立发布")}}else if(p.getString("status")=="published"&&m.identity?.allows("privacy.policy.publish")==true)TextButton(onClick={choose("privacy-withdraw",p)}){Text("撤下")}}}}
   }else if("customer.experience.feature.manage" in b.permissions)item{val current=b.data.optJSONObject("contact");Panel{Text("门店公开联系信息",style=MaterialTheme.typography.titleMedium);Text(when(current?.optString("rolloutState")){"enabled"->"已启用";"pilot"->"试运行";else->"已停用"});current?.optJSONObject("contact")?.let{Text("${it.getString("phoneLabel")}：${it.getString("phone")}\n企业微信：${it.getString("wecomName")}")};SecondaryAction(onClick={choose("contact",current)},enabled=m.canUsePublication){Text("修改门店联系")}}}
   if(action.isNotBlank())item{key(action,row?.optString("id"),b.data.getJSONObject("versions").toString()){PublicationFields(m,b,row,action){body,confirmation->try{proposed=publicationCommand(m.identity!!,b,action,body,confirmation);error=""}catch(e:Exception){error=e.message.orEmpty()}}}}
  }
 }}}
 proposed?.let{c->AlertDialog(onDismissRequest={proposed=null},title={Text("核对公开内容操作")},text={Text(c.steps[0].publicationProof!!.getString("confirmation"))},confirmButton={TextButton(onClick={proposed=null;action="";row=null;m.executeLive(c)},enabled=m.canExecuteLive(c)){Text("确认提交")}},dismissButton={TextButton(onClick={proposed=null}){Text("返回")}})}
}
@Composable private fun PublicationFields(m:AppModel,b:PublicationBoard,row:JSONObject?,action:String,submit:(JSONObject,String)->Unit){
 var imagePicker by remember{mutableStateOf(false)}
 var employee by remember{mutableStateOf(row?.textOrNull("employeeId")?:"")};var name by remember{mutableStateOf(row?.textOrNull("publicDisplayName")?:"")};var policy by remember{mutableStateOf(row?.textOrNull("policyVersion")?:"")};var content by remember{mutableStateOf(row?.textOrNull("content")?:"")};var operator by remember{mutableStateOf(row?.textOrNull("operatorName")?:"")};var contact by remember{mutableStateOf(row?.textOrNull("contact")?:"")};var retention by remember{mutableStateOf(row?.textOrNull("dataRetentionPolicyVersion")?:"")};var third by remember{mutableStateOf(row?.textOrNull("thirdPartyRegisterVersion")?:"")};var approved by remember{mutableStateOf("")};var reference by remember{mutableStateOf("")};var reason by remember{mutableStateOf("")};val originalContact=row?.optJSONObject("contact");var state by remember{mutableStateOf(row?.textOrNull("rolloutState")?:"disabled")};var phone by remember{mutableStateOf(originalContact?.optString("phone")?:"")};var phoneLabel by remember{mutableStateOf(originalContact?.optString("phoneLabel")?:"门店电话")};var wecom by remember{mutableStateOf(originalContact?.optString("wecomName")?:"门店客服")};var qr by remember{mutableStateOf(originalContact?.textOrNull("wecomQrImageUrl")?:"")}
 if(imagePicker)LiveMediaAssetPicker(m,"support_contact",{imagePicker=false}){value->qr=value;imagePicker=false}
 Panel{Text(when(action){"profile-draft"->"服务名草稿";"privacy-draft"->"隐私政策草稿";"contact"->"公开联系方式";else->if(action.endsWith("publish"))"独立复核并立即发布" else "撤下公开内容"},style=MaterialTheme.typography.titleMedium)
  if(action=="profile-draft"){AssignmentChoice("服务员工",employee,listOf("" to "请选择")+b.employees.map{it.getString("id") to "${it.getString("displayName")} · ${it.getString("employeeCode")}"}){employee=it};CustodyField("顾客可见服务名",name,80){name=it};Text("保存为草稿；所属员工和草拟人都不能自行发布。")}
  if(action=="privacy-draft"){CustodyField("政策版本编号",policy,64){policy=it};CustodyField("运营主体",operator,200){operator=it};CustodyField("联系渠道",contact,500){contact=it};CustodyField("数据保留规则版本",retention,80){retention=it};CustodyField("第三方服务清单版本",third,80){third=it};OutlinedTextField(content,{content=it.take(50000)},label={Text("已批准的政策正文（80至50000字）")},modifier=Modifier.fillMaxWidth(),minLines=6,maxLines=18);Text("草稿不会向顾客发布。已发布版本不能改写；更正时请建立新的版本编号并独立发布。")}
  if(action.endsWith("publish")){Text("发布对象：${row?.textOrNull("publicDisplayName")?:row?.textOrNull("policyVersion")}\n发布后替换当前版本，立即生效。请先阅读原内容并核对实际批准材料。");if(action.startsWith("privacy"))CustodyField("实际法务或运营批准人",approved,200){approved=it};CustodyField("批准材料编号",reference,240){reference=it}}
  if(action.endsWith("withdraw"))Text("撤下 ${row?.textOrNull("publicDisplayName")?:row?.textOrNull("policyVersion")} 后，顾客不再看到这个版本。撤下隐私政策不会自动回退为送审稿。")
  if(action=="contact"){AssignmentChoice("启用状态",state,listOf("disabled" to "停用","pilot" to "试运行","enabled" to "启用")){state=it};CustodyField("联系电话",phone,31){phone=it};CustodyField("电话名称",phoneLabel,40){phoneLabel=it};CustodyField("企业微信名称",wecom,40){wecom=it};if(qr.isNotBlank()){Text("已选择客服二维码");qr.substringAfterLast('/').takeIf{Regex("^MA[0-9A-F]{32}$").matches(it)}?.let{MediaAssetThumbnail(m,it)}};Row{TextButton(onClick={imagePicker=true}){Text("选择或上传二维码")};if(qr.isNotBlank())TextButton(onClick={qr=""}){Text("移除二维码")}};Text("保存后在顾客页面展示此联系信息。")}
  CustodyField("操作原因",reason,500){reason=it};PrimaryAction(onClick={val body=JSONObject().put("reason",reason.trim());when(action){"profile-draft"->body.put("employeeId",employee).put("publicDisplayName",name.trim());"privacy-draft"->body.put("policyVersion",policy.trim()).put("content",content.trim()).put("operatorName",operator.trim()).put("contact",contact.trim()).put("dataRetentionPolicyVersion",retention.trim()).put("thirdPartyRegisterVersion",third.trim());"contact"->body.put("rolloutState",state).put("configuration",JSONObject().put("phone",phone.trim()).put("phoneLabel",phoneLabel.trim()).put("wecomName",wecom.trim()).put("wecomQrImageUrl",qr.trim().ifBlank{null}?:JSONObject.NULL));else->{if(action.startsWith("profile"))body.put("profileId",row!!.getString("id"))else body.put("policyVersion",row!!.getString("policyVersion"));if(action.endsWith("publish")){body.put("approvalReference",reference.trim()).put("effectiveAt",java.time.Instant.now().toString());if(action.startsWith("privacy"))body.put("approvedBy",approved.trim())}}};submit(body,when(action){"profile-draft"->"保存服务名草稿：$name\n员工：${b.employees.find{it.getString("id")==employee}?.getString("displayName")}";"privacy-draft"->"保存政策草稿：$policy\n运营主体：$operator\n正文${content.trim().length}字；本次不发布";"contact"->"更新门店联系：$phoneLabel $phone\n企业微信：$wecom\n${when(state){"enabled"->"启用";"pilot"->"试运行";else->"停用"}}";else->"${if(action.endsWith("publish"))"立即发布" else "撤下"} ${row?.textOrNull("publicDisplayName")?:row?.textOrNull("policyVersion")}\n批准材料：$reference"}+"\n原因：$reason")}){Text("核对操作")}
 }
}
