package com.mbox.staff
import org.json.JSONObject
import org.json.JSONArray
import java.util.UUID
const val recommendationPolicyRoot="/api/staff/native-recommendation-policies"
val recommendationWeights=listOf("preferenceWeight" to "偏好权重","sceneWeight" to "场景权重","marginWeight" to "毛利权重","priorityWeight" to "经营优先级权重","performanceWeight" to "历史演出权重","inventoryWeight" to "历史库存权重","capacityWeight" to "历史产能权重")
val recommendationLimits=listOf("minimumGrossMarginBasisPoints" to ("最低毛利率（%）" to 0..9999),"preferenceHalfLifeDays" to ("偏好半衰期（天）" to 7..730),"preferenceMaxAgeDays" to ("偏好最长有效期（天）" to 30..3650),"preferenceMinEffectiveScore" to ("最低有效偏好分" to 1..10000),"preferenceMinConfidenceBasisPoints" to ("最低匹配把握（%）" to 0..10000))
val recommendationRollouts=listOf("disabled" to "关闭","shadow" to "仅后台观察","pilot" to "门店试运行","enabled" to "正式开放")
fun recommendationPolicyCommand(actor:StaffIdentity,b:CouponCalendarsBoard,action:String,row:JSONObject?,input:JSONObject):LiveCommand{
 require(b.enabled&&b.actor==actor.employeeId);require(action in listOf("create","clone","approve","publish","rollout"));val permission=when(action){"create","clone"->"recommendation.rule.draft";"approve"->"recommendation.rule.approve";else->"recommendation.rule.publish"};require(actor.allows(permission)){"没有此项规则权限"};val body=JSONObject(input.toString());val reason=body.getString("reason").trim();require(reason.length in 2..500){"请输入操作原因"};body.put("reason",reason)
 if(action=="create"){require(Regex("^[A-Z][A-Z0-9_-]{2,63}$").matches(body.getString("code"))&&body.getString("code")==b.data.getString("code"));body.put("expectedLatest",b.data.getInt("latest"));for((k,_)in recommendationWeights)require(body.getInt(k) in -1000..1000);for((k,v)in recommendationLimits)require(body.getInt(k) in v.second){"${v.first}超出范围"};require(body.getInt("preferenceMaxAgeDays")>=body.getInt("preferenceHalfLifeDays")){"最长有效期不能短于半衰期"};require(body.getString("explanationTemplate").trim().length in 2..500);body.put("explanationTemplate",body.getString("explanationTemplate").trim());body.getJSONObject("displayConfiguration")}
 else if(action=="rollout"){require(body.getString("rolloutState") in recommendationRollouts.map{it.first});body.put("expectedVersion",b.data.getJSONObject("feature").getString("nativeVersion"))}
 else{require(row!=null&&b.rows.any{it.getString("publicId")==row.getString("publicId")&&it.getString("nativeVersion")==row.getString("nativeVersion")}){"原规则已变化，请重新读取"};body.put("publicId",row.getString("publicId")).put("expectedVersion",row.getString("nativeVersion"));if(action=="approve")require(row.getString("status")=="draft"&&row.textOrNull("createdByEmployeeId")!=actor.employeeId){"须由另一位员工审批草稿"};if(action=="publish"){require(row.getString("status")=="approved"&&row.textOrNull("createdByEmployeeId")!=actor.employeeId&&row.textOrNull("approvedByEmployeeId")!=actor.employeeId){"发布人须与起草、审批人不同"};serverInstant(body.getString("effectiveFrom"))}}
 val label=mapOf("create" to "建立推荐草稿","clone" to "复制历史推荐规则","approve" to "独立审批推荐规则","publish" to "安排推荐规则生效","rollout" to "调整顾客推荐开放").getValue(action);val id=UUID.randomUUID().toString();return LiveCommand(id,actor.employeeId,label,permission,listOf(LiveStep("$recommendationPolicyRoot/$action",body.toString(),"idempotency-key","native-business-$id",JSONObject().put("recommendationPolicy",JSONObject().put("employeeId",actor.employeeId).put("action",action).put("before",row?:JSONObject.NULL).put("confirmation","$label\n${row?.let{"${it.getString("code")} 第${it.getInt("version")}版\n"}?:""}原因：$reason\n"+when(action){"publish"->"生效时间：${calendarLocal(body.getString("effectiveFrom"))}\n发布规则不会自动开放顾客推荐。";"rollout"->"开放状态：${recommendationRollouts.toMap()[body.getString("rolloutState")]}。开放还须满足当前规则、库存和出品条件。";else->"此操作不会自动向顾客开放推荐。"})).toString())))
}
val LiveStep.recommendationPolicyProof:JSONObject? get()=recoveryBody?.let{JSONObject(it).optJSONObject("recommendationPolicy")}
fun validateRecommendationPolicyReply(text:String,s:LiveStep){val r=JSONObject(text);val d=r.getJSONObject("data");val p=s.recommendationPolicyProof!!;val b=JSONObject(s.body);val action=p.getString("action");require(r.getJSONObject("meta").getInt("protocol")==1&&r.getJSONObject("meta").get("replayed") is Boolean&&d.getString("employeeId")==p.getString("employeeId")&&d.getString("action")==action&&d.getString("requestKey")==s.key&&calendarJson(d.getJSONObject("accepted"))==calendarJson(b)){"回执不属于原推荐操作"};val row=d.getJSONObject("row");require(Regex("^[a-f0-9]{64}$").matches(row.getString("nativeVersion")));if(action=="rollout"){require(row.getString("rolloutState")==b.getString("rolloutState")&&row.getString("reason")==b.getString("reason"));return};val before=p.optJSONObject("before");val expected=if(action=="create")b else before!!;for(k in recommendationWeights.map{it.first}+recommendationLimits.map{it.first}+listOf("explanationTemplate","displayConfiguration","code"))require(calendarJson(row.get(k))==calendarJson(expected.get(k))){"规则参数与原版本不符"};require(row.getString("status")==when(action){"approve"->"approved";"publish"->"published";else->"draft"});when(action){"create"->{require(row.getInt("version")==b.getInt("expectedLatest")+1&&row.getString("createdByEmployeeId")==p.getString("employeeId")&&row.getString("draftReason")==b.getString("reason"))};"clone"->{require(row.getInt("version")>before!!.getInt("version")&&row.getString("publicId")!=before.getString("publicId")&&row.getString("createdByEmployeeId")==p.getString("employeeId")&&row.getString("draftReason")==b.getString("reason"))};else->{require(row.getString("publicId")==b.getString("publicId")&&row.getInt("version")==before!!.getInt("version"));if(action=="approve")require(row.getString("approvedByEmployeeId")==p.getString("employeeId")&&row.getString("approvalReason")==b.getString("reason"));if(action=="publish")require(row.getString("publishedByEmployeeId")==p.getString("employeeId")&&row.getString("publicationReason")==b.getString("reason")&&serverInstant(row.getString("effectiveFrom"))==serverInstant(b.getString("effectiveFrom")))}}}
