package com.mbox.staff
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import org.json.JSONObject
import org.json.JSONArray
@Composable fun LiveCheckoutManagementView(m:AppModel,close:()->Unit){
 val access=remember{m.priorityAccessKey};val workspace=remember{m.workspaceVersion};var area by remember{mutableStateOf(if(m.identity?.allows("checkout.upgrade.rule.view")==true)"rules"else "capacities")};var code by remember{mutableStateOf("")};var action by remember{mutableStateOf("")};var selected by remember{mutableStateOf<JSONObject?>(null)};var error by remember{mutableStateOf("")};var reason by remember{mutableStateOf("")};var proposed by remember{mutableStateOf<LiveCommand?>(null)}
 LaunchedEffect(Unit){m.loadCheckoutManagement(area)};LaunchedEffect(m.priorityAccessKey,m.workspaceVersion){if(access!=m.priorityAccessKey||workspace!=m.workspaceVersion)close()};if(access!=m.priorityAccessKey||workspace!=m.workspaceVersion)return
 fun propose(b:JSONObject){try{val board=m.checkoutManagementBoard?:error("请先读取原配置");proposed=checkoutManagementCommand(m.identity!!,CouponCalendarsBoard(JSONObject(board.data.toString()).put("rows",JSONArray(m.checkoutManagementRows))),action,selected,b);error=""}catch(e:Exception){error=e.message?:"请核对完整配置"}}
 Dialog(onDismissRequest=close,properties=DialogProperties(usePlatformDefaultWidth=false)){
  Surface(Modifier.fillMaxSize(),color=Paper){LazyColumn(Modifier.safeDrawingPadding().imePadding().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
   item{Row{Text("升级规则与出品产能",Modifier.weight(1f),style=MaterialTheme.typography.titleLarge);TextButton(onClick=close){Text("关闭")}};LivePendingView(m);Text(m.checkoutManagementState);Text("规则发布不会自动向顾客开放升级。付款前升级仍须通过真实支付、产能和营业验收；原购物车结账继续可用。",style=MaterialTheme.typography.bodySmall);if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error)}
   when(action){
    "rule-draft"->item{CheckoutRuleEditor(m,code,selected,{action=""},::propose)}
    "capacity-draft"->item{CheckoutCapacityEditor({action=""},::propose)}
    else->{
     item{AssignmentChoice("查看",area,(if(m.identity?.allows("checkout.upgrade.rule.view")==true)listOf("rules" to "升级规则","outcomes" to "升级经营结果")else emptyList())+(if(m.identity?.allows("fulfillment.capacity.view")==true)listOf("capacities" to "出品产能")else emptyList())){if(m.loadCheckoutManagement(it,code)){area=it}};if(area=="rules")CustodyField("规则编号（大写，留空查看全部）",code,64){code=it};TextButton(onClick={m.loadCheckoutManagement(area,code)},enabled=!m.busy){Text("读取 / 刷新")};if(area=="rules"&&m.identity?.allows("checkout.upgrade.rule.draft")==true)TextButton(onClick={selected=null;action="rule-draft"},enabled=m.canUseCheckoutManagement&&code.isNotBlank()&&m.checkoutManagementBoard?.data?.textOrNull("code")==code){Text("新建此编号下一版本")};if(area=="capacities"&&m.identity?.allows("fulfillment.capacity.draft")==true)TextButton(onClick={selected=null;action="capacity-draft"},enabled=m.canUseCheckoutManagement){Text("新建产能时间窗草稿")}}
     items(if(m.checkoutManagementBoard?.data?.textOrNull("area")==area)m.checkoutManagementRows else emptyList(),key={it.getString(if(area=="outcomes")"offerPublicId"else "id")}){r->Panel{
      when(area){
       "rules"->{Text("${r.getString("name")} · 第${r.getInt("revision")}版",style=MaterialTheme.typography.titleMedium);Text("${r.getString("code")} · ${checkoutStatus(r.getString("status"))}");Text("${r.getString("sourceProductName")} → ${r.getString("targetProductName")}");Text("${r.getInt("minimumPartySize")}–${r.getInt("maximumPartySize")} 人 · 报价 ${r.getInt("offerValidMinutes")} 分钟\n最低毛利 ${checkoutDecimal(r.getInt("minimumGrossMarginBasisPoints"))}% · 优先级 ${r.getInt("priority")}");Text("${r.getString("promptTitle")}\n${r.getString("promptBody")}\n按键：${r.getString("callToAction")}");Text("适配场景："+r.getJSONArray("occasionTags").strings().map{checkoutOccasions.toMap()[it]?:it}.joinToString("、").ifBlank{"不限"});Text("酒水偏好："+r.getJSONArray("alcoholPreferenceTags").strings().map{checkoutAlcohol.toMap()[it]?:it}.joinToString("、").ifBlank{"不限"});r.optJSONObject("qualification")?.let{q->Text("最多加价 ${historyMoney(q.getLong("maximumAddMinor"))} · 相对加价 ${if(q.isNull("maximumAddBasisPoints"))"不限"else checkoutDecimal(q.getInt("maximumAddBasisPoints"))+"%"}\n最低贡献 ${historyMoney(q.getLong("minimumContributionMinor"))} · 最低新增贡献 ${historyMoney(q.getLong("minimumIncrementalContributionMinor"))}\n${q.getString("positiveFitReason")}");for(p in q.getJSONArray("maximumQuantitiesPerPerson").objects())Text("${checkoutProductName(m,p.getString("productId"))} · 每人最多 ${p.getInt("quantity")} 份");for(id in q.getJSONArray("excludedProductIds").strings())Text("排除：${checkoutProductName(m,id)}") }?:Text("旧版未设置完整高匹配准入条件");if(m.identity?.allows("checkout.upgrade.rule.draft")==true)TextButton(onClick={if(m.loadCheckoutManagement("rules",r.getString("code"))){selected=r;code=r.getString("code");action="rule-draft"}},enabled=!m.busy){Text("复制为新草稿")};for((kind,label,perm)in listOf(Triple("rule-approve","独立审批","checkout.upgrade.rule.approve"),Triple("rule-publish","第三人发布","checkout.upgrade.rule.publish"),Triple("rule-rollback","历史版本建立回滚草稿","checkout.upgrade.rule.publish"))){val visible=kind=="rule-rollback"||r.getString("status")==if(kind=="rule-approve")"draft"else "approved";if(visible&&m.identity?.allows(perm)==true)TextButton(onClick={selected=r;action=kind;reason=""},enabled=m.canUseCheckoutManagement){Text(label)}}}
       "capacities"->{Text("${checkoutStations.toMap()[r.getString("stationCode")]} · 第${r.getInt("policyVersion")}版",style=MaterialTheme.typography.titleMedium);Text(checkoutStatus(r.getString("status")));Text(r.getString("reason"));for(w in r.getJSONArray("windows").objects())Text("${calendarLocal(w.getString("startsAt"))} 至 ${calendarLocal(w.getString("endsAt"))}\n上限 ${w.getInt("capacityLimitUnits")} · 已占用 ${w.getInt("usedUnits")}");for(kind in listOf("approve","publish"))if(r.getString("status")==if(kind=="approve")"draft"else "approved")if(m.identity?.allows("fulfillment.capacity.$kind")==true)TextButton(onClick={selected=r;action="capacity-$kind";reason=""},enabled=m.canUseCheckoutManagement){Text(if(kind=="approve")"独立审批"else "第三人发布")}}
       "outcomes"->{Text("${r.getString("sourceProductName")} → ${r.getString("targetProductName")}",style=MaterialTheme.typography.titleMedium);Text("${r.getString("ruleCode")} 第${r.getInt("ruleRevision")}版 · ${r.getString("offerPublicId")}");Text("报价加价 ${historyMoney(r.getLong("amountToAddMinor"))} · ${calendarLocal(r.getString("offeredAt"))}");Text("付款：${mapOf("not_created" to "未创建付款","pending" to "等待付款","paid" to "已付款","failed_or_closed" to "失败或已关闭")[r.getString("paymentState")]}");Text("已付 ${historyMoney(r.getLong("paidAmountMinor"))} · 已退 ${historyMoney(r.getLong("refundedAmountMinor"))} · 投诉 ${r.getInt("complaintCount")}");r.textOrNull("convertedOrderPublicId")?.let{Text("关联订单 $it")};val e=r.getJSONObject("eventCounts");Text("查看 ${e.getInt("viewed")} · 拒绝 ${e.getInt("declined")} · 接受 ${e.getInt("accepted")}\n转化 ${e.getInt("converted")} · 失效 ${e.getInt("invalidated")}")}
      }
     }}
     if(m.checkoutManagementBoard?.next!=null)item{TextButton(onClick={m.loadCheckoutManagement(area,code,true)},enabled=!m.busy){Text("加载更多记录")}}
    }
   }
  }}
 }
 if(action.isNotBlank()&&!action.endsWith("draft"))AlertDialog(onDismissRequest={action=""},title={Text("核对版本操作")},text={Column{Text(if(action=="rule-rollback")"复制原版本成为新草稿，仍须重新审批发布。"else "审批发布须满足原商品、毛利、配方和权限规则。");CustodyField("操作原因",reason,240){reason=it};if(error.isNotBlank())Text(error)}},confirmButton={TextButton(onClick={propose(JSONObject().put("reason",reason));if(proposed!=null)action=""}){Text("继续核对")}},dismissButton={TextButton(onClick={action=""}){Text("取消")}})
 proposed?.let{c->AlertDialog(onDismissRequest={proposed=null},title={Text("确认升级 / 产能操作")},text={Text(c.steps[0].checkoutManagementProof!!.getString("confirmation"))},confirmButton={TextButton(onClick={proposed=null;action="";m.executeLive(c)},enabled=m.canExecuteLive(c)){Text("确认提交")}},dismissButton={TextButton(onClick={proposed=null}){Text("返回核对")}})}
}
private fun checkoutStatus(s:String)=mapOf("draft" to "待审批","approved" to "待发布","active" to "已生效","published" to "已发布","paused" to "已暂停","retired" to "历史版本")[s]?:s
fun checkoutProductName(m:AppModel,id:String)=m.checkoutManagementProducts[id]?.getString("name")?:"原商品（${id.take(8)}）"
