package com.mbox.staff
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import kotlinx.coroutines.launch
import org.json.JSONObject
import org.json.JSONArray

@Composable fun LiveCategoryConfigurationView(m:AppModel,close:()->Unit){
 val access=remember{m.priorityAccessKey};val version=remember{m.workspaceVersion};var row by remember{mutableStateOf<JSONObject?>(null)};var create by remember{mutableStateOf(false)};var proposed by remember{mutableStateOf<LiveCommand?>(null)};var error by remember{mutableStateOf("")}
 LaunchedEffect(m.priorityAccessKey,m.workspaceVersion){if(access!=m.priorityAccessKey||version!=m.workspaceVersion)close()}
 if(access!=m.priorityAccessKey||version!=m.workspaceVersion)return
 Dialog(onDismissRequest=close,properties=DialogProperties(usePlatformDefaultWidth=false)){Surface(Modifier.fillMaxSize(),color=Paper){LazyColumn(Modifier.safeDrawingPadding().imePadding().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
  item{Row{Text("菜单分类",Modifier.weight(1f),style=MaterialTheme.typography.titleLarge);TextButton(onClick=close){Text("关闭")}};LivePendingView(m);TextButton(onClick={row=null;create=false;m.loadProducts()},enabled=!m.busy){Text("刷新分类")};SecondaryAction(onClick={row=null;create=true},enabled=m.canUseProducts&&m.productBoard?.configurable==true){Text("新增分类")};Text(error,color=MaterialTheme.colorScheme.error)}
  m.productBoard?.let{b->
   if(create||row!=null)item{key(row?.getString("id")?:"new",row?.getString("updatedAt")){CategoryFields(b,row){body->try{proposed=categoryConfigurationCommand(m.identity!!,b,row,body);error=""}catch(e:Exception){error=e.message.orEmpty()}}}}
   for(c in b.categories)item{Panel{Text(c.getString("displayName"),style=MaterialTheme.typography.titleMedium);Text("${c.getString("code")} · ${c.textOrNull("parentCode")?:"一级分类"} · ${c.getInt("productCount")}个商品");Text("排序${c.getInt("sortOrder")} · ${if(c.getBoolean("guestVisible"))"显示" else "隐藏"}");TextButton(onClick={row=c;create=false},enabled=m.canUseProducts){Text("编辑")}}}
  }
 }}}
 proposed?.let{c->AlertDialog(onDismissRequest={proposed=null},title={Text(c.title)},text={Text(c.steps[0].categoryConfigurationProof!!.getString("confirmation"))},confirmButton={TextButton(onClick={proposed=null;row=null;create=false;m.executeLive(c)},enabled=m.canExecuteLive(c)){Text("确认保存")}},dismissButton={TextButton(onClick={proposed=null}){Text("返回")}})}
}
@Composable private fun CategoryFields(b:ProductManagementBoard,row:JSONObject?,submit:(JSONObject)->Unit){
 var code by remember{mutableStateOf(row?.getString("code")?:"")};var name by remember{mutableStateOf(row?.getString("displayName")?:"")};var parent by remember{mutableStateOf(row?.textOrNull("parentCode")?:"")};var sort by remember{mutableStateOf((row?.getInt("sortOrder")?:100).toString())};var visible by remember{mutableStateOf(row?.getBoolean("guestVisible")?:true)}
 Panel{if(row==null)CustodyField("唯一分类编号",code,64){code=it};CustodyField("分类名称",name,32){name=it};AssignmentChoice("上级分类",parent,listOf("" to "无（一级分类）")+b.categories.filter{it.textOrNull("parentCode")==null&&it.getString("code")!=code}.map{it.getString("code") to it.getString("displayName")}){parent=it};CustodyField("排序",sort,6){sort=it};Row{Checkbox(visible,{visible=it});Text("客人菜单显示")};SecondaryAction(onClick={val body=JSONObject().put("displayName",name.trim()).put("parentCode",parent.ifBlank{null}?:JSONObject.NULL).put("sortOrder",sort.toIntOrNull()?:-1).put("guestVisible",visible);if(row==null)body.put("code",code.trim());submit(body)}){Text("核对分类")}}
}
@Composable fun LiveProductConfigurationView(m:AppModel,p:JSONObject,close:()->Unit){
 var productImagePicker by remember{mutableStateOf(false)};var imageUrl by remember{mutableStateOf(p.optJSONObject("productSnapshot")?.textOrNull("imageUrl")?:"")};var description by remember{mutableStateOf(p.optJSONObject("productSnapshot")?.textOrNull("description")?:"")}
 if(productImagePicker)LiveMediaAssetPicker(m,"menu",{productImagePicker=false}){imageUrl=it;productImagePicker=false}
 var newCode by remember{mutableStateOf(p.optString("suggestedCode",""))};var newPrice by remember{mutableStateOf("")};val creating=p.getString("id")=="new"
 val access=remember{m.priorityAccessKey};val version=remember{m.workspaceVersion};var name by remember{mutableStateOf(p.getString("name"))};var category by remember{mutableStateOf(p.getString("categoryCode"))};var kind by remember{mutableStateOf(p.getString("productKind"))};var station by remember{mutableStateOf(p.getString("fulfillmentStation"))};var mode by remember{mutableStateOf(p.getString("inventoryControlMode"))};var max by remember{mutableStateOf(p.getInt("maxOrderQuantity").toString())};var from by remember{mutableStateOf(p.textOrNull("availableFrom")?.take(5)?:"")};var until by remember{mutableStateOf(p.textOrNull("availableUntil")?.take(5)?:"")};var channels by remember{mutableStateOf(p.getJSONArray("allowedChannels").strings())};var components by remember{mutableStateOf(p.getJSONArray("bundleComponents").objects().map{r->JSONObject().put("productId",r.getString("productId")).put("quantity",r.getInt("quantity")).put("sortOrder",r.getInt("sortOrder")).put("note",r.textOrNull("note")?:JSONObject.NULL).put("name",r.optString("productName",r.optString("name",r.getString("productId"))))})};var groups by remember{mutableStateOf(p.getJSONArray("bundleChoiceGroups").objects().map{JSONObject(it.toString())})};var selectedGroup by remember{mutableStateOf(-1)};var picker by remember{mutableStateOf(false)};var notice by remember{mutableStateOf("")};var proposed by remember{mutableStateOf<LiveCommand?>(null)}
 LaunchedEffect(m.priorityAccessKey,m.workspaceVersion){if(access!=m.priorityAccessKey||version!=m.workspaceVersion)close()};if(access!=m.priorityAccessKey||version!=m.workspaceVersion)return
 Dialog(onDismissRequest=close,properties=DialogProperties(usePlatformDefaultWidth=false)){Surface(Modifier.fillMaxSize(),color=Paper){LazyColumn(Modifier.safeDrawingPadding().imePadding().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
  item{Row{Text("商品与套餐配置",Modifier.weight(1f),style=MaterialTheme.typography.titleLarge);TextButton(onClick=close){Text("关闭")}};Text(p.getString("code"));if(creating){CustodyField("唯一商品编号",newCode,64){newCode=it};CustodyField("初始售价（元，可留空后设置）",newPrice,12){newPrice=it};Text("新商品先以未上架保存，完成配方、成本和售价核对后再上架。")}
   CustodyField("商品名称",name,160){name=it};CustodyField("商品介绍",description,2000){description=it};if(imageUrl.isNotBlank()){Text("已选择商品图片");imageUrl.substringAfterLast('/').takeIf{Regex("^MA[0-9A-F]{32}$").matches(it)}?.let{MediaAssetThumbnail(m,it)}};if(m.identity?.allows("media.asset.menu.manage")==true)Row{TextButton(onClick={productImagePicker=true}){Text("选择或上传商品图")};if(imageUrl.isNotBlank())TextButton(onClick={imageUrl=""}){Text("移除商品图")}};AssignmentChoice("二级菜单分类",category,m.productBoard?.categories?.filter{it.textOrNull("parentCode")!=null}?.map{it.getString("code") to it.getString("displayName")}?:emptyList()){category=it};AssignmentChoice("商品类型",kind,listOf("single" to "单品","bundle" to "套餐")){kind=it};AssignmentChoice("出品位置",station,listOf("bar" to "吧台","kitchen" to "厨房","cashier" to "收银","none" to "无需制作")){station=it};AssignmentChoice("库存控制",mode,listOf("tracked" to "按配方跟踪库存","not_managed" to "不管理库存")){mode=it};Text("更改库存模式和套餐构成会影响后续成本与备料；已下单商品保持原快照。套餐成本由组成商品计算。")
   CustodyField("单次最大数量",max,4){max=it};CustodyField("供应开始（HH:mm，可留空）",from,5){from=it};CustodyField("供应结束（HH:mm，可留空）",until,5){until=it};for((code,label) in listOf("guest_qr" to "顾客扫码","staff_assisted" to "员工点单","cashier" to "收银","reservation" to "预约","integration" to "外部接入"))Row{Checkbox(code in channels,{checked->channels=if(checked)(channels+code).distinct() else channels-code});Text(label)}
  }
  if(kind=="bundle"){
   item{Text("固定组成",style=MaterialTheme.typography.titleMedium);SecondaryAction(onClick={selectedGroup=-1;picker=true}){Text("添加固定单品")}}
   for((i,c) in components.withIndex())item{Panel{Text(c.optString("name",c.getString("productId")));CustodyField("份数",c.getInt("quantity").toString(),3){v->components=components.mapIndexed{j,r->if(i==j)JSONObject(r.toString()).put("quantity",v.toIntOrNull()?:0) else r}};CustodyField("备注",c.textOrNull("note")?:"",500){v->components=components.mapIndexed{j,r->if(i==j)JSONObject(r.toString()).put("note",v.ifBlank{null}?:JSONObject.NULL) else r}};TextButton(onClick={components=components.filterIndexed{j,_->j!=i}}){Text("移除")}}}
   item{Text("自选组",style=MaterialTheme.typography.titleMedium);SecondaryAction(onClick={groups=groups+JSONObject().put("code","choice_${java.util.UUID.randomUUID().toString().take(8)}").put("name","自选组${groups.size+1}").put("selectionCount",1).put("sortOrder",(groups.size+1)*10).put("options",JSONArray())},enabled=groups.size<20){Text("新增自选组")}}
   for((i,g) in groups.withIndex())item{Panel{CustodyField("组名称",g.getString("name"),80){v->groups=groups.mapIndexed{j,r->if(i==j)JSONObject(r.toString()).put("name",v) else r}};CustodyField("每套选几种",g.getInt("selectionCount").toString(),2){v->groups=groups.mapIndexed{j,r->if(i==j)JSONObject(r.toString()).put("selectionCount",v.toIntOrNull()?:0) else r}};for((oi,o) in g.getJSONArray("options").objects().withIndex()){Text(o.optString("productName",o.optString("name",o.getString("productId"))));CustodyField("选中后份数",o.getInt("quantity").toString(),3){v->groups=groups.mapIndexed{j,r->if(i==j)JSONObject(r.toString()).put("options",JSONArray(r.getJSONArray("options").objects().mapIndexed{oj,x->if(oi==oj)JSONObject(x.toString()).put("quantity",v.toIntOrNull()?:0) else x})) else r}};TextButton(onClick={groups=groups.mapIndexed{j,r->if(i==j)JSONObject(r.toString()).put("options",JSONArray(r.getJSONArray("options").objects().filterIndexed{oj,_->oi!=oj})) else r}}){Text("移除此候选")}}
    Row{TextButton(onClick={selectedGroup=i;picker=true}){Text("添加候选单品")};TextButton(onClick={groups=groups.filterIndexed{j,_->j!=i}}){Text("删除自选组")}}
   }}
  }
  item{Text(notice,color=MaterialTheme.colorScheme.error);PrimaryAction(onClick={try{require(channels.isNotEmpty()){ "至少选择一个销售渠道" };require((from.isBlank()&&until.isBlank())||(Regex("^(?:[01]\\d|2[0-3]):[0-5]\\d$").matches(from)&&Regex("^(?:[01]\\d|2[0-3]):[0-5]\\d$").matches(until))){"供应时间须成对填写HH:mm"};val patch=JSONObject().put("productSnapshot",JSONObject((p.optJSONObject("productSnapshot")?:JSONObject()).toString()).put("description",description.trim()).put("imageUrl",imageUrl)).put("name",name.trim()).put("categoryCode",category).put("productKind",kind).put("fulfillmentStation",station).put("inventoryControlMode",mode).put("maxOrderQuantity",max.toIntOrNull()?:0).put("availableFrom",from.ifBlank{null}?:JSONObject.NULL).put("availableUntil",until.ifBlank{null}?:JSONObject.NULL).put("allowedChannels",JSONArray(channels));val clean:(JSONObject)->JSONObject={r->JSONObject(r.toString()).also{it.remove("name");it.remove("productName");it.remove("available");it.remove("productCode");it.remove("fulfillmentStation");it.remove("status")}};patch.put("bundleComponents",JSONArray(if(kind=="bundle")components.map(clean) else emptyList<JSONObject>())).put("bundleChoiceGroups",JSONArray(if(kind=="bundle")groups else emptyList<JSONObject>()));if(creating){patch.put("code",newCode.trim()).put("status","inactive");if(newPrice.isNotBlank()){require(m.productBoard?.canPrice==true){"设置初始售价需要价格管理权"};patch.put("standardPrice",JSONObject().put("amountMinor",ownerMoney(newPrice)).put("currency","CNY").put("reason","原生创建商品初始售价"))}};proposed=productConfigurationCommand(m.identity!!,m.productBoard!!,p,patch,"${if(creating)"新建未上架商品 $newCode" else "配置商品"} $name\n${if(creating)"初始售价：${newPrice.ifBlank{"未配置"}}\n" else ""}分类：${m.productBoard!!.categories.find{it.getString("code")==category}?.getString("displayName")}\n${if(kind=="bundle")"套餐：${components.size}个固定单品、${groups.size}个自选组" else "单品"}\n供应：${if(from.isBlank())"全天" else "$from 至 $until"}\n最大数量：$max\n库存：${if(mode=="tracked")"配方跟踪" else "不管理"}\n商品介绍与图片按编辑预览保存；组成与份数请按编辑清单核对。保存只影响新订单。")}catch(e:Exception){notice=e.message.orEmpty()}},enabled=m.canUseProducts&&m.productBoard?.configurable==true){Text("核对保存")}}
 }}}
 if(picker)ProductConfigurationPicker(m,p.getString("id"),close={picker=false}){r->val c=JSONObject().put("productId",r.getString("id")).put("name",r.getString("name")).put("quantity",1).put("sortOrder",10);if(selectedGroup<0){if(components.none{it.getString("productId")==r.getString("id")})components=components+c.put("sortOrder",(components.size+1)*10)}else groups=groups.mapIndexed{i,g->if(i==selectedGroup&&g.getJSONArray("options").objects().none{it.getString("productId")==r.getString("id")})JSONObject(g.toString()).put("options",JSONArray(g.getJSONArray("options").objects()+c.put("sortOrder",(g.getJSONArray("options").length()+1)*10))) else g};picker=false}
 proposed?.let{c->AlertDialog(onDismissRequest={proposed=null},title={Text(c.title)},text={Text(c.steps[0].productManagementProof!!.getString("confirmation"))},confirmButton={TextButton(onClick={proposed=null;m.executeLive(c);close()},enabled=m.canExecuteLive(c)){Text("确认保存")}},dismissButton={TextButton(onClick={proposed=null}){Text("返回")}})}
}
@Composable fun ProductConfigurationPicker(m:AppModel,exclude:String,singleOnly:Boolean=true,close:()->Unit,choose:(JSONObject)->Unit){var query by remember{mutableStateOf("")};var rows by remember{mutableStateOf(emptyList<JSONObject>())};var offset by remember{mutableStateOf(0)};var loading by remember{mutableStateOf(false)};var error by remember{mutableStateOf("")};val scope=rememberCoroutineScope();fun load(page:Int){if(loading)return;scope.launch{loading=true;try{rows=m.queryProductConfigurationChoices(query,page,singleOnly).filter{it.getString("id")!=exclude};offset=page;error=""}catch(e:Exception){rows=emptyList();error=e.message.orEmpty()}finally{loading=false}}};LaunchedEffect(Unit){load(0)}
 Dialog(onDismissRequest=close,properties=DialogProperties(usePlatformDefaultWidth=false)){Surface(Modifier.fillMaxSize(),color=Paper){LazyColumn(Modifier.safeDrawingPadding().imePadding().padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text(if(singleOnly)"选择原门店单品" else "选择原门店商品",style=MaterialTheme.typography.titleLarge);CustodyField("搜索名称或编码",query,80){query=it};Row{TextButton(onClick={load(0)},enabled=!loading){Text("查询")};TextButton(onClick=close){Text("关闭")}};Text(error)};for(r in rows)item{SecondaryAction(onClick={choose(r)}){Text("${r.getString("name")} · ${r.getString("code")}")}};item{Row{TextButton(onClick={load((offset-50).coerceAtLeast(0))},enabled=!loading&&offset>0){Text("上一页")};TextButton(onClick={load(offset+50)},enabled=!loading&&offset<10000){Text("下一页")}};if(rows.isEmpty())Text("本页没有可选单品，可继续翻页或更改搜索")}}}}
}
